/****** Object:  Table [dbo].[TERMonthly]    Script Date: 2/5/2024 12:45:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TERMonthly](
	[TERMonthlyID] [int] IDENTITY(1,1) NOT NULL,
	[ValidFrom] [datetime] NOT NULL,
	[SRTaxStatus] [varchar](20) NOT NULL,
	[LastUpdateDateTime] [datetime] NULL,
	[LastUpdateByUserID] [varchar](15) NULL,
 CONSTRAINT [PK_TERMonthly] PRIMARY KEY CLUSTERED 
(
	[TERMonthlyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


