
/****** Object:  Index [_idx_RegNo]    Script Date: 20/02/2024 10:28:43 ******/
CREATE NONCLUSTERED INDEX [_idx_RegNo] ON [dbo].[JournalTransactionDetails]
(
	[RegistrationNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

