namespace Temiang.Avicenna.Common
{
    public class AppEnum
    {
        public enum AutoCompleteBox
        {
            Antibiotic,
            OtherDrug,
            ZatActive
        }
        public enum PopUpSearch
        {
            BridgingType,
            Accounts,
            AcctLinkEmployee,
            AcctLinkGuarantor,
            AcctLinkSupplier,
            AcctLinkLoanBank,
            AcctInitialGL,
            AcctSubGroup,
            VoucherCodeReceive,
            VoucherCodePayment,
            VoucherCodeMemorial,
            VoucherCodeAutomatic,
            Employee,
            Donator,
            Bank,
            BankAccount,
            BillGurantor,
            BillDonator,
            BillSupplier,
            BillEmployee,
            BillLoanBank,
            Appointment,
            AssetByServiceUnit,
            Bed,
            BedByServiceRoomID,
            Charge,
            ChargeClass,
            Class,
            CoverageClass,
            Department,
            Diagnose,
            Fabric,
            Guarantor,
            InPatientClass,
            InPatientCoverageClass,
            Item,
            ItemAndZatActive,
            ItemServices,
            ItemBalanceByLocation,
            ItemJobOrder,
            ItemProductInventory,
            ItemKitchen,
            ItemProductNonMedical,
            ItemProductNonMedicalTariff,
            ItemGroup,
            ItemProductMargin,
            ItemProductMedical,
            ItemService,
            ItemServiceExcludeProduct,
            ItemServiceTariff,
            ItemTariffByServiceUnitTransaction,
            ItemTariffByServiceUnitOrder,
            ItemTransactionListPurchaseOrder,
            ItemLaboratory,
            ItemLaboratoryTariff,
            ItemDiagnostic,
            ItemDiagnosticTariff,
            ItemRadiology,
            ItemPackage,
            ItemUnit,
            ItemTransactionListRequestOrder,
            JobOrderNoByRegistration,
            Location,
            MarginRangeType,
            MorphologyByDiagnoseID,
            NonInPatientClass,
            NonInPatientCoverageClass,
            Paramedic,
            ParamedicByServiceUnitID,
            ParamedicByRegistration,
            ParamedicClusterDetail,
            MedicalNo,
            Pathway,
            Patient,
            Permit,
            Procedure,
            Referral,
            Registration,
            RegistrationByRegType,
            RegistrationByDepartment,
            Reservation,
            ServiceRoom,
            ServiceRoomByServiceUnitID,
            ServiceRoomInPatient,
            ServiceUnit,
            ServiceUnitAutoBillItem,
            ServiceUnitByRegistrationType,
            ServiceUnitItemService,
            ServiceUnitVisitType,
            ServiceUnitTransaction,
            ServiceUnitJobOrder,
            Specialty,
            SubSpecialty,
            Supplier,
            TransactionNoByRegistration,
            User,
            VisitReason,
            VisitType,
            ZipCode,
            TransPrescriptionSales,
            Label,
            ZatActive,
            Interaction
        }

        public enum StandardReference
        {
            Flacc,
            KelurahanKemenkes,
            KecamatanKemenkes,
            KabKotaKemenkes,
            ProvinsiKemenkes,
            EklaimFactorGroup,
            EvaluatorType,
            BpjsServiceUnit,
            InhealthAccidentType,
            InhealthClassType,
            InhealthParamedic,
            InhealthServiceType,
            InhealthServiceUnit,
            InhealthItemService,
            BridgingType,
            AttendanceFileFormat,
            EttType,
            AcctLevel,
            AcctDbCr,
            AcctLink,
            AcctLinkType,
            AcctProcess,
            AcctSubsidiary,
            AcctSubsidiary1,
            AcctSubsidiary2,
            AcctSubsidiary3,
            AcctGroup,
            AcctCashFlow,
            AnswerType,
            AssetInsurance,
            VoucherType,
            EmployeeStatus,
            GenderType,
            ReceivableType,
            ReceivableStatus,
            PayableType,
            PayableStatus,
            InvoicePayment,
            AutoNumber,
            AppointmentStatus,
            AppoinmentType,
            AccompaniedBy,
            GlobalConsumeUnit,
            AdjustmentType,
            LinenExterminationReason,
            AgeUnit,
            AlcoholConfirm,
            AlcoholResult,
            Anaphylaxis,
            AnesthesiaMethod,
            AnimalAllergen,
            Anestesi,
            AppoinmentTime,
            AssetItemUnit,
            AssetType,
            AssetGroupCategory,
            AwardCriteria,
            AwardType,
            BedStatus,
            BirthMethod,
            BirthType,
            BloodType,
            BloodGroup,
            BloodSource,
            BloodSourceFrom,
            BloodBagStatus,
            ReasonsForExtermination,
            BodyPart,
            BornAt,
            BornCondition,
            BornDeath,
            BusinessMethod,
            CaesarMethod,
            CardProvider,
            CardType,
            CashierCounter,
            CausesOfBurns,
            CensusStatus,
            Chronicity,
            ClassRL,
            BpjsClassID,
            Color,
            CompanyDept,
            CompleteStatusRM,
            ConductionType,
            ConsumptionType,
            Course,
            CovidStatus,
            CrashSite,
            Currency,
            ChronicDisease,
            DegreeOfBurns,
            DependentType,
            DermatomsID,
            DiagnosaBumil,
            DiagnosaNeonatal,
            DiagnoseSummary,
            DiagnoseType,
            DiagnosticType,
            DifferenceReason,
            Disability,
            DischargeCondition,
            DischargeMethod,
            ReferReason,
            DiscountReason,
            OverPaymentReason,
            DistributionType,
            DocumentOutType,
            DocumentType,
            DosageUnit,
            DownPaymentType,
            DrugAlcoholTest,
            DrugAllergen,
            DrugSpecimen,
            DrugTest,
            DrugTestResult,
            DrugTestType,
            DustAllergen,
            EAPConsult,
            EAPReferral,
            Education,
            EmbalaceLabel,
            EncounterType,
            ERCaseType,
            Ethnic,
            ExacerbatedBy,
            ExaminationGroup,
            ExaminationType,
            FamilyIllnessID,
            FamilyPlanning,
            FamilyProblem,
            FamilyRelation,
            FamilyOccupation,
            FilesAnalysis,
            FeeVerificationNo,
            FeePaymentNo,
            FluidType,
            FoodAllergen,
            GCFileReceiverType,
            GLASGOWEYE,
            GLASGOWMOTOR,
            GLASGOWVERBAL,
            GuarantorRuleType,
            GuarantorIncomeGroup,
            GuarantorType,
            HealthcareOPG,
            HearingComment,
            HearingTestType,
            InjectionSite,
            Interpretation,
            InvoiceCategory,
            IntervalTime,
            IssuedReason,
            ItemBin,
            ItemUnit,
            ItemType,
            InpatientClassificationUnit,
            CovidComorbidStatus,
            JournalType,
            LaboratoryUnit,
            LabReportType,
            LabTestCategory,
            SRPatientLanguage,
            Language,
            LensType,
            MaintenanceType,
            Manufacturer,
            MarginRangeType,
            MaritalStatus,
            MedicationConsume,
            MedicationType,
            MonthID,
            Mood,
            NarcoticType,
            Nationality,
            Occupation,
            ResidentialHome,
            Onset,
            OperationType,
            OralMucosa,
            OtherInvItem,
            PainLevel,
            ParamedicRL1,
            PaymentType,
            PaymentMethod,
            ParamedicFeeCaseType,
            ParamedicStatus,
            ParamedicTeamStatus,
            ParamedicFeeIsTeam,
            ParamedicFeeTeamStatus,
            ParamedicFeeDeductionMethod,
            ParamedicFeeDeduction,
            ParamedicType,
            PatientCategory,
            PatientInCondition,
            PatientInType,
            PaymentTypePO,
            PhysicalLimit,
            PRBRecommendation,
            PRBStatus,
            PrimaryProblem,
            ProblemStatus,
            ProductType,
            ProdiaContractID,
            ProcedureCategory,
            ProtectorType,
            Province,
            Promotion,
            Psychological,
            PULSERHYTHM,
            PurchaseUnit,
            Quality,
            Recommendation,
            Referal,
            ReferralDestination,
            ReferralGroup,
            ReferralItem,
            ReferralServiceUnit,
            RegistrationType,
            Relationship,
            RelievedBy,
            Religion,
            District,
            County,
            Restriction,
            Risk,
            RptTindakanIGD,
            RLTypeID,
            ROSystem,
            Route,
            Severity,
            Shift,
            WorkingDay,
            SickLeaveReason,
            SickLeaveType,
            SingleTwin,
            Specialty,
            SpecimenType,
            SpectaclePrescType,
            SpectacleType,
            Speech,
            SpirometryTest,
            SubstanceAbuse,
            SupplierType,
            AgingDateType,
            SurgeryOutcome,
            TariffComponentType,
            TariffType,
            Term,
            TestDuration,
            TherapyGroup,
            Title,
            TimeType,
            Tooth,
            ToothProblem,
            ToothStatus,
            TransactionCode,
            Triage,
            Triage5Level,
            TypeOfService,
            CauseOfDisease,
            CauseOfDevelopDisorder,
            NatureOfSurgery,
            VaccinationGroup,
            VaccineStatus,
            VisitType,
            VisitReason,
            ValueType,
            WorkplaceStress,
            WPP,
            Salutation,
            MedicalFileBin,
            MedicalFileStatus,
            MedicalFileCategory,
            DrugLabelType,
            PurchaseOrderType,
            BillingGroup,
            ItemCategory,
            BpjsItemGroup,
            EklaimTariffGroup,
            VoidReason,
            CashTransType,
            CashManagementType,
            CashTransactionCode,
            CenterID,
            ParamedicFeeAdjustType,
            PhysicianLeaveReason,
            PettyCashUnitID,
            Film,
            EmrDiagnoseGroupID,
            BillingType,
            GuarantorFreeOfPhysicianFee,
            FeeItemAfterPaid,
            FeeItemExcForFreeGuar,
            PurchaseReturnType,
            FormOfFood,
            TypeOfInventory,
            ItemRequestFollowUp,
            PurchaseCategorization,
            ProcurementType,
            PatientHealthRecord,
            MrbForThePurposesOf,
            BirthComplication,
            DeathCondition,
            BirthIndication,
            MidwivesType,
            ItemGroupKitchen,
            KiaCaseType,
            ObstetricType,
            SurgerySpecialty, //deactivated due to duplication with smf
            Keeping,
            UnitIntended,
            UnitForExtraMealOrder,
            VenClass,
            MedicalNotesInputType,
            PhysicianFeeType,
            PhysicianFeeCategory,
            ExaminationClass,
            PphType,
            ServiceUnitGroup,
            AssessmentType,
            RiskFactorsType,
            RiskFactorsLocation,
            SignsOfInfection,
            TypesOfSurgery,
            AntimicrobialApplicationTiming,
            AsaScore,
            DiseaseFactors,
            IndicationOfSurgery,
            InfectionType,
            WoundClassification,
            ProcedureClassification,
            RiskCategory,
            TTime,
            BloodSampleTakenBy,
            Building,
            PatientDepositType,
            AntibioticLine,
            InterventionReason,
            PresentStatus,

            Pph,
            ApAgingDateType,
            CitoPercentage,
            DocumentChecklist,
            TransferredPatientWith,
            MembershipType,
            DocumentFileType,

            // BPJS
            BpjsTypeOfService,
            BpjsTypeOfApproval,
            BpjsPolyclinicDestination,
            BpjsClass,
            BpjsDischargeMethod,
            BpjsRefferalLetter,
            BpjsSeverityLevel3,
            BpjsTariffType,
            BpjsGuarantorGroup,

            // HRD & Payroll
            RecruitmentTest,
            EmployeeCoverageType,
            LineBusiness,
            LanguageProficiency,
            LanguageCapable,
            LicenseType,
            HRLevelRequirement,
            ContactType,
            EducationLevel,
            ResignReason,
            OrganizationType,
            OrganizationRole,
            RecruitmentMethod,
            MiscellaneousBenefit,
            PhysicalCharacteristic,
            PositionFunctionalArea,
            QuarterPeriod,
            ActivitySubType,
            EmployeeTrainingComponent,

            MeasurementCode,
            City,
            OperandType,
            AddressType,
            WarningLevel,
            ViolationDegree,
            ViolationType,
            RL4Status,
            RL4Type,
            RL4ProfessionType,
            RL4EducationLevel,
            RL4EducationMajor,
            RL4MedisType,
            PaySequent,
            PurposeOfLoan,
            HRPaymentMethod,
            AttedanceInsentif,
            EmploymentType,
            EmploymentCategory,
            TaxStatus,
            SalaryType,
            SalaryComponentGroup,
            EmployeeTypeSalary,
            SalaryCategory,
            IncomeTaxMethod,
            DeductionType,
            JamsostekType,
            ResultType,
            FieldLabor,
            ProcessType,
            OrganizationLevel,
            IdentificationType,
            ApplicantStatus,
            ApplicantSource,
            EmployeeType,
            RemunerationType,
            MedicalPaidRules,
            UnusedBalance,
            DependentPaidRules,
            RequestStatus,
            PreferredSource,
            EducationField,
            InformationFrom,
            DecreeType,
            Dp3,
            EmployeeLeaveType,
            PermissionType,
            EmployeeLeaveRequestStatus,
            StructuralBenefitsType,
            BankHRD,
            IncentiveServiceUnitGroup,
            IncentivePositionGroup,
            IncentivePosition,
            EmployeeShiftType,
            EmployeeScheduleType,
            ProfessionType,
            ProfessionGroup,
            EducationGroup,
            ActivityType,
            TrainingFinancingSources,
            EmployeeTrainingPointType,
            EmployeeTrainingDateSeparator,
            EmployeeTrainingRole,
            OrientationType,
            EducationStatus,
            EducationFinancingSources,
            StudyPeriodStatus,
            WageStructureAndScaleType,
            WageStructureAndScaleItem,
            EmployeeWorkGroup,
            EmployeeWorkSubGroup,
            EmployeeJobPosition,
            RecruitmentTestConclusion,

            AppraisalAnswer,
            AppraisalType,
            AppraisalActionType,

            ClinicalWorkArea,
            ClinicalAuthorityLevel,
            CredentialActionType,
            CredentialQuestionLevel,
            CredentialSupportingDocuments,
            EducationalQualification,
            CredentialingStatus,
            RecredentialReason,
            CredentialingConclusion,
            CredentialingTeamPosition,
            CredentialRecomendationResult,
            CompetencyAssessmentEvalRole,
            MedicalClinicalCompetence,
            MedicalGeneralCompetence,
            MedicalEthicalStanding,
            ClinicalAppoinmentStatus,
            KtklLevel,
            CompetencyAssessmentExplor,
            EthicsCredentialQuestion,
            CredentialEvaluatorNo,
            CredentialEvaluatorRole,

            AddAPReason,
            APWriteOffReason,
            AddARReason,
            ARWriteOffReason,
            ItemTariffRoom,
            ServiceUnitResetPrice,
            ExamSummaryType,
            STBPaymentType,
            PhysicianTypeAnesthetic,
            IcdXMorphologyExc,
            ExcUnitOpLabDirectPayment,
            ServiceUnitAutoMergeBilling,

            //K3RS
            EmployeeIncidentType,
            NeedleType,
            EmployeeInjuryCategory,
            EmployeeIncidentStatus,
            HealthDegreeConclusion,
            EmployeeAccidentReportStatus,

            //KEPK
            ResearchDecision,
            ResearchInstitution,
            ResearchFaculty,
            ResearchMajors,
            EducationDegree,
            ResearchReviewerName,

            //KEHRS
            IncidentReportStatus,
            ParticipantStatus,

            //RENKIN
            PerformancePlanIndicator,
            PerformancePlanDataSource,
            AchievementFormula,
            RealizationFormula,
            SectionPerspective,
            PerformancePlanActivityType,
            ActivityCategory,

            //Nutrient
            FoodGroup1,
            FoodGroup2,
            MealSet,
            DietType,
            DayName,
            DietLiquidTime,
            EatingPatientStatus,
            EatingPatientStatusReason,
            MenuItemFoodGroup,
            LiquidTime,

            //Asset
            AssetsStatus,
            AssetsCriticality,
            AssetsWarrantyContract,
            WorkStatus,
            WorkType,
            WorkPriority,
            WorkTrade,
            FailureCode,
            WasteType,
            AssetUsageTimeEstimation,
            WorkOrderPoint,

            //Patient Safety
            IncidentType,
            IncidentGroup,
            ClinicalImpact,
            IncidentProbabilityFrequency,
            IncidentHandledBy,
            IncidentFollowUp,
            IncidentKtd,
            IncidentOccurredOn,
            IncidentOccurredInPatientsWith,
            SafetyGoals,
            TreatmentForAnimalBites,

            //Risk Management
            RiskManagementCategory,
            RiskManagementImpact,
            RiskManagementProbability,
            RiskManagementBands,
            RiskManagementControlling,

            Opportunity,
            HandWashType,
            HandHygieneNote,
            Apply6StepsResult,
            ApdType,


            //Health and Safety
            IncidentImpact,
            EmployerStatus,
            EmployeeOutpatientTreatment,
            EmployeeTreatment,
            // Nursing Care Standard
            NursingDiagnosaLevel,
            NursingAssessmentType,
            NursingNocType,
            NursingNicType,
            NsDiagnosaType,
            NsEtiologyType,
            NsDiagnosaPrefix,
            NsDiagnosaSuffix,
            NsMandatoryLevel,
            NursingCarePlanning,
            NsType,

            Floor,
            ImageTemplateType,

            //Cssd
            CssdProcessType,
            CssdItemGroup,
            CssdSender,
            DecontaminationPhase,
            AbstersionType,
            CssdPhase,

            //Laundry
            LaundryProcessType,
            LaundryProgram,
            LaundryType,

            ParamedicTypeExcludeInReg,
            StockGroup,
            KioskQueueType,
            KioskQueueStatus,
            KioskQueueFar,
            Procedure,
            ProcedureDiagnoseType,

            LetterType,
            MedicationReason,

            GeneralChateterNo,
            SiliconChateterNo,
            IVChateter,
            InfusSet,
            InfusLocation,
            ExudateCharacter,
            PatientEducationEvaluation,
            PatientEducationProblem,
            PatientEducationMethod,
            PatientEducationRecipient,
            PatientEducationGoal,

            NutritionCarePlanning,
            UserType,
            ParamedicConsultType,
            ConsultAnswerType,
            NounToVerb,
            PrescriptionCategory,
            RadiologyCriticalResults,

            //CRM
            ItemReedemGroup,

            RASPRO,
            AbRestrictionType,
            OrganizationLevelType,
            JenisBlud,
            PelangganBlud,
            UnitBlud,
            RekeningBlud,
            PioCategory,
            PioSource,

            VehicleStatus,
            VehicleType,
            DriverStatus,
            ZatActiveGroup,
            VehicleOrderType,

            BudgetingGroup,
            ItemSubGroup,
            ItemConditionRuleType,

            RenkinJenisKegiatan,
            RenkinPeriodeStatus,
            RenkinTransactionStatus,
            RenkinRumusCapaian,
            RenkinRumusRealisasi,
            EsoStatus,
            EsoManifestation,
            EsoComorbid,
            EsoScale,
            NervusCranialis,
            GcsEye,
            GcsMotor,
            GcsVerbal,
            HaisMonitoring,
            GeneralCleanliness,
            MedicalStorage,
            ManagementWaste,
            MonitoringToilet,
            ComplianceWasteDisposal,
            ManagementSharpsWaste,
            LinenHandling,
            BirthMethodPhr,
            CollectMethod,

            //Allergy
            AllergyCategory,
            AllergyClinicalStatus,
            AllergyVerificationStatus,
            AllergySatuSehat,

        }

        public enum AutoNumber
        {
            InvoiceARCustomerNo,
            InvoicePaymentARCustomerNo,
            PaymentOrderNo,
            CommunicationID,
            AppointmentNo,
            AppointmentNoPostRanap,
            AppointmentNoWebService,
            AnnouncementNo,
            MedicalNo,
            InventoryIssueOut,
            InventoryIssueRequestOut,
            PatientID,
            DownPaymentNo,
            PaymentNo,
            ClosingVisitDpNo,
            PaymentReturnNo,
            PaymentReceiptNo,
            PatientTransfer,
            PaymentCorrectionNo,
            CashManagementNo,
            PrescriptionNo,
            PrescIpNo, //resep ip
            PrescOpNo, //resep op
            PrescRetIpNo, //retur resep ip
            PrescRetOpNo, // retur resep op
            UnitDoseNo, //unit dose
            RegistrationNo,
            RegistrationInfoNo,
            RegInfoMedicNo,
            RequestOrder,
            PurchaseOrder,
            PurchaseOrderReturn,
            PurchaseOrderReceive,
            GrantsReceive,
            DistributionRequest,
            Distribution,
            DistributionConfirm,
            ServiceUnitQueNo,
            TariffRequestNo,
            TariffRequestProcessNo,
            TransactionNo,
            JobOrderNo,
            AutoChargeBedNo,
            AncillaryServiceNo,
            TransCorrectionNo,
            StockAdjustment,
            StockTaking,
            ConsignmentReceive,
            InvoiceARNo,
            InvoicePaymentARNo,
            InvoiceAPNo,
            InvoicePaymentAPNo,
            ServiceUnitBookingNo,
            OpticPrescriptionNo,
            FeePaymentNo,
            FeePaymentGroupNo,
            FeeVerificationNo,
            ReservationID,
            FeeAddDeducNo,
            PhysicianLeave,
            DocumentSignature,
            ProductionOfGoods,
            DirectPurchase,
            AssetMovementNo,
            AssetMaintOrderNo,
            AssetMaintenanceNo,
            TestNumber,
            SupplierContract,
            IntermBill,
            HealthScreeningNo,
            PettyCashTransNo,
            RecalculationProcess,
            ARAddition,
            APAddition,
            ReportRlNo,
            ConsignmentReturn,
            BillingToPatientNo,
            SalesToBranch,
            SalesToBranchReturn,
            BudgetPlanNo,
            NonPatientCharges,
            MrFileBorrowed,
            RequestNonStockItems,
            ReqNonStockItemsConf,
            PrescriptionOrder,
            PatientHealthRecord,
            DestrOfExpItems,
            BudgetPlanApprovalNo,
            GuarantorDepositNo,
            AssetID,
            GuarantorInfoNo,
            AmplopFilmNo,
            DeathCertificateNo,
            PatientDepositNo,
            ReceiptOfSubstitute,
            PriceQuoteRequest,
            ConsignmentTransfer,
            HandHygieneNo,
            ApdSurveyNo,
            ComplaintNo,
            PatIdentificationComplianceNo,
            PatientFallRisk,
            //PatientMembershipNo,
            MembershipNo,
            MembershipEmployeeNo,
            PatientInfoNo,

            ItemRedemptionNo,
            RadiologyFilmNo,

            Sales,
            SalesReturn,

            //Asset
            AssetWorkOrder,
            AssetPM,
            SanitationWorkOrder,
            SanitationMaintenanceActivity,
            SanitationWasteReceipt,
            SanitationWasteDisposal,
            SanitationControlSheetNo,

            //Nutrient
            DietPatientNo,
            SnackOrderNo,
            EventMealOrderNo,
            AddMealOrderNo,
            MealOrderNo,
            MealOrderOprNo,
            DietLiquidNo,
            NonPatientMealOrderNo,

            //patient safety
            PatientIncidentNo,
            EmpHealthAndSafetyNo,
            QualityIndicatorNo,
            RiskManagement,
            PpiNo,

            //Nursing Care Standard
            NursingCareNo,

            //Pathology Anatomy
            Cytology,
            Histology,
            PapSmear,
            Immunohistochemistry,
            FNAB,
            VC,
            Histochemistry,

            PrescTemplateNo,
            JobOrderTemplateNo,

            //Blood Bank
            BloodBankTxNo,
            BloodReceivedNo,
            BloodTransformNo,
            BloodExterminationNo,

            //Nutrition Care
            NutritionCareNo,

            //Cssd
            CssdRequestNo,
            CssdReceivedNo,
            CssdItemNo,
            CssdUltrasoundNo,
            CssdDttNo,
            CssdProcessNo,
            CssdProcessTo,
            CssdReturnNo,
            CssdPackagingNo,
            CssdDeconImmersionNo,
            CssdDeconAbstersionNo,
            CssdDeconDryingNo,
            CssdFeasibilityTestNo,
            CssdDistributionNo,
            CssdStockOpnameNo,

            //Laundry
            LaundryReceivedNo,
            LaundryReceivedInfNo,
            LaundryProcessNo,
            LaundryProcessInfNo,
            LaundryReProcessNo,
            LaundryReturnNo,
            LaundrySortingNo,
            LaundryRecapNo,
            LaundryDistributionNo,
            LinenExterminationNo,
            LinenRepairingNo,

            //HR
            EmpMedicalInsuranceNo,

            //K3RS
            K3rsFormNo,
            EmployeeIncidentNo,
            EmployeeNsiNo,

            //KEHRS
            IncidentReportNo,

            //Credentialing
            CredentialingNo,
            DispositionNo,
            InvitationNo,

            ClinicalAppraisalNo,

            //Payroll
            EmployeeOvertimeNo,
            EmployeeFormNo,
            ApplicantNo,

            //Master
            ParamedicId,
            GuarantorId,
            SupplierId,
            CustomerId,
            FabricId,
            ReferralGroupId,
            ReferralId,
            KioskQueueNo,

            //Khusus Film No Radiology di RSI
            CRRadiologyFilmNo,
            CTRadiologyFilmNo,

            VehicleTransactionNo,
            GeneralCleanlinessNo,
            MedicalStorageNo,
            ManagementWasteNo,
            MonitoringToiletNo,
            ComplianceWasteDisposalNo,
            ManagementSharpsWasteNo,
            LinenHandlingNo
        }

        public enum RoundingType
        {
            Transaction,
            Payment,
            PaymentWithCard,
            Prescription,
            GlobalTransaction
        }

        public enum Months
        {
            January = 1,
            February = 2,
            March = 3,
            April = 4,
            May = 5,
            June = 6,
            July = 7,
            August = 8,
            September = 9,
            October = 10,
            November = 11,
            December = 12
        };

        public enum DataMode
        {
            Read = 0,
            Edit = 1,
            New = 2
        }
        public sealed class BridgingType
        {
            private readonly string name;
            private readonly int value;

            public static readonly BridgingType BPJS = new BridgingType(1, "BridgingType-001");
            public static readonly BridgingType INACBG = new BridgingType(2, "BridgingType-002");
            public static readonly BridgingType Inhealth = new BridgingType(3, "BridgingType-003");
            public static readonly BridgingType BPJS_TNI_POLRI_PNS = new BridgingType(4, "BridgingType-004");
            public static readonly BridgingType BPJS_PASIEN_UMUM = new BridgingType(5, "BridgingType-005");
            public static readonly BridgingType LINK_LIS = new BridgingType(6, "BridgingType-006");
            public static readonly BridgingType ANTROL = new BridgingType(6, "BridgingType-007");
            public static readonly BridgingType APOTEKONLINE = new BridgingType(18, "BridgingType-018");
            //public static readonly BridgingType SATUSEHAT = new BridgingType(8, Temiang.Avicenna.BusinessObject.AppParameter.GetParameterValue(Temiang.Avicenna.BusinessObject.AppParameter.ParameterItem.SatuSehatBridgingTypeID));

            private BridgingType(int value, string name)
            {
                this.name = name;
                this.value = value;
            }

            public override string ToString()
            {
                return name;
            }
        }

        public sealed class ParamedicType
        {
            private readonly string name;
            private readonly int value;

            public static readonly ParamedicType ClinicalPathologist = new ParamedicType(1, "ParamedicType-014");
            public static readonly ParamedicType LaboratoryAnalyst = new ParamedicType(2, "ParamedicType-015");

            private ParamedicType(int value, string name)
            {
                this.name = name;
                this.value = value;
            }

            public override string ToString()
            {
                return name;
            }
        }

        public sealed class ReferralGroup
        {
            private readonly string name;
            private readonly int value;

            public static readonly ReferralGroup FASKES = new ReferralGroup(98, "FASKES");

            private ReferralGroup(int value, string name)
            {
                this.name = name;
                this.value = value;
            }

            public string Name
            {
                get { return name; }
            }

            public string Value
            {
                get { return value.ToString(); }
            }
        }
    }
}