(function(b,a){a("kendo.color",["kendo.core"],b);
}(function(){var a={id:"color",name:"Color utils",category:"framework",advanced:true,description:"Color utilities used across components",depends:["core"]};
window.kendo=window.kendo||{};
var e=kendo.Class;
var o=kendo.support;
var l={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"00ffff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000000",blanchedalmond:"ffebcd",blue:"0000ff",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",cornsilk:"fff8dc",crimson:"dc143c",cyan:"00ffff",darkblue:"00008b",darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgrey:"a9a9a9",darkgreen:"006400",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",darkslategray:"2f4f4f",darkslategrey:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dimgrey:"696969",dodgerblue:"1e90ff",firebrick:"b22222",floralwhite:"fffaf0",forestgreen:"228b22",fuchsia:"ff00ff",gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",grey:"808080",green:"008000",greenyellow:"adff2f",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgray:"d3d3d3",lightgrey:"d3d3d3",lightgreen:"90ee90",lightpink:"ffb6c1",lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",lightslategray:"778899",lightslategrey:"778899",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"00ff00",limegreen:"32cd32",linen:"faf0e6",magenta:"ff00ff",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370d8",mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"d87093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",powderblue:"b0e0e6",purple:"800080",red:"ff0000",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",slategray:"708090",slategrey:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",wheat:"f5deb3",white:"ffffff",whitesmoke:"f5f5f5",yellow:"ffff00",yellowgreen:"9acd32"};
var c=o.browser;
var k=function(p){var q=Object.keys(l);
q.push("transparent");
var r=new RegExp("^("+q.join("|")+")(\\W|$)","i");
k=function(s){return r.exec(s);
};
return r.exec(p);
};
var b=e.extend({init:function(){},toHSV:function(){return this;
},toRGB:function(){return this;
},toHex:function(){return this.toBytes().toHex();
},toBytes:function(){return this;
},toCss:function(){return"#"+this.toHex();
},toCssRgba:function(){var p=this.toBytes();
return"rgba("+p.r+", "+p.g+", "+p.b+", "+parseFloat(Number(this.a).toFixed(3))+")";
},toDisplay:function(){if(c.msie&&c.version<9){return this.toCss();
}return this.toCssRgba();
},equals:function(p){return p===this||p!==null&&this.toCssRgba()===m(p).toCssRgba();
},diff:function(r){if(r===null){return NaN;
}var p=this.toBytes();
var q=r.toBytes();
return Math.sqrt(Math.pow((p.r-q.r)*0.3,2)+Math.pow((p.g-q.g)*0.59,2)+Math.pow((p.b-q.b)*0.11,2));
},clone:function(){var p=this.toBytes();
if(p===this){p=new d(p.r,p.g,p.b,p.a);
}return p;
}});
var n=b.extend({init:function(t,s,q,p){b.fn.init.call(this);
this.r=t;
this.g=s;
this.b=q;
this.a=p;
},toHSV:function(){var z=this;
var y=z.r;
var t=z.g;
var p=z.b;
var x=Math.min(y,t,p);
var w=Math.max(y,t,p);
var q=w-x;
var B=w;
var u,A;
if(q===0){return new i(0,0,B,this.a);
}if(w!==0){A=q/w;
if(y===w){u=(t-p)/q;
}else{if(t===w){u=2+(p-y)/q;
}else{u=4+(y-t)/q;
}}u*=60;
if(u<0){u+=360;
}}else{A=0;
u=-1;
}return new i(u,A,B,this.a);
},toHSL:function(){var z=this;
var y=z.r;
var t=z.g;
var p=z.b;
var w=Math.max(y,t,p);
var x=Math.min(y,t,p);
var u,A,v=(w+x)/2;
if(w===x){u=A=0;
}else{var q=w-x;
A=v>0.5?q/(2-w-x):q/(w+x);
switch(w){case y:u=(t-p)/q+(t<p?6:0);
break;
case t:u=(p-y)/q+2;
break;
case p:u=(y-t)/q+4;
break;
default:break;
}}return new h(u*60,A*100,v*100,this.a);
},toBytes:function(){return new d(this.r*255,this.g*255,this.b*255,this.a);
}});
var d=n.extend({init:function(t,s,q,p){n.fn.init.call(this,Math.round(t),Math.round(s),Math.round(q),p);
},toRGB:function(){return new n(this.r/255,this.g/255,this.b/255,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toHSL:function(){return this.toRGB().toHSL();
},toHex:function(){return g(this.r,2)+g(this.g,2)+g(this.b,2);
},toBytes:function(){return this;
}});
function g(p,s,q){if(q===void 0){q="0";
}var r=p.toString(16);
while(s>r.length){r=q+r;
}return r;
}var i=b.extend({init:function(q,r,t,p){b.fn.init.call(this);
this.h=q;
this.s=r;
this.v=t;
this.a=p;
},toRGB:function(){var D=this;
var y=D.h;
var E=D.s;
var G=D.v;
var C,x,u;
if(E===0){C=x=u=G;
}else{y/=60;
var z=Math.floor(y);
var w=y-z;
var A=G*(1-E);
var B=G*(1-E*w);
var F=G*(1-E*(1-w));
switch(z){case 0:C=G;
x=F;
u=A;
break;
case 1:C=B;
x=G;
u=A;
break;
case 2:C=A;
x=G;
u=F;
break;
case 3:C=A;
x=B;
u=G;
break;
case 4:C=F;
x=A;
u=G;
break;
default:C=G;
x=A;
u=B;
break;
}}return new n(C,x,u,this.a);
},toHSL:function(){return this.toRGB().toHSL();
},toBytes:function(){return this.toRGB().toBytes();
}});
var h=b.extend({init:function(q,t,r,p){b.fn.init.call(this);
this.h=q;
this.s=t;
this.l=r;
this.a=p;
},toRGB:function(){var v=this.h/360;
var A=this.s/100;
var w=this.l/100;
var z,u,t;
if(A===0){z=u=t=w;
}else{var y=w<0.5?w*(1+A):w+A-w*A;
var x=2*w-y;
z=j(x,y,v+1/3);
u=j(x,y,v);
t=j(x,y,v-1/3);
}return new n(z,u,t,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toBytes:function(){return this.toRGB().toBytes();
}});
function j(r,u,v){var w=v;
if(w<0){w+=1;
}if(w>1){w-=1;
}if(w<1/6){return r+(u-r)*6*w;
}if(w<1/2){return u;
}if(w<2/3){return r+(u-r)*(2/3-w)*6;
}return r;
}function m(t,s){var q,r;
if(t==null||t==="none"){return null;
}if(t instanceof b){return t;
}var p=t.toLowerCase();
if(q=k(p)){if(q[1]==="transparent"){p=new n(1,1,1,0);
}else{p=m(l[q[1]],s);
}p.match=[q[1]];
return p;
}if(q=/^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})\b/i.exec(p)){r=new d(parseInt(q[1],16),parseInt(q[2],16),parseInt(q[3],16),1);
}else{if(q=/^#?([0-9a-f])([0-9a-f])([0-9a-f])\b/i.exec(p)){r=new d(parseInt(q[1]+q[1],16),parseInt(q[2]+q[2],16),parseInt(q[3]+q[3],16),1);
}else{if(q=/^rgb\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)/.exec(p)){r=new d(parseInt(q[1],10),parseInt(q[2],10),parseInt(q[3],10),1);
}else{if(q=/^rgba\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9.]+)\s*\)/.exec(p)){r=new d(parseInt(q[1],10),parseInt(q[2],10),parseInt(q[3],10),parseFloat(q[4]));
}else{if(q=/^rgb\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*\)/.exec(p)){r=new n(parseFloat(q[1])/100,parseFloat(q[2])/100,parseFloat(q[3])/100,1);
}else{if(q=/^rgba\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9.]+)\s*\)/.exec(p)){r=new n(parseFloat(q[1])/100,parseFloat(q[2])/100,parseFloat(q[3])/100,parseFloat(q[4]));
}}}}}}if(r){r.match=q;
}else{if(!s){throw new Error("Cannot parse color: "+p);
}}return r;
}var f=e.extend({init:function(x){var w=this;
if(arguments.length===1){var r=f.formats;
var v=this.resolveColor(x);
for(var s=0;
s<r.length;
s++){var q=r[s].re;
var u=r[s].process;
var t=q.exec(v);
if(t){var p=u(t);
w.r=p[0];
w.g=p[1];
w.b=p[2];
}}}else{this.r=arguments[0];
this.g=arguments[1];
this.b=arguments[2];
}this.r=this.normalizeByte(this.r);
this.g=this.normalizeByte(this.g);
this.b=this.normalizeByte(this.b);
},toHex:function(){var s=this.padDigit;
var t=this.r.toString(16);
var q=this.g.toString(16);
var p=this.b.toString(16);
return"#"+s(t)+s(q)+s(p);
},resolveColor:function(q){var p=q||"black";
if(p.charAt(0)==="#"){p=p.substr(1,6);
}p=p.replace(/ /g,"");
p=p.toLowerCase();
p=f.namedColors[p]||p;
return p;
},normalizeByte:function(p){if(p<0||isNaN(p)){return 0;
}return p>255?255:p;
},padDigit:function(p){return p.length===1?"0"+p:p;
},brightness:function(q){var p=Math.round;
this.r=p(this.normalizeByte(this.r*q));
this.g=p(this.normalizeByte(this.g*q));
this.b=p(this.normalizeByte(this.b*q));
return this;
},percBrightness:function(){return Math.sqrt(0.241*this.r*this.r+0.691*this.g*this.g+0.06800000000000001*this.b*this.b);
}});
f.fromBytes=function(t,s,q,p){return new d(t,s,q,p!=null?p:1);
};
f.fromRGB=function(t,s,q,p){return new n(t,s,q,p!=null?p:1);
};
f.fromHSV=function(q,r,t,p){return new i(q,r,t,p!=null?p:1);
};
f.fromHSL=function(q,t,r,p){return new h(q,t,r,p!=null?p:1);
};
f.formats=[{re:/^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,process:function(p){return[parseInt(p[1],10),parseInt(p[2],10),parseInt(p[3],10)];
}},{re:/^(\w{2})(\w{2})(\w{2})$/,process:function(p){return[parseInt(p[1],16),parseInt(p[2],16),parseInt(p[3],16)];
}},{re:/^(\w{1})(\w{1})(\w{1})$/,process:function(p){return[parseInt(p[1]+p[1],16),parseInt(p[2]+p[2],16),parseInt(p[3]+p[3],16)];
}}];
f.namedColors=l;
kendo.deepExtend(kendo,{parseColor:m,Color:f});
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
