(function(b,a){a("kendo.core",["jquery"],b);
}(function(){var a={id:"core",name:"Core",category:"framework",description:"The core of the Kendo framework."};
(function(b,aR,aM){var W=aR.kendo=aR.kendo||{cultures:{}},D=b.extend,u=b.each,P=b.isArray,au=b.proxy,af=b.noop,aa=Math,aG,T=aR.JSON||{},aF={},aq=/%/,F=/\{(\d+)(:[^\}]+)?\}/g,j=/(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+)?/i,ai=/^(\+|-?)\d+(\.?)\d*$/,G="function",aE="string",ah="number",aj="object",ag="null",i="boolean",aN="undefined",M={},aA={},aD=[].slice,ae=function(){var a4,aY,aX,a2,a3,aW,a5=arguments[0]||{},a0=1,a1=arguments.length,aZ=false;
if(typeof a5==="boolean"){aZ=a5;
a5=arguments[a0]||{};
a0++;
}if(typeof a5!=="object"&&!b.isFunction(a5)){a5={};
}if(a0===a1){a5=this;
a0--;
}for(;
a0<a1;
a0++){if((a3=arguments[a0])!=null){for(a2 in a3){if(a2=="filters"||a2=="concat"||a2==":"){continue;
}a4=a5[a2];
aX=a3[a2];
if(a5===aX){continue;
}if(aZ&&aX&&(b.isPlainObject(aX)||(aY=b.isArray(aX)))){if(aY){aY=false;
aW=a4&&b.isArray(a4)?a4:[];
}else{aW=a4&&b.isPlainObject(a4)?a4:{};
}a5[a2]=ae(aZ,aW,aX);
}else{if(aX!==aM){a5[a2]=aX;
}}}}}return a5;
};
W.version="2019.3.1023".replace(/^\s+|\s+$/g,"");
function k(){}k.extend=function(aZ){var aW=function(){},aY,a1=this,a0=aZ&&aZ.init?aZ.init:function(){a1.apply(this,arguments);
},aX;
aW.prototype=a1.prototype;
aX=a0.fn=a0.prototype=new aW();
for(aY in aZ){if(aZ[aY]!=null&&aZ[aY].constructor===Object){aX[aY]=D(true,{},aW.prototype[aY],aZ[aY]);
}else{aX[aY]=aZ[aY];
}}aX.constructor=a0;
a0.extend=a1.extend;
return a0;
};
k.prototype._initOptions=function(aW){this.options=r({},this.options,aW);
};
var R=W.isFunction=function(aW){return typeof aW==="function";
};
var at=function(){this._defaultPrevented=true;
};
var Q=function(){return this._defaultPrevented===true;
};
var ak=k.extend({init:function(){this._events={};
},bind:function(aW,a0,a4){var a6=this,a2,aX=typeof aW===aE?[aW]:aW,a3,a5,aZ,a1=typeof a0===G,aY;
if(a0===aM){for(a2 in aW){a6.bind(a2,aW[a2]);
}return a6;
}for(a2=0,a3=aX.length;
a2<a3;
a2++){aW=aX[a2];
aZ=a1?a0:a0[aW];
if(aZ){if(a4){a5=aZ;
aZ=function(){a6.unbind(aW,aZ);
a5.apply(a6,arguments);
};
aZ.original=a5;
}aY=a6._events[aW]=a6._events[aW]||[];
aY.push(aZ);
}}return a6;
},one:function(aW,aX){return this.bind(aW,aX,true);
},first:function(aW,a0){var a4=this,a2,aX=typeof aW===aE?[aW]:aW,a3,aZ,a1=typeof a0===G,aY;
for(a2=0,a3=aX.length;
a2<a3;
a2++){aW=aX[a2];
aZ=a1?a0:a0[aW];
if(aZ){aY=a4._events[aW]=a4._events[aW]||[];
aY.unshift(aZ);
}}return a4;
},trigger:function(aX,aW){var a1=this,aY=a1._events[aX],aZ,a0;
if(aY){aW=aW||{};
aW.sender=a1;
aW._defaultPrevented=false;
aW.preventDefault=at;
aW.isDefaultPrevented=Q;
aY=aY.slice();
for(aZ=0,a0=aY.length;
aZ<a0;
aZ++){aY[aZ].call(a1,aW);
}return aW._defaultPrevented===true;
}return false;
},unbind:function(aW,aY){var a0=this,aX=a0._events[aW],aZ;
if(aW===aM){a0._events={};
}else{if(aX){if(aY){for(aZ=aX.length-1;
aZ>=0;
aZ--){if(aX[aZ]===aY||aX[aZ].original===aY){aX.splice(aZ,1);
}}}else{a0._events[aW]=[];
}}}return a0;
}});
function l(aX,aZ){if(aZ){return"'"+aX.split("'").join("\\'").split('\\"').join('\\\\\\"').replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t")+"'";
}else{var aW=aX.charAt(0),aY=aX.substring(1);
if(aW==="="){return"+("+aY+")+";
}else{if(aW===":"){return"+$kendoHtmlEncode("+aY+")+";
}else{return";"+aX+";$kendoOutput+=";
}}}}var h=/^\w+/,w=/\$\{([^}]*)\}/g,x=/\\\}/g,o=/__CURLY__/g,y=/\\#/g,aB=/__SHARP__/g,aV=["","0","00","000","0000"];
aG={paramName:"data",useWithBlock:true,render:function(a0,aW){var aY,aZ,aX="";
for(aY=0,aZ=aW.length;
aY<aZ;
aY++){aX+=a0(aW[aY]);
}return aX;
},compile:function(a5,a1){var a4=D({},this,a1),a2=a4.paramName,aW=a2.match(h)[0],a6=a4.useWithBlock,aZ="var $kendoOutput, $kendoHtmlEncode = kendo.htmlEncode;",aY,a3,a0;
if(R(a5)){return a5;
}aZ+=a6?"with("+a2+"){":"";
aZ+="$kendoOutput=";
a3=a5.replace(x,"__CURLY__").replace(w,"#=$kendoHtmlEncode($1)#").replace(o,"}").replace(y,"__SHARP__").split("#");
for(a0=0;
a0<a3.length;
a0++){aZ+=l(a3[a0],a0%2===0);
}aZ+=a6?";}":";";
aZ+="return $kendoOutput;";
aZ=aZ.replace(aB,"#");
try{aY=new Function(aW,aZ);
aY._slotCount=Math.floor(a3.length/2);
return aY;
}catch(aX){throw new Error(W.format("Invalid template:'{0}' Generated code:'{1}'",a5,aZ));
}}};
function am(aY,aW,aX){aY=aY+"";
aW=aW||2;
aX=aW-aY.length;
if(aX){return aV[aW].substring(0,aX)+aY;
}return aY;
}(function(){var aW=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,aX,aY,aZ={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},a1,a3={}.toString;
if(typeof Date.prototype.toJSON!==G){Date.prototype.toJSON=function(){var a4=this;
return isFinite(a4.valueOf())?am(a4.getUTCFullYear(),4)+"-"+am(a4.getUTCMonth()+1)+"-"+am(a4.getUTCDate())+"T"+am(a4.getUTCHours())+":"+am(a4.getUTCMinutes())+":"+am(a4.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf();
};
}function a0(a4){aW.lastIndex=0;
return aW.test(a4)?'"'+a4.replace(aW,function(a5){var a6=aZ[a5];
return typeof a6===aE?a6:"\\u"+("0000"+a5.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+a4+'"';
}function a2(a7,a4){var a5,a6,bc,a8,a9=aX,ba,bd=a4[a7],bb;
if(bd&&typeof bd===aj&&typeof bd.toJSON===G){bd=bd.toJSON(a7);
}if(typeof a1===G){bd=a1.call(a4,a7,bd);
}bb=typeof bd;
if(bb===aE){return a0(bd);
}else{if(bb===ah){return isFinite(bd)?String(bd):ag;
}else{if(bb===i||bb===ag){return String(bd);
}else{if(bb===aj){if(!bd){return ag;
}aX+=aY;
ba=[];
if(a3.apply(bd)==="[object Array]"){a8=bd.length;
for(a5=0;
a5<a8;
a5++){ba[a5]=a2(a5,bd)||ag;
}bc=ba.length===0?"[]":aX?"[\n"+aX+ba.join(",\n"+aX)+"\n"+a9+"]":"["+ba.join(",")+"]";
aX=a9;
return bc;
}if(a1&&typeof a1===aj){a8=a1.length;
for(a5=0;
a5<a8;
a5++){if(typeof a1[a5]===aE){a6=a1[a5];
bc=a2(a6,bd);
if(bc){ba.push(a0(a6)+(aX?": ":":")+bc);
}}}}else{for(a6 in bd){if(Object.hasOwnProperty.call(bd,a6)){bc=a2(a6,bd);
if(bc){ba.push(a0(a6)+(aX?": ":":")+bc);
}}}}bc=ba.length===0?"{}":aX?"{\n"+aX+ba.join(",\n"+aX)+"\n"+a9+"}":"{"+ba.join(",")+"}";
aX=a9;
return bc;
}}}}}if(typeof T.stringify!==G){T.stringify=function(a7,a5,a6){var a4;
aX="";
aY="";
if(typeof a6===ah){for(a4=0;
a4<a6;
a4+=1){aY+=" ";
}}else{if(typeof a6===aE){aY=a6;
}}a1=a5;
if(a5&&typeof a5!==G&&(typeof a5!==aj||typeof a5.length!==ah)){throw new Error("JSON.stringify");
}return a2("",{"":a7});
};
}}());
(function(){var aY=/dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|HH|H|hh|h|mm|m|fff|ff|f|tt|ss|s|zzz|zz|z|"[^"]*"|'[^']*'/g,bc=/^(n|c|p|e)(\d*)$/i,a6=/(\\.)|(['][^']*[']?)|(["][^"]*["]?)/g,aX=/\,/g,aZ="",a9=".",aW=",",bb="#",be="0",a8="??",a0="en-US",a7={}.toString;
W.cultures["en-US"]={name:a0,numberFormat:{pattern:["-n"],decimals:2,",":",",".":".",groupSize:[3],percent:{pattern:["-n %","n %"],decimals:2,",":",",".":".",groupSize:[3],symbol:"%"},currency:{name:"US Dollar",abbr:"USD",pattern:["($n)","$n"],decimals:2,",":",",".":".",groupSize:[3],symbol:"$"}},calendars:{standard:{days:{names:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],namesAbbr:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],namesShort:["Su","Mo","Tu","We","Th","Fr","Sa"]},months:{names:["January","February","March","April","May","June","July","August","September","October","November","December"],namesAbbr:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},AM:["AM","am","AM"],PM:["PM","pm","PM"],patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",F:"dddd, MMMM dd, yyyy h:mm:ss tt",g:"M/d/yyyy h:mm tt",G:"M/d/yyyy h:mm:ss tt",m:"MMMM dd",M:"MMMM dd",s:"yyyy'-'MM'-'ddTHH':'mm':'ss",t:"h:mm tt",T:"h:mm:ss tt",u:"yyyy'-'MM'-'dd HH':'mm':'ss'Z'",y:"MMMM, yyyy",Y:"MMMM, yyyy"},"/":"/",":":":",firstDay:0,twoDigitYearMax:2029}}};
function a1(bf){if(bf){if(bf.numberFormat){return bf;
}if(typeof bf===aE){var bg=W.cultures;
return bg[bf]||bg[bf.split("-")[0]]||null;
}return null;
}return null;
}function a4(bf){if(bf){bf=a1(bf);
}return bf||W.cultures.current;
}W.culture=function(bg){var bh=W.cultures,bf;
if(bg!==aM){bf=a1(bg)||bh[a0];
bf.calendar=bf.calendars.standard;
bh.current=bf;
}else{return bh.current;
}};
W.findCulture=a1;
W.getCulture=a4;
W.culture(a0);
function a2(bh,bj,bg){bg=a4(bg);
var bf=bg.calendars.standard,bi=bf.days,bk=bf.months;
bj=bf.patterns[bj]||bj;
return bj.replace(aY,function(bl){var bm;
var bn;
var bo;
if(bl==="d"){bn=bh.getDate();
}else{if(bl==="dd"){bn=am(bh.getDate());
}else{if(bl==="ddd"){bn=bi.namesAbbr[bh.getDay()];
}else{if(bl==="dddd"){bn=bi.names[bh.getDay()];
}else{if(bl==="M"){bn=bh.getMonth()+1;
}else{if(bl==="MM"){bn=am(bh.getMonth()+1);
}else{if(bl==="MMM"){bn=bk.namesAbbr[bh.getMonth()];
}else{if(bl==="MMMM"){bn=bk.names[bh.getMonth()];
}else{if(bl==="yy"){bn=am(bh.getFullYear()%100);
}else{if(bl==="yyyy"){bn=am(bh.getFullYear(),4);
}else{if(bl==="h"){bn=bh.getHours()%12||12;
}else{if(bl==="hh"){bn=am(bh.getHours()%12||12);
}else{if(bl==="H"){bn=bh.getHours();
}else{if(bl==="HH"){bn=am(bh.getHours());
}else{if(bl==="m"){bn=bh.getMinutes();
}else{if(bl==="mm"){bn=am(bh.getMinutes());
}else{if(bl==="s"){bn=bh.getSeconds();
}else{if(bl==="ss"){bn=am(bh.getSeconds());
}else{if(bl==="f"){bn=aa.floor(bh.getMilliseconds()/100);
}else{if(bl==="ff"){bn=bh.getMilliseconds();
if(bn>99){bn=aa.floor(bn/10);
}bn=am(bn);
}else{if(bl==="fff"){bn=am(bh.getMilliseconds(),3);
}else{if(bl==="tt"){bn=bh.getHours()<12?bf.AM[0]:bf.PM[0];
}else{if(bl==="zzz"){bm=bh.getTimezoneOffset();
bo=bm<0;
bn=aa.abs(bm/60).toString().split(".")[0];
bm=aa.abs(bm)-bn*60;
bn=(bo?"+":"-")+am(bn);
bn+=":"+am(bm);
}else{if(bl==="zz"||bl==="z"){bn=bh.getTimezoneOffset()/60;
bo=bn<0;
bn=aa.abs(bn).toString().split(".")[0];
bn=(bo?"+":"-")+(bl==="zz"?am(bn):bn);
}}}}}}}}}}}}}}}}}}}}}}}}return bn!==aM?bn:bl.slice(1,bl.length-1);
});
}function a3(bD,bn,bg){bg=a4(bg);
var bE=bg.numberFormat,bj=bE[a9],bH=bE.decimals,bF=bE.pattern[0],bB=[],bN,by,bz,bi,bo,bC=bD<0,bw,bp,bx,bq,bI=aZ,bO=aZ,bv,bA,bf,br,bs,bk,bK,bP,bu,bt,bG,bh,bM,bL=-1,bl;
if(bD===aM){return aZ;
}if(!isFinite(bD)){return bD;
}if(!bn){return bg.name.length?bD.toLocaleString():bD.toString();
}bo=bc.exec(bn);
if(bo){bn=bo[1].toLowerCase();
by=bn==="c";
bz=bn==="p";
if(by||bz){bE=by?bE.currency:bE.percent;
bj=bE[a9];
bH=bE.decimals;
bN=bE.symbol;
bF=bE.pattern[bC?0:1];
}bi=bo[2];
if(bi){bH=+bi;
}if(bn==="e"){var bm=bi?bD.toExponential(bH):bD.toExponential();
return bm.replace(a9,bE[a9]);
}if(bz){bD*=100;
}bD=ba(bD,bH);
bC=bD<0;
bD=bD.split(a9);
bw=bD[0];
bp=bD[1];
if(bC){bw=bw.substring(1);
}bO=a5(bw,0,bw.length,bE);
if(bp){bO+=bj+bp;
}if(bn==="n"&&!bC){return bO;
}bD=aZ;
for(bv=0,bA=bF.length;
bv<bA;
bv++){bf=bF.charAt(bv);
if(bf==="n"){bD+=bO;
}else{if(bf==="$"||bf==="%"){bD+=bN;
}else{bD+=bf;
}}}return bD;
}if(bn.indexOf("'")>-1||bn.indexOf('"')>-1||bn.indexOf("\\")>-1){bn=bn.replace(a6,function(bR){var bS=bR.charAt(0).replace("\\",""),bQ=bR.slice(1).replace(bS,"");
bB.push(bQ);
return a8;
});
}bn=bn.split(";");
if(bC&&bn[1]){bn=bn[1];
bs=true;
}else{if(bD===0&&bn[2]){bn=bn[2];
if(bn.indexOf(bb)==-1&&bn.indexOf(be)==-1){return bn;
}}else{bn=bn[0];
}}bG=bn.indexOf("%");
bh=bn.indexOf("$");
bz=bG!=-1;
by=bh!=-1;
if(bz){bD*=100;
}if(by&&bn[bh-1]==="\\"){bn=bn.split("\\").join("");
by=false;
}if(by||bz){bE=by?bE.currency:bE.percent;
bj=bE[a9];
bH=bE.decimals;
bN=bE.symbol;
}br=bn.indexOf(aW)>-1;
if(br){bn=bn.replace(aX,aZ);
}bk=bn.indexOf(a9);
bA=bn.length;
if(bk!=-1){bp=bD.toString().split("e");
if(bp[1]){bp=ba(bD,Math.abs(bp[1]));
}else{bp=bp[0];
}bp=bp.split(a9)[1]||aZ;
bP=bn.lastIndexOf(be)-bk;
bK=bn.lastIndexOf(bb)-bk;
bu=bP>-1;
bt=bK>-1;
bv=bp.length;
if(!bu&&!bt){bn=bn.substring(0,bk)+bn.substring(bk+1);
bA=bn.length;
bk=-1;
bv=0;
}if(bu&&bP>bK){bv=bP;
}else{if(bK>bP){if(bt&&bv>bK){var bJ=ba(bD,bK,bC);
while(bJ.charAt(bJ.length-1)===be&&bK>0&&bK>bP){bK--;
bJ=ba(bD,bK,bC);
}bv=bK;
}else{if(bu&&bv<bP){bv=bP;
}}}}}bD=ba(bD,bv,bC);
bK=bn.indexOf(bb);
bM=bP=bn.indexOf(be);
if(bK==-1&&bP!=-1){bL=bP;
}else{if(bK!=-1&&bP==-1){bL=bK;
}else{bL=bK>bP?bP:bK;
}}bK=bn.lastIndexOf(bb);
bP=bn.lastIndexOf(be);
if(bK==-1&&bP!=-1){bl=bP;
}else{if(bK!=-1&&bP==-1){bl=bK;
}else{bl=bK>bP?bK:bP;
}}if(bL==bA){bl=bL;
}if(bL!=-1){bO=bD.toString().split(a9);
bw=bO[0];
bp=bO[1]||aZ;
bx=bw.length;
bq=bp.length;
if(bC&&bD*-1>=0){bC=false;
}bD=bn.substring(0,bL);
if(bC&&!bs){bD+="-";
}for(bv=bL;
bv<bA;
bv++){bf=bn.charAt(bv);
if(bk==-1){if(bl-bv<bx){bD+=bw;
break;
}}else{if(bP!=-1&&bP<bv){bI=aZ;
}if(bk-bv<=bx&&bk-bv>-1){bD+=bw;
bv=bk;
}if(bk===bv){bD+=(bp?bj:aZ)+bp;
bv+=bl-bk+1;
continue;
}}if(bf===be){bD+=bf;
bI=bf;
}else{if(bf===bb){bD+=bI;
}}}if(br){bD=a5(bD,bL+(bC&&!bs?1:0),Math.max(bl,bx+bL),bE);
}if(bl>=bL){bD+=bn.substring(bl+1);
}if(by||bz){bO=aZ;
for(bv=0,bA=bD.length;
bv<bA;
bv++){bf=bD.charAt(bv);
bO+=bf==="$"||bf==="%"?bN:bf;
}bD=bO;
}bA=bB.length;
if(bA){for(bv=0;
bv<bA;
bv++){bD=bD.replace(a8,bB[bv]);
}}}return bD;
}var a5=function(bn,bq,bg,bo){var bf=bn.indexOf(bo[a9]);
var bi=bo.groupSize.slice();
var bh=bi.shift();
var bk,bl;
var bj,bp,br;
var bm;
bg=bf!==-1?bf:bg+1;
bk=bn.substring(bq,bg);
bl=bk.length;
if(bl>=bh){bj=bl;
bp=[];
while(bj>-1){br=bk.substring(bj-bh,bj);
if(br){bp.push(br);
}bj-=bh;
bm=bi.shift();
bh=bm!==aM?bm:bh;
if(bh===0){if(bj>0){bp.push(bk.substring(0,bj));
}break;
}}bk=bp.reverse().join(bo[aW]);
bn=bn.substring(0,bq)+bk+bn.substring(bg);
}return bn;
};
var ba=function(bh,bg,bf){bg=bg||0;
bh=bh.toString().split("e");
bh=Math.round(+(bh[0]+"e"+(bh[1]?+bh[1]+bg:bg)));
if(bf){bh=-bh;
}bh=bh.toString().split("e");
bh=+(bh[0]+"e"+(bh[1]?+bh[1]-bg:-bg));
return bh.toFixed(Math.min(bg,20));
};
var bd=function(bh,bg,bf){if(bg){if(a7.call(bh)==="[object Date]"){return a2(bh,bg,bf);
}else{if(typeof bh===ah){return a3(bh,bg,bf);
}}}return bh!==aM?bh:"";
};
W.format=function(bf){var bg=arguments;
return bf.replace(F,function(bi,bh,bj){var bk=bg[parseInt(bh,10)+1];
return bd(bk,bj?bj.substring(1):"");
});
};
W._extractFormat=function(bf){if(bf.slice(0,3)==="{0:"){bf=bf.slice(3,bf.length-1);
}return bf;
};
W._activeElement=function(){try{return document.activeElement;
}catch(bf){return document.documentElement.activeElement;
}};
W._round=ba;
W._outerWidth=function(bf,bg){return b(bf).outerWidth(bg||false)||0;
};
W._outerHeight=function(bf,bg){return b(bf).outerHeight(bg||false)||0;
};
W.toString=bd;
}());
(function(){var a7=/\u00A0/g,aZ=/[eE][\-+]?[0-9]+/,be=/[+|\-]\d{1,2}/,a3=/[+|\-]\d{1,2}:?\d{2}/,aX=/^\/Date\((.*?)\)\/$/,ba=/[+-]\d*/,a0=[[],["G","g","F"],["D","d","y","m","T","t"]],bf=[["yyyy-MM-ddTHH:mm:ss.fffffffzzz","yyyy-MM-ddTHH:mm:ss.fffffff","yyyy-MM-ddTHH:mm:ss.fffzzz","yyyy-MM-ddTHH:mm:ss.fff","ddd MMM dd yyyy HH:mm:ss","yyyy-MM-ddTHH:mm:sszzz","yyyy-MM-ddTHH:mmzzz","yyyy-MM-ddTHH:mmzz","yyyy-MM-ddTHH:mm:ss","yyyy-MM-dd HH:mm:ss","yyyy/MM/dd HH:mm:ss"],["yyyy-MM-ddTHH:mm","yyyy-MM-dd HH:mm","yyyy/MM/dd HH:mm"],["yyyy/MM/dd","yyyy-MM-dd","HH:mm:ss","HH:mm"]],a8={2:/^\d{1,2}/,3:/^\d{1,3}/,4:/^\d{4}/},a9={}.toString;
function bb(bi,bh,bg){return !(bi>=bh&&bi<=bg);
}function aY(bg){return bg.charAt(0);
}function a6(bg){return b.map(bg,aY);
}function aW(bg,bh){if(!bh&&bg.getHours()===23){bg.setHours(bg.getHours()+2);
}}function a4(bh){var bi=0,bj=bh.length,bg=[];
for(;
bi<bj;
bi++){bg[bi]=(bh[bi]+"").toLowerCase();
}return bg;
}function a5(bg){var bh={},bi;
for(bi in bg){bh[bi]=a4(bg[bi]);
}return bh;
}function bc(bM,bp,bl,bJ){if(!bM){return null;
}var by=function(bQ){var bP=0;
while(bp[bv]===bQ){bP++;
bv++;
}if(bP>0){bv-=1;
}return bP;
},br=function(bR){var bQ=a8[bR]||new RegExp("^\\d{1,"+bR+"}"),bP=bM.substr(bN,bR).match(bQ);
if(bP){bP=bP[0];
bN+=bP.length;
return parseInt(bP,10);
}return null;
},bq=function(bW,bR){var bP=0,bQ=bW.length,bU,bV,bT=0,bS=0,bX;
for(;
bP<bQ;
bP++){bU=bW[bP];
bV=bU.length;
bX=bM.substr(bN,bV);
if(bR){bX=bX.toLowerCase();
}if(bX==bU&&bV>bT){bT=bV;
bS=bP;
}}if(bT){bN+=bT;
return bS+1;
}return null;
},bj=function(){var bP=false;
if(bM.charAt(bN)===bp[bv]){bN++;
bP=true;
}return bP;
},bh=bl.calendars.standard,bO=null,bE=null,bn=null,bt=null,bC=null,bI=null,bB=null,bv=0,bN=0,bx=false,bm=new Date(),bK=bh.twoDigitYearMax||2029,bo=bm.getFullYear(),bi,bk,bw,bF,bH,bL,bA,bg,bG,bu,bD,bs,bz;
if(!bp){bp="d";
}bF=bh.patterns[bp];
if(bF){bp=bF;
}bp=bp.split("");
bw=bp.length;
for(;
bv<bw;
bv++){bi=bp[bv];
if(bx){if(bi==="'"){bx=false;
}else{bj();
}}else{if(bi==="d"){bk=by("d");
if(!bh._lowerDays){bh._lowerDays=a5(bh.days);
}if(bn!==null&&bk>2){continue;
}bn=bk<3?br(2):bq(bh._lowerDays[bk==3?"namesAbbr":"names"],true);
if(bn===null||bb(bn,1,31)){return null;
}}else{if(bi==="M"){bk=by("M");
if(!bh._lowerMonths){bh._lowerMonths=a5(bh.months);
}bE=bk<3?br(2):bq(bh._lowerMonths[bk==3?"namesAbbr":"names"],true);
if(bE===null||bb(bE,1,12)){return null;
}bE-=1;
}else{if(bi==="y"){bk=by("y");
bO=br(bk);
if(bO===null){return null;
}if(bk==2){if(typeof bK==="string"){bK=bo+parseInt(bK,10);
}bO=bo-bo%100+bO;
if(bO>bK){bO-=100;
}}}else{if(bi==="h"){by("h");
bt=br(2);
if(bt==12){bt=0;
}if(bt===null||bb(bt,0,11)){return null;
}}else{if(bi==="H"){by("H");
bt=br(2);
if(bt===null||bb(bt,0,23)){return null;
}}else{if(bi==="m"){by("m");
bC=br(2);
if(bC===null||bb(bC,0,59)){return null;
}}else{if(bi==="s"){by("s");
bI=br(2);
if(bI===null||bb(bI,0,59)){return null;
}}else{if(bi==="f"){bk=by("f");
bz=bM.substr(bN,bk).match(a8[3]);
bB=br(bk);
if(bB!==null){bB=parseFloat("0."+bz[0],10);
bB=W._round(bB,3);
bB*=1000;
}if(bB===null||bb(bB,0,999)){return null;
}}else{if(bi==="t"){bk=by("t");
bg=bh.AM;
bG=bh.PM;
if(bk===1){bg=a6(bg);
bG=a6(bG);
}bH=bq(bG);
if(!bH&&!bq(bg)){return null;
}}else{if(bi==="z"){bL=true;
bk=by("z");
if(bM.substr(bN,1)==="Z"){bj();
continue;
}bA=bM.substr(bN,6).match(bk>2?a3:be);
if(!bA){return null;
}bA=bA[0].split(":");
bu=bA[0];
bD=bA[1];
if(!bD&&bu.length>3){bN=bu.length-2;
bD=bu.substring(bN);
bu=bu.substring(0,bN);
}bu=parseInt(bu,10);
if(bb(bu,-12,13)){return null;
}if(bk>2){bD=bA[0][0]+bD;
bD=parseInt(bD,10);
if(isNaN(bD)||bb(bD,-59,59)){return null;
}}}else{if(bi==="'"){bx=true;
bj();
}else{if(!bj()){return null;
}}}}}}}}}}}}}}if(bJ&&!/^\s*$/.test(bM.substr(bN))){return null;
}bs=bt!==null||bC!==null||bI||null;
if(bO===null&&bE===null&&bn===null&&bs){bO=bo;
bE=bm.getMonth();
bn=bm.getDate();
}else{if(bO===null){bO=bo;
}if(bn===null){bn=1;
}}if(bH&&bt<12){bt+=12;
}if(bL){if(bu){bt+=-bu;
}if(bD){bC+=-bD;
}bM=new Date(Date.UTC(bO,bE,bn,bt,bC,bI,bB));
}else{bM=new Date(bO,bE,bn,bt,bC,bI,bB);
aW(bM,bt);
}if(bO<100){bM.setFullYear(bO);
}if(bM.getDate()!==bn&&bL===aM){return null;
}return bM;
}function bd(bg){var bh=bg.substr(0,1)==="-"?-1:1;
bg=bg.substring(1);
bg=parseInt(bg.substr(0,2),10)*60+parseInt(bg.substring(2),10);
return bh*bg;
}function a1(bh){var bm=aa.max(a0.length,bf.length);
var bg=bh.calendar||bh.calendars.standard;
var bn=bg.patterns;
var bi,bj,bl;
var bk=[];
for(bl=0;
bl<bm;
bl++){bi=a0[bl];
for(bj=0;
bj<bi.length;
bj++){bk.push(bn[bi[bj]]);
}bk=bk.concat(bf[bl]);
}return bk;
}function a2(bn,bi,bg,bl){if(a9.call(bn)==="[object Date]"){return bn;
}var bj=0;
var bh=null;
var bk;
var bm;
if(bn&&bn.indexOf("/D")===0){bh=aX.exec(bn);
if(bh){bh=bh[1];
bm=ba.exec(bh.substring(1));
bh=new Date(parseInt(bh,10));
if(bm){bm=bd(bm[0]);
bh=W.timezone.apply(bh,0);
bh=W.timezone.convert(bh,0,-1*bm);
}return bh;
}}bg=W.getCulture(bg);
if(!bi){bi=a1(bg);
}bi=P(bi)?bi:[bi];
bk=bi.length;
for(;
bj<bk;
bj++){bh=bc(bn,bi[bj],bg,bl);
if(bh){return bh;
}}return bh;
}W.parseDate=function(bi,bh,bg){return a2(bi,bh,bg,false);
};
W.parseExactDate=function(bi,bh,bg){return a2(bi,bh,bg,true);
};
W.parseInt=function(bi,bg){var bh=W.parseFloat(bi,bg);
if(bh){bh=bh|0;
}return bh;
};
W.parseFloat=function(bq,bg,bi){if(!bq&&bq!==0){return null;
}if(typeof bq===ah){return bq;
}bq=bq.toString();
bg=W.getCulture(bg);
var bl=bg.numberFormat,bn=bl.percent,bh=bl.currency,bp=bh.symbol,bo=bn.symbol,bk=bq.indexOf("-"),bm,bj;
if(aZ.test(bq)){bq=parseFloat(bq.replace(bl["."],"."));
if(isNaN(bq)){bq=null;
}return bq;
}if(bk>0){return null;
}else{bk=bk>-1;
}if(bq.indexOf(bp)>-1||bi&&bi.toLowerCase().indexOf("c")>-1){bl=bh;
bm=bl.pattern[0].replace("$",bp).split("n");
if(bq.indexOf(bm[0])>-1&&bq.indexOf(bm[1])>-1){bq=bq.replace(bm[0],"").replace(bm[1],"");
bk=true;
}}else{if(bq.indexOf(bo)>-1){bj=true;
bl=bn;
bp=bo;
}}bq=bq.replace("-","").replace(bp,"").replace(a7," ").split(bl[","].replace(a7," ")).join("").replace(bl["."],".");
bq=parseFloat(bq);
if(isNaN(bq)){bq=null;
}else{if(bk){bq*=-1;
}}if(bq&&bj){bq/=100;
}return bq;
};
}());
function L(aX){var aZ=aX.css(W.support.transitions.css+"box-shadow")||aX.css("box-shadow"),aY=aZ?aZ.match(j)||[0,0,0,0,0]:[0,0,0,0,0],aW=aa.max(+aY[3],+(aY[4]||0));
return{left:-aY[1]+aW,right:+aY[1]+aW,bottom:+aY[2]+aW};
}function aS(aY,aW){var aX=aF.browser,a4,a2=W._outerWidth,a1=W._outerHeight,a3=aY.parent(),a8=a2(aR);
a3.removeClass("k-animation-container-sm");
if(!a3.hasClass("k-animation-container")){var a7=aY[0].style.width,a0=aY[0].style.height,a6=aq.test(a7),a5=aq.test(a0),aZ=aY.hasClass("k-tooltip")||aY.is(".k-menu-horizontal.k-context-menu");
a4=a6||a5;
if(!a6&&(!aW||aW&&a7||aZ)){a7=aW?a2(aY)+1:a2(aY);
}if(!a5&&(!aW||aW&&a0)||aY.is(".k-menu-horizontal.k-context-menu")){a0=a1(aY);
}aY.wrap(b("<div/>").addClass("k-animation-container").css({width:a7,height:a0}));
a3=aY.parent();
if(a4){aY.css({width:"100%",height:"100%",boxSizing:"border-box",mozBoxSizing:"border-box",webkitBoxSizing:"border-box"});
}}else{aU(aY,aW);
}if(a8<a2(a3)){a3.addClass("k-animation-container-sm");
aU(aY,aW);
}if(aX.msie&&aa.floor(aX.version)<=7){aY.css({zoom:1});
aY.children(".k-menu").width(aY.width());
}return a3;
}function aU(aX,aW){var a0,aZ=W._outerWidth,aY=W._outerHeight,a1=aX.parent(".k-animation-container"),a2=a1[0].style;
if(a1.is(":hidden")){a1.css({display:"",position:""});
}a0=aq.test(a2.width)||aq.test(a2.height);
if(!a0){a1.css({width:aW?aZ(aX)+1:aZ(aX),height:aY(aX),boxSizing:"content-box",mozBoxSizing:"content-box",webkitBoxSizing:"content-box"});
}}function r(aW){var aX=1,aY=arguments.length;
for(aX=1;
aX<aY;
aX++){s(aW,arguments[aX]);
}return aW;
}function s(aX,a6){var a1=W.data.ObservableArray,a0=W.data.LazyObservableArray,aW=W.data.DataSource,aZ=W.data.HierarchicalDataSource,a2,a5,a4,a3,aY;
for(a2 in a6){a5=a6[a2];
a4=typeof a5;
if(a4===aj&&a5!==null){a3=a5.constructor;
}else{a3=null;
}if(a3&&a3!==Array&&a3!==a1&&a3!==a0&&a3!==aW&&a3!==aZ&&a3!==RegExp&&(!W.isFunction(aR.ArrayBuffer)||a3!==ArrayBuffer)){if(a5 instanceof Date){aX[a2]=new Date(a5.getTime());
}else{if(R(a5.clone)){aX[a2]=a5.clone();
}else{aY=aX[a2];
if(typeof aY===aj){aX[a2]=aY||{};
}else{aX[a2]={};
}s(aX[a2],a5);
}}}else{if(a4!==aN){aX[a2]=a5;
}}}return aX;
}function aI(aW,aZ,aX){for(var aY in aZ){if(aZ.hasOwnProperty(aY)&&aZ[aY].test(aW)){return aY;
}}return aX!==aM?aX:aW;
}function aL(aW){return aW.replace(/([a-z][A-Z])/g,function(aX){return aX.charAt(0)+"-"+aX.charAt(1).toLowerCase();
});
}function aJ(aW){return aW.replace(/\-(\w)/g,function(aY,aX){return aX.toUpperCase();
});
}function I(aX,aY){var aZ={},aW;
if(document.defaultView&&document.defaultView.getComputedStyle){aW=document.defaultView.getComputedStyle(aX,"");
if(aY){b.each(aY,function(a0,a1){aZ[a1]=aW.getPropertyValue(a1);
});
}}else{aW=aX.currentStyle;
if(aY){b.each(aY,function(a0,a1){aZ[a1]=aW[aJ(a1)];
});
}}if(!W.size(aZ)){aZ=aW;
}return aZ;
}function S(aW){if(aW&&aW.className&&typeof aW.className==="string"&&aW.className.indexOf("k-auto-scrollable")>-1){return true;
}var aX=I(aW,["overflow"]).overflow;
return aX=="auto"||aX=="scroll";
}function az(aX,a0){var a1=aF.browser.webkit;
var aZ=aF.browser.mozilla;
var aW=aX instanceof b?aX[0]:aX;
var aY;
if(!aX){return;
}aY=aF.isRtl(aX);
if(a0!==aM){if(aY&&a1){aW.scrollLeft=aW.scrollWidth-aW.clientWidth-a0;
}else{if(aY&&aZ){aW.scrollLeft=-a0;
}else{aW.scrollLeft=a0;
}}}else{if(aY&&a1){return aW.scrollWidth-aW.clientWidth-aW.scrollLeft;
}else{return Math.abs(aW.scrollLeft);
}}}(function(){aF._scrollbar=aM;
aF.scrollbar=function(ba){if(!isNaN(aF._scrollbar)&&!ba){return aF._scrollbar;
}else{var a9=document.createElement("div"),bb;
a9.style.cssText="overflow:scroll;overflow-x:hidden;zoom:1;clear:both;display:block";
a9.innerHTML="&nbsp;";
document.body.appendChild(a9);
aF._scrollbar=bb=a9.offsetWidth-a9.scrollWidth;
document.body.removeChild(a9);
return bb;
}};
aF.isRtl=function(a9){return b(a9).closest(".k-rtl").length>0;
};
var a6=document.createElement("table");
try{a6.innerHTML="<tr><td></td></tr>";
aF.tbodyInnerHtml=true;
}catch(aZ){aF.tbodyInnerHtml=false;
}aF.touch="ontouchstart" in aR;
var aX=document.documentElement.style;
var a8=aF.transitions=false,a7=aF.transforms=false,a0="HTMLElement" in aR?HTMLElement.prototype:[];
aF.hasHW3D="WebKitCSSMatrix" in aR&&"m11" in new aR.WebKitCSSMatrix()||"MozPerspective" in aX||"msPerspective" in aX;
aF.cssFlexbox="flexWrap" in aX||"WebkitFlexWrap" in aX||"msFlexWrap" in aX;
u(["Moz","webkit","O","ms"],function(){var bb=this.toString(),a9=typeof a6.style[bb+"Transition"]===aE;
if(a9||typeof a6.style[bb+"Transform"]===aE){var ba=bb.toLowerCase();
a7={css:ba!="ms"?"-"+ba+"-":"",prefix:bb,event:ba==="o"||ba==="webkit"?ba:""};
if(a9){a8=a7;
a8.event=a8.event?a8.event+"TransitionEnd":"transitionend";
}return false;
}});
a6=null;
aF.transforms=a7;
aF.transitions=a8;
aF.devicePixelRatio=aR.devicePixelRatio===aM?1:aR.devicePixelRatio;
try{aF.screenWidth=aR.outerWidth||aR.screen?aR.screen.availWidth:aR.innerWidth;
aF.screenHeight=aR.outerHeight||aR.screen?aR.screen.availHeight:aR.innerHeight;
}catch(aZ){aF.screenWidth=aR.screen.availWidth;
aF.screenHeight=aR.screen.availHeight;
}aF.detectOS=function(bi){var bg=false,be,bd=[],bf=!/mobile safari/i.test(bi),ba={wp:/(Windows Phone(?: OS)?)\s(\d+)\.(\d+(\.\d+)?)/,fire:/(Silk)\/(\d+)\.(\d+(\.\d+)?)/,android:/(Android|Android.*(?:Opera|Firefox).*?\/)\s*(\d+)\.?(\d+(\.\d+)?)?/,iphone:/(iPhone|iPod).*OS\s+(\d+)[\._]([\d\._]+)/,ipad:/(iPad).*OS\s+(\d+)[\._]([\d_]+)/,meego:/(MeeGo).+NokiaBrowser\/(\d+)\.([\d\._]+)/,webos:/(webOS)\/(\d+)\.(\d+(\.\d+)?)/,blackberry:/(BlackBerry|BB10).*?Version\/(\d+)\.(\d+(\.\d+)?)/,playbook:/(PlayBook).*?Tablet\s*OS\s*(\d+)\.(\d+(\.\d+)?)/,windows:/(MSIE)\s+(\d+)\.(\d+(\.\d+)?)/,tizen:/(tizen).*?Version\/(\d+)\.(\d+(\.\d+)?)/i,sailfish:/(sailfish).*rv:(\d+)\.(\d+(\.\d+)?).*firefox/i,ffos:/(Mobile).*rv:(\d+)\.(\d+(\.\d+)?).*Firefox/},bh={ios:/^i(phone|pad|pod)$/i,android:/^android|fire$/i,blackberry:/^blackberry|playbook/i,windows:/windows/,wp:/wp/,flat:/sailfish|ffos|tizen/i,meego:/meego/},bc={tablet:/playbook|ipad|fire/i},bb={omini:/Opera\sMini/i,omobile:/Opera\sMobi/i,firefox:/Firefox|Fennec/i,mobilesafari:/version\/.*safari/i,ie:/MSIE|Windows\sPhone/i,chrome:/chrome|crios/i,webkit:/webkit/i};
for(var a9 in ba){if(ba.hasOwnProperty(a9)){bd=bi.match(ba[a9]);
if(bd){if(a9=="windows"&&"plugins" in navigator){return false;
}bg={};
bg.device=a9;
bg.tablet=aI(a9,bc,false);
bg.browser=aI(bi,bb,"default");
bg.name=aI(a9,bh);
bg[bg.name]=true;
bg.majorVersion=bd[2];
bg.minorVersion=(bd[3]||"0").replace("_",".");
be=bg.minorVersion.replace(".","").substr(0,2);
bg.flatVersion=bg.majorVersion+be+new Array(3-(be.length<3?be.length:2)).join("0");
bg.cordova=typeof aR.PhoneGap!==aN||typeof aR.cordova!==aN;
bg.appMode=aR.navigator.standalone||/file|local|wmapp/.test(aR.location.protocol)||bg.cordova;
if(bg.android&&(aF.devicePixelRatio<1.5&&bg.flatVersion<400||bf)&&(aF.screenWidth>800||aF.screenHeight>800)){bg.tablet=a9;
}break;
}}}return bg;
};
var a3=aF.mobileOS=aF.detectOS(navigator.userAgent);
aF.wpDevicePixelRatio=a3.wp?screen.width/320:0;
aF.hasNativeScrolling=false;
if(a3.ios||a3.android&&a3.majorVersion>2||a3.wp){aF.hasNativeScrolling=a3;
}aF.delayedClick=function(){if(aF.touch){if(a3.ios){return true;
}if(a3.android){if(!aF.browser.chrome){return true;
}if(aF.browser.version<32){return false;
}return !(b("meta[name=viewport]").attr("content")||"").match(/user-scalable=no/i);
}}return false;
};
aF.mouseAndTouchPresent=aF.touch&&!(aF.mobileOS.ios||aF.mobileOS.android);
aF.detectBrowser=function(bd){var ba=false,bc=[],bb={edge:/(edge)[ \/]([\w.]+)/i,webkit:/(chrome|crios)[ \/]([\w.]+)/i,safari:/(webkit)[ \/]([\w.]+)/i,opera:/(opera)(?:.*version|)[ \/]([\w.]+)/i,msie:/(msie\s|trident.*? rv:)([\w.]+)/i,mozilla:/(mozilla)(?:.*? rv:([\w.]+)|)/i};
for(var a9 in bb){if(bb.hasOwnProperty(a9)){bc=bd.match(bb[a9]);
if(bc){ba={};
ba[a9]=true;
ba[bc[1].toLowerCase().split(" ")[0].split("/")[0]]=true;
ba.version=parseInt(document.documentMode||bc[2],10);
break;
}}}return ba;
};
aF.browser=aF.detectBrowser(navigator.userAgent);
aF.detectClipboardAccess=function(){var a9={copy:document.queryCommandSupported?document.queryCommandSupported("copy"):false,cut:document.queryCommandSupported?document.queryCommandSupported("cut"):false,paste:document.queryCommandSupported?document.queryCommandSupported("paste"):false};
if(aF.browser.chrome){a9.paste=false;
if(aF.browser.version>=43){a9.copy=true;
a9.cut=true;
}}return a9;
};
aF.clipboard=aF.detectClipboardAccess();
aF.zoomLevel=function(){try{var a9=aF.browser;
var bc=0;
var ba=document.documentElement;
if(a9.msie&&a9.version==11&&ba.scrollHeight>ba.clientHeight&&!aF.touch){bc=aF.scrollbar();
}return aF.touch?ba.clientWidth/aR.innerWidth:a9.msie&&a9.version>=10?((top||aR).document.documentElement.offsetWidth+bc)/(top||aR).innerWidth:1;
}catch(bb){return 1;
}};
aF.cssBorderSpacing=typeof aX.borderSpacing!="undefined"&&!(aF.browser.msie&&aF.browser.version<8);
(function(a9){var ba="",bb=b(document.documentElement),bc=parseInt(a9.version,10);
if(a9.msie){ba="ie";
}else{if(a9.mozilla){ba="ff";
}else{if(a9.safari){ba="safari";
}else{if(a9.webkit){ba="webkit";
}else{if(a9.opera){ba="opera";
}else{if(a9.edge){ba="edge";
}}}}}}if(ba){ba="k-"+ba+" k-"+ba+bc;
}if(aF.mobileOS){ba+=" k-mobile";
}if(!aF.cssFlexbox){ba+=" k-no-flexbox";
}bb.addClass(ba);
}(aF.browser));
aF.eventCapture=document.documentElement.addEventListener;
var a1=document.createElement("input");
aF.placeholder="placeholder" in a1;
aF.propertyChangeEvent="onpropertychange" in a1;
aF.input=function(){var bd=["number","date","time","month","week","datetime","datetime-local"];
var ba=bd.length;
var be="test";
var bb={};
var a9=0;
var bc;
for(;
a9<ba;
a9++){bc=bd[a9];
a1.setAttribute("type",bc);
a1.value=be;
bb[bc.replace("-","")]=a1.type!=="text"&&a1.value!==be;
}return bb;
}();
a1.style.cssText="float:left;";
aF.cssFloat=!!a1.style.cssFloat;
a1=null;
aF.stableSort=function(){var bb=513;
var ba=[{index:0,field:"b"}];
for(var a9=1;
a9<bb;
a9++){ba.push({index:a9,field:"a"});
}ba.sort(function(bc,bd){return bc.field>bd.field?1:bc.field<bd.field?-1:0;
});
return ba[0].index===1;
}();
aF.matchesSelector=a0.webkitMatchesSelector||a0.mozMatchesSelector||a0.msMatchesSelector||a0.oMatchesSelector||a0.matchesSelector||a0.matches||function(bb){var ba=document.querySelectorAll?(this.parentNode||document).querySelectorAll(bb)||[]:b(bb),a9=ba.length;
while(a9--){if(ba[a9]==this){return true;
}}return false;
};
aF.matchMedia="matchMedia" in aR;
aF.pushState=aR.history&&aR.history.pushState;
var aY=document.documentMode;
aF.hashChange="onhashchange" in aR&&!(aF.browser.msie&&(!aY||aY<=8));
aF.customElements="registerElement" in aR.document;
var aW=aF.browser.chrome,a2=aF.browser.crios,a4=aF.browser.mozilla,a5=aF.browser.safari;
aF.msPointers=!aW&&aR.MSPointerEvent;
aF.pointers=!aW&&!a2&&!a4&&!a5&&aR.PointerEvent;
aF.kineticScrollNeeded=a3&&(aF.touch||aF.msPointers||aF.pointers);
}());
function aC(aX){var aY=0,aW;
for(aW in aX){if(aX.hasOwnProperty(aW)&&aW!="toJSON"){aY++;
}}return aY;
}function K(aW,a1,aY){if(!a1){a1="offset";
}var aX=aW[a1]();
var aZ={top:aX.top,right:aX.right,bottom:aX.bottom,left:aX.left};
if(aF.browser.msie&&(aF.pointers||aF.msPointers)&&!aY){var a0=aF.isRtl(aW)?1:-1;
aZ.top-=aR.pageYOffset-document.documentElement.scrollTop;
aZ.left-=aR.pageXOffset+a0*document.documentElement.scrollLeft;
}return aZ;
}var t={left:{reverse:"right"},right:{reverse:"left"},down:{reverse:"up"},up:{reverse:"down"},top:{reverse:"bottom"},bottom:{reverse:"top"},"in":{reverse:"out"},out:{reverse:"in"}};
function an(aX){var aW={};
u(typeof aX==="string"?aX.split(" "):aX,function(aY){aW[aY]=this;
});
return aW;
}function H(aW){return new W.effects.Element(aW);
}var v={};
b.extend(v,{enabled:true,Element:function(aW){this.element=b(aW);
},promise:function(aW,aX){if(!aW.is(":visible")){aW.css({display:aW.data("olddisplay")||"block"}).css("display");
}if(aX.hide){aW.data("olddisplay",aW.css("display")).hide();
}if(aX.init){aX.init();
}if(aX.completeCallback){aX.completeCallback(aW);
}aW.dequeue();
},disable:function(){this.enabled=false;
this.promise=this.promiseShim;
},enable:function(){this.enabled=true;
this.promise=this.animatedPromise;
}});
v.promiseShim=v.promise;
function ar(aY,aX,aZ,aW){if(typeof aY===aE){if(R(aX)){aW=aX;
aX=400;
aZ=false;
}if(R(aZ)){aW=aZ;
aZ=false;
}if(typeof aX===i){aZ=aX;
aX=400;
}aY={effects:aY,duration:aX,reverse:aZ,complete:aW};
}return D({effects:{},duration:400,reverse:false,init:af,teardown:af,hide:false},aY,{completeCallback:aY.complete,complete:af});
}function d(aY,a2,aX,a3,aW){var aZ=0,a1=aY.length,a0;
for(;
aZ<a1;
aZ++){a0=b(aY[aZ]);
a0.queue(function(){v.promise(a0,ar(a2,aX,a3,aW));
});
}return aY;
}function aK(aY,aX,aZ,aW){if(aX){aX=aX.split(" ");
u(aX,function(a0,a1){aY.toggleClass(a1,aW);
});
}return aY;
}if(!("kendoAnimate" in b.fn)){D(b.fn,{kendoStop:function(aW,aX){return this.stop(aW,aX);
},kendoAnimate:function(aY,aX,aZ,aW){return d(this,aY,aX,aZ,aW);
},kendoAddClass:function(aW,aX){return W.toggleClass(this,aW,aX,true);
},kendoRemoveClass:function(aW,aX){return W.toggleClass(this,aW,aX,false);
},kendoToggleClass:function(aW,aX,aY){return W.toggleClass(this,aW,aX,aY);
}});
}var c=/&/g,Z=/</g,aw=/"/g,g=/'/g,N=/>/g;
function O(aW){return(""+aW).replace(c,"&amp;").replace(Z,"&lt;").replace(N,"&gt;").replace(aw,"&quot;").replace(g,"&#39;");
}function aO(aY){var aX;
try{aX=aR.decodeURIComponent(aY);
}catch(aW){aX=aY.replace(/%u([\dA-F]{4})|%([\dA-F]{2})/gi,function(aZ,a0,a1){return String.fromCharCode(parseInt("0x"+(a0||a1),16));
});
}return aX;
}var B=function(aW){return aW.target;
};
if(aF.touch){B=function(aW){var aX="originalEvent" in aW?aW.originalEvent.changedTouches:"changedTouches" in aW?aW.changedTouches:null;
return aX?document.elementFromPoint(aX[0].clientX,aX[0].clientY):aW.target;
};
u(["swipe","swipeLeft","swipeRight","swipeUp","swipeDown","doubleTap","tap"],function(aW,aX){b.fn[aX]=function(aY){return this.bind(aX,aY);
};
});
}if(aF.touch){if(!aF.mobileOS){aF.mousedown="mousedown touchstart";
aF.mouseup="mouseup touchend";
aF.mousemove="mousemove touchmove";
aF.mousecancel="mouseleave touchcancel";
aF.click="click";
aF.resize="resize";
}else{aF.mousedown="touchstart";
aF.mouseup="touchend";
aF.mousemove="touchmove";
aF.mousecancel="touchcancel";
aF.click="touchend";
aF.resize="orientationchange";
}}else{if(aF.pointers){aF.mousemove="pointermove";
aF.mousedown="pointerdown";
aF.mouseup="pointerup";
aF.mousecancel="pointercancel";
aF.click="pointerup";
aF.resize="orientationchange resize";
}else{if(aF.msPointers){aF.mousemove="MSPointerMove";
aF.mousedown="MSPointerDown";
aF.mouseup="MSPointerUp";
aF.mousecancel="MSPointerCancel";
aF.click="MSPointerUp";
aF.resize="orientationchange resize";
}else{aF.mousemove="mousemove";
aF.mousedown="mousedown";
aF.mouseup="mouseup";
aF.mousecancel="mouseleave";
aF.click="click";
aF.resize="resize";
}}}var aT=function(a1,a2){var a3=a2||"d",aY,aX,aZ,a0,aW=1;
for(aX=0,aZ=a1.length;
aX<aZ;
aX++){a0=a1[aX];
if(a0!==""){aY=a0.indexOf("[");
if(aY!==0){if(aY==-1){a0="."+a0;
}else{aW++;
a0="."+a0.substring(0,aY)+" || {})"+a0.substring(aY);
}}aW++;
a3+=a0+(aX<aZ-1?" || {})":")");
}}return new Array(aW).join("(")+a3;
},Y=/^([a-z]+:)?\/\//i;
D(W,{widgets:[],_widgetRegisteredCallbacks:[],ui:W.ui||{},fx:W.fx||H,effects:W.effects||v,mobile:W.mobile||{},data:W.data||{},dataviz:W.dataviz||{},drawing:W.drawing||{},spreadsheet:{messages:{}},keys:{INSERT:45,DELETE:46,BACKSPACE:8,TAB:9,ENTER:13,ESC:27,LEFT:37,UP:38,RIGHT:39,DOWN:40,END:35,HOME:36,SPACEBAR:32,PAGEUP:33,PAGEDOWN:34,F2:113,F10:121,F12:123,NUMPAD_PLUS:107,NUMPAD_MINUS:109,NUMPAD_DOT:110},support:W.support||aF,animate:W.animate||d,ns:"",attr:function(aW){return"data-"+W.ns+aW;
},getShadows:L,wrap:aS,deepExtend:r,getComputedStyles:I,isScrollable:S,scrollLeft:az,size:aC,toCamelCase:aJ,toHyphens:aL,getOffset:W.getOffset||K,parseEffects:W.parseEffects||an,toggleClass:W.toggleClass||aK,directions:W.directions||t,Observable:ak,Class:k,Template:aG,template:au(aG.compile,aG),render:au(aG.render,aG),stringify:au(T.stringify,T),eventTarget:B,htmlEncode:O,unescape:aO,isLocalUrl:function(aW){return aW&&!Y.test(aW);
},expr:function(aW,aY,aX){aW=aW||"";
if(typeof aY==aE){aX=aY;
aY=false;
}aX=aX||"d";
if(aW&&aW.charAt(0)!=="["){aW="."+aW;
}if(aY){aW=aW.replace(/"([^.]*)\.([^"]*)"/g,'"$1_$DOT$_$2"');
aW=aW.replace(/'([^.]*)\.([^']*)'/g,"'$1_$DOT$_$2'");
aW=aT(aW.split("."),aX);
aW=aW.replace(/_\$DOT\$_/g,".");
}else{aW=aX+aW;
}return aW;
},getter:function(aW,aY){var aX=aW+aY;
return M[aX]=M[aX]||new Function("d","return "+W.expr(aW,aY));
},setter:function(aW){return aA[aW]=aA[aW]||new Function("d,value",W.expr(aW)+"=value");
},accessor:function(aW){return{get:W.getter(aW),set:W.setter(aW)};
},guid:function(){var aX="",aW,aY;
for(aW=0;
aW<32;
aW++){aY=aa.random()*16|0;
if(aW==8||aW==12||aW==16||aW==20){aX+="-";
}aX+=(aW==12?4:aW==16?aY&3|8:aY).toString(16);
}return aX;
},roleSelector:function(aW){return aW.replace(/(\S+)/g,"["+W.attr("role")+"=$1],").slice(0,-1);
},directiveSelector:function(aW){var aY=aW.split(" ");
if(aY){for(var aX=0;
aX<aY.length;
aX++){if(aY[aX]!="view"){aY[aX]=aY[aX].replace(/(\w*)(view|bar|strip|over)$/,"$1-$2");
}}}return aY.join(" ").replace(/(\S+)/g,"kendo-mobile-$1,").slice(0,-1);
},triggeredByInput:function(aW){return/^(label|input|textarea|select)$/i.test(aW.target.tagName);
},onWidgetRegistered:function(aW){for(var aX=0,aY=W.widgets.length;
aX<aY;
aX++){aW(W.widgets[aX]);
}W._widgetRegisteredCallbacks.push(aW);
},logToConsole:function(aX,aY){var aW=aR.console;
if(!W.suppressLog&&typeof aW!="undefined"&&aW.log){aW[aY||"log"](aX);
}}});
var aQ=ak.extend({init:function(aX,aY){var aZ=this;
aZ.element=W.jQuery(aX).handler(aZ);
aZ.angular("init",aY);
ak.fn.init.call(aZ);
var aW=aY?aY.dataSource:null;
if(aW){aY=D({},aY,{dataSource:{}});
}aY=aZ.options=D(true,{},aZ.options,aY);
if(aW){aY.dataSource=aW;
}if(!aZ.element.attr(W.attr("role"))){aZ.element.attr(W.attr("role"),(aY.name||"").toLowerCase());
}aZ.element.data("kendo"+aY.prefix+aY.name,aZ);
aZ.bind(aZ.events,aY);
},events:[],options:{prefix:""},_hasBindingTarget:function(){return !!this.element[0].kendoBindingTarget;
},_tabindex:function(aZ){aZ=aZ||this.wrapper;
var aW=this.element,aY="tabindex",aX=aZ.attr(aY)||aW.attr(aY);
aW.removeAttr(aY);
aZ.attr(aY,!isNaN(aX)?aX:0);
},setOptions:function(aW){this._setEvents(aW);
b.extend(this.options,aW);
},_setEvents:function(aZ){var a0=this,aX=0,aY=a0.events.length,aW;
for(;
aX<aY;
aX++){aW=a0.events[aX];
if(a0.options[aW]&&aZ[aW]){a0.unbind(aW,a0.options[aW]);
if(a0._events&&a0._events[aW]){delete a0._events[aW];
}}}a0.bind(a0.events,aZ);
},resize:function(aX){var aY=this.getSize(),aW=this._size;
if(aX||(aY.width>0||aY.height>0)&&(!aW||aY.width!==aW.width||aY.height!==aW.height)){this._size=aY;
this._resize(aY,aX);
this.trigger("resize",aY);
}},getSize:function(){return W.dimensions(this.element);
},size:function(aW){if(!aW){return this.getSize();
}else{this.setSize(aW);
}},setSize:b.noop,_resize:b.noop,destroy:function(){var aW=this;
aW.element.removeData("kendo"+aW.options.prefix+aW.options.name);
aW.element.removeData("handler");
aW.unbind();
},_destroy:function(){this.destroy();
},angular:function(){},_muteAngularRebind:function(aW){this._muteRebind=true;
aW.call(this);
this._muteRebind=false;
}});
var q=aQ.extend({dataItems:function(){return this.dataSource.flatView();
},_angularItems:function(aW){var aX=this;
aX.angular(aW,function(){return{elements:aX.items(),data:b.map(aX.dataItems(),function(aY){return{dataItem:aY};
})};
});
}});
W.dimensions=function(aY,aW){var aX=aY[0];
if(aW){aY.css(aW);
}return{width:aX.offsetWidth,height:aX.offsetHeight};
};
W.notify=af;
var aH=/template$/i,V=/^\s*(?:\{(?:.|\r\n|\n)*\}|\[(?:.|\r\n|\n)*\])\s*$/,U=/^\{(\d+)(:[^\}]+)?\}|^\[[A-Za-z_]+\]$/,p=/([A-Z])/g;
function ao(aW,aX){var aY;
if(aX.indexOf("data")===0){aX=aX.substring(4);
aX=aX.charAt(0).toLowerCase()+aX.substring(1);
}aX=aX.replace(p,"-$1");
aY=aW.getAttribute("data-"+W.ns+aX);
if(aY===null){aY=aM;
}else{if(aY==="null"){aY=null;
}else{if(aY==="true"){aY=true;
}else{if(aY==="false"){aY=false;
}else{if(ai.test(aY)&&aX!="mask"){aY=parseFloat(aY);
}else{if(V.test(aY)&&!U.test(aY)){aY=new Function("return ("+aY+")")();
}}}}}}return aY;
}function ap(aW,aY,a1){var aZ={},aX,a2,a0=aW.getAttribute("data-"+W.ns+"role");
for(aX in aY){a2=ao(aW,aX);
if(a2!==aM){if(aH.test(aX)&&a0!="drawer"){if(typeof a2==="string"){if(b("#"+a2).length){a2=W.template(b("#"+a2).html());
}else{if(a1){a2=W.template(a1[a2]);
}}}else{a2=aW.getAttribute(aX);
}}aZ[aX]=a2;
}}return aZ;
}W.initWidget=function(aY,a4,a7){var a5,a3,a9,a0,a2,a6,a8,aX,aZ,bb;
if(!a7){a7=W.ui.roles;
}else{if(a7.roles){a7=a7.roles;
}}aY=aY.nodeType?aY:aY[0];
a6=aY.getAttribute("data-"+W.ns+"role");
if(!a6){return;
}aZ=a6.indexOf(".")===-1;
if(aZ){a9=a7[a6];
}else{a9=W.getter(a6)(aR);
}var aW=b(aY).data(),ba=a9?"kendo"+a9.fn.options.prefix+a9.fn.options.name:"";
if(aZ){bb=new RegExp("^kendo.*"+a6+"$","i");
}else{bb=new RegExp("^"+ba+"$","i");
}for(var a1 in aW){if(a1.match(bb)){if(a1===ba){a5=aW[a1];
}else{return aW[a1];
}}}if(!a9){return;
}aX=ao(aY,"dataSource");
a4=b.extend({},ap(aY,a9.fn.options),a4);
if(aX){if(typeof aX===aE){a4.dataSource=W.getter(aX)(aR);
}else{a4.dataSource=aX;
}}for(a0=0,a2=a9.fn.events.length;
a0<a2;
a0++){a3=a9.fn.events[a0];
a8=ao(aY,a3);
if(a8!==aM){a4[a3]=W.getter(a8)(aR);
}}if(!a5){a5=new a9(aY,a4);
}else{if(!b.isEmptyObject(a4)){a5.setOptions(a4);
}}return a5;
};
W.rolesFromNamespaces=function(aY){var aZ=[],aW,aX;
if(!aY[0]){aY=[W.ui,W.dataviz.ui];
}for(aW=0,aX=aY.length;
aW<aX;
aW++){aZ[aW]=aY[aW].roles;
}return D.apply(null,[{}].concat(aZ.reverse()));
};
W.init=function(aW){var aX=W.rolesFromNamespaces(aD.call(arguments,1));
b(aW).find("[data-"+W.ns+"role]").addBack().each(function(){W.initWidget(this,{},aX);
});
};
W.destroy=function(aW){b(aW).find("[data-"+W.ns+"role]").addBack().each(function(){var aX=b(this).data();
for(var aY in aX){if(aY.indexOf("kendo")===0&&typeof aX[aY].destroy===G){aX[aY].destroy();
}}});
};
function n(aW,aX){return b.contains(aW,aX)?-1:1;
}function ax(){var aW=b(this);
return b.inArray(aW.attr("data-"+W.ns+"role"),["slider","rangeslider"])>-1||aW.is(":visible");
}W.resize=function(aW,aX){var aY=b(aW).find("[data-"+W.ns+"role]").addBack().filter(ax);
if(!aY.length){return;
}var aZ=b.makeArray(aY);
aZ.sort(n);
b.each(aZ,function(){var a0=W.widgetInstance(b(this));
if(a0){a0.resize(aX);
}});
};
W.parseOptions=ap;
D(W.ui,{Widget:aQ,DataBoundWidget:q,roles:{},progress:function(aX,a5,a3){var a2=aX.find(".k-loading-mask"),a4=W.support,aW=a4.browser,a0,a1,a6,aY,aZ;
a3=b.extend({},{width:"100%",height:"100%",top:aX.scrollTop(),opacity:false},a3);
aZ=a3.opacity?"k-loading-mask k-opaque":"k-loading-mask";
if(a5){if(!a2.length){a0=a4.isRtl(aX);
a1=a0?"right":"left";
aY=aX.scrollLeft();
a6=aW.webkit?!a0?0:aX[0].scrollWidth-aX.width()-2*aY:0;
a2=b(W.format("<div class='{0}'><span class='k-loading-text'>{1}</span><div class='k-loading-image'/><div class='k-loading-color'/></div>",aZ,W.ui.progress.messages.loading)).width(a3.width).height(a3.height).css("top",a3.top).css(a1,Math.abs(aY)+a6).prependTo(aX);
}}else{if(a2){a2.remove();
}}},plugin:function(a2,a1,a0){var aZ=a2.fn.options.name,aW;
a1=a1||W.ui;
a0=a0||"";
a1[aZ]=a2;
a1.roles[aZ.toLowerCase()]=a2;
aW="getKendo"+a0+aZ;
aZ="kendo"+a0+aZ;
var a3={name:aZ,widget:a2,prefix:a0||""};
W.widgets.push(a3);
for(var aX=0,aY=W._widgetRegisteredCallbacks.length;
aX<aY;
aX++){W._widgetRegisteredCallbacks[aX](a3);
}b.fn[aZ]=function(a5){var a6=this,a4;
if(typeof a5===aE){a4=aD.call(arguments,1);
this.each(function(){var a9=b.data(this,aZ),a7,a8;
if(!a9){throw new Error(W.format("Cannot call method '{0}' of {1} before it is initialized",a5,aZ));
}a7=a9[a5];
if(typeof a7!==G){throw new Error(W.format("Cannot find method '{0}' of {1}",a5,aZ));
}a8=a7.apply(a9,a4);
if(a8!==aM){a6=a8;
return false;
}});
}else{this.each(function(){return new a2(this,a5);
});
}return a6;
};
b.fn[aZ].widget=a2;
b.fn[aW]=function(){return this.data(aZ);
};
}});
W.ui.progress.messages={loading:"Loading..."};
var m={bind:function(){return this;
},nullObject:true,options:{}};
var ab=aQ.extend({init:function(aW,aX){aQ.fn.init.call(this,aW,aX);
this.element.autoApplyNS();
this.wrapper=this.element;
this.element.addClass("km-widget");
},destroy:function(){aQ.fn.destroy.call(this);
this.element.kendoDestroy();
},options:{prefix:"Mobile"},events:[],view:function(){var aW=this.element.closest(W.roleSelector("view splitview modalview drawer"));
return W.widgetInstance(aW,W.mobile.ui)||m;
},viewHasNativeScrolling:function(){var aW=this.view();
return aW&&aW.options.useNativeScrolling;
},container:function(){var aW=this.element.closest(W.roleSelector("view layout modalview drawer splitview"));
return W.widgetInstance(aW.eq(0),W.mobile.ui)||m;
}});
D(W.mobile,{init:function(aW){W.init(aW,W.mobile.ui,W.ui,W.dataviz.ui);
},appLevelNativeScrolling:function(){return W.mobile.application&&W.mobile.application.options&&W.mobile.application.options.useNativeScrolling;
},roles:{},ui:{Widget:ab,DataBoundWidget:q.extend(ab.prototype),roles:{},plugin:function(aW){W.ui.plugin(aW,W.mobile.ui,"Mobile");
}}});
r(W.dataviz,{init:function(aW){W.init(aW,W.dataviz.ui);
},ui:{roles:{},themes:{},views:[],plugin:function(aW){W.ui.plugin(aW,W.dataviz.ui);
}},roles:{}});
W.touchScroller=function(aW,aX){if(!aX){aX={};
}aX.useNative=true;
return b(aW).map(function(aZ,aY){aY=b(aY);
if(aF.kineticScrollNeeded&&W.mobile.ui.Scroller&&!aY.data("kendoMobileScroller")){aY.kendoMobileScroller(aX);
return aY.data("kendoMobileScroller");
}else{return false;
}})[0];
};
W.preventDefault=function(aW){aW.preventDefault();
};
W.widgetInstance=function(aX,a3){var a2=aX.data(W.ns+"role"),a5=[],aZ,a1,aY=aX.data("kendoView");
if(a2){if(a2==="content"){a2="scroller";
}if(a2==="editortoolbar"){var aW=aX.data("kendoEditorToolbar");
if(aW){return aW;
}}if(a2==="view"&&aY){return aY;
}if(a3){if(a3[0]){for(aZ=0,a1=a3.length;
aZ<a1;
aZ++){a5.push(a3[aZ].roles[a2]);
}}else{a5.push(a3.roles[a2]);
}}else{a5=[W.ui.roles[a2],W.dataviz.ui.roles[a2],W.mobile.ui.roles[a2]];
}if(a2.indexOf(".")>=0){a5=[W.getter(a2)(aR)];
}for(aZ=0,a1=a5.length;
aZ<a1;
aZ++){var a4=a5[aZ];
if(a4){var a0=aX.data("kendo"+a4.fn.options.prefix+a4.fn.options.name);
if(a0){return a0;
}}}}};
W.onResize=function(aW){var aX=aW;
if(aF.mobileOS.android){aX=function(){setTimeout(aW,600);
};
}b(aR).on(aF.resize,aX);
return aX;
};
W.unbindResize=function(aW){b(aR).off(aF.resize,aW);
};
W.attrValue=function(aW,aX){return aW.data(W.ns+aX);
};
W.days={Sunday:0,Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6};
function E(aW,aX){var aY=aW.nodeName.toLowerCase();
return(/input|select|textarea|button|object/.test(aY)?!aW.disabled:"a"===aY?aW.href||aX:aX)&&aP(aW);
}function aP(aW){return b.expr.pseudos.visible(aW)&&!b(aW).parents().addBack().filter(function(){return b.css(this,"visibility")==="hidden";
}).length;
}b.extend(b.expr.pseudos,{kendoFocusable:function(aW){var aX=b.attr(aW,"tabindex");
return E(aW,!isNaN(aX)&&aX>-1);
}});
var ac=["mousedown","mousemove","mouseenter","mouseleave","mouseover","mouseout","mouseup","click"];
var C="label, input, [data-rel=external]";
var ad={setupMouseMute:function(){var aY=0,aZ=ac.length,aW=document.documentElement;
if(ad.mouseTrap||!aF.eventCapture){return;
}ad.mouseTrap=true;
ad.bustClick=false;
ad.captureMouse=false;
var aX=function(a0){if(ad.captureMouse){if(a0.type==="click"){if(ad.bustClick&&!b(a0.target).is(C)){a0.preventDefault();
a0.stopPropagation();
}}else{a0.stopPropagation();
}}};
for(;
aY<aZ;
aY++){aW.addEventListener(ac[aY],aX,true);
}},muteMouse:function(aW){ad.captureMouse=true;
if(aW.data.bustClick){ad.bustClick=true;
}clearTimeout(ad.mouseTrapTimeoutID);
},unMuteMouse:function(){clearTimeout(ad.mouseTrapTimeoutID);
ad.mouseTrapTimeoutID=setTimeout(function(){ad.captureMouse=false;
ad.bustClick=false;
},400);
}};
var z={down:"touchstart mousedown",move:"mousemove touchmove",up:"mouseup touchend touchcancel",cancel:"mouseleave touchcancel"};
if(aF.touch&&(aF.mobileOS.ios||aF.mobileOS.android)){z={down:"touchstart",move:"touchmove",up:"touchend touchcancel",cancel:"touchcancel"};
}else{if(aF.pointers){z={down:"pointerdown",move:"pointermove",up:"pointerup",cancel:"pointercancel pointerleave"};
}else{if(aF.msPointers){z={down:"MSPointerDown",move:"MSPointerMove",up:"MSPointerUp",cancel:"MSPointerCancel MSPointerLeave"};
}}}if(aF.msPointers&&!("onmspointerenter" in aR)){b.each({MSPointerEnter:"MSPointerOver",MSPointerLeave:"MSPointerOut"},function(aX,aW){b.event.special[aX]={delegateType:aW,bindType:aW,handle:function(aY){var a1,a2=this,a0=aY.relatedTarget,aZ=aY.handleObj;
if(!a0||a0!==a2&&!b.contains(a2,a0)){aY.type=aZ.origType;
a1=aZ.handler.apply(this,arguments);
aY.type=aW;
}return a1;
}};
});
}var J=function(aW){return z[aW]||aW;
},A=/([^ ]+)/g;
W.applyEventMap=function(aW,aX){aW=aW.replace(A,J);
if(aX){aW=aW.replace(A,"$1."+aX);
}return aW;
};
var al=b.fn.on;
function X(aX,aW){return new X.fn.init(aX,aW);
}ae(true,X,b);
X.fn=X.prototype=new b();
X.fn.constructor=X;
X.fn.init=function(aX,aW){if(aW&&aW instanceof b&&!(aW instanceof X)){aW=X(aW);
}return b.fn.init.call(this,aX,aW,ay);
};
X.fn.init.prototype=X.fn;
var ay=X(document);
D(X.fn,{handler:function(aW){this.data("handler",aW);
return this;
},autoApplyNS:function(aW){this.data("kendoNS",aW||W.guid());
return this;
},on:function(){var a3=this,a1=a3.data("kendoNS");
if(arguments.length===1){return al.call(a3,arguments[0]);
}var aZ=a3,aW=aD.call(arguments);
if(typeof aW[aW.length-1]===aN){aW.pop();
}var aY=aW[aW.length-1],a0=W.applyEventMap(aW[0],a1);
if(aF.mouseAndTouchPresent&&a0.search(/mouse|click/)>-1&&this[0]!==document.documentElement){ad.setupMouseMute();
var a2=aW.length===2?null:aW[1],aX=a0.indexOf("click")>-1&&a0.indexOf("touchend")>-1;
al.call(this,{touchstart:ad.muteMouse,touchend:ad.unMuteMouse},a2,{bustClick:aX});
}if(typeof aY===aE){aZ=a3.data("handler");
aY=aZ[aY];
aW[aW.length-1]=function(a4){aY.call(aZ,a4);
};
}aW[0]=a0;
al.apply(a3,aW);
return a3;
},kendoDestroy:function(aW){aW=aW||this.data("kendoNS");
if(aW){this.off("."+aW);
}return this;
}});
W.jQuery=X;
W.eventMap=z;
W.timezone=function(){var a2={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};
var aZ={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};
function a5(bg,bd){var a9;
var be;
var bc;
var ba=bd[3];
var bb=bd[4];
var bf=bd[5];
var a8=bd[8];
if(!a8){bd[8]=a8={};
}if(a8[bg]){return a8[bg];
}if(!isNaN(bb)){a9=new Date(Date.UTC(bg,a2[ba],bb,bf[0],bf[1],bf[2],0));
}else{if(bb.indexOf("last")===0){a9=new Date(Date.UTC(bg,a2[ba]+1,1,bf[0]-24,bf[1],bf[2],0));
be=aZ[bb.substr(4,3)];
bc=a9.getUTCDay();
a9.setUTCDate(a9.getUTCDate()+be-bc-(be>bc?7:0));
}else{if(bb.indexOf(">=")>=0){a9=new Date(Date.UTC(bg,a2[ba],bb.substr(5),bf[0],bf[1],bf[2],0));
be=aZ[bb.substr(0,3)];
bc=a9.getUTCDay();
a9.setUTCDate(a9.getUTCDate()+be-bc+(be<bc?7:0));
}}}return a8[bg]=a9;
}function a0(bc,ba,be){ba=ba[be];
if(!ba){var bb=be.split(":");
var a8=0;
if(bb.length>1){a8=bb[0]*60+Number(bb[1]);
}return[-1000000,"max","-","Jan",1,[0,0,0],a8,"-"];
}var bd=new Date(bc).getUTCFullYear();
ba=jQuery.grep(ba,function(bg){var bf=bg[0];
var bh=bg[1];
return bf<=bd&&(bh>=bd||bf==bd&&bh=="only"||bh=="max");
});
ba.push(bc);
ba.sort(function(bf,bg){if(typeof bf!="number"){bf=Number(a5(bd,bf));
}if(typeof bg!="number"){bg=Number(a5(bd,bg));
}return bf-bg;
});
var a9=ba[jQuery.inArray(bc,ba)-1]||ba[ba.length-1];
return isNaN(a9)?a9:null;
}function a1(bb,be,a9){var bd=be[a9];
if(typeof bd==="string"){bd=be[bd];
}if(!bd){throw new Error('Timezone "'+a9+'" is either incorrect, or kendo.timezones.min.js is not included.');
}for(var a8=bd.length-1;
a8>=0;
a8--){var ba=bd[a8][3];
if(ba&&bb>ba){break;
}}var bc=bd[a8+1];
if(!bc){throw new Error('Timezone "'+a9+'" not found on '+bb+".");
}return bc;
}function a7(ba,bc,a8,a9){if(typeof ba!=ah){ba=Date.UTC(ba.getFullYear(),ba.getMonth(),ba.getDate(),ba.getHours(),ba.getMinutes(),ba.getSeconds(),ba.getMilliseconds());
}var bb=a1(ba,bc,a9);
return{zone:bb,rule:a0(ba,a8,bb[1])};
}function a3(bb,ba){if(ba=="Etc/UTC"||ba=="Etc/GMT"){return 0;
}var a8=a7(bb,this.zones,this.rules,ba);
var bc=a8.zone;
var a9=a8.rule;
return W.parseFloat(a9?bc[0]-a9[6]:bc[0]);
}function aW(bc,bb){var a9=a7(bc,this.zones,this.rules,bb);
var bd=a9.zone;
var ba=a9.rule;
var a8=bd[2];
if(a8.indexOf("/")>=0){return a8.split("/")[ba&&+ba[6]?1:0];
}else{if(a8.indexOf("%s")>=0){return a8.replace("%s",!ba||ba[7]=="-"?"":ba[7]);
}}return a8;
}function aY(a8,bb,be){var bc=be;
var a9;
if(typeof bb==aE){bb=this.offset(a8,bb);
}if(typeof be==aE){be=this.offset(a8,be);
}var ba=a8.getTimezoneOffset();
a8=new Date(a8.getTime()+(bb-be)*60000);
var bd=a8.getTimezoneOffset();
if(typeof bc==aE){bc=this.offset(a8,bc);
}a9=bd-ba+(be-bc);
return new Date(a8.getTime()+a9*60000);
}function aX(a8,a9){return this.convert(a8,a8.getTimezoneOffset(),a9);
}function a4(a8,a9){return this.convert(a8,a9,a8.getTimezoneOffset());
}function a6(a8){return this.apply(new Date(a8),"Etc/UTC");
}return{zones:{},rules:{},offset:a3,convert:aY,apply:aX,remove:a4,abbr:aW,toLocalDate:a6};
}();
W.date=function(){var a9=60000,a8=86400000;
function aX(bh,bi){if(bi===0&&bh.getHours()===23){bh.setHours(bh.getHours()+2);
return true;
}return false;
}function ba(bh,bi,bj){var bk=bh.getHours();
bj=bj||1;
bi=(bi-bh.getDay()+7*bj)%7;
bh.setDate(bh.getDate()+bi);
aX(bh,bk);
}function aZ(bh,bi,bj){bh=new Date(bh);
ba(bh,bi,bj);
return bh;
}function a0(bh){return new Date(bh.getFullYear(),bh.getMonth(),1);
}function a6(bh){var bj=new Date(bh.getFullYear(),bh.getMonth()+1,0),bi=a0(bh),bk=Math.abs(bj.getTimezoneOffset()-bi.getTimezoneOffset());
if(bk){bj.setHours(bi.getHours()+bk/60);
}return bj;
}function a7(bh,bi){if(bi!==1){return aW(aZ(bh,bi,-1),4);
}return aW(bh,4-(bh.getDay()||7));
}function aY(bh,bm){var bk=new Date(bh.getFullYear(),0,1,-6);
var bl=a7(bh,bm);
var bj=bl.getTime()-bk.getTime();
var bi=Math.floor(bj/a8);
return 1+Math.floor(bi/7);
}function bg(bh,bl){if(bl===aM){bl=W.culture().calendar.firstDay;
}var bj=aW(bh,-7);
var bi=aW(bh,7);
var bk=aY(bh,bl);
if(bk===0){return aY(bj,bl)+1;
}if(bk===53&&aY(bi,bl)>1){return 1;
}return bk;
}function a1(bh){bh=new Date(bh.getFullYear(),bh.getMonth(),bh.getDate(),0,0,0);
aX(bh,0);
return bh;
}function bf(bh){return Date.UTC(bh.getFullYear(),bh.getMonth(),bh.getDate(),bh.getHours(),bh.getMinutes(),bh.getSeconds(),bh.getMilliseconds());
}function a2(bh){return be(bh).getTime()-a1(be(bh));
}function a4(bm,bi,bh){var bk=a2(bi),bj=a2(bh),bl;
if(!bm||bk==bj){return true;
}if(bi>=bh){bh+=a8;
}bl=a2(bm);
if(bk>bl){bl+=a8;
}if(bj<bk){bj+=a8;
}return bl>=bk&&bl<=bj;
}function a3(bm,bi,bh){var bk=bi.getTime(),bj=bh.getTime(),bl;
if(bk>=bj){bj+=a8;
}bl=bm.getTime();
return bl>=bk&&bl<=bj;
}function aW(bh,bj){var bi=bh.getHours();
bh=new Date(bh);
bc(bh,bj*a8);
aX(bh,bi);
return bh;
}function bc(bh,bk,bj){var bl=bh.getTimezoneOffset();
var bi;
bh.setTime(bh.getTime()+bk);
if(!bj){bi=bh.getTimezoneOffset()-bl;
bh.setTime(bh.getTime()+bi*a9);
}}function bb(bh,bi){bh=new Date(bh.getFullYear(),bh.getMonth(),bh.getDate(),bi.getHours(),bi.getMinutes(),bi.getSeconds(),bi.getMilliseconds());
aX(bh,bi.getHours());
return bh;
}function bd(){return a1(new Date());
}function a5(bh){return a1(bh).getTime()==bd().getTime();
}function be(bh){var bi=new Date(1980,1,1,0,0,0);
if(bh){bi.setHours(bh.getHours(),bh.getMinutes(),bh.getSeconds(),bh.getMilliseconds());
}return bi;
}return{adjustDST:aX,dayOfWeek:aZ,setDayOfWeek:ba,getDate:a1,isInDateRange:a3,isInTimeRange:a4,isToday:a5,nextDay:function(bh){return aW(bh,1);
},previousDay:function(bh){return aW(bh,-1);
},toUtcTime:bf,MS_PER_DAY:a8,MS_PER_HOUR:60*a9,MS_PER_MINUTE:a9,setTime:bc,setHours:bb,addDays:aW,today:bd,toInvariantTime:be,firstDayOfMonth:a0,lastDayOfMonth:a6,weekInYear:bg,getMilliseconds:a2};
}();
W.stripWhitespace=function(aX){if(document.createNodeIterator){var aZ=document.createNodeIterator(aX,NodeFilter.SHOW_TEXT,function(a0){return a0.parentNode==aX?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;
},false);
while(aZ.nextNode()){if(aZ.referenceNode&&!aZ.referenceNode.textContent.trim()){aZ.referenceNode.parentNode.removeChild(aZ.referenceNode);
}}}else{for(var aY=0;
aY<aX.childNodes.length;
aY++){var aW=aX.childNodes[aY];
if(aW.nodeType==3&&!/\S/.test(aW.nodeValue)){aX.removeChild(aW);
aY--;
}if(aW.nodeType==1){W.stripWhitespace(aW);
}}}};
var e=aR.requestAnimationFrame||aR.webkitRequestAnimationFrame||aR.mozRequestAnimationFrame||aR.oRequestAnimationFrame||aR.msRequestAnimationFrame||function(aW){setTimeout(aW,1000/60);
};
W.animationFrame=function(aW){e.call(aR,aW);
};
var f=[];
W.queueAnimation=function(aW){f[f.length]=aW;
if(f.length===1){W.runNextAnimation();
}};
W.runNextAnimation=function(){W.animationFrame(function(){if(f[0]){f.shift()();
if(f[0]){W.runNextAnimation();
}}});
};
W.parseQueryStringParams=function(a1){var a0=a1.split("?")[1]||"",aZ={},aY=a0.split(/&|=/),aX=aY.length,aW=0;
for(;
aW<aX;
aW+=2){if(aY[aW]!==""){aZ[decodeURIComponent(aY[aW])]=decodeURIComponent(aY[aW+1]);
}}return aZ;
};
W.elementUnderCursor=function(aW){if(typeof aW.x.client!="undefined"){return document.elementFromPoint(aW.x.client,aW.y.client);
}};
W.wheelDeltaY=function(aZ){var aY=aZ.originalEvent,aX=aY.wheelDeltaY,aW;
if(aY.wheelDelta){if(aX===aM||aX){aW=aY.wheelDelta;
}}else{if(aY.detail&&aY.axis===aY.VERTICAL_AXIS){aW=-aY.detail*10;
}}return aW;
};
W.throttle=function(aX,aW){var a0;
var aY=0;
if(!aW||aW<=0){return aX;
}var aZ=function(){var a4=this;
var a2=+new Date()-aY;
var a1=arguments;
function a3(){aX.apply(a4,a1);
aY=+new Date();
}if(!aY){return a3();
}if(a0){clearTimeout(a0);
}if(a2>aW){a3();
}else{a0=setTimeout(a3,aW-a2);
}};
aZ.cancel=function(){clearTimeout(a0);
};
return aZ;
};
W.caret=function(aX,a5,aY){var a2;
var aZ=a5!==aM;
if(aY===aM){aY=a5;
}if(aX[0]){aX=aX[0];
}if(aZ&&aX.disabled){return;
}try{if(aX.selectionStart!==aM){if(aZ){aX.focus();
var a0=aF.mobileOS;
if(a0.wp||a0.android){setTimeout(function(){aX.setSelectionRange(a5,aY);
},0);
}else{aX.setSelectionRange(a5,aY);
}}else{a5=[aX.selectionStart,aX.selectionEnd];
}}else{if(document.selection){if(b(aX).is(":visible")){aX.focus();
}a2=aX.createTextRange();
if(aZ){a2.collapse(true);
a2.moveStart("character",a5);
a2.moveEnd("character",aY-a5);
a2.select();
}else{var a1=a2.duplicate(),a4,a3;
a2.moveToBookmark(document.selection.createRange().getBookmark());
a1.setEndPoint("EndToStart",a2);
a4=a1.text.length;
a3=a4+a2.text.length;
a5=[a4,a3];
}}}}catch(aW){a5=[];
}return a5;
};
W.compileMobileDirective=function(aX,aY){var aW=aR.angular;
aX.attr("data-"+W.ns+"role",aX[0].tagName.toLowerCase().replace("kendo-mobile-","").replace("-",""));
aW.element(aX).injector().invoke(["$compile",function(aZ){aZ(aX)(aY);
if(!/^\$(digest|apply)$/.test(aY.$$phase)){aY.$digest();
}}]);
return W.widgetInstance(aX,W.mobile.ui);
};
W.antiForgeryTokens=function(){var aY={},aX=b("meta[name=csrf-token],meta[name=_csrf]").attr("content"),aW=b("meta[name=csrf-param],meta[name=_csrf_header]").attr("content");
b("input[name^='__RequestVerificationToken']").each(function(){aY[this.name]=this.value;
});
if(aW!==aM&&aX!==aM){aY[aW]=aX;
}return aY;
};
W.cycleForm=function(aY){var aW=aY.find("input, .k-widget").first();
var aZ=aY.find("button, .k-button").last();
function aX(a0){var a1=W.widgetInstance(a0);
if(a1&&a1.focus){a1.focus();
}else{a0.focus();
}}aZ.on("keydown",function(a0){if(a0.keyCode==W.keys.TAB&&!a0.shiftKey){a0.preventDefault();
aX(aW);
}});
aW.on("keydown",function(a0){if(a0.keyCode==W.keys.TAB&&a0.shiftKey){a0.preventDefault();
aX(aZ);
}});
};
W.focusElement=function(aX){var aZ=[];
var aY=aX.parentsUntil("body").filter(function(a2,a1){var a0=W.getComputedStyles(a1,["overflow"]);
return a0.overflow!=="visible";
}).add(aR);
aY.each(function(a0,a1){aZ[a0]=b(a1).scrollTop();
});
try{aX[0].setActive();
}catch(aW){aX[0].focus();
}aY.each(function(a0,a1){b(a1).scrollTop(aZ[a0]);
});
};
W.matchesMedia=function(aX){var aW=W._bootstrapToMedia(aX)||aX;
return aF.matchMedia&&aR.matchMedia(aW).matches;
};
W._bootstrapToMedia=function(aW){return{xs:"(max-width: 576px)",sm:"(min-width: 576px)",md:"(min-width: 768px)",lg:"(min-width: 992px)",xl:"(min-width: 1200px)"}[aW];
};
(function(){function aY(a2,a3,a8,a7){var a4=b("<form>").attr({action:a8,method:"POST",target:a7});
var a1=W.antiForgeryTokens();
a1.fileName=a3;
var a6=a2.split(";base64,");
a1.contentType=a6[0].replace("data:","");
a1.base64=a6[1];
for(var a5 in a1){if(a1.hasOwnProperty(a5)){b("<input>").attr({value:a1[a5],name:a5,type:"hidden"}).appendTo(a4);
}}a4.appendTo("body").submit().remove();
}var aX=document.createElement("a");
var aW="download" in aX&&!W.support.browser.edge;
function aZ(a5,a6){var a3=a5;
if(typeof a5=="string"){var a8=a5.split(";base64,");
var a4=a8[0];
var a2=atob(a8[1]);
var a1=new Uint8Array(a2.length);
for(var a7=0;
a7<a2.length;
a7++){a1[a7]=a2.charCodeAt(a7);
}a3=new Blob([a1.buffer],{type:a4});
}navigator.msSaveBlob(a3,a6);
}function a0(a1,a3){if(aR.Blob&&a1 instanceof Blob){a1=URL.createObjectURL(a1);
}aX.download=a3;
aX.href=a1;
var a2=document.createEvent("MouseEvents");
a2.initMouseEvent("click",true,false,aR,0,0,0,0,0,false,false,false,false,0,null);
aX.dispatchEvent(a2);
setTimeout(function(){URL.revokeObjectURL(a1);
});
}W.saveAs=function(a1){var a2=aY;
if(!a1.forceProxy){if(aW){a2=a0;
}else{if(navigator.msSaveBlob){a2=aZ;
}}}a2(a1.dataURI,a1.fileName,a1.proxyURL,a1.proxyTarget);
};
}());
W.proxyModelSetters=function av(aW){var aX={};
Object.keys(aW||{}).forEach(function(aY){Object.defineProperty(aX,aY,{get:function(){return aW[aY];
},set:function(aZ){aW[aY]=aZ;
aW.dirty=true;
}});
});
return aX;
};
}($telerik.$,window));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
