(function(b,a){a("kendo.drawer",["kendo.userevents"],b);
}(function(){var a={id:"drawer",name:"Drawer",category:"web",description:"The Kendo Drawer widget provides slide to reveal sidebar",depends:["userevents"]};
(function(b,m){var f=window.kendo,l=f.ui,n=l.Widget,k="show",d="hide",e="itemClick",i="push",h="overlay",g="left",j="right";
var c=f.ui.Widget.extend({init:function(o,p){var r=this;
var s;
n.fn.init.call(this,o,p);
p=r.options;
r._element(o);
r._wrapper(o);
r.position();
r._mode();
if(p.mini){r._miniMode();
}r._initDrawerItems();
if(p.mini&&p.mode!=i){r._setBodyOffset();
}s=this.userEvents=new f.UserEvents(p.mode!=i?b(document.body):this.drawerContainer,{fastTap:true,allowSelection:true});
var q=function(t){if(b.contains(r.drawerItemsWrapper[0],t.event.target)){r._itemClick(t);
}if(r.visible&&!r.trigger("hide",{sender:this})){r.hide();
t.preventDefault();
}};
if(this.options.swipeToOpen){s.bind("start",function(t){r._start(t);
});
s.bind("move",function(t){r._update(t);
});
s.bind("end",function(t){r._end(t);
});
s.bind("tap",q);
}else{s.bind("press",q);
}if(p.minHeight&&p.mode==i){r.drawerContainer.css("min-height",p.minHeight);
}},_element:function(){var r=this;
var p=r.element;
var q=r.options;
var o=r.contentElement=p.children().first();
r.drawerElement=b(q.template);
o.addClass("k-drawer-content");
p.addClass("k-widget k-drawer");
},_wrapper:function(){var u=this.options;
var q=this.drawerElement;
var t=this.element;
var o=this.contentElement;
var r=this.drawerItemsWrapper=q.wrap("<div class='k-drawer-items'></div>").parent();
var s=this.drawerWrapper=r.wrap("<div class='k-drawer-wrapper'></div>").parent();
var p=this.drawerContainer=t.wrap("<div class='k-drawer-container'></div>").parent();
if(u.mini){if(u.mini.width){s.width(u.mini.width);
}}else{s.width(0);
}if(u.mode===i){p.append(o);
}else{if(u.mode===h){p.after(o);
b(document.body).prepend(p);
}}t.append(s);
},_setBodyOffset:function(){var o=this.element.outerWidth();
if(this.leftPositioned){b(document.body).css("padding-left",o);
}else{b(document.body).css("padding-right",o);
}},_initDrawerItems:function(){var p=this.drawerItemsWrapper;
var o=p.find("[data-role='drawer-item']");
var q=p.find("[data-role='drawer-separator']");
o.addClass("k-drawer-item");
q.addClass("k-drawer-item k-drawer-separator");
if(this._selectedItemIndex>=0){o.removeClass("k-state-selected");
o.eq(this._selectedItemIndex).addClass("k-state-selected");
}},_mode:function(){var p=this.options;
var o=this.drawerContainer;
var q;
if(p.mode==i){o.addClass("k-drawer-"+i);
}else{o.addClass("k-drawer-"+h);
q=this.overlayContainer=b('<div class="k-overlay"></div>');
q.hide();
o.prepend(q);
}},_miniMode:function(){var t=this.options;
var o=this.drawerContainer;
var s=t.mini.width;
var r=this._miniTemplate=t.mini.template&&b(t.mini.template);
var p=this.drawerItemsWrapper;
var q=this.drawerWrapper;
o.addClass("k-drawer-mini");
if(r){p.html(r);
}if(s){q.width(s);
}this.minWidth=t.mini.width||this.drawerWrapper.width();
},show:function(){var r=this.drawerWrapper;
var o=this.drawerContainer;
var u=this.options;
var s=o.hasClass("k-drawer-expanded");
var t=this._miniTemplate;
var p=this.drawerElement;
var q=this.drawerItemsWrapper;
if(!s){o.addClass("k-drawer-expanded");
this.visible=true;
}if(t){q.html(p);
this._initDrawerItems();
this._selectItem();
}r.width(u.width);
if(u.mode===h){this.overlayContainer.show();
this.visible=true;
}},hide:function(){var u=this;
var q=u.drawerWrapper;
var o=u.drawerContainer;
var t=this.options;
var p=this.drawerItemsWrapper;
var r=this._miniTemplate;
var s=t.mini&&t.mini.width;
if(this._miniTemplate){p.html(r);
u._initDrawerItems();
this._selectItem();
}if(t.mini){if(s){q.width(s);
}else{q.width("");
}}else{q.width(0);
}if(this.visible){o.removeClass("k-drawer-expanded");
this.visible=false;
}if(t.mode===h){this.overlayContainer.hide();
}},position:function(s){var r=this;
var p=r.options;
var q=s||p.position;
var o=r.drawerContainer;
if(q==j){o.removeClass("k-drawer-"+g);
o.addClass("k-drawer-"+j);
}else{o.removeClass("k-drawer-"+j);
o.addClass("k-drawer-"+g);
}this.leftPositioned=q===g;
},_start:function(q){var s=this;
var r=this.options;
var p=this.drawerWrapper;
var o=this.drawerItemsWrapper;
var t=q.sender;
if(Math.abs(q.x.velocity)<Math.abs(q.y.velocity)||f.triggeredByInput(q.event)){t.cancel();
return;
}if(this.drawerMini){o.html(s.drawerElement);
}p.css("transition","none");
if(r.mode!=i){this.overlayContainer.show();
}},_update:function(o){var q=this.options;
var p=q.mode;
if(p==i){this._push(o);
}else{this._overlay(o);
}},_end:function(p){var u=p.x.velocity;
var r=this.options;
var o=this.drawerWrapper;
var q=o.width();
var s=q>r.width/2;
var v=0.8;
var t;
o.css("transition","all .3s ease-out");
if(this.leftPositioned){t=u>-v&&(u>v||s);
}else{t=u<v&&(u<-v||s);
}if(t){if(this.trigger("show",{sender:this})){p.preventDefault();
this.hide();
}else{this.show();
}}else{if(this.trigger("hide",{sender:this})){p.preventDefault();
this.show();
}else{this.hide();
}}},_overlay:function(s){var t=this.options;
var r=t.mini&&t.mini.width||this.minWidth||0;
var o=this.drawerWrapper;
var p=o.width();
var q;
var u;
u=p+(this.leftPositioned?s.x.delta:-s.x.delta);
q=Math.min(Math.max(u,r),t.width);
s.event.preventDefault();
s.event.stopPropagation();
o.width(q);
},_push:function(s){var t=this.options;
var r=t.mini&&t.mini.width||this.minWidth||0;
var o=this.drawerWrapper;
var p=o.width();
var q;
var u;
u=p+(this.leftPositioned?s.x.delta:-s.x.delta);
q=Math.min(Math.max(u,r),t.width);
s.event.preventDefault();
s.event.stopPropagation();
o.width(q);
},_selectItem:function(o){var p;
if(o){o.addClass("k-state-selected");
this.trigger("itemClick",{item:o,sender:this});
this._selectedItemIndex=o.index();
return;
}p=this._selectedItemIndex;
if(p){this.drawerItemsWrapper.find("[data-role='drawer-item']").eq(p).addClass("k-state-selected");
}},_itemClick:function(o){var q=this;
var p;
if(b(o.event.target).find(".k-drawer-item").length>0){p=b(o.event.target).find(".k-drawer-item");
}else{if(b(o.event.target).closest(".k-drawer-item").length>0){p=b(o.event.target).closest(".k-drawer-item");
}else{if(b(o.event.target).hasClass(".k-drawer-item")){p=b(o.event.target);
}}}q.drawerItemsWrapper.find(".k-drawer-item").removeClass("k-state-selected");
q._selectItem(p);
},destroy:function(){var o=this.options;
if(o.mode!=i){if(this.leftPositioned){b(document.body).css("padding-left",0);
}else{b(document.body).css("padding-right",0);
}}n.fn.destroy.call(this);
this.userEvents.destroy();
f.destroy(this.element);
this.element=this.drawerWrapper=this.drawerElement=this.drawerContainer=this.drawerItemsWrapper=this._miniTemplate=null;
},options:{name:"Drawer",position:g,mode:"overlay",swipeToOpen:true,width:280,mini:false,template:""},events:[d,k,e]});
f.ui.plugin(c);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
