(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,p){var o=this._map;
var m={key:n,value:p};
o[n]=m;
if(!this._head){this._head=this._tail=m;
}else{this._tail.newer=m;
m.older=this._tail;
this._tail=m;
}if(this._length>=this._size){o[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(n){var m=this._map[n];
if(m){if(m===this._head&&m!==this._tail){this._head=m.newer;
this._head.older=null;
}if(m!==this._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=this._tail;
m.newer=null;
this._tail.newer=m;
this._tail=m;
}return m.value;
}}});
var i=/\r?\n|\r|\t/g;
var j=" ";
function g(m){return String(m).replace(i,j);
}function h(n){var o=[];
for(var m in n){o.push(m+n[m]);
}return o.sort().join("");
}function d(o){var m=2166136261;
for(var n=0;
n<o.length;
++n){m+=(m<<1)+(m<<4)+(m<<7)+(m<<8)+(m<<24);
m^=o.charCodeAt(n);
}return m>>>0;
}function l(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: pre!important;";
}var k=kendo.Class.extend({init:function(m){this._cache=new e(1000);
this.options=a.extend({},b,m);
},measure:function(v,t,r){if(r===void 0){r={};
}if(!v){return l();
}var u=h(t);
var o=d(v+u);
var n=this._cache.get(o);
if(n){return n;
}var s=l();
var q=r.box||c;
var m=this._baselineMarker().cloneNode(false);
for(var p in t){var x=t[p];
if(typeof x!=="undefined"){q.style[p]=x;
}}var w=r.normalizeText!==false?g(v):String(v);
q.textContent=w;
q.appendChild(m);
document.body.appendChild(q);
if(w.length){s.width=q.offsetWidth-this.options.baselineMarkerSize;
s.height=q.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(o,s);
}q.parentNode.removeChild(q);
return s;
},_baselineMarker:function(){var m=document.createElement("div");
m.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return m;
}});
k.current=new k();
function f(o,n,m){return k.current.measure(o,n,m);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:k,measureText:f,objectKey:h,hashKey:d,normalizeText:g});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.gantt",["kendo.data","kendo.popup","kendo.window","kendo.resizable","kendo.gantt.list","kendo.gantt.timeline","kendo.grid","kendo.pdf"],b);
}(function(){var a={id:"gantt",name:"Gantt",category:"web",description:"The Gantt component.",depends:["data","popup","resizable","window","gantt.list","gantt.timeline","grid"]};
(function(b,ai){var I=window.kendo;
var J=b.extend({F10:121},I.keys);
var ab="matchMedia" in window;
var g=I.support.browser;
var L=I.support.mobileOS;
var N=I.Observable;
var ak=I.ui.Widget;
var l=I.data.DataSource;
var P=I.data.ObservableObject;
var O=I.data.ObservableArray;
var V=I.data.Query;
var F=b.isArray;
var E=b.inArray;
var G=I.isFunction;
var U=b.proxy;
var v=b.extend;
var H=b.isPlainObject;
var K=b.map;
var R=I._outerWidth;
var Q=I._outerHeight;
var p=3;
var M=".kendoGantt";
var S="p0";
var ac="tabIndex";
var i="click";
var al="width";
var aa="string";
var r={down:{origin:"bottom left",position:"top left"},up:{origin:"top left",position:"bottom left"}};
var e="aria-activedescendant";
var f="aria-label";
var c="gantt_active_cell";
var d="action-option-focused";
var s=".";
var ad="Are you sure you want to delete this task?";
var q="Are you sure you want to delete this dependency?";
var ag=I.template('<button class="#=styles.buttonToggle#" type="button" '+f+'="Toggle"><span class="#=styles.iconToggle#"></span></button>');
var h='<button class="#=styles.button# #=className#" type="button" #if (action) {#data-action="#=action#"#}#><span class="#=iconClass#"></span><span>#=text#</span></button>';
var j='<a class="#=className#" #=attr# href="\\#">#=text#</a>';
var aj=I.template('<li class="#=styles.currentView# #=styles.viewButtonDefault#"><a href="\\#" class="#=styles.link#">&nbps;</a></li>');
var D=I.template('<ul class="#=styles.viewsWrapper#">#for(var view in views){#<li class="#=styles.viewButtonDefault# #=styles.viewButton#-#= view.toLowerCase() #" data-#=ns#name="#=view#"><a href="\\#" class="#=styles.link#">#=views[view].title#</a></li>#}#</ul>');
var ae=I.template('<div class="#=styles.popupWrapper#"><ul class="#=styles.popupList#" role="listbox">#for(var i = 0, l = actions.length; i < l; i++){#<li class="#=styles.item#" data-action="#=actions[i].data#" role="option">#=actions[i].text#</span>#}#</ul></div>');
var n=function(an,ao){var am={name:ao.field,title:ao.title};
var ap=ao.model.fields[ao.field].validation;
if(ap&&H(ap)&&ap.message){am[I.attr("dateCompare-msg")]=ap.message;
}b('<input type="text" required '+I.attr("type")+'="date" '+I.attr("role")+'="datetimepicker" '+I.attr("bind")+'="value:'+ao.field+'" '+I.attr("validate")+"='true' />").attr(am).appendTo(an);
b("<span "+I.attr("for")+'="'+ao.field+'" class="k-invalid-msg"/>').hide().appendTo(an);
};
var X=function(am,an){b('<a href="#" class="'+an.styles.button+'">'+an.messages.assignButton+"</a>").click(an.click).appendTo(am);
};
var B={wrapper:"k-widget k-gantt",rowHeight:"k-gantt-rowheight",listWrapper:"k-gantt-layout k-gantt-treelist",list:"k-gantt-treelist",timelineWrapper:"k-gantt-layout k-gantt-timeline",timeline:"k-gantt-timeline",splitBarWrapper:"k-splitbar k-state-default k-splitbar-horizontal k-splitbar-draggable-horizontal k-gantt-layout",splitBar:"k-splitbar",splitBarHover:"k-splitbar-horizontal-hover",popupWrapper:"k-list-container",popupList:"k-list k-reset",resizeHandle:"k-resize-handle",icon:"k-icon",item:"k-item",line:"k-line",buttonDelete:"k-gantt-delete",buttonCancel:"k-gantt-cancel",buttonSave:"k-gantt-update",buttonToggle:"k-gantt-toggle",primary:"k-primary",hovered:"k-state-hover",selected:"k-state-selected",focused:"k-state-focused",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",tasks:"k-gantt-tasks",popup:{form:"k-popup-edit-form",editForm:"k-gantt-edit-form",formContainer:"k-edit-form-container",resourcesFormContainer:"k-resources-form-container",message:"k-popup-message",buttonsContainer:"k-edit-buttons k-state-default",button:"k-button",editField:"k-edit-field",editLabel:"k-edit-label",resourcesField:"k-gantt-resources"},toolbar:{headerWrapper:"k-floatwrap k-header k-gantt-toolbar",footerWrapper:"k-floatwrap k-header k-gantt-toolbar",toolbar:"k-gantt-toolbar",expanded:"k-state-expanded",views:"k-gantt-views",viewsWrapper:"k-reset k-header k-gantt-views",actions:"k-gantt-actions",button:"k-button k-button-icontext",buttonToggle:"k-button k-button-icon k-gantt-toggle",iconPlus:"k-icon k-i-plus",iconPdf:"k-icon k-i-file-pdf",iconToggle:"k-icon k-i-layout-1-by-4",viewButtonDefault:"k-state-default",viewButton:"k-view",currentView:"k-current-view",link:"k-link",pdfButton:"k-gantt-pdf",appendButton:"k-gantt-create"}};
function Z(am){return"["+I.attr("uid")+(am?"='"+am+"']":"]");
}function ah(am){delete am.name;
delete am.prefix;
delete am.remove;
delete am.edit;
delete am.add;
delete am.navigate;
return am;
}function m(aq){if(aq.filter("[name=end], [name=start]").length){var ap=aq.attr("name");
var at=I.widgetInstance(aq,I.ui);
var an={};
var am=aq;
var ao;
var ar;
while(am!==window&&!ao){am=am.parent();
ao=am.data("kendoEditable");
}ar=ao?ao.options.model:null;
if(!ar){return true;
}an.start=ar.start;
an.end=ar.end;
an[ap]=at?at.value():I.parseDate(aq.val());
return an.start<=an.end;
}return true;
}function w(aq,am){var ar=aq.parents("["+I.attr("role")+'="gantt"]');
var ap=[];
var ao=Y(ar);
aq.attr(ac,0);
if(am){ao.each(function(at,au){ap[at]=b(au).scrollTop();
});
}try{aq[0].setActive();
}catch(an){aq[0].focus();
}if(am){ao.each(function(at,au){b(au).scrollTop(ap[at]);
});
}}function Y(am){return b(am).parentsUntil("body").filter(function(ap,ao){var an=I.getComputedStyles(ao,["overflow"]);
return an.overflow!="visible";
}).add(window);
}var o;
var af=N.extend({init:function(am,an){N.fn.init.call(this);
this.element=am;
this.options=v(true,{},this.options,an);
this._popup();
},options:{direction:"down",navigatable:false},_current:function(ao){var an=x.styles;
var am=this.list.find(s+an.focused);
var ap=am[ao]();
if(ap.length){am.removeClass(an.focused).removeAttr("id");
ap.addClass(an.focused).attr("id",d);
this.list.find("ul").removeAttr(e).attr(e,d);
}},_popup:function(){var ar=this;
var ao=x.styles;
var ap="li"+s+ao.item;
var an=s+ao.toolbar.appendButton;
var am=this.options.messages.actions;
var aq=this.options.navigatable;
this.list=b(ae({styles:ao,actions:[{data:"add",text:am.addChild},{data:"insert-before",text:am.insertBefore},{data:"insert-after",text:am.insertAfter}]}));
this.element.append(this.list);
this.popup=new I.ui.Popup(this.list,v({anchor:this.element.find(an),open:function(){ar._adjustListWidth();
},animation:this.options.animation},r[this.options.direction]));
this.element.on(i+M,an,function(au){var av=b(this);
var at=av.attr(I.attr("action"));
au.preventDefault();
if(at){ar.trigger("command",{type:at});
}else{ar.popup.open();
if(aq){ar.list.find("li:first").addClass(ao.focused).attr("id",d).end().find("ul").attr({TABINDEX:0,"aria-activedescendant":d}).focus();
}}});
this.list.find(ap).hover(function(){b(this).addClass(ao.hovered);
},function(){b(this).removeClass(ao.hovered);
}).end().on(i+M,ap,function(){ar.trigger("command",{type:b(this).attr(I.attr("action"))});
ar.popup.close();
});
if(aq){this.popup.bind("close",function(){ar.list.find(ap).removeClass(ao.focused).end().find("ul").attr(ac,0);
ar.element.parents("["+I.attr("role")+'="gantt"]').find(s+ao.gridContent+" > table:first").focus();
});
this.list.find("ul").on("keydown"+M,function(at){var au=at.keyCode;
switch(au){case J.UP:at.preventDefault();
ar._current("prev");
break;
case J.DOWN:at.preventDefault();
ar._current("next");
break;
case J.ENTER:ar.list.find(s+ao.focused).click();
break;
case J.ESC:at.preventDefault();
ar.popup.close();
break;
}});
}},_adjustListWidth:function(){var ap=this.list;
var ao=x.styles;
var ar=ap[0].style.width;
var at=this.element.find(s+ao.toolbar.appendButton);
var aq=R(ap);
var am;
var an;
if(!ap.data(al)&&ar){return;
}am=window.getComputedStyle?window.getComputedStyle(at[0],null):0;
an=am?parseFloat(am.width):R(at);
if(am&&(g.mozilla||g.msie)){an+=parseFloat(am.paddingLeft)+parseFloat(am.paddingRight)+parseFloat(am.borderLeftWidth)+parseFloat(am.borderRightWidth);
}if(ap.css("box-sizing")!=="border-box"){ar=an-(R(ap)-ap.width());
}else{ar=an;
}if(aq>ar){ar=aq;
}ap.css({fontFamily:at.css("font-family"),width:ar}).data(al,ar);
},destroy:function(){clearTimeout(this._focusTimeout);
this.popup.destroy();
this.element.off(M);
this.list.off(M);
this.unbind();
}});
var k=function(an,am){return function(aq){aq=F(aq)?{data:aq}:aq;
var ap=aq||{};
var ao=ap.data;
ap.data=ao;
if(!(ap instanceof an)&&ap instanceof l){throw new Error("Incorrect DataSource type. Only "+am+" instances are supported");
}return ap instanceof an?ap:new an(ap);
};
};
var z=I.data.Model.define({id:"id",fields:{id:{type:"number"},predecessorId:{type:"number"},successorId:{type:"number"},type:{type:"number"}}});
var A=l.extend({init:function(am){l.fn.init.call(this,v(true,{},{schema:{modelBase:z,model:z}},am));
},successors:function(am){return this._dependencies("predecessorId",am);
},predecessors:function(am){return this._dependencies("successorId",am);
},dependencies:function(am){var an=this.predecessors(am);
var ao=this.successors(am);
an.push.apply(an,ao);
return an;
},_dependencies:function(an,ap){var am=this.view();
var ao={field:an,operator:"eq",value:ap};
am=new V(am).filter(ao).toArray();
return am;
}});
A.create=k(A,"GanttDependencyDataSource");
var C=I.data.Model.define({duration:function(){var am=this.end;
var an=this.start;
return am-an;
},isMilestone:function(){return this.duration()===0;
},_offset:function(ap){var am=["start","end"];
var ao;
for(var an=0;
an<am.length;
an++){ao=new Date(this.get(am[an]).getTime()+ap);
this.set(am[an],ao);
}},id:"id",fields:{id:{type:"number"},parentId:{type:"number",defaultValue:null,validation:{required:true}},orderId:{type:"number",validation:{required:true}},title:{type:"string",defaultValue:"New task"},start:{type:"date",validation:{required:true}},end:{type:"date",validation:{required:true,dateCompare:m,message:"End date should be after or equal to the start date"}},percentComplete:{type:"number",validation:{required:true,min:0,max:1,step:0.01}},summary:{type:"boolean"},expanded:{type:"boolean",defaultValue:true}}});
var y=l.extend({init:function(am){l.fn.init.call(this,v(true,{},{schema:{modelBase:C,model:C}},am));
},remove:function(ao){var an=ao.get("parentId");
var am=this.taskAllChildren(ao);
this._removeItems(am);
ao=l.fn.remove.call(this,ao);
this._childRemoved(an,ao.get("orderId"));
return ao;
},add:function(am){if(!am){return;
}am=this._toGanttTask(am);
return this.insert(this.taskSiblings(am).length,am);
},insert:function(am,an){if(!an){return;
}an=this._toGanttTask(an);
an.set("orderId",am);
an=l.fn.insert.call(this,am,an);
this._reorderSiblings(an,this.taskSiblings(an).length-1);
this._resolveSummaryFields(this.taskParent(an));
return an;
},taskChildren:function(ap){var am=this.view();
var an={field:"parentId",operator:"eq",value:null};
var ao=this._sort&&this._sort.length?this._sort:{field:"orderId",dir:"asc"};
var aq;
if(!!ap){aq=ap.get("id");
if(aq===ai||aq===null||aq===""){return[];
}an.value=aq;
}am=new V(am).filter(an).sort(ao).toArray();
return am;
},taskAllChildren:function(ao){var an=[];
var ap=this;
var am=function(aq){var ar=ap.taskChildren(aq);
an.push.apply(an,ar);
K(ar,am);
};
if(!!ao){am(ao);
}else{an=this.view();
}return an;
},taskSiblings:function(an){if(!an){return null;
}var am=this.taskParent(an);
return this.taskChildren(am);
},taskParent:function(am){if(!am||am.get("parentId")===null){return null;
}return this.get(am.parentId);
},taskLevel:function(ao){var am=0;
var an=this.taskParent(ao);
while(an!==null){am+=1;
an=this.taskParent(an);
}return am;
},taskTree:function(ar){var ao=[];
var an;
var at=this.taskChildren(ar);
for(var ap=0,aq=at.length;
ap<aq;
ap++){an=at[ap];
ao.push(an);
if(an.get("expanded")){var am=this.taskTree(an);
ao.push.apply(ao,am);
}}return ao;
},update:function(aq,ar){var at=this;
var ap;
var ao=function(ay,ax){var au=at.taskAllChildren(ay);
for(var av=0,aw=au.length;
av<aw;
av++){au[av]._offset(ax);
}};
var an=function(au){var av=au.field;
var aw=au.sender;
switch(av){case"start":at._resolveSummaryStart(at.taskParent(aw));
ao(aw,aw.get(av).getTime()-ap.getTime());
break;
case"end":at._resolveSummaryEnd(at.taskParent(aw));
break;
case"percentComplete":at._resolveSummaryPercentComplete(at.taskParent(aw));
break;
case"orderId":at._reorderSiblings(aw,ap);
break;
}};
if(ar.parentId!==ai){ap=aq.get("parentId");
if(ap!==ar.parentId){aq.set("parentId",ar.parentId);
at._childRemoved(ap,aq.get("orderId"));
aq.set("orderId",at.taskSiblings(aq).length-1);
at._resolveSummaryFields(at.taskParent(aq));
}delete ar.parentId;
}aq.bind("change",an);
for(var am in ar){ap=aq.get(am);
aq.set(am,ar[am]);
}aq.unbind("change",an);
},_resolveSummaryFields:function(am){if(!am){return;
}this._updateSummary(am);
if(!this.taskChildren(am).length){return;
}this._resolveSummaryStart(am);
this._resolveSummaryEnd(am);
this._resolveSummaryPercentComplete(am);
},_resolveSummaryStart:function(an){var ao=this;
var am=function(av){var ap=ao.taskChildren(av);
var au=ap[0].start.getTime();
var aq;
for(var ar=1,at=ap.length;
ar<at;
ar++){aq=ap[ar].start.getTime();
if(aq<au){au=aq;
}}return new Date(au);
};
this._updateSummaryRecursive(an,"start",am);
},_resolveSummaryEnd:function(an){var ao=this;
var am=function(av){var ap=ao.taskChildren(av);
var au=ap[0].end.getTime();
var aq;
for(var ar=1,at=ap.length;
ar<at;
ar++){aq=ap[ar].end.getTime();
if(aq>au){au=aq;
}}return new Date(au);
};
this._updateSummaryRecursive(an,"end",am);
},_resolveSummaryPercentComplete:function(an){var ao=this;
var am=function(aq){var ap=ao.taskChildren(aq);
var ar=new V(ap).aggregate([{field:"percentComplete",aggregate:"average"}]);
return ar.percentComplete.average;
};
this._updateSummaryRecursive(an,"percentComplete",am);
},_updateSummaryRecursive:function(ap,an,am){if(!ap){return;
}var aq=am(ap);
ap.set(an,aq);
var ao=this.taskParent(ap);
if(ao){this._updateSummaryRecursive(ao,an,am);
}},_childRemoved:function(ar,ao){var aq=ar===null?null:this.get(ar);
var am=this.taskChildren(aq);
for(var an=ao,ap=am.length;
an<ap;
an++){am[an].set("orderId",an);
}this._resolveSummaryFields(aq);
},_reorderSiblings:function(av,aq){var ar=av.get("orderId");
var am=ar>aq;
var au=am?aq:ar;
var an=am?ar:aq;
var ap=am?au:au+1;
var at=this.taskSiblings(av);
an=Math.min(an,at.length-1);
for(var ao=au;
ao<=an;
ao++){if(at[ao]===av){continue;
}at[ao].set("orderId",ap);
ap+=1;
}},_updateSummary:function(an){if(an!==null){var am=this.taskChildren(an).length;
an.set("summary",am>0);
}},_toGanttTask:function(am){if(!(am instanceof C)){var an=am;
am=this._createNewModel();
am.accept(an);
}return am;
}});
y.create=k(y,"GanttDataSource");
v(true,I.data,{GanttDataSource:y,GanttTask:C,GanttDependencyDataSource:A,GanttDependency:z});
var u={desktop:{dateRange:n,resources:X}};
var t=I.Observable.extend({init:function(am,an){I.Observable.fn.init.call(this);
this.element=am;
this.options=v(true,{},this.options,an);
this.createButton=this.options.createButton;
},fields:function(an,aq){var au=this;
var ar=this.options;
var ap=ar.messages.editor;
var at=ar.resources;
var ao;
var am=function(av){av.preventDefault();
at.editor(au.container.find(s+x.styles.popup.resourcesField),aq);
};
if(ar.editable.template){ao=b.map(aq.fields,function(aw,av){return{field:av};
});
}else{ao=[{field:"title",title:ap.title},{field:"start",title:ap.start,editor:an.dateRange},{field:"end",title:ap.end,editor:an.dateRange},{field:"percentComplete",title:ap.percentComplete,format:S}];
if(aq.get(at.field)){ao.push({field:at.field,title:ap.resources,messages:ap,editor:an.resources,click:am,styles:x.styles.popup});
}}return ao;
},_buildEditTemplate:function(at,ao,am){var aw=this.options.resources;
var ay=this.options.editable.template;
var ax=v({},I.Template,this.options.templateSettings);
var au=ax.paramName;
var av=x.styles.popup;
var ap="";
if(ay){if(typeof ay===aa){ay=I.unescape(ay);
}ap+=I.template(ay,ax)(at);
}else{for(var aq=0,ar=ao.length;
aq<ar;
aq++){var an=ao[aq];
ap+='<div class="'+av.editLabel+'"><label for="'+an.field+'">'+(an.title||an.field||"")+"</label></div>";
if(an.field===aw.field){ap+='<div class="'+av.resourcesField+'" style="display:none"></div>';
}if(!at.editable||at.editable(an.field)){am.push(an);
ap+="<div "+I.attr("container-for")+'="'+an.field+'" class="'+av.editField+'"></div>';
}else{var az="#:";
if(an.field){an=I.expr(an.field,au);
az+=an+"==null?'':"+an;
}else{az+="''";
}az+="#";
az=I.template(az,ax);
ap+='<div class="'+av.editField+'">'+az(at)+"</div>";
}}}return ap;
}});
var T=t.extend({destroy:function(){this.close();
this.unbind();
},editTask:function(am){this.editable=this._createPopupEditor(am);
},close:function(){var an=this;
var am=function(){if(an.editable){an.editable.destroy();
an.editable=null;
an.container=null;
}if(an.popup){an.popup.destroy();
an.popup=null;
}};
if(this.editable&&this.container.is(":visible")){an.trigger("close",{window:an.container});
this.container.data("kendoWindow").bind("deactivate",am).close();
}else{am();
}},showDialog:function(aq){var am=aq.buttons;
var at=x.styles.popup;
var an=I.format('<div class="{0}"><div class="{1}"><p class="{2}">{3}</p><div class="{4}">',at.form,at.formContainer,at.message,aq.text,at.buttonsContainer);
for(var ao=0,ap=am.length;
ao<ap;
ao++){an+=this.createButton(am[ao]);
}an+="</div></div></div>";
var au=this.element;
if(this.popup){this.popup.destroy();
}var ar=this.popup=b(an).appendTo(au).eq(0).on("click",s+at.button,function(aw){aw.preventDefault();
ar.close();
var av=b(aw.currentTarget).index();
am[av].click();
}).kendoWindow({modal:true,autoFocus:false,resizable:false,draggable:false,title:aq.title,visible:false,deactivate:function(){this.destroy();
au.focus();
}}).getKendoWindow();
ar.center().open();
ar.element.find(".k-primary").focus();
},_createPopupEditor:function(aw){var ax=this;
var au={};
var at=this.options.messages;
var aq=x.styles;
var av=aq.popup;
var ar=I.format('<div {0}="{1}" class="{2} {3}"><div class="{4}">',I.attr("uid"),aw.uid,av.form,av.editForm,av.formContainer);
var ap=this.fields(u.desktop,aw);
var an=[];
ar+=this._buildEditTemplate(aw,ap,an);
ar+='<div class="'+av.buttonsContainer+'">';
ar+=this.createButton({name:"update",text:at.save,className:x.styles.primary});
ar+=this.createButton({name:"cancel",text:at.cancel});
if(ax.options.editable.destroy!==false){ar+=this.createButton({name:"delete",text:at.destroy});
}ar+="</div></div></div>";
var am=this.container=b(ar).appendTo(this.element).eq(0).kendoWindow(v({modal:true,resizable:false,draggable:true,title:at.editor.editorTitle,visible:false,close:function(ay){if(ay.userTriggered){if(ax.trigger("cancel",{container:am,model:aw})){ay.preventDefault();
}}}},au));
var ao=am.kendoEditable({fields:an,model:aw,clearContainer:false,validateOnBlur:true,target:ax.options.target}).data("kendoEditable");
I.cycleForm(am);
if(!this.trigger("edit",{container:am,model:aw})){am.data("kendoWindow").center().open();
am.on(i+M,s+aq.buttonCancel,function(ay){ay.preventDefault();
ay.stopPropagation();
ax.trigger("cancel",{container:am,model:aw});
});
am.on(i+M,s+aq.buttonSave,function(ay){ay.preventDefault();
ay.stopPropagation();
var aA=ax.fields(u.desktop,aw);
var aD={};
var az;
for(var aB=0,aC=aA.length;
aB<aC;
aB++){az=aA[aB].field;
aD[az]=aw.get(az);
}ax.trigger("save",{container:am,model:aw,updateInfo:aD});
});
am.on(i+M,s+aq.buttonDelete,function(ay){ay.preventDefault();
ay.stopPropagation();
ax.trigger("remove",{container:am,model:aw});
});
}else{ax.trigger("cancel",{container:am,model:aw});
}return ao;
}});
var W=ak.extend({init:function(am,an){ak.fn.init.call(this,am,an);
this.wrapper=this.element;
this.model=this.options.model;
this.resourcesField=this.options.resourcesField;
this.createButton=this.options.createButton;
this._initContainer();
this._attachHandlers();
},events:["save"],open:function(){this.window.center().open();
},close:function(){this.window.bind("deactivate",U(this.destroy,this)).close();
},destroy:function(){this._dettachHandlers();
this.grid.destroy();
this.grid=null;
this.window.destroy();
this.window=null;
ak.fn.destroy.call(this);
I.destroy(this.wrapper);
this.element=this.wrapper=null;
},_attachHandlers:function(){var an=x.styles;
var ao=this.grid;
var am=this._cancelProxy=U(this._cancel,this);
this.container.on(i+M,s+an.buttonCancel,this._cancelProxy);
this._saveProxy=U(this._save,this);
this.container.on(i+M,s+an.buttonSave,this._saveProxy);
this.window.bind("close",function(ap){if(ap.userTriggered){am(ap);
}});
ao.wrapper.on(i+M,"input[type='checkbox']",function(){var ap=b(this);
var ar=b(ap).closest("tr");
var aq=ao.dataSource.getByUid(ar.attr(I.attr("uid")));
var at=b(ap).is(":checked")?1:"";
aq.set("value",at);
});
},_dettachHandlers:function(){this._cancelProxy=null;
this._saveProxy=null;
this.container.off(M);
this.grid.wrapper.off();
},_cancel:function(am){am.preventDefault();
this.close();
},_save:function(am){am.preventDefault();
this._updateModel();
if(!this.wrapper.is(s+x.styles.popup.resourcesField)){this.trigger("save",{container:this.wrapper,model:this.model});
}this.close();
},_initContainer:function(){var ao=this;
var an=x.styles.popup;
var am=I.format('<div class="{0} {1}"><div class="{2} {3}"/></div>"',an.form,an.editForm,an.formContainer,an.resourcesFormContainer);
am=b(am);
this.container=am.find(s+an.resourcesFormContainer);
this.window=am.kendoWindow({modal:true,resizable:false,draggable:true,visible:false,title:this.options.messages.resourcesEditorTitle,open:function(){ao.grid.resize(true);
}}).data("kendoWindow");
this._resourceGrid();
this._createButtons();
},_resourceGrid:function(){var ao=this;
var an=this.options.messages;
var am=b('<div id="resources-grid"/>').appendTo(this.container);
this.grid=new I.ui.Grid(am,{columns:[{field:"name",title:an.resourcesHeader,template:"<label><input type='checkbox' value='#=name#'# if (value > 0 && value !== null) {#checked='checked'# } #/>#=name#</labe>"},{field:"value",title:an.unitsHeader,template:function(ap){var ar=ap.format;
var aq=ap.value!==null?ap.value:"";
return ar?I.toString(aq,ar):aq;
}}],height:280,sortable:true,editable:true,filterable:true,dataSource:{data:ao.options.data,schema:{model:{id:"id",fields:{id:{from:"id"},name:{from:"name",type:"string",editable:false},value:{from:"value",type:"number",validation:this.options.unitsValidation},format:{from:"format",type:"string"}}}}},save:function(ap){var aq=!!ap.values.value;
ap.container.parent().find("input[type='checkbox']").prop("checked",aq);
}});
},_createButtons:function(){var am=this.options.buttons;
var an='<div class="'+x.styles.popup.buttonsContainer+'">';
for(var ao=0,ap=am.length;
ao<ap;
ao++){an+=this.createButton(am[ao]);
}an+="</div>";
this.container.append(an);
},_updateModel:function(){var ap=[];
var aq;
var am=this.grid.dataSource.data();
for(var an=0,ao=am.length;
an<ao;
an++){aq=am[an].get("value");
if(aq!==null&&aq>0){ap.push(am[an]);
}}this.model[this.resourcesField]=ap;
}});
var x=ak.extend({init:function(am,ao,an){if(F(ao)){ao={dataSource:ao};
}o={append:{text:"Add Task",action:"add",className:x.styles.toolbar.appendButton,iconClass:x.styles.toolbar.iconPlus},pdf:{text:"Export to PDF",className:x.styles.toolbar.pdfButton,iconClass:x.styles.toolbar.iconPdf}};
ak.fn.init.call(this,am,ao);
if(an){this._events=an;
}this._wrapper();
this._resources();
if(!this.options.views||!this.options.views.length){this.options.views=["day","week","month"];
}this._timeline();
this._toolbar();
this._footer();
this._adjustDimensions();
this._preventRefresh=true;
this.view(this.timeline._selectedViewName);
this._preventRefresh=false;
this._dataSource();
this._assignments();
this._dropDowns();
this._list();
this._dependencies();
this._resizable();
this._scrollable();
this._dataBind();
this._attachEvents();
this._createEditor();
I.notify(this);
},events:["dataBinding","dataBound","add","edit","remove","cancel","save","change","navigate","moveStart","move","moveEnd","resizeStart","resize","resizeEnd","columnResize"],options:{name:"Gantt",autoBind:true,navigatable:false,selectable:true,editable:true,resizable:false,columnResizeHandleWidth:p,columns:[],views:[],dataSource:{},dependencies:{},resources:{},assignments:{},taskTemplate:null,messages:{save:"Save",cancel:"Cancel",destroy:"Delete",deleteTaskConfirmation:ad,deleteDependencyConfirmation:q,deleteTaskWindowTitle:"Delete task",deleteDependencyWindowTitle:"Delete dependency",views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"},actions:{append:"Add Task",addChild:"Add Child",insertBefore:"Add Above",insertAfter:"Add Below",pdf:"Export to PDF"},editor:{editorTitle:"Task",resourcesEditorTitle:"Resources",title:"Title",start:"Start",end:"End",percentComplete:"Complete",resources:"Resources",assignButton:"Assign",resourcesHeader:"Resources",unitsHeader:"Units"}},showWorkHours:true,showWorkDays:true,toolbar:null,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,snap:true,height:600,listWidth:"30%",rowHeight:null},select:function(an){var am=this.list;
if(!an){return am.select();
}am.select(an);
this.list.element.find("table[role=treegrid]").focus();
return;
},clearSelection:function(){this.list.clearSelection();
},destroy:function(){ak.fn.destroy.call(this);
if(this.dataSource){this.dataSource.unbind("change",this._refreshHandler);
this.dataSource.unbind("progress",this._progressHandler);
this.dataSource.unbind("error",this._errorHandler);
}if(this.dependencies){this.dependencies.unbind("change",this._dependencyRefreshHandler);
this.dependencies.unbind("error",this._dependencyErrorHandler);
}if(this.timeline){this.timeline.unbind();
this.timeline.destroy();
}if(this.list){this.list.unbind();
this.list.destroy();
}if(this.footerDropDown){this.footerDropDown.destroy();
}if(this.headerDropDown){this.headerDropDown.destroy();
}if(this._editor){this._editor.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}this.toolbar.off(M);
if(ab){this._mediaQuery.removeListener(this._mediaQueryHandler);
this._mediaQuery=null;
}b(window).off("resize"+M,this._resizeHandler);
b(this.wrapper).off(M);
this.toolbar=null;
this.footer=null;
},setOptions:function(ao){var an=I.deepExtend({},this.options,ao);
var am=this._events;
if(!ao.views){var ap=this.view().name;
an.views=b.map(this.options.views,function(at){var aq=H(at);
var ar=aq?typeof at.type!=="string"?at.title:at.type:at;
if(ap===ar){if(aq){at.selected=true;
}else{at={type:ar,selected:true};
}}else{if(aq){at.selected=false;
}}return at;
});
}if(!ao.dataSource){an.dataSource=this.dataSource;
}if(!ao.dependencies){an.dependencies=this.dependencies;
}if(!ao.resources){an.resources=this.resources;
}if(!ao.assignments){an.assignments=this.assignments;
}this.destroy();
this.element.empty();
this.options=null;
this.init(this.element,an,am);
ak.fn._setEvents.call(this,an);
},_attachEvents:function(){this._resizeHandler=U(this.resize,this,false);
b(window).on("resize"+M,this._resizeHandler);
},_wrapper:function(){var am=x.styles;
var ap=[am.icon,am.resizeHandle].join(" ");
var ao=this.options;
var an=ao.height;
var aq=ao.width;
this.wrapper=this.element.addClass(am.wrapper).append("<div class='"+am.listWrapper+"'><div></div></div>").append("<div class='"+am.splitBarWrapper+"'><div class='"+ap+"'></div></div>").append("<div class='"+am.timelineWrapper+"'><div></div></div>");
this.wrapper.find(s+am.list).width(ao.listWidth);
if(an){this.wrapper.height(an);
}if(aq){this.wrapper.width(aq);
}if(ao.rowHeight){this.wrapper.addClass(am.rowHeight);
}},_toolbar:function(){var au=this;
var ap=x.styles;
var aB=s+ap.toolbar.views+" > li";
var at=s+ap.toolbar.pdfButton;
var ax=s+ap.buttonToggle;
var ao=s+ap.gridContent;
var az=b(s+ap.list);
var av=b(s+ap.timeline);
var ar=ap.hovered;
var am=this.options.toolbar;
var an=b("<div class='"+ap.toolbar.actions+"'>");
var ay;
var aA;
var aw;
var aq=function(aC){if(aC.matches){az.css({display:"none","max-width":0});
}else{az.css({display:"inline-block",width:"30%","max-width":"none"});
av.css("display","inline-block");
au.refresh();
av.find(ao).scrollTop(au.scrollTop);
}au._resize();
};
if(!G(am)){am=typeof am===aa?am:this._actions(am);
am=U(I.template(am),this);
}aw=b(ag({styles:ap.toolbar}));
aA=b(D({ns:I.ns,views:this.timeline.views,styles:ap.toolbar}));
an.append(am({}));
ay=b("<div class='"+ap.toolbar.headerWrapper+"'>").append(aw).append(aA).append(an);
if(aA.find("li").length>1){aA.prepend(aj({styles:ap.toolbar}));
}this.wrapper.prepend(ay);
this.toolbar=ay;
if(ab){this._mediaQueryHandler=U(aq,this);
this._mediaQuery=window.matchMedia("(max-width: 480px)");
this._mediaQuery.addListener(this._mediaQueryHandler);
}ay.on(i+M,aB,function(aD){aD.preventDefault();
var aE=au.list;
var aF=b(this).attr(I.attr("name"));
var aC=aA.find(s+ap.toolbar.currentView);
if(aC.is(":visible")){aC.parent().toggleClass(ap.toolbar.expanded);
}if(aE.editable&&aE.editable.trigger("validate")){return;
}if(!au.trigger("navigate",{view:aF})){au.view(aF);
}au.toolbar.find(s+ap.focused).removeClass(ap.focused);
}).on("keydown"+M,aB,function(aC){var aE=b(s+ap.toolbar.views).children(":not(.k-current-view)");
var aD=aE.index(au._focusedView&&au._focusedView[0]||aE.closest(s+ap.selected)[0]);
if(aC.keyCode===J.RIGHT){b(au.toolbar.find(s+ap.focused)).removeClass(ap.focused);
au._focusedView=aD+1===aE.length?b(aE[0]):b(aE[aD+1]);
au._focusedView.focus().addClass(ap.focused);
aC.preventDefault();
}else{if(aC.keyCode===J.LEFT){b(au.toolbar.find(s+ap.focused)).removeClass(ap.focused);
au._focusedView=aD===0?b(aE[aE.length-1]):b(aE[aD-1]);
au._focusedView.focus().addClass(ap.focused);
aC.preventDefault();
}else{if(aC.keyCode===J.DOWN&&au.toolbar.find(s+ap.toolbar.currentView).parent().hasClass(ap.toolbar.expanded)){b(au.toolbar.find(s+ap.focused)).removeClass(ap.focused);
au._focusedView=aD+1===aE.length?b(aE[0]):b(aE[aD+1]);
au._focusedView.focus().addClass(ap.focused);
aC.preventDefault();
}else{if(aC.keyCode===J.UP&&au.toolbar.find(s+ap.toolbar.currentView).parent().hasClass(ap.toolbar.expanded)){b(au.toolbar.find(s+ap.focused)).removeClass(ap.focused);
au._focusedView=aD===0?b(aE[aE.length-1]):b(aE[aD-1]);
au._focusedView.focus().addClass(ap.focused);
aC.preventDefault();
}else{if((aC.keyCode===J.ENTER||aC.keyCode===J.SPACEBAR)&&au._focusedView){au.view(au._focusedView.text().toLowerCase());
aC.preventDefault();
}else{if((aC.keyCode===J.SPACEBAR||aC.keyCode===J.ENTER||aC.keyCode===J.DOWN&&aC.altKey)&&au.toolbar.find(s+ap.toolbar.currentView+" > a").hasClass(ap.focused)){au.toolbar.find(s+ap.toolbar.currentView).parent().toggleClass(ap.toolbar.expanded);
aC.preventDefault();
}else{if(aC.keyCode===J.ESC&&au.toolbar.find(s+ap.toolbar.currentView).parent().hasClass(ap.toolbar.expanded)){au.toolbar.find(s+ap.toolbar.currentView).parent().toggleClass(ap.toolbar.expanded).blur();
au._focusedView=null;
au.toolbar.find(s+ap.toolbar.currentView+" > a").addClass(ap.focused).focus();
aC.preventDefault();
}else{if(aC.keyCode>=49&&aC.keyCode<=57){au.view(au.timeline._viewByIndex(aC.keyCode-49));
}}}}}}}}}).on(i+M,at,function(aC){aC.preventDefault();
au.saveAsPDF();
}).on(i+M,ax,function(aC){aC.preventDefault();
if(az.is(":visible")){az.css({display:"none",width:"0"});
av.css({display:"inline-block",width:"100%"});
au.refresh();
av.find(ao).scrollTop(au.scrollTop);
}else{av.css({display:"none",width:0});
az.css({display:"inline-block",width:"100%","max-width":"none"}).find(ao).scrollTop(au.scrollTop);
}au._resize();
});
this.wrapper.on("focusout"+M,function(aC){if(!b(aC.relatedTarget).closest(s+ap.toolbar.toolbar).length){au.toolbar.find(s+ap.focused).removeClass(ap.focused);
}if(!b(aC.relatedTarget).closest(s+ap.toolbar.views).length){au.toolbar.find(s+ap.toolbar.views).removeClass(ap.toolbar.expanded);
}}).find(s+ap.toolbar.toolbar+" li").hover(function(){b(this).addClass(ar);
},function(){b(this).removeClass(ar);
});
},_actions:function(){var ar=this.options;
var an=ar.editable;
var am=ar.toolbar;
var ao="";
if(!F(am)){if(an&&an.create!==false){am=["append"];
}else{return ao;
}}for(var ap=0,aq=am.length;
ap<aq;
ap++){ao+=this._createButton(am[ap]);
}return ao;
},_footer:function(){var ao=this.options.editable;
if(!ao||ao.create===false){return;
}var aq=x.styles.toolbar;
var ar=this.options.messages.actions;
var an=b(I.template(h)(v(true,{styles:aq},o.append,{text:ar.append})));
var am=b("<div class='"+aq.actions+"'>").append(an);
var ap=b("<div class='"+aq.footerWrapper+"'>").append(am);
this.wrapper.append(ap);
this.footer=ap;
},_createButton:function(an){var ar=an.template||h;
var ap=this.options.messages.actions;
var ao=typeof an===aa?an:an.name||an.text;
var am=o[ao]?o[ao].className:"k-gantt-"+(ao||"").replace(/\s/g,"");
var aq={iconClass:"",action:"",text:ao,className:am,styles:x.styles.toolbar};
if(!ao&&!(H(an)&&an.template)){throw new Error("Custom commands should have name specified");
}aq=v(true,aq,o[ao],{text:ap[ao]});
if(H(an)){if(an.className&&E(aq.className,an.className.split(" "))<0){an.className+=" "+aq.className;
}aq=v(true,aq,an);
}return I.template(ar)(aq);
},_adjustDimensions:function(){var am=this.element;
var ao=x.styles;
var ap=s+ao.list;
var at=s+ao.timeline;
var aq=s+ao.splitBar;
var au=Q(this.toolbar);
var an=this.footer?Q(this.footer):0;
var av=am.height();
var aw=am.width();
var ar=R(am.find(aq));
var ax=R(am.find(ap));
am.children([ap,at,aq].join(",")).height(av-(au+an)).end().children(at).width(aw-(ar+ax));
if(aw<ax+ar){am.find(ap).width(aw-ar);
}},_scrollTo:function(at){var au=this.timeline.view();
var ap=this.list;
var an=I.attr("uid");
var ao=typeof at==="string"?at:at.closest("tr"+Z()).attr(an);
var am;
var ar;
var aq=function(){if(ar.length!==0){am();
}};
if(au.content.is(":visible")){ar=au.content.find(Z(ao));
am=function(){au._scrollTo(ar);
};
}else{ar=ap.content.find(Z(ao));
am=function(){ar.get(0).scrollIntoView();
};
}aq();
},_dropDowns:function(){var aq=this;
var an=s+x.styles.toolbar.actions;
var am=this.options.messages.actions;
var ar=this.timeline;
var ao=this.options.editable;
var ap=function(au){var aC=au.type;
var ax;
var at=aq.dataSource;
var aB=at._createNewModel();
var az=aq.dataItem(aq.select());
var ay=at.taskParent(az);
var aw=ar.view()._timeSlots()[0];
var aA=aC==="add"?az:ay;
var av=aq.list.editable;
if(av&&av.trigger("validate")){return;
}aB.set("title","New task");
if(aA){aB.set("parentId",aA.get("id"));
aB.set("start",aA.get("start"));
aB.set("end",aA.get("end"));
}else{aB.set("start",aw.start);
aB.set("end",aw.end);
}if(aC!=="add"){ax=az.get("orderId");
ax=aC==="insert-before"?ax:ax+1;
}aq._createTask(aB,ax);
};
if(!ao||ao.create===false){return;
}this.footerDropDown=new af(this.footer.children(an).eq(0),{messages:{actions:am},direction:"up",animation:{open:{effects:"slideIn:up"}},navigatable:aq.options.navigatable});
this.headerDropDown=new af(this.toolbar.children(an).eq(0),{messages:{actions:am},navigatable:aq.options.navigatable});
this.footerDropDown.bind("command",ap);
this.headerDropDown.bind("command",ap);
},_list:function(){var aw=this;
var at=aw.options.navigatable;
var ap=x.styles;
var ar=this.wrapper.find(s+ap.list);
var ao=ar.find("> div");
var ax=this.wrapper.find(s+ap.toolbar.actions+" > button");
var au={columns:this.options.columns||[],dataSource:this.dataSource,selectable:this.options.selectable,editable:this.options.editable,resizable:this.options.resizable,columnResizeHandleWidth:this.options.columnResizeHandleWidth,listWidth:R(ar),resourcesField:this.resources.field,rowHeight:this.options.rowHeight};
var an=au.columns;
var am;
var av=function(){if(at){aw._current(aw._cachedCurrent);
w(aw.list.content.find("table"),true);
}delete aw._cachedCurrent;
};
for(var aq=0;
aq<an.length;
aq++){am=an[aq];
if(am.field===this.resources.field&&typeof am.editor!=="function"){am.editor=U(this._createResourceEditor,this);
}}this.list=new I.ui.GanttList(ao,au);
this.list.bind("render",function(){aw._navigatable();
},true).bind("edit",function(ay){aw._cachedCurrent=ay.cell;
if(aw.trigger("edit",{task:ay.model,container:ay.cell})){ay.preventDefault();
}}).bind("cancel",function(ay){if(aw.trigger("cancel",{task:ay.model,container:ay.cell})){ay.preventDefault();
}av();
}).bind("update",function(ay){aw._updateTask(ay.task,ay.updateInfo);
av();
}).bind("change",function(){aw.trigger("change");
var ay=aw.list.select();
if(ay.length){ax.removeAttr("data-action","add");
aw.timeline.select("[data-uid='"+ay.attr("data-uid")+"']");
}else{ax.attr("data-action","add");
aw.timeline.clearSelection();
}}).bind("columnResize",function(ay){aw.trigger("columnResize",{column:ay.column,oldWidth:ay.oldWidth,newWidth:ay.newWidth});
});
},_timeline:function(){var aq=this;
var ao=x.styles;
var ap=ah(v(true,{resourcesField:this.resources.field},this.options));
var an=this.wrapper.find(s+ao.timeline+" > div");
var am=s+ao.toolbar.currentView+" > "+s+ao.toolbar.link;
this.timeline=new I.ui.GanttTimeline(an,ap);
this.timeline.bind("navigate",function(ar){var au=ar.view.replace(/\./g,"\\.").toLowerCase();
var at=aq.toolbar.find(s+ao.toolbar.views+" > li").removeClass(ao.selected).end().find(s+ao.toolbar.viewButton+"-"+au).addClass(ao.selected).find(s+ao.toolbar.link).text();
aq.toolbar.find(am).text(at);
aq.refresh();
}).bind("moveStart",function(ar){var at=aq.list.editable;
if(at&&at.trigger("validate")){ar.preventDefault();
return;
}if(aq.trigger("moveStart",{task:ar.task})){ar.preventDefault();
}}).bind("move",function(ar){var av=ar.task;
var au=ar.start;
var at=new Date(au.getTime()+av.duration());
if(aq.trigger("move",{task:av,start:au,end:at})){ar.preventDefault();
}}).bind("moveEnd",function(ar){var av=ar.task;
var au=ar.start;
var at=new Date(au.getTime()+av.duration());
if(!aq.trigger("moveEnd",{task:av,start:au,end:at})){aq._updateTask(aq.dataSource.getByUid(av.uid),{start:au,end:at});
}}).bind("resizeStart",function(ar){var at=aq.list.editable;
if(at&&at.trigger("validate")){ar.preventDefault();
return;
}if(aq.trigger("resizeStart",{task:ar.task})){ar.preventDefault();
}}).bind("resize",function(ar){if(aq.trigger("resize",{task:ar.task,start:ar.start,end:ar.end})){ar.preventDefault();
}}).bind("resizeEnd",function(ar){var at=ar.task;
var au={};
if(ar.resizeStart){au.start=ar.start;
}else{au.end=ar.end;
}if(!aq.trigger("resizeEnd",{task:at,start:ar.start,end:ar.end})){aq._updateTask(aq.dataSource.getByUid(at.uid),au);
}}).bind("percentResizeStart",function(ar){var at=aq.list.editable;
if(at&&at.trigger("validate")){ar.preventDefault();
}}).bind("percentResizeEnd",function(ar){aq._updateTask(aq.dataSource.getByUid(ar.task.uid),{percentComplete:ar.percentComplete});
}).bind("dependencyDragStart",function(ar){var at=aq.list.editable;
if(at&&at.trigger("validate")){ar.preventDefault();
}}).bind("dependencyDragEnd",function(at){var ar=aq.dependencies._createNewModel({type:at.type,predecessorId:at.predecessor.id,successorId:at.successor.id});
aq._createDependency(ar);
}).bind("select",function(ar){var at=aq.list.editable;
if(at){at.trigger("validate");
}aq.select("[data-uid='"+ar.uid+"']");
}).bind("editTask",function(ar){var at=aq.list.editable;
if(at&&at.trigger("validate")){return;
}aq.editTask(ar.uid);
}).bind("clear",function(){aq.clearSelection();
}).bind("removeTask",function(ar){var at=aq.list.editable;
if(at&&at.trigger("validate")){return;
}aq.removeTask(aq.dataSource.getByUid(ar.uid));
}).bind("removeDependency",function(ar){var at=aq.list.editable;
if(at&&at.trigger("validate")){return;
}aq.removeDependency(aq.dependencies.getByUid(ar.uid));
});
},_dataSource:function(){var an=this.options;
var am=an.dataSource;
am=F(am)?{data:am}:am;
if(this.dataSource&&this._refreshHandler){this.dataSource.unbind("change",this._refreshHandler).unbind("progress",this._progressHandler).unbind("error",this._errorHandler);
}else{this._refreshHandler=U(this.refresh,this);
this._progressHandler=U(this._requestStart,this);
this._errorHandler=U(this._error,this);
}this.dataSource=I.data.GanttDataSource.create(am).bind("change",this._refreshHandler).bind("progress",this._progressHandler).bind("error",this._errorHandler);
},_dependencies:function(){var an=this.options.dependencies||{};
var am=F(an)?{data:an}:an;
if(this.dependencies&&this._dependencyRefreshHandler){this.dependencies.unbind("change",this._dependencyRefreshHandler).unbind("error",this._dependencyErrorHandler);
}else{this._dependencyRefreshHandler=U(this.refreshDependencies,this);
this._dependencyErrorHandler=U(this._error,this);
}this.dependencies=I.data.GanttDependencyDataSource.create(am).bind("change",this._dependencyRefreshHandler).bind("error",this._dependencyErrorHandler);
},_resources:function(){var an=this.options.resources;
var am=an.dataSource||{};
this.resources={field:"resources",dataTextField:"name",dataColorField:"color",dataFormatField:"format"};
v(this.resources,an);
this.resources.dataSource=I.data.DataSource.create(am);
},_assignments:function(){var am=this.options.assignments;
var an=am.dataSource||{};
if(this.assignments){this.assignments.dataSource.unbind("change",this._assignmentsRefreshHandler);
}else{this._assignmentsRefreshHandler=U(this.refresh,this);
}this.assignments={dataTaskIdField:"taskId",dataResourceIdField:"resourceId",dataValueField:"value"};
v(this.assignments,am);
this.assignments.dataSource=I.data.DataSource.create(an);
this.assignments.dataSource.bind("change",this._assignmentsRefreshHandler);
},_createEditor:function(){var an=this;
var am=this._editor=new T(this.wrapper,v({},this.options,{target:this,resources:{field:this.resources.field,editor:U(this._createResourceEditor,this)},createButton:U(this._createPopupButton,this)}));
am.bind("cancel",function(ao){var ap=an.dataSource.getByUid(ao.model.uid);
if(an.trigger("cancel",{container:ao.container,task:ap})){ao.preventDefault();
return;
}an.cancelTask();
}).bind("edit",function(ao){var ap=an.dataSource.getByUid(ao.model.uid);
if(an.trigger("edit",{container:ao.container,task:ap})){ao.preventDefault();
}}).bind("save",function(ao){var ap=an.dataSource.getByUid(ao.model.uid);
an.saveTask(ap,ao.updateInfo);
}).bind("remove",function(ao){an.removeTask(ao.model.uid);
}).bind("close",an._onDialogClose);
},_onDialogClose:function(){},_createResourceEditor:function(an,at){var av=this;
var ar=at instanceof P?at:at.model;
var ap=ar.get("id");
var aq=this.options.messages;
var au=this.resources.field;
var aw={step:0.01};
var am=this.assignments.dataSource.options.schema.model;
if(am&&am.fields.Units&&am.fields.Units.validation){v(true,aw,am.fields.Units.validation);
}var ao=this._resourceEditor=new W(an,{resourcesField:au,unitsValidation:aw,data:this._wrapResourceData(ap),model:ar,messages:v({},aq.editor),buttons:[{name:"update",text:aq.save,className:x.styles.primary},{name:"cancel",text:aq.cancel}],createButton:U(this._createPopupButton,this),save:function(ax){av._updateAssignments(ax.model.get("id"),ax.model.get(au));
}});
ao.open();
},_createPopupButton:function(am){var an=am.name||am.text;
var ao={className:x.styles.popup.button+" k-gantt-"+(an||"").replace(/\s/g,""),text:an,attr:""};
if(!an&&!(H(am)&&am.template)){throw new Error("Custom commands should have name specified");
}if(H(am)){if(am.className){am.className+=" "+ao.className;
}ao=v(true,ao,am);
}return I.template(j)(ao);
},view:function(am){return this.timeline.view(am);
},range:function(an){var am=this.dataSource;
var ap=this.view();
var ao=this.timeline;
if(an){ap.options.range={start:an.start,end:an.end};
ao._render(am.taskTree());
ao._renderDependencies(this.dependencies.view());
}return{start:ap.start,end:ap.end};
},date:function(am){var an=this.view();
if(am){an.options.date=am;
an._scrollToDate(am);
}return an.options.date;
},dataItem:function(ao){if(!ao){return null;
}var an=this.list;
var am=an.content.find(ao);
return an._modelFromElement(am);
},setDataSource:function(am){this.options.dataSource=am;
this._dataSource();
this.list._setDataSource(this.dataSource);
if(this.options.autoBind){am.fetch();
}},setDependenciesDataSource:function(am){this.options.dependencies=am;
this._dependencies();
if(this.options.autoBind){am.fetch();
}},items:function(){return this.wrapper.children(".k-task");
},_updateAssignments:function(ar,ay){var ao=this.assignments.dataSource;
var az=this.assignments.dataTaskIdField;
var ax=this.assignments.dataResourceIdField;
var ap=false;
var an=new V(ao.view()).filter({field:az,operator:"eq",value:ar}).toArray();
var am;
var aw;
var aA;
while(an.length){am=an[0];
for(var aq=0,au=ay.length;
aq<au;
aq++){aw=ay[aq];
if(am.get(ax)===aw.get("id")){aA=ay[aq].get("value");
this._updateAssignment(am,aA);
ay.splice(aq,1);
ap=true;
break;
}}if(!ap){this._removeAssignment(am);
}ap=false;
an.shift();
}for(var at=0,av=ay.length;
at<av;
at++){aw=ay[at];
this._createAssignment(aw,ar);
}ao.sync();
},cancelTask:function(){var an=this._editor;
var am=an.container;
if(am){an.close();
}},editTask:function(ao){var am=typeof ao==="string"?this.dataSource.getByUid(ao):ao;
if(!am){return;
}var an=this.dataSource._createNewModel(am.toJSON());
an.uid=am.uid;
this.cancelTask();
this._editTask(an);
},_editTask:function(am){this._editor.editTask(am);
},saveTask:function(ap,aq){var ao=this._editor;
var am=ao.container;
var an=ao.editable;
if(am&&an&&an.end()){this._updateTask(ap,aq);
}},_updateTask:function(an,ao){var am=this.resources.field;
if(!this.trigger("save",{task:an,values:ao})){this._preventRefresh=true;
this.dataSource.update(an,ao);
if(ao[am]){this._updateAssignments(an.get("id"),ao[am]);
}this._syncDataSource();
}},_updateAssignment:function(am,ao){var an=this.assignments.dataValueField;
am.set(an,ao);
},removeTask:function(ao){var an=this;
var am=typeof ao==="string"?this.dataSource.getByUid(ao):ao;
if(!am){return;
}this._taskConfirm(function(ap){if(!ap){an._removeTask(am);
}},am);
},_createTask:function(ao,an){if(!this.trigger("add",{task:ao,dependency:null})){var am=this.dataSource;
this._preventRefresh=true;
if(an===ai){am.add(ao);
}else{am.insert(an,ao);
}this._scrollToUid=ao.uid;
this._syncDataSource();
}},_createDependency:function(am){if(!this.trigger("add",{task:null,dependency:am})){this._preventDependencyRefresh=true;
this.dependencies.add(am);
this._preventDependencyRefresh=false;
this.dependencies.sync();
}},_createAssignment:function(aq,ap){var an=this.assignments;
var ao=an.dataSource;
var au=an.dataTaskIdField;
var ar=an.dataResourceIdField;
var at=an.dataValueField;
var am=ao._createNewModel();
am[au]=ap;
am[ar]=aq.get("id");
am[at]=aq.get("value");
ao.add(am);
},removeDependency:function(ao){var an=this;
var am=typeof ao==="string"?this.dependencies.getByUid(ao):ao;
if(!am){return;
}this._dependencyConfirm(function(ap){if(!ap){an._removeDependency(am);
}},am);
},_removeTaskDependencies:function(ap,am){this._preventDependencyRefresh=true;
for(var an=0,ao=am.length;
an<ao;
an++){this.dependencies.remove(am[an]);
}this._preventDependencyRefresh=false;
this.dependencies.sync();
},_removeTaskAssignments:function(ar){var an=this.assignments.dataSource;
var am=an.view();
var ao={field:this.assignments.dataTaskIdField,operator:"eq",value:ar.get("id")};
am=new V(am).filter(ao).toArray();
this._preventRefresh=true;
for(var ap=0,aq=am.length;
ap<aq;
ap++){an.remove(am[ap]);
}this._preventRefresh=false;
an.sync();
},_removeTask:function(an){var am=this.dependencies.dependencies(an.id);
if(!this.trigger("remove",{task:an,dependencies:am})){this._removeTaskDependencies(an,am);
this._removeTaskAssignments(an);
this._preventRefresh=true;
if(this.dataSource.remove(an)){this._syncDataSource();
}this._preventRefresh=false;
}},_removeDependency:function(am){if(!this.trigger("remove",{task:null,dependencies:[am]})){if(this.dependencies.remove(am)){this.dependencies.sync();
}}},_removeAssignment:function(am){this.assignments.dataSource.remove(am);
},_taskConfirm:function(am,ao){var an=this.options.messages;
this._confirm(am,{model:ao,text:an.deleteTaskConfirmation,title:an.deleteTaskWindowTitle});
},_dependencyConfirm:function(am,an){var ao=this.options.messages;
this._confirm(am,{model:an,text:ao.deleteDependencyConfirmation,title:ao.deleteDependencyWindowTitle});
},_confirm:function(an,aq){var ao=this.options.editable;
var ap;
var am;
if(ao===true||ao.confirmation!==false){ap=this.options.messages;
am=[{name:"delete",text:ap.destroy,className:x.styles.primary,click:function(){an();
}},{name:"cancel",text:ap.cancel,click:function(){an(true);
}}];
this.showDialog(v(true,{},aq,{buttons:am}));
}else{an();
}},showDialog:function(am){this._editor.showDialog(am);
},refresh:function(){if(this._preventRefresh||this.list.editable){return;
}this._progress(false);
var ap=this.dataSource;
var ar=ap.taskTree();
var aq=this._scrollToUid;
var ao;
var an;
var am=-1;
if(this.current){an=this.current.closest("tr").attr(I.attr("uid"));
am=this.current.index();
}if(this.trigger("dataBinding")){return;
}if(this.resources.dataSource.data().length!==0){this._assignResources(ar);
}if(this._editor){this._editor.close();
}this.clearSelection();
this.list._render(ar);
this.timeline._render(ar);
this.timeline._renderDependencies(this.dependencies.view());
if(aq){this._scrollTo(aq);
this.select(Z(aq));
}if((aq||an)&&am>=0){ao=this.list.content.find("tr"+Z(aq||an)+" > td:eq("+am+")");
this._current(ao);
}this._scrollToUid=null;
this.trigger("dataBound");
},refreshDependencies:function(){if(this._preventDependencyRefresh){return;
}if(this.trigger("dataBinding")){return;
}this.timeline._renderDependencies(this.dependencies.view());
this.trigger("dataBound");
},_assignResources:function(au){var at=this.resources;
var ao=this.assignments;
var ap=function(){var aw=ao.dataSource.view();
var ax={field:ao.dataTaskIdField};
aw=new V(aw).group(ax).toArray();
return aw;
};
var an=ap();
var am=function(az,aw){var aA=az.get("id");
I.setter(at.field)(az,new O([]));
for(var ax=0,ay=an.length;
ax<ay;
ax++){if(an[ax].value===aA){aw(az,an[ax].items);
}}};
var av=function(aE,ay){for(var az=0,aA=ay.length;
az<aA;
az++){var ax=ay[az];
var aB=at.dataSource.get(ax.get(ao.dataResourceIdField));
var aD=ax.get(ao.dataValueField);
var aC=ax.get(ao.dataResourceIdField);
var aF=aB.get(at.dataFormatField)||S;
var aw=I.toString(aD,aF);
aE[at.field].push(new P({id:aC,name:aB.get(at.dataTextField),color:aB.get(at.dataColorField),value:aD,formatedValue:aw}));
}};
for(var aq=0,ar=au.length;
aq<ar;
aq++){am(au[aq],av);
}},_wrapResourceData:function(ao){var av=this;
var at=[];
var aq;
var ar=this.resources.dataSource.view();
var am=this.assignments.dataSource.view();
var au=new V(am).filter({field:av.assignments.dataTaskIdField,operator:"eq",value:ao}).toArray();
var aw=function(ax){var ay=null;
new V(au).filter({field:av.assignments.dataResourceIdField,operator:"eq",value:ax}).select(function(az){ay+=az.get(av.assignments.dataValueField);
});
return ay;
};
for(var an=0,ap=ar.length;
an<ap;
an++){aq=ar[an];
at.push({id:aq.get("id"),name:aq.get(av.resources.dataTextField),format:aq.get(av.resources.dataFormatField)||S,value:aw(aq.id)});
}return at;
},_syncDataSource:function(){this._preventRefresh=false;
this._requestStart();
this.dataSource.sync();
},_requestStart:function(){this._progress(true);
},_error:function(){this._progress(false);
},_progress:function(am){I.ui.progress(this.element,am);
},_resizable:function(){var ao=this;
var av=this.wrapper;
var an=x.styles;
var am=s+an.gridContent;
var au=av.find(s+an.list);
var ar=av.find(s+an.timeline);
var at;
var aq;
var ap;
this._resizeDraggable=av.find(s+an.splitBar).height(au.height()).hover(function(){b(this).addClass(an.splitBarHover);
},function(){b(this).removeClass(an.splitBarHover);
}).end().kendoResizable({orientation:"horizontal",handle:s+an.splitBar,start:function(){at=au.width();
aq=ar.width();
ap=ar.find(am).scrollLeft();
},resize:function(ax){var aw=ax.x.initialDelta;
if(I.support.isRtl(av)){aw*=-1;
}if(at+aw<0||aq-aw<0){return;
}au.width(at+aw);
ar.width(aq-aw);
ar.find(am).scrollLeft(ap+aw);
ao.timeline.view()._renderCurrentTime();
}}).data("kendoResizable");
},_scrollable:function(){var ap=this;
var an=x.styles;
var am=s+an.gridContent;
var ao=s+an.gridHeaderWrap;
var ar=this.timeline.element.find(ao);
var aq=this.timeline.element.find(am);
var au=this.list.element.find(ao);
var at=this.list.element.find(am);
if(L){at.css("overflow-y","auto");
}aq.on("scroll",function(){ap.scrollTop=this.scrollTop;
ar.scrollLeft(this.scrollLeft);
at.scrollTop(this.scrollTop);
});
at.on("scroll",function(){au.scrollLeft(this.scrollLeft);
}).on("DOMMouseScroll"+M+" mousewheel"+M,function(aw){var ax=aq.scrollTop();
var av=I.wheelDeltaY(aw);
if(av){aw.preventDefault();
b(aw.currentTarget).one("wheel"+M,false);
aq.scrollTop(ax+-av);
}});
},_navigatable:function(){var aC=this;
var ay=this.options.navigatable;
var aq=this.options.editable;
var au=this.list.header.find("table");
var ao=this.list.content.find("table");
var at=x.styles;
var av=I.support.isRtl(this.wrapper);
var aD=this.timeline.element.find(s+at.gridContent);
var aB=au.add(ao);
var am=Z();
var an;
var ar={collapse:false,expand:true};
var az=function(aF){var aG=aC.timeline.view()._timeSlots()[0].offsetWidth;
aD.scrollLeft(aD.scrollLeft()+(aF?-aG:aG));
};
var aA=function(aG){var aF=aC.timeline.view()._rowHeight;
aD.scrollTop(aD.scrollTop()+(aG?-aF:aF));
};
var ax=function(aG){var aH=aC.current.parent("tr"+Z());
var aF=aC.current.index();
var aI=aH[aG]();
if(aC.select().length!==0){aC.clearSelection();
}if(aI.length!==0){aC._current(aI.children("td:eq("+aF+")"));
aC._scrollTo(aC.current);
}else{if(aC.current.is("td")&&aG=="prev"){w(au);
}else{if(aC.current.is("th")&&aG=="next"){w(ao);
}}}};
var aw=function(aF){var aG=aC.current[aF]();
if(aG.length!==0){aC._current(aG);
an=aC.current.index();
}};
var aE=function(aG){var aF=aC.dataItem(aC.current);
if(aF.summary&&aF.expanded!==aG){aF.set("expanded",aG);
}};
var ap=function(){var aF=aC.options.editable;
if(!aF||aF.destroy===false||aC.list.editable){return;
}var aG=aC.select();
var aH=I.attr("uid");
if(aG.length){aC.removeTask(aG.attr(aH));
}};
b(this.wrapper).on("mousedown"+M,"tr"+am+", div"+am+":not("+s+at.line+")",function(aH){var aG=b(aH.currentTarget);
var aI=b(aH.target).is(":button,a,:input,a>.k-icon,textarea,span.k-icon,span.k-link,.k-input,.k-multiselect-wrap");
var aF;
if(aH.ctrlKey){return;
}if(ay){if(aG.is("tr")){aF=b(aH.target).closest("td");
}else{aF=aC.list.content.find("tr"+Z(aG.attr(I.attr("uid")))+" > td:first");
}aC._current(aF);
}if((ay||aq)&&!aI){aC._focusTimeout=setTimeout(function(){w(aC.list.content.find("table"),true);
},2);
}}).on("keydown"+M,function(aF){var aJ=aF.keyCode;
var aK=this;
var aG=b(aK._getToolbarItems());
var aH=aG.index(aK.toolbar.find(s+at.focused)[0]);
if(aH===-1&&b(aF.target).closest(s+at.toolbar.views).length){aH=aG.index(aK.toolbar.find(".k-gantt-views > .k-state-selected:visible > a, .k-current-view:visible > a")[0]);
}var aI=aF.shiftKey?aG[aH-1]:aG[aH+1];
if(aJ===J.F10){aK.toolbar.find(".k-button:visible:first").addClass(at.focused).focus();
aF.preventDefault();
}else{if(aJ==J.TAB&&b(aF.target).closest(s+at.toolbar.toolbar).length){aK.toolbar.find(s+at.focused).removeClass(at.focused).blur();
if(aI){b(aI).addClass(at.focused).focus();
aF.preventDefault();
return;
}if(this.list.element.is(":visible")){this.list.element.find("table[role=treegrid]").focus();
}else{this.element.find(s+at.tasks)[0].focus();
}aF.preventDefault();
}}}.bind(this));
if(ay!==true){ao.on("keydown"+M,function(aF){if(aF.keyCode==J.DELETE){ap();
}});
return;
}aB.on("focus"+M,function(){var aH=this===ao.get(0)?"td":"th";
var aG=aC.select();
var aF=aC.current||b(aG.length?aG:this).find(aH+":eq("+(an||0)+")");
aC._current(aF);
b(aC.toolbar.find(s+at.focused)).removeClass(at.focused);
b(aC.toolbar.find(s+at.toolbar.currentView)).parent().removeClass(at.toolbar.expanded);
}).on("blur"+M,function(){aC._current();
if(this==au){b(this).attr(ac,-1);
}}).on("keydown"+M,function(aF){var aH=aF.keyCode;
var aG;
if(!aC.current){return;
}aG=aC.current.is("td");
switch(aH){case J.RIGHT:aF.preventDefault();
if(aF.altKey){az();
}else{if(aF.ctrlKey){aE(av?ar.collapse:ar.expand);
}else{aw(av?"prev":"next");
}}break;
case J.LEFT:aF.preventDefault();
if(aF.altKey){az(true);
}else{if(aF.ctrlKey){aE(av?ar.expand:ar.collapse);
}else{aw(av?"next":"prev");
}}break;
case J.UP:aF.preventDefault();
if(aF.altKey){aA(true);
}else{ax("prev");
}break;
case J.DOWN:aF.preventDefault();
if(aF.altKey){aA();
}else{ax("next");
}break;
case J.SPACEBAR:aF.preventDefault();
if(aG){aC.select(aC.current.closest("tr"));
}break;
case J.ENTER:aF.preventDefault();
if(aG){if(aC.options.editable&&aC.options.editable.update!==false){aC._cachedCurrent=aC.current;
aC.list._startEditHandler(aC.current);
b(this).one("keyup",function(aI){aI.stopPropagation();
});
}}else{aC.current.children("a.k-link").click();
}break;
case J.ESC:break;
case J.DELETE:if(aG){ap();
}break;
default:if(aH>=49&&aH<=57&&aF.target.tagName.toLowerCase()!=="input"){aC.view(aC.timeline._viewByIndex(aH-49));
}break;
}});
},_getToolbarItems:function(){return this.toolbar.find(".k-gantt-toggle:visible").toArray().concat(this.toolbar.find(".k-gantt-actions > .k-button:visible").toArray(),this.toolbar.find(".k-gantt-views > .k-state-selected:visible > a, .k-current-view:visible > a").toArray());
},_current:function(an){var ao=x.styles;
var am;
if(this.current&&this.current.length){this.current.removeClass(ao.focused).removeAttr("id");
}if(an&&an.length){this.current=an.addClass(ao.focused).attr("id",c);
am=b(I._activeElement());
if(am.is("table")&&this.wrapper.find(am).length>0){am.removeAttr(e).attr(e,c);
}}else{this.current=null;
}},_dataBind:function(){var an=this;
if(an.options.autoBind){this._preventRefresh=true;
this._preventDependencyRefresh=true;
var am=b.map([this.dataSource,this.dependencies,this.resources.dataSource,this.assignments.dataSource],function(ao){return ao.fetch();
});
b.when.apply(null,am).done(function(){an._preventRefresh=false;
an._preventDependencyRefresh=false;
an.refresh();
});
}},_resize:function(){this._adjustDimensions();
this.timeline.view()._adjustHeight();
this.timeline.view()._renderCurrentTime();
this.list._adjustHeight();
}});
if(I.PDFMixin){I.PDFMixin.extend(x.fn);
x.fn._drawPDF=function(){var an=x.styles;
var ao="."+an.list;
var ap=this.wrapper.find(ao).width();
var am=this.wrapper.clone();
am.find(ao).css("width",ap);
return this._drawPDFShadow({content:am},{avoidLinks:this.options.pdf.avoidLinks});
};
}I.ui.plugin(x);
v(true,x,{styles:B});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
