(function(b,a){a("kendo.multicolumncombobox",["kendo.combobox"],b);
}(function(){var a={id:"multicolumncombobox",name:"MultiColumnComboBox",category:"web",description:"The MultiColumnComboBox widget allows the selection from pre-defined values or entering a new value where the list popup is rendered in table layout.",depends:["combobox"],features:[{id:"mobile-scroller",name:"Mobile scroller",description:"Support for kinetic scrolling in mobile device",depends:["mobile.scroller"]},{id:"virtualization",name:"VirtualList",description:"Support for virtualization",depends:["virtuallist"]}]};
(function(b,j){var d=window.kendo,i=d.ui,c=i.ComboBox,g=/^\d+(\.\d+)?%$/i,e="k-dropdowngrid",h="k-dropdowngrid-popup k-popup-flush";
var f=c.extend({init:function(k,l){c.fn.init.call(this,k,l);
this.list.addClass(h);
if(this._allColumnsWidthsAreSet(this.options)){this.list.width(this._calculateDropDownWidth(this.options));
}else{if(this.options.dropDownWidth){this.list.width(this.options.dropDownWidth);
}}},options:{name:"MultiColumnComboBox",ns:".kendoMultiColumnComboBox",columns:[],dropDownWidth:null,filterFields:[]},setOptions:function(k){c.fn.setOptions.call(this,k);
if(this._allColumnsWidthsAreSet(k)){this.list.width(this._calculateDropDownWidth(k));
}else{if(this.options.dropDownWidth){this.list.width(this.options.dropDownWidth);
}}},_allColumnsWidthsAreSet:function(n){var k=n.columns;
if(!k||!k.length){return false;
}for(var m=0;
m<k.length;
m++){var l=k[m].width;
if(!l||isNaN(parseInt(l,10))||g.test(l)){return false;
}}return true;
},_calculateDropDownWidth:function(n){var k=n.columns;
var o=d.support.scrollbar();
for(var m=0;
m<k.length;
m++){var l=k[m].width;
o=o+parseInt(l,10);
}return o;
},_wrapper:function(){c.fn._wrapper.call(this);
this.wrapper.addClass(e);
}});
i.plugin(f);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
