(function(b,a){a("kendo.tabstrip",["kendo.data"],b);
}(function(){var a={id:"tabstrip",name:"TabStrip",category:"web",description:"The TabStrip widget displays a collection of tabs with associated tab content.",depends:["data"],features:[{id:"tabstrip-fx",name:"Animation",description:"Support for animation",depends:["fx"]}]};
(function(b,W){var y=window.kendo,V=y.ui,A=y.keys,D=b.map,l=b.each,U=b.trim,p=b.extend,x=y.isFunction,S=y.template,K=y._outerWidth,J=y._outerHeight,Z=V.Widget,o=/^(a|div)$/i,I=".kendoTabStrip",w="img",u="href",L="prev",H="next",P="show",C="k-link",B="k-last",e="click",n="error",m=":empty",v="k-image",q="k-first",O="select",c="activate",f="k-content",h="contentUrl",E="mouseenter",F="mouseleave",g="contentLoad",k="k-state-disabled",j="k-state-default",d="k-state-active",r="k-state-focused",t="k-state-hover",Q="k-tab-on-top",G=".k-item:not(."+k+")",z=".k-item",s=".k-tabstrip-items > "+G+":not(."+d+")",i=200,T={content:S("<div class='k-content'#= contentAttributes(data) # role='tabpanel'>#= content(item) #</div>"),itemWrapper:S("<#= tag(item) # class='k-link'#= contentUrl(item) ##= textAttributes(item) #>#= image(item) ##= sprite(item) ##= text(item) #</#= tag(item) #>"),item:S("<li class='#= wrapperCssClass(group, item) #' role='tab' #=item.active ? \"aria-selected='true'\" : ''#>#= itemWrapper(data) #</li>"),image:S("<img class='k-image' alt='' src='#= imageUrl #' />"),sprite:S("<span class='k-sprite #= spriteCssClass #'></span>"),empty:S("")},M={wrapperCssClass:function(aa,ac){var ad="k-item",ab=ac.index;
if(ac.enabled===false){ad+=" k-state-disabled";
}else{ad+=" k-state-default";
}if(ab===0){ad+=" k-first";
}if(ab==aa.length-1){ad+=" k-last";
}return ad;
},textAttributes:function(aa){return aa.url?" href='"+aa.url+"'":"";
},text:function(aa){return aa.encoded===false?aa.text:y.htmlEncode(aa.text);
},tag:function(aa){return aa.url?"a":"span";
},contentAttributes:function(aa){return aa.active!==true?" style='display:none' aria-hidden='true' aria-expanded='false'":"";
},content:function(aa){return aa.content?aa.content:aa.contentUrl?"":"&nbsp;";
},contentUrl:function(aa){return aa.contentUrl?y.attr("content-url")+'="'+aa.contentUrl+'"':"";
}};
function Y(aa){aa.children(w).addClass(v);
aa.children("a").addClass(C).children(w).addClass(v);
aa.filter(":not([disabled]):not([class*=k-state-disabled])").addClass(j);
aa.filter("li[disabled]").addClass(k).attr("aria-disabled","true").removeAttr("disabled");
aa.filter(":not([class*=k-state])").children("a").filter(":focus").parent().addClass(d+" "+Q);
aa.attr("role","tab");
aa.filter("."+d).attr("aria-selected",true);
aa.each(function(){var ab=b(this);
if(!ab.children("."+C).length){ab.contents().filter(function(){return !this.nodeName.match(o)&&!(this.nodeType==3&&!U(this.nodeValue));
}).wrapAll("<span UNSELECTABLE='on' class='"+C+"'/>");
}});
}function X(aa){var ab=aa.children(".k-item");
ab.filter(".k-first:not(:first-child)").removeClass(q);
ab.filter(".k-last:not(:last-child)").removeClass(B);
ab.filter(":first-child").addClass(q);
ab.filter(":last-child").addClass(B);
}function N(aa,ab){return"<span class='k-button k-button-icon k-bare k-tabstrip-"+aa+"' unselectable='on'><span class='k-icon "+ab+"'></span></span>";
}var R=Z.extend({init:function(ab,ac){var ae=this,af;
Z.fn.init.call(ae,ab,ac);
ae._animations(ae.options);
ac=ae.options;
ae._contentUrls=ac.contentUrls||[];
ae._wrapper();
ae._isRtl=y.support.isRtl(ae.wrapper);
ae._tabindex();
ae._updateClasses();
ae._dataSource();
if(ac.dataSource){ae.dataSource.fetch();
}ae._tabPosition();
ae._scrollable();
if(ae._contentUrls.length){ae.wrapper.find(".k-tabstrip-items > .k-item").each(function(ag,ah){var ai=ae._contentUrls[ag];
if(typeof ai==="string"){b(ah).find(">."+C).data(h,ai);
}});
}else{ae._contentUrls.length=ae.tabGroup.find("li.k-item").length;
}ae.wrapper.on(E+I+" "+F+I,s,ae._toggleHover).on("focus"+I,b.proxy(ae._active,ae)).on("blur"+I,function(){ae._current(null);
});
ae._keyDownProxy=b.proxy(ae._keydown,ae);
if(ac.navigatable){ae.wrapper.on("keydown"+I,ae._keyDownProxy);
}if(ae.options.value){af=ae.options.value;
}ae.wrapper.children(".k-tabstrip-items").on(e+I,".k-state-disabled .k-link",false).on(e+I," > "+G,function(ag){var aj=ae.wrapper[0];
if(aj!==document.activeElement){var ai=y.support.browser.msie;
if(ai){try{aj.setActive();
}catch(ah){aj.focus();
}}else{aj.focus();
}}if(ae._click(b(ag.currentTarget))){ag.preventDefault();
}});
var ad=ae.tabGroup.children("li."+d),aa=ae.contentHolder(ad.index());
if(ad[0]&&aa.length>0&&aa[0].childNodes.length===0){ae.activateTab(ad.eq(0));
}ae.element.attr("role","tablist");
if(ae.element[0].id){ae._ariaId=ae.element[0].id+"_ts_active";
}ae.value(af);
y.notify(ae);
},_active:function(){var aa=this.tabGroup.children().filter("."+d);
aa=aa[0]?aa:this._endItem("first");
if(aa[0]){this._current(aa);
}},_endItem:function(aa){return this.tabGroup.children(G)[aa]();
},_getItem:function(aa){return this.tabGroup.children(z)[aa]();
},_item:function(ac,aa){var ab;
if(aa===L){ab="last";
}else{ab="first";
}if(!ac){return this._endItem(ab);
}ac=ac[aa]();
if(!ac[0]){ac=this.tabGroup.children(z)[ab]();
}if(ac.hasClass(k)){ac.addClass(r);
}if(ac.hasClass(k)||ac.hasClass(d)){this._focused=ac;
}return ac;
},_current:function(aa){var ad=this,ab=ad._focused,ac=ad._ariaId;
if(aa===W){return ab;
}if(ab){ad.tabGroup.children("#"+ac).removeAttr("id");
ab.removeClass(r);
}if(aa){if(!aa.hasClass(d)){aa.addClass(r);
}ad.element.removeAttr("aria-activedescendant");
ac=aa[0].id||ac;
if(ac){aa.attr("id",ac);
ad.element.attr("aria-activedescendant",ac);
}}ad._focused=aa;
},_keydown:function(ac){var ag=this,ae=ac.keyCode,ab=ag._current(),af=ag._isRtl,ad=/top|bottom/.test(ag.options.tabPosition),aa;
if(ac.target!=ac.currentTarget||!ab){return;
}if(ae===A.DOWN&&!ad){aa=H;
}else{if(ae===A.UP&&!ad){aa=L;
}else{if(ae===A.RIGHT&&ad){aa=af?L:H;
}else{if(ae===A.LEFT&&ad){aa=af?H:L;
}else{if(ae==A.ENTER||ae==A.SPACEBAR){ag._click(ab);
ac.preventDefault();
}else{if(ae==A.HOME){ag._click(ag._getItem("first"));
ac.preventDefault();
return;
}else{if(ae==A.END){ag._click(ag._getItem("last"));
ac.preventDefault();
return;
}}}}}}}if(aa){ag._click(ag._item(ab,aa));
ac.preventDefault();
}},_dataSource:function(){var aa=this;
if(aa.dataSource&&aa._refreshHandler){aa.dataSource.unbind("change",aa._refreshHandler);
}else{aa._refreshHandler=b.proxy(aa.refresh,aa);
}aa.dataSource=y.data.DataSource.create(aa.options.dataSource).bind("change",aa._refreshHandler);
},setDataSource:function(aa){var ab=this;
ab.options.dataSource=aa;
ab._dataSource();
ab.dataSource.fetch();
},_animations:function(aa){if(aa&&"animation" in aa&&!aa.animation){aa.animation={open:{effects:{}},close:{effects:{}}};
}},refresh:function(ad){var an=this,ai=an.options,ae=y.getter(ai.dataEncodedField),am=y.getter(ai.dataTextField),ab=y.getter(ai.dataContentField),ac=y.getter(ai.dataContentUrlField),ag=y.getter(ai.dataImageUrlField),ao=y.getter(ai.dataUrlField),aj=y.getter(ai.dataSpriteCssClass),af,al=[],ak,aa,ap=an.dataSource.view(),ah;
ad=ad||{};
aa=ad.action;
if(aa){ap=ad.items;
}for(af=0,ah=ap.length;
af<ah;
af++){ak={text:am(ap[af])};
if(ai.dataEncodedField){ak.encoded=ae(ap[af]);
}if(ai.dataContentField){ak.content=ab(ap[af]);
}if(ai.dataContentUrlField){ak.contentUrl=ac(ap[af]);
}if(ai.dataUrlField){ak.url=ao(ap[af]);
}if(ai.dataImageUrlField){ak.imageUrl=ag(ap[af]);
}if(ai.dataSpriteCssClass){ak.spriteCssClass=aj(ap[af]);
}al[af]=ak;
}if(ad.action=="add"){if(ad.index<an.tabGroup.children().length){an.insertBefore(al,an.tabGroup.children().eq(ad.index));
}else{an.append(al);
}}else{if(ad.action=="remove"){for(af=0;
af<ap.length;
af++){an.remove(ad.index);
}}else{if(ad.action=="itemchange"){af=an.dataSource.view().indexOf(ap[0]);
if(ad.field===ai.dataTextField){an.tabGroup.children().eq(af).find(".k-link").text(ap[0].get(ad.field));
}if(ad.field===ai.dataUrlField){an._contentUrls[af]=ap[0].get(ad.field);
}}else{an.trigger("dataBinding");
an.remove("li");
an._contentUrls=[];
an.append(al);
an.trigger("dataBound");
}}}},value:function(ab){var aa=this;
if(ab!==W){if(ab!=aa.value()){aa.tabGroup.children().each(function(){if(b.trim(b(this).text())==ab){aa.select(this);
}});
}}else{return aa.select().text();
}},items:function(){return this.tabGroup[0].children;
},setOptions:function(ab){var ac=this,aa=ac.options.animation;
ac._animations(ab);
if(ab.contentUrls){ac._contentUrls=ab.contentUrls;
}ab.animation=p(true,aa,ab.animation);
if(ab.navigatable){ac.wrapper.on("keydown"+I,ac._keyDownProxy);
}else{ac.wrapper.off("keydown"+I,ac._keyDownProxy);
}Z.fn.setOptions.call(ac,ab);
},events:[O,c,P,n,g,"change","dataBinding","dataBound"],options:{name:"TabStrip",dataEncodedField:"",dataTextField:"",dataContentField:"",dataImageUrlField:"",dataUrlField:"",dataSpriteCssClass:"",dataContentUrlField:"",tabPosition:"top",animation:{open:{effects:"expand:vertical fadeIn",duration:200},close:{duration:200}},collapsible:false,navigatable:true,contentUrls:false,scrollable:{distance:i}},destroy:function(){var ab=this,aa=ab.scrollWrap;
Z.fn.destroy.call(ab);
if(ab._refreshHandler){ab.dataSource.unbind("change",ab._refreshHandler);
}ab.wrapper.off(I);
ab.wrapper.children(".k-tabstrip-items").off(I);
if(ab._scrollableModeActive){ab._scrollPrevButton.off().remove();
ab._scrollNextButton.off().remove();
}y.destroy(ab.wrapper);
aa.children(".k-tabstrip").unwrap();
},select:function(aa){var ab=this;
if(arguments.length===0){return ab.tabGroup.children("li."+d);
}if(!isNaN(aa)){aa=ab.tabGroup.children().get(aa);
}aa=ab.tabGroup.find(aa);
b(aa).each(function(ac,ad){ad=b(ad);
if(!ad.hasClass(d)&&!ab.trigger(O,{item:ad[0],contentElement:ab.contentHolder(ad.index())[0]})){ab.activateTab(ad);
}});
return ab;
},enable:function(aa,ab){this._toggleDisabled(aa,ab!==false);
return this;
},disable:function(aa){this._toggleDisabled(aa,false);
return this;
},reload:function(ab){ab=this.tabGroup.find(ab);
var ac=this;
var aa=ac._contentUrls;
ab.each(function(){var af=b(this),ae=af.find("."+C).data(h)||aa[af.index()],ad=ac.contentHolder(af.index());
if(ae){ac.ajaxRequest(af,ad,null,ae);
}});
return ac;
},append:function(ab){var ac=this,aa=ac._create(ab);
l(aa.tabs,function(ae){var ad=aa.contents[ae];
ac.tabGroup.append(this);
if(ac.options.tabPosition=="bottom"){ac.tabGroup.before(ad);
}else{if(ac._scrollableModeActive){ac._scrollPrevButton.before(ad);
}else{ac.wrapper.append(ad);
}}ac.angular("compile",function(){return{elements:[ad]};
});
});
X(ac.tabGroup);
ac._updateContentElements();
ac.resize(true);
return ac;
},_appendUrlItem:function(aa){this._contentUrls.push(aa);
},_moveUrlItem:function(aa,ab){this._contentUrls.splice(ab,0,this._contentUrls.splice(aa,1)[0]);
},_removeUrlItem:function(aa){this._contentUrls.splice(aa,1);
},insertBefore:function(ad,ac){if(b(ad).is(b(ac))){ac=this.tabGroup.find(ac).next();
}else{ac=this.tabGroup.find(ac);
}var ae=this,aa=ae._create(ad),ab=ae.element.find("[id='"+ac.attr("aria-controls")+"']");
l(aa.tabs,function(ah){var af=aa.contents[ah];
var ag=aa.newTabsCreated?ae._contentUrls.length-(aa.tabs.length-ah):b(af).index()-1;
ac.before(this);
ab.before(af);
ae._moveUrlItem(ag,b(this).index());
ae.angular("compile",function(){return{elements:[af]};
});
});
X(ae.tabGroup);
ae._updateContentElements(aa.newTabsCreated);
ae.resize(true);
return ae;
},insertAfter:function(ad,ac){if(b(ad).is(b(ac))){ac=this.tabGroup.find(ac).prev();
}else{ac=this.tabGroup.find(ac);
}var ae=this,aa=ae._create(ad),ab=ae.element.find("[id='"+ac.attr("aria-controls")+"']");
l(aa.tabs,function(ah){var af=aa.contents[ah];
var ag=aa.newTabsCreated?ae._contentUrls.length-(aa.tabs.length-ah):b(af).index()-1;
ac.after(this);
ab.after(af);
ae._moveUrlItem(ag,b(this).index());
ae.angular("compile",function(){return{elements:[af]};
});
});
X(ae.tabGroup);
ae._updateContentElements(aa.newTabsCreated);
ae.resize(true);
return ae;
},remove:function(ab){var ac=this;
var ad=typeof ab;
var aa;
if(ad==="string"){ab=ac.tabGroup.find(ab);
}else{if(ad==="number"){ab=ac.tabGroup.children().eq(ab);
}}aa=ab.map(function(){var af=b(this).index();
var ae=ac.contentElement(af);
y.destroy(ae);
ac._removeUrlItem(af);
return ae;
});
ab.remove();
aa.empty();
aa.remove();
ac._updateContentElements();
ac.resize(true);
return ac;
},_create:function(ad){var af=this,ae,ab,aa,ac=false;
ad=ad instanceof y.data.ObservableArray?ad.toJSON():ad;
if(b.isPlainObject(ad)||b.isArray(ad)){ad=b.isArray(ad)?ad:[ad];
ac=true;
ae=D(ad,function(ah,ag){af._appendUrlItem(ad[ag].contentUrl||null);
return b(R.renderItem({group:af.tabGroup,item:p(ah,{index:ag})}));
});
ab=D(ad,function(ah,ag){if(typeof ah.content=="string"||ah.contentUrl){return b(R.renderContent({item:p(ah,{index:ag})}));
}});
}else{if(typeof ad=="string"&&ad[0]!="<"){ae=af.element.find(ad);
}else{ae=b(ad);
}ab=b();
ae.each(function(){if(/k-tabstrip-items/.test(this.parentNode.className)){var ag=af.element.find("[id='"+this.getAttribute("aria-controls")+"']");
aa=ag;
}else{aa=b("<div class='"+f+"'/>");
}ab=ab.add(aa);
});
Y(ae);
}return{tabs:ae,contents:ab,newTabsCreated:ac};
},_toggleDisabled:function(aa,ab){aa=this.tabGroup.find(aa);
aa.each(function(){b(this).toggleClass(j,ab).toggleClass(k,!ab).attr("aria-disabled",!ab);
});
},_updateClasses:function(){var ad=this,ac,aa,ab;
ad.wrapper.addClass("k-widget k-header k-tabstrip");
ad.tabGroup=ad.wrapper.children("ul").addClass("k-tabstrip-items k-reset");
if(!ad.tabGroup[0]){ad.tabGroup=b("<ul class='k-tabstrip-items k-reset'/>").appendTo(ad.wrapper);
}ac=ad.tabGroup.find("li").addClass("k-item");
if(ac.length){aa=ac.filter("."+d).index();
ab=aa>=0?aa:W;
ad.tabGroup.contents().filter(function(){return this.nodeType==3&&!U(this.nodeValue);
}).remove();
}if(aa>=0){ac.eq(aa).addClass(Q);
}ad.contentElements=ad.wrapper.children("div");
ad.contentElements.addClass(f).eq(ab).addClass(d).css({display:"block"});
if(ac.length){Y(ac);
X(ad.tabGroup);
ad._updateContentElements(true);
}},_elementId:function(aa,ac){var ab=aa.attr("id");
var ae=this.element.attr("id");
if(!ab||ab.indexOf(ae+"-")>-1){var ad=(ae||y.guid())+"-";
return ad+(ac+1);
}return ab;
},_updateContentElements:function(ad){var af=this,ac=af._contentUrls,ae=af.tabGroup.children(".k-item"),ab=af.wrapper.children("div"),aa=af._elementId.bind(af);
if(ab.length&&ae.length>ab.length){ab.each(function(ah){var ag=aa(b(this),ah);
var ai=ae.filter("[aria-controls="+(this.id||0)+"]")[0];
if(!ai&&ad){ai=ae[ah];
}if(ai){ai.setAttribute("aria-controls",ag);
}this.setAttribute("id",ag);
});
}else{ae.each(function(ai){var ag=ab.eq(ai);
var ah=aa(ag,ai);
this.setAttribute("aria-controls",ah);
if(!ag.length&&ac[ai]){b("<div class='"+f+"'/>").appendTo(af.wrapper).attr("id",ah);
}else{ag.attr("id",ah);
if(!b(this).children(".k-loading")[0]&&!ac[ai]){b("<span class='k-loading k-complete'/>").prependTo(this);
}}ag.attr("role","tabpanel");
ag.filter(":not(."+d+")").attr("aria-hidden",true).attr("aria-expanded",false);
ag.filter("."+d).attr("aria-expanded",true);
});
}af.contentElements=af.contentAnimators=af.wrapper.children("div");
af.tabsHeight=J(af.tabGroup)+parseInt(af.wrapper.css("border-top-width"),10)+parseInt(af.wrapper.css("border-bottom-width"),10);
if(y.kineticScrollNeeded&&y.mobile.ui.Scroller){y.touchScroller(af.contentElements);
af.contentElements=af.contentElements.children(".km-scroll-container");
}},_wrapper:function(){var aa=this;
if(aa.element.is("ul")){aa.wrapper=aa.element.wrapAll("<div />").parent();
}else{aa.wrapper=aa.element;
}aa.scrollWrap=aa.wrapper.parent(".k-tabstrip-wrapper");
if(!aa.scrollWrap[0]){aa.scrollWrap=aa.wrapper.wrapAll("<div class='k-tabstrip-wrapper' />").parent();
}},_tabPosition:function(){var ab=this,aa=ab.options.tabPosition;
ab.wrapper.addClass("k-floatwrap k-tabstrip-"+aa);
if(aa=="bottom"){ab.tabGroup.appendTo(ab.wrapper);
}ab.resize(true);
},_setContentElementsDimensions:function(){var ah=this,ag=ah.options.tabPosition;
if(ag=="left"||ag=="right"){var ab=ah.wrapper.children(".k-content"),aa=ab.filter(":visible"),ad="margin-"+ag,af=ah.tabGroup,ac=K(af);
var ae=Math.ceil(af.height())-parseInt(aa.css("padding-top"),10)-parseInt(aa.css("padding-bottom"),10)-parseInt(aa.css("border-top-width"),10)-parseInt(aa.css("border-bottom-width"),10);
setTimeout(function(){ab.css(ad,ac).css("min-height",ae);
});
}},_resize:function(){this._setContentElementsDimensions();
this._scrollable();
},_sizeScrollWrap:function(aa){if(aa.is(":visible")){var ac=this.options.tabPosition;
var ab=Math.floor(J(aa,true))+(ac==="left"||ac==="right"?2:this.tabsHeight);
this.scrollWrap.css("height",ab).css("height");
}},_toggleHover:function(aa){b(aa.currentTarget).toggleClass(t,aa.type==E);
},_click:function(af){var ak=this,ag=af.find("."+C),ac=ag.attr(u),aa=ak.options.collapsible,ad=af.index(),ab=ak.contentHolder(ad),aj,ae,ah=af.parent().children(),ai=ah.filter("."+r);
if(af.closest(".k-widget")[0]!=ak.wrapper[0]){return;
}if(af.is("."+k+(!aa?",."+d:""))){ai.removeClass(r);
ak._focused=af;
af.addClass(r);
ak._current(af);
if(ak._scrollableModeActive){ak._scrollTabsToItem(af);
}return true;
}ae=ag.data(h)||ak._contentUrls[ad]||ac&&(ac.charAt(ac.length-1)=="#"||ac.indexOf("#"+ak.element[0].id+"-")!=-1);
aj=!ac||ae;
if(ak.tabGroup.children("[data-animating]").length){return aj;
}if(ak.trigger(O,{item:af[0],contentElement:ab[0]})){return true;
}if(aj===false){return;
}if(aa&&af.is("."+d)){ak.deactivateTab(af);
return true;
}if(ak.activateTab(af)){aj=true;
}return aj;
},_scrollable:function(){var ai=this,ae=ai.options,aj,ah,ag,af;
if(ai._scrollableAllowed()){ai.wrapper.addClass("k-tabstrip-scrollable");
aj=ai.wrapper[0].offsetWidth;
ah=ai.tabGroup[0].scrollWidth;
if(ah>aj&&!ai._scrollableModeActive){ai._nowScrollingTabs=false;
ai._isRtl=y.support.isRtl(ai.element);
var ac=y.support.mobileOS?"touchstart":"mousedown";
var ad=y.support.mobileOS?"touchend":"mouseup";
var aa=y.support.browser;
var ab=ai._isRtl&&!aa.msie&&!aa.edge;
ai.wrapper.append(N("prev","k-i-arrow-60-left")+N("next","k-i-arrow-60-right"));
ag=ai._scrollPrevButton=ai.wrapper.children(".k-tabstrip-prev");
af=ai._scrollNextButton=ai.wrapper.children(".k-tabstrip-next");
ai.tabGroup.css({marginLeft:K(ag)+9,marginRight:K(af)+12});
ag.on(ac+I,function(){ai._nowScrollingTabs=true;
ai._scrollTabsByDelta(ae.scrollable.distance*(ab?1:-1));
});
af.on(ac+I,function(){ai._nowScrollingTabs=true;
ai._scrollTabsByDelta(ae.scrollable.distance*(ab?-1:1));
});
ag.add(af).on(ad+I,function(){ai._nowScrollingTabs=false;
});
ai._scrollableModeActive=true;
ai._toggleScrollButtons();
}else{if(ai._scrollableModeActive&&ah<=aj){ai._scrollableModeActive=false;
ai.wrapper.removeClass("k-tabstrip-scrollable");
ai._scrollPrevButton.off().remove();
ai._scrollNextButton.off().remove();
ai.tabGroup.css({marginLeft:"",marginRight:""});
}else{if(!ai._scrollableModeActive){ai.wrapper.removeClass("k-tabstrip-scrollable");
}else{ai._toggleScrollButtons();
}}}}},_scrollableAllowed:function(){var aa=this.options;
if(aa.scrollable&&!aa.scrollable.distance){aa.scrollable={distance:i};
}return aa.scrollable&&!isNaN(aa.scrollable.distance)&&(aa.tabPosition=="top"||aa.tabPosition=="bottom");
},_scrollTabsToItem:function(ab){var ai=this,af=ai.tabGroup,aa=af.scrollLeft(),ae=K(ab),ac=ai._isRtl?ab.position().left:ab.position().left-af.children().first().position().left,ah=af[0].offsetWidth,ag=Math.ceil(parseFloat(af.css("padding-left"))),ad;
if(ai._isRtl){if(ac<0){ad=aa+ac-(ah-aa)-ag;
}else{if(ac+ae>ah){ad=aa+ac-ae+ag*2;
}}}else{if(aa+ah<ac+ae){ad=ac+ae-ah+ag*2;
}else{if(aa>ac){ad=ac-ag;
}}}af.finish().animate({scrollLeft:ad},"fast","linear",function(){ai._toggleScrollButtons();
});
},_scrollTabsByDelta:function(aa){var ad=this;
var ac=ad.tabGroup;
var ab=ac.scrollLeft();
ac.finish().animate({scrollLeft:ab+aa},"fast","linear",function(){if(ad._nowScrollingTabs&&!jQuery.fx.off){ad._scrollTabsByDelta(aa);
}else{ad._toggleScrollButtons();
}});
},_toggleScrollButtons:function(){var ab=this,ac=ab.tabGroup,aa=y.scrollLeft(ac);
ab._scrollPrevButton.toggle(aa!==0);
ab._scrollNextButton.toggle(aa<ac[0].scrollWidth-ac[0].offsetWidth-1);
},deactivateTab:function(ae){var af=this,ab=af.options.animation,aa=ab.open,ac=p({},ab.close),ad=ac&&"effects" in ac;
ae=af.tabGroup.find(ae);
ac=p(ad?ac:p({reverse:true},aa),{hide:true});
if(y.size(aa.effects)){ae.kendoAddClass(j,{duration:aa.duration});
ae.kendoRemoveClass(d,{duration:aa.duration});
}else{ae.addClass(j);
ae.removeClass(d);
}ae.removeAttr("aria-selected");
af.contentAnimators.filter("."+d).kendoStop(true,true).kendoAnimate(ac).removeClass(d).attr("aria-hidden",true);
},activateTab:function(aj){if(this.tabGroup.children("[data-animating]").length){return;
}aj=this.tabGroup.find(aj);
var ap=this,ab=ap.options.animation,aa=ab.open,ac=p({},ab.close),ag=ac&&"effects" in ac,al=aj.parent().children(),am=al.filter("."+d),ak=al.index(aj),ai=aa&&"duration" in aa&&"effects" in aa;
ac=p(ag?ac:p({reverse:true},aa),{hide:true});
if(y.size(aa.effects)){am.kendoRemoveClass(d,{duration:ac.duration});
aj.kendoRemoveClass(t,{duration:ac.duration});
}else{am.removeClass(d);
aj.removeClass(t);
}var ad=ap.contentAnimators;
if(ap.inRequest){ap.xhr.abort();
ap.inRequest=false;
}if(ad.length===0){ap.tabGroup.find("."+Q).removeClass(Q);
aj.addClass(Q).css("z-index");
aj.addClass(d);
ap._current(aj);
ap.trigger("change");
if(ap._scrollableModeActive){ap._scrollTabsToItem(aj);
}return false;
}var aq=ad.filter("."+d),af=ap.contentHolder(ak),ae=af.closest(".k-content");
ap.tabsHeight=J(ap.tabGroup)+parseInt(ap.wrapper.css("border-top-width"),10)+parseInt(ap.wrapper.css("border-bottom-width"),10);
ap._sizeScrollWrap(aq);
if(af.length===0){aq.removeClass(d).attr("aria-hidden",true).kendoStop(true,true).kendoAnimate(ac);
return false;
}aj.attr("data-animating",true);
var ah=(aj.children("."+C).data(h)||ap._contentUrls[ak]||false)&&af.is(m),ao=function(){am.removeAttr("aria-selected");
aj.attr("aria-selected",true);
ap._current(aj);
ap._sizeScrollWrap(ae);
ae.addClass(d).removeAttr("aria-hidden").kendoStop(true,true).attr("aria-expanded",true).kendoAnimate(p({init:function(){ap.trigger(P,{item:aj[0],contentElement:af[0]});
y.resize(af);
}},aa,{complete:function(){aj.removeAttr("data-animating");
ap.trigger(c,{item:aj[0],contentElement:af[0]});
y.resize(af);
ap.scrollWrap.css("height","").css("height");
if(ai&&(y.support.browser.msie||y.support.browser.edge)){af.finish().animate({opacity:0.9},"fast","linear",function(){af.finish().animate({opacity:1},"fast","linear");
});
}}}));
},an=function(){if(!ah){ao();
ap.trigger("change");
}else{aj.removeAttr("data-animating");
ap.ajaxRequest(aj,af,function(){aj.attr("data-animating",true);
ao();
ap.trigger("change");
});
}if(ap._scrollableModeActive){ap._scrollTabsToItem(aj);
}};
aq.removeClass(d);
ap.tabGroup.find("."+Q).removeClass(Q);
aj.addClass(Q).css("z-index");
if(y.size(aa.effects)){am.kendoAddClass(j,{duration:aa.duration});
aj.kendoAddClass(d,{duration:aa.duration});
}else{am.addClass(j);
aj.addClass(d);
}aq.attr("aria-hidden",true);
aq.attr("aria-expanded",false);
if(aq.length){aq.kendoStop(true,true).kendoAnimate(p({complete:an},ac));
}else{an();
}return true;
},contentElement:function(ad){if(isNaN(ad-0)){return W;
}var aa=this.contentElements&&this.contentElements[0]&&!y.kineticScrollNeeded?this.contentElements:this.contentAnimators;
var ac=b(this.tabGroup.children()[ad]).attr("aria-controls");
if(aa){for(var ab=0,ae=aa.length;
ab<ae;
ab++){if(aa.eq(ab).closest(".k-content")[0].id==ac){return aa[ab];
}}}return W;
},contentHolder:function(ab){var aa=b(this.contentElement(ab)),ac=aa.children(".km-scroll-container");
return y.support.touch&&ac[0]?ac:aa;
},ajaxRequest:function(ae,ac,ab,am){ae=this.tabGroup.find(ae);
var al=this,an=b.ajaxSettings.xhr,ai=ae.find("."+C),ad={},ah=ae.width()/2,ag=false,ak=ae.find(".k-loading").removeClass("k-complete");
if(!ak[0]){ak=b("<span class='k-loading'/>").prependTo(ae);
}var af=ah*2-ak.width();
var aj=function(){ak.animate({marginLeft:(parseInt(ak.css("marginLeft"),10)||0)<ah?af:0},500,aj);
};
if(y.support.browser.msie&&y.support.browser.version<10){setTimeout(aj,40);
}am=am||ai.data(h)||al._contentUrls[ae.index()]||ai.attr(u);
al.inRequest=true;
var aa={type:"GET",cache:false,url:am,dataType:"html",data:ad,xhr:function(){var ao=this,aq=an(),ap=ao.progressUpload?"progressUpload":ao.progress?"progress":false;
if(aq){b.each([aq,aq.upload],function(){if(this.addEventListener){this.addEventListener("progress",function(ar){if(ap){ao[ap](ar);
}},false);
}});
}ao.noProgress=!(window.XMLHttpRequest&&"upload" in new XMLHttpRequest());
return aq;
},progress:function(ao){if(ao.lengthComputable){var ap=parseInt(ao.loaded/ao.total*100,10)+"%";
ak.stop(true).addClass("k-progress").css({width:ap,marginLeft:0});
}},error:function(ap,ao){if(al.trigger("error",{xhr:ap,status:ao})){this.complete();
}},stopProgress:function(){clearInterval(ag);
ak.stop(true).addClass("k-progress")[0].style.cssText="";
},complete:function(ao){al.inRequest=false;
if(this.noProgress){setTimeout(this.stopProgress,500);
}else{this.stopProgress();
}if(ao.statusText=="abort"){ak.remove();
}},success:function(aq){ak.addClass("k-complete");
try{var ap=this,at=10;
if(ap.noProgress){ak.width(at+"%");
ag=setInterval(function(){ap.progress({lengthComputable:true,loaded:Math.min(at,100),total:100});
at+=10;
},40);
}al.angular("cleanup",function(){return{elements:ac.get()};
});
y.destroy(ac);
ac.html(aq);
}catch(ar){var ao=window.console;
if(ao&&ao.error){ao.error(ar.name+": "+ar.message+" in "+am);
}this.error(this.xhr,"error");
}if(ab){ab.call(al,ac);
}al.angular("compile",function(){return{elements:ac.get()};
});
al.trigger(g,{item:ae[0],contentElement:ac[0]});
}};
if(typeof am==="object"){aa=b.extend(true,{},aa,am);
if(x(aa.url)){aa.url=aa.url();
}}al.xhr=b.ajax(aa);
}});
p(R,{renderItem:function(ac){ac=p({tabStrip:{},group:{}},ac);
var aa=T.empty,ab=ac.item;
return T.item(p(ac,{image:ab.imageUrl?T.image:aa,sprite:ab.spriteCssClass?T.sprite:aa,itemWrapper:T.itemWrapper},M));
},renderContent:function(aa){return T.content(p(aa,M));
}});
y.ui.plugin(R);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
