(function(b,a){a("kendo.timepicker",["kendo.popup","kendo.dateinput"],b);
}(function(){var a={id:"timepicker",name:"TimePicker",category:"web",description:"The TimePicker widget allows the end user to select a value from a list of predefined values or to type a new value.",depends:["popup"]};
(function(b,W){var z=window.kendo,A=z.keys,K=z.parseDate,c=z._activeElement,r=z._extractFormat,R=z.support,i=R.browser,V=z.ui,X=V.Widget,J="open",l="close",j="change",I=".kendoTimePicker",k="click"+I,n="k-state-default",o="disabled",N="readonly",C="li",P="<span/>",s="k-state-focused",u="k-state-hover",v="mouseenter"+I+" mouseleave"+I,E="mousedown"+I,G=60000,F=86400000,O="k-state-selected",Q="k-state-disabled",h="aria-selected",f="aria-expanded",g="aria-hidden",e="aria-disabled",d="aria-activedescendant",w="id",x=b.isArray,q=b.extend,M=b.proxy,m=Date,U=new m();
U=new m(U.getFullYear(),U.getMonth(),U.getDate(),0,0,0);
var T=function(Z){var aa=this,Y=Z.id;
aa.options=Z;
aa._dates=[];
aa.ul=b('<ul tabindex="-1" role="listbox" aria-hidden="true" unselectable="on" class="k-list k-reset"/>').css({overflow:R.kineticScrollNeeded?"":"auto"}).on(k,C,M(aa._click,aa)).on("mouseenter"+I,C,function(){b(this).addClass(u);
}).on("mouseleave"+I,C,function(){b(this).removeClass(u);
});
aa.list=b("<div class='k-list-container k-list-scroller' unselectable='on'/>").append(aa.ul).on(E,L);
if(Y){aa._timeViewID=Y+"_timeview";
aa._optionID=Y+"_option_selected";
aa.ul.attr(w,aa._timeViewID);
}aa._popup();
aa._heightHandler=M(aa._height,aa);
aa.template=z.template('<li tabindex="-1" role="option" class="k-item" unselectable="on">#=data#</li>',{useWithBlock:false});
};
T.prototype={current:function(Z){var aa=this,Y=aa.options.active;
if(Z!==W){if(aa._current){aa._current.removeClass(O);
if(aa._current&&aa._current.length){aa._current[0].removeAttribute(w);
aa._current[0].removeAttribute(h);
}}if(Z){Z=b(Z).addClass(O).attr(w,aa._optionID).attr(h,true);
aa.scroll(Z[0]);
}aa._current=Z;
if(Y){Y(Z);
}}else{return aa._current;
}},close:function(){this.popup.close();
},destroy:function(){var Y=this;
Y.ul.off(I);
Y.list.off(I);
Y.popup.destroy();
},open:function(){var Z=this;
var Y;
if(!Z.ul[0].firstChild){Z.bind();
}Y=Z.popup._hovered;
Z.popup._hovered=true;
Z.popup.open();
setTimeout(function(){Z.popup._hovered=Y;
},1);
if(Z._current){Z.scroll(Z._current[0]);
}},dataBind:function(Z){var ag=this,ae=ag.options,aa=ae.format,ah=z.toString,af=ag.template,ad=Z.length,ac=0,Y,ab="";
for(;
ac<ad;
ac++){Y=Z[ac];
if(y(Y,ae.min,ae.max)){ab+=af(ah(Y,aa,ae.culture));
}}ag._html(ab);
},refresh:function(){var ap=this,ak=ap.options,Y=ak.format,aj=p(),aa=aj<0,ar=z.parseDate(ap._value),al=ar?D(ar,ak.min):D(new Date(),ak.min),ad=ak.min,ac=ak.max,ah=t(ad),ag=t(ac),af=t(B(ak.interval)),ae=ak.interval*G,aq=z.toString,ao=ap.template,am=ak.useValueToRender?al:new Date(+ak.min),an=new m(am),ai,ab,Z="";
if(aa){ab=(F+aj*G)/ae;
}else{ab=F/ae;
}if(ah!=ag||af===ag){if(ah>ag){ag+=F;
}ab=(ag-ah)/ae+1;
}while(true){if(ag&&(t(am)>=ag||an.getDate()!=am.getDate())){ai=t(am);
if(an<am){ai+=F;
}if(ai>ag){am=new m(+ac);
}if(t(am)>0){Z+=ao(aq(am,Y,ak.culture));
}break;
}if(an.getDate()!=am.getDate()){break;
}Z+=ao(aq(am,Y,ak.culture));
am.setTime(am.getTime()+ae);
}ap._html(Z);
},bind:function(){var Z=this,Y=Z.options.dates;
if(Y&&Y[0]){Z.dataBind(Y);
}else{Z.refresh();
}},_html:function(Y){var Z=this;
Z.ul[0].innerHTML=Y;
Z.popup.unbind(J,Z._heightHandler);
Z.popup.one(J,Z._heightHandler);
Z.current(null);
Z.select(Z._value);
},scroll:function(ac){if(!ac){return;
}var Z=this.list[0],ae=ac.offsetTop,ad=ac.offsetHeight,ab=Z.scrollTop,aa=Z.clientHeight,Y=ae+ad;
if(ab>ae){ab=ae;
}else{if(Y>ab+aa){ab=Y-aa;
}}Z.scrollTop=ab;
},select:function(Z){var ac=this,aa=ac.options,Y=ac._current,ab;
if(Z instanceof Date){Z=z.toString(Z,aa.format,aa.culture);
}if(typeof Z==="string"){if(!Y||Y.text()!==Z){Z=b.grep(ac.ul[0].childNodes,function(ad){return(ad.textContent||ad.innerText)==Z;
});
Z=Z[0]?Z:null;
}else{Z=Y;
}}ab=ac._distinctSelection(Z);
ac.current(ab);
},_distinctSelection:function(Z){var ab=this,Y,aa;
if(Z&&Z.length>1){Y=t(ab._value);
aa=b.inArray(Y,ab._dates);
Z=ab.ul.children()[aa];
}return Z;
},setOptions:function(Z){var Y=this.options;
Z.min=K(Z.min);
Z.max=K(Z.max);
this.options=q(Y,Z,{active:Y.active,change:Y.change,close:Y.close,open:Y.open});
this.bind();
},toggle:function(){var Y=this;
if(Y.popup.visible()){Y.close();
}else{Y.open();
}},value:function(Z){var Y=this;
Y._value=Z;
if(Y.ul[0].firstChild){Y.select(Z);
}},_click:function(aa){var ac=this,ab=b(aa.currentTarget),Y=ab.text(),Z=ac.options.dates;
if(Z&&Z.length>0){Y=Z[ab.index()];
}if(!aa.isDefaultPrevented()){ac.select(ab);
ac.options.change(Y,true);
ac.close();
}},_height:function(){var ab=this;
var Z=ab.list;
var aa=Z.parent(".k-animation-container");
var Y=ab.options.height;
if(ab.ul[0].children.length){Z.add(aa).show().height(ab.ul[0].scrollHeight>Y?Y:"auto").hide();
}},_parse:function(ad){var ac=this,ab=ac.options,aa=t(ab.min)!=t(U)?ab.min:null,Z=t(ab.max)!=t(U)?ab.max:null,Y=ac._value||aa||Z||U;
if(ad instanceof m){return ad;
}ad=K(ad,ab.parseFormats,ab.culture);
if(ad){ad=new m(Y.getFullYear(),Y.getMonth(),Y.getDate(),ad.getHours(),ad.getMinutes(),ad.getSeconds(),ad.getMilliseconds());
}return ad;
},_adjustListWidth:function(){var aa=this.list,ac=aa[0].style.width,ad=this.options.anchor,Y,Z,ab=z._outerWidth;
if(!aa.data("width")&&ac){return;
}Y=window.getComputedStyle?window.getComputedStyle(ad[0],null):0;
Z=Y?parseFloat(Y.width):ab(ad);
if(Y&&(i.mozilla||i.msie)){Z+=parseFloat(Y.paddingLeft)+parseFloat(Y.paddingRight)+parseFloat(Y.borderLeftWidth)+parseFloat(Y.borderRightWidth);
}ac=Z-(ab(aa)-aa.width());
aa.css({fontFamily:ad.css("font-family"),width:ac}).data("width",ac);
},_popup:function(){var ab=this,Z=ab.list,aa=ab.options,Y=aa.anchor;
ab.popup=new V.Popup(Z,q(aa.popup,{anchor:Y,open:aa.open,close:aa.close,animation:aa.animation,isRtl:R.isRtl(aa.anchor)}));
},move:function(aa){var ac=this,ab=aa.keyCode,ad=ac.ul[0],Y=ac._current,Z=ab===A.DOWN;
if(ab===A.UP||Z){if(aa.altKey){ac.toggle(Z);
return;
}else{if(Z){Y=Y?Y[0].nextSibling:ad.firstChild;
}else{Y=Y?Y[0].previousSibling:ad.lastChild;
}}if(Y){ac.select(Y);
}ac.options.change(ac._current.text());
aa.preventDefault();
}else{if(ab===A.ENTER||ab===A.TAB||ab===A.ESC){aa.preventDefault();
if(Y){ac.options.change(Y.text(),true);
}ac.close();
}}}};
function p(){var aa=new m(),Y=new m(aa.getFullYear(),aa.getMonth(),aa.getDate(),0,0,0),Z=new m(aa.getFullYear(),aa.getMonth(),aa.getDate(),12,0,0);
return -1*(Y.getTimezoneOffset()-Z.getTimezoneOffset());
}function t(Y){return Y.getHours()*60*G+Y.getMinutes()*G+Y.getSeconds()*1000+Y.getMilliseconds();
}function B(Z){var Y=new Date(2100,0,1);
Y.setMinutes(-Z);
return Y;
}function y(ad,Z,Y){var ab=t(Z),aa=t(Y),ac;
if(!ad||ab==aa){return true;
}ac=t(ad);
if(ab>ac){ac+=F;
}if(aa<ab){aa+=F;
}return ac>=ab&&ac<=aa;
}T.getMilliseconds=t;
z.TimeView=T;
var S=X.extend({init:function(aa,ad){var ae=this,ah,af,Y;
X.fn.init.call(ae,aa,ad);
aa=ae.element;
ad=ae.options;
ad.min=K(aa.attr("min"))||K(ad.min);
ad.max=K(aa.attr("max"))||K(ad.max);
H(ad);
ae._initialOptions=q({},ad);
ae._wrapper();
ae.timeView=af=new T(q({},ad,{id:aa.attr(w),anchor:ae.wrapper,format:ad.format,change:function(aj,ai){if(ai){ae._change(aj);
}else{aa.val(aj);
}},open:function(ai){ae.timeView._adjustListWidth();
if(ae.trigger(J)){ai.preventDefault();
}else{aa.attr(f,true);
ah.attr(g,false);
}},close:function(ai){if(ae.trigger(l)){ai.preventDefault();
}else{aa.attr(f,false);
ah.attr(g,true);
}},active:function(ai){if(aa&&aa.length){aa[0].removeAttribute(d);
}if(ai){aa.attr(d,af._optionID);
}}}));
ah=af.ul;
ae._icon();
ae._reset();
try{aa[0].setAttribute("type","text");
}catch(Z){aa[0].type="text";
}aa.addClass("k-input").attr({role:"combobox","aria-expanded":false,"aria-owns":af._timeViewID,autocomplete:"off"});
Y=aa.is("[disabled]")||b(ae.element).parents("fieldset").is(":disabled");
if(Y){ae.enable(false);
}else{ae.readonly(aa.is("[readonly]"));
}if(ad.dateInput){var ac=ad.min;
var ab=ad.max;
var ag=new m();
if(t(ac)==t(ab)){ac=new m(ag.getFullYear(),ag.getMonth(),ag.getDate(),0,0,0);
ab=new m(ag.getFullYear(),ag.getMonth(),ag.getDate(),24,0,0);
}ae._dateInput=new V.DateInput(aa,{culture:ad.culture,format:ad.format,min:ac,max:ab,value:ad.value,interval:ad.interval});
}ae._old=ae._update(ad.value||ae.element.val());
ae._oldText=aa.val();
z.notify(ae);
},options:{name:"TimePicker",min:U,max:U,format:"",dates:[],parseFormats:[],value:null,interval:30,height:200,animation:{},dateInput:false},events:[J,l,j],setOptions:function(Y){var Z=this;
var aa=Z._value;
X.fn.setOptions.call(Z,Y);
Y=Z.options;
H(Y);
Z.timeView.setOptions(Y);
if(aa){Z.element.val(z.toString(aa,Y.format,Y.culture));
}},dataBind:function(Y){if(x(Y)){this.timeView.dataBind(Y);
}},_editable:function(ab){var ad=this,Z=ab.disable,ac=ab.readonly,Y=ad._arrow.off(I),aa=ad.element.off(I),ae=ad._inputWrapper.off(I);
if(ad._dateInput){ad._dateInput._unbindInput();
}if(!ac&&!Z){ae.addClass(n).removeClass(Q).on(v,ad._toggleHover);
if(aa&&aa.length){aa[0].removeAttribute(o);
aa[0].removeAttribute(N);
}aa.attr(e,false).on("keydown"+I,M(ad._keydown,ad)).on("focusout"+I,M(ad._blur,ad)).on("focus"+I,function(){ad._inputWrapper.addClass(s);
});
if(ad._dateInput){ad._dateInput._bindInput();
}Y.on(k,M(ad._click,ad)).on(E,L);
}else{ae.addClass(Z?Q:n).removeClass(Z?n:Q);
aa.attr(o,Z).attr(N,ac).attr(e,Z);
}},readonly:function(Y){this._editable({readonly:Y===W?true:Y,disable:false});
},enable:function(Y){this._editable({readonly:false,disable:!(Y=Y===W?true:Y)});
},destroy:function(){var Y=this;
X.fn.destroy.call(Y);
Y.timeView.destroy();
Y.element.off(I);
Y._arrow.off(I);
Y._inputWrapper.off(I);
if(Y._form){Y._form.off("reset",Y._resetHandler);
}},close:function(){this.timeView.close();
},open:function(){this.timeView.open();
},min:function(Y){return this._option("min",Y);
},max:function(Y){return this._option("max",Y);
},value:function(Z){var Y=this;
if(Z===W){return Y._value;
}Y._old=Y._update(Z);
if(Y._old===null){Y.element.val("");
}Y._oldText=Y.element.val();
},_blur:function(){var Y=this,Z=Y.element.val();
Y.close();
if(Z!==Y._oldText){Y._change(Z);
}Y._inputWrapper.removeClass(s);
},_click:function(){var Z=this,Y=Z.element;
Z.timeView.toggle();
if(!R.touch&&Y[0]!==c()){Y.trigger("focus");
}},_change:function(ac){var ab=this,Z=ab.element.val(),Y;
ac=ab._update(ac);
Y=!z.calendar.isEqualDate(ab._old,ac);
var ad=Y&&!ab._typing;
var aa=Z!==ab.element.val();
if(ad||aa){ab.element.trigger(j);
}if(Y){ab._old=ac;
ab._oldText=ab.element.val();
ab.trigger(j);
}ab._typing=false;
},_icon:function(){var aa=this,Z=aa.element,Y;
Y=Z.next("span.k-select");
if(!Y[0]){Y=b('<span unselectable="on" class="k-select" aria-label="select"><span class="k-icon k-i-clock"></span></span>').insertAfter(Z);
}aa._arrow=Y.attr({role:"button","aria-controls":aa.timeView._timeViewID});
},_keydown:function(Y){var aa=this,Z=Y.keyCode,ab=aa.timeView,ac=aa.element.val();
if(ab.popup.visible()||Y.altKey){ab.move(Y);
if(aa._dateInput&&Y.stopImmediatePropagation){Y.stopImmediatePropagation();
}}else{if(Z===A.ENTER&&ac!==aa._oldText){aa._change(ac);
}else{aa._typing=true;
}}},_option:function(Y,ab){var aa=this,Z=aa.options;
if(ab===W){return Z[Y];
}ab=aa.timeView._parse(ab);
if(!ab){return;
}ab=new m(+ab);
Z[Y]=ab;
aa.timeView.options[Y]=ab;
aa.timeView.bind();
},_toggleHover:function(Y){b(Y.currentTarget).toggleClass(u,Y.type==="mouseenter");
},_update:function(ac){var aa=this,Z=aa.options,ab=aa.timeView,Y=ab._parse(ac);
if(!y(Y,Z.min,Z.max)){Y=null;
}aa._value=Y;
if(aa._dateInput&&Y){aa._dateInput.value(Y||ac);
}else{aa.element.val(z.toString(Y||ac,Z.format,Z.culture));
}ab.value(Y);
return Y;
},_wrapper:function(){var Z=this,Y=Z.element,aa;
aa=Y.parents(".k-timepicker");
if(!aa[0]){aa=Y.wrap(P).parent().addClass("k-picker-wrap k-state-default");
aa=aa.wrap(P).parent();
}aa[0].style.cssText=Y[0].style.cssText;
Z.wrapper=aa.addClass("k-widget k-timepicker").addClass(Y[0].className);
Y.css({width:"100%",height:Y[0].style.height});
Z._inputWrapper=b(aa[0].firstChild);
},_reset:function(){var ab=this,Y=ab.element,aa=Y.attr("form"),Z=aa?b("#"+aa):Y.closest("form");
if(Z[0]){ab._resetHandler=function(){ab.value(Y[0].defaultValue);
ab.max(ab._initialOptions.max);
ab.min(ab._initialOptions.min);
};
ab._form=Z.on("reset",ab._resetHandler);
}}});
function H(Y){var Z=Y.parseFormats;
Y.format=r(Y.format||z.getCulture(Y.culture).calendars.standard.patterns.t);
Z=x(Z)?Z:[Z];
Z.splice(0,0,Y.format);
Y.parseFormats=Z;
}function L(Y){Y.preventDefault();
}function D(Y,Z){return new Date(Y.getFullYear(),Y.getMonth(),Y.getDate(),Z.getHours(),Z.getMinutes(),Z.getSeconds(),Z.getMilliseconds());
}V.plugin(S);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
