(function(b,a){a("kendo.window",["kendo.draganddrop","kendo.popup"],b);
}(function(){var a={id:"window",name:"Window",category:"web",description:"The Window widget displays content in a modal or non-modal HTML window.",depends:["draganddrop","popup"],features:[{id:"window-fx",name:"Animation",description:"Support for animation",depends:["fx"]}]};
(function(b,ah){var y=window.kendo,aj=y.ui.Widget,ac=y.ui.Popup.TabKeyTrap,m=y.ui.Draggable,v=b.isPlainObject,d=y._activeElement,S=y._outerWidth,R=y._outerHeight,V=b.proxy,r=b.extend,o=b.each,ad=y.template,e="body",ae,P=".kendoWindow",O=".kendoWindowModal",E=".k-window",H=".k-window-title",I=H+"bar",F=".k-window-content",x=".k-dialog-content",G=".k-resize-handle",B=".k-overlay",w="k-content-frame",J="k-i-loading",A="k-state-hover",z="k-state-focused",L="k-window-maximized",ai=":visible",t="hidden",h="cursor",Q="open",c="activate",j="deactivate",f="close",W="refresh",M="minimize",K="maximize",aa="resizeStart",Y="resize",Z="resizeEnd",n="dragstart",l="dragend",p="error",T="overflow",i="original-overflow-rule",ap="zIndex",N=".k-window-actions .k-i-window-minimize,.k-window-actions .k-i-window-maximize",C=".k-i-pin",D=".k-i-unpin",U=C+","+D,af=".k-window-titlebar .k-window-action",X=".k-window-titlebar .k-i-refresh",am="WindowEventsHandled",ao=/^0[a-z]*$/i,u=y.isLocalUrl,ab={small:"k-window-sm",medium:"k-window-md",large:"k-window-lg"};
function k(aq){return typeof aq!="undefined";
}function ag(aq,ar){return parseInt(aq.css(ar),10)||0;
}function g(au,ar,aq){var at;
if(au&&isNaN(au)&&au.toString().indexOf("px")<0){at=au;
}else{at=Math.max(Math.min(parseInt(au,10),aq===Infinity?aq:parseInt(aq,10)),ar===-Infinity?ar:parseInt(ar,10));
}return at;
}function q(){return !this.type||this.type.toLowerCase().indexOf("script")>=0;
}function s(aq){var av={top:aq.offsetTop,left:aq.offsetLeft},ar=aq.offsetParent;
while(ar){av.top+=ar.offsetTop;
av.left+=ar.offsetLeft;
var at=b(ar).css("overflowX");
var au=b(ar).css("overflowY");
if(au==="auto"||au==="scroll"){av.top-=ar.scrollTop;
}if(at==="auto"||at==="scroll"){av.left-=ar.scrollLeft;
}ar=ar.offsetParent;
}return av;
}var ak=aj.extend({init:function(at,ay){var aB=this,aF,ax={},aC,ar,az,aw=false,aq,aD,aE,au,aA=ay&&ay.actions&&!ay.actions.length,av;
aj.fn.init.call(aB,at,ay);
ay=aB.options;
az=ay.position;
at=aB.element;
aq=ay.content;
au=b(window);
if(aA){ay.actions=[];
}aB.appendTo=b(ay.appendTo);
aB.containment=ay.draggable.containment?b(ay.draggable.containment).first():null;
if(aq&&!v(aq)){aq=ay.content={url:aq};
}at.find("script").filter(q).remove();
if(!at.parent().is(aB.appendTo)&&!aB.containment&&(az.top===ah||az.left===ah)){if(at.is(ai)){ax=at.offset();
aw=true;
}else{aC=at.css("visibility");
ar=at.css("display");
at.css({visibility:t,display:""});
ax=at.offset();
at.css({visibility:aC,display:ar});
}if(az.top===ah){az.top=ax.top;
}if(az.left===ah){az.left=ax.left;
}}if(!k(ay.visible)||ay.visible===null){ay.visible=at.is(ai);
}aF=aB.wrapper=at.closest(E);
if(!at.is(".k-content")||!aF[0]){at.addClass("k-window-content k-content");
aB._createWindow(at,ay);
aF=aB.wrapper=at.closest(E);
aB.title(aB.options.title);
aB._dimensions();
}aB.minTop=aB.minLeft=-Infinity;
aB.maxTop=aB.maxLeft=Infinity;
aB._position();
if(aq){aB.refresh(aq);
}if(ay.visible){aB.toFront();
}aD=aF.children(F);
aB._tabindex(aD);
if(ay.visible&&ay.modal){aB._overlay(aF.is(ai)).css({opacity:0.5});
}aF.on("mouseenter"+P,af,V(aB._buttonEnter,aB)).on("mouseleave"+P,af,V(aB._buttonLeave,aB)).on("click"+P,"> "+af,V(aB._windowActionHandler,aB)).on("keydown"+P,V(aB._keydown,aB)).on("focus"+P,V(aB._focus,aB)).on("blur"+P,V(aB._blur,aB));
aD.on("keydown"+P,V(aB._keydown,aB)).on("focus"+P,V(aB._focus,aB)).on("blur"+P,V(aB._blur,aB));
aE=aD.find("."+w)[0];
if(aE&&!au.data(am)){au.on("blur"+P,function(){var aG=b(document.activeElement).parent(F);
if(aG.length){var aH=y.widgetInstance(aG);
aH._focus();
}});
au.on("focus"+P,function(){b(F).not(x).each(function(aH,aG){y.widgetInstance(b(aG))._blur();
});
});
au.data(am,true);
}this._resizable();
this._draggable();
if(ay.pinned&&this.wrapper.is(":visible")){aB.pin();
}av=at.attr("id");
if(av){av=av+"_wnd_title";
aF.children(I).children(H).attr("id",av);
aD.attr({role:"dialog","aria-labelledby":av});
}aF.add(aF.children(".k-resize-handle,"+I)).on("mousedown"+P,V(aB.toFront,aB));
aB.touchScroller=y.touchScroller(at);
aB._resizeHandler=V(aB._onDocumentResize,aB);
aB._marker=y.guid().substring(0,8);
b(window).on("resize"+P+aB._marker,aB._resizeHandler);
if(ay.visible){aB.trigger(Q);
aB.trigger(c);
}y.notify(aB);
if(this.options.modal){this._tabKeyTrap=new ac(aF);
this._tabKeyTrap.trap();
this._tabKeyTrap.shouldTrap=function(){return aD.data("isFront");
};
}},_buttonEnter:function(aq){b(aq.currentTarget).addClass(A);
},_buttonLeave:function(aq){b(aq.currentTarget).removeClass(A);
},_focus:function(){this.wrapper.addClass(z);
},_blur:function(){this.wrapper.removeClass(z);
},_dimensions:function(){var aD=this.wrapper;
var ax=this.options;
var aC=ax.width;
var at=ax.height;
var aw=ax.maxHeight;
var az=ax.size;
var ar=["minWidth","minHeight","maxWidth","maxHeight"];
var aq=aD.css("box-sizing")=="content-box";
var av=aq?ag(aD,"border-left-width")+ag(aD,"border-right-width"):0;
var aA=aq?ag(aD,"border-top-width")+ag(aD,"border-bottom-width"):0;
var ay=aq?ag(aD,"padding-top"):0;
if(this.containment&&!this._isPinned){this._updateBoundaries();
ax.maxHeight=Math.min(this.containment.height-(aA+ay),aw);
ax.maxWidth=Math.min(this.containment.width-av,ax.maxWidth);
}for(var au=0;
au<ar.length;
au++){var aB=ax[ar[au]]||"";
if(aB!=Infinity){aD.css(ar[au],aB);
}}if(aw!=Infinity){this.element.css("maxHeight",aw);
}if(aC){aD.width(g(aC,ax.minWidth,ax.maxWidth));
}else{aD.width("");
}if(at){aD.height(g(at,ax.minHeight,ax.maxHeight));
}else{aD.height("");
}if(!ax.visible){aD.hide();
}if(az&&ab[az]){aD.addClass(ab[az]);
}},_position:function(){var ar=this.wrapper,aq=this.options.position;
this._updateBoundaries();
if(this.containment){aq.top=Math.min(this.minTop+(aq.top||0),this.maxTop);
aq.left=Math.min(this.minLeft+(aq.left||0),this.maxLeft);
}if(aq.top===0){aq.top=aq.top.toString();
}if(aq.left===0){aq.left=aq.left.toString();
}ar.css({top:aq.top||"",left:aq.left||""});
},_updateBoundaries:function(){var aq=this.containment;
if(!aq){return null;
}aq.width=aq.innerWidth();
aq.height=aq.innerHeight();
if(parseInt(aq.width,10)>aq[0].clientWidth){aq.width-=y.support.scrollbar();
}if(parseInt(aq.height,10)>aq[0].clientHeight){aq.height-=y.support.scrollbar();
}aq.position=s(aq[0]);
if(this._isPinned){this.minTop=this.minLeft=-Infinity;
this.maxTop=this.maxLeft=Infinity;
}else{this.minTop=aq.scrollTop();
this.minLeft=aq.scrollLeft();
this.maxLeft=this.minLeft+aq.width-S(this.wrapper,true);
this.maxTop=this.minTop+aq.height-R(this.wrapper,true);
}},_animationOptions:function(at){var aq=this.options.animation;
var ar={open:{effects:{}},close:{hide:true,effects:{}}};
return aq&&aq[at]||ar[at];
},_resize:function(){y.resize(this.element.children());
},_resizable:function(){var aq=this.options.resizable;
var ar=this.wrapper;
if(this.resizing){ar.off("dblclick"+P).children(G).remove();
this.resizing.destroy();
this.resizing=null;
}if(aq){ar.on("dblclick"+P,I,V(function(at){if(!b(at.target).closest(".k-window-action").length){this.toggleMaximization();
}},this));
o("n e s w se sw ne nw".split(" "),function(au,at){ar.append(ae.resizeHandle(at));
});
this.resizing=new an(this);
}ar=null;
},_draggable:function(){var aq=this.options.draggable;
if(this.dragging){this.dragging.destroy();
this.dragging=null;
}if(aq){this.dragging=new al(this,aq.dragHandle||I);
}},_actions:function(){var at=this.options;
var aq=at.actions;
var au=at.pinned;
var av=this.wrapper.children(I);
var ar=av.find(".k-window-actions");
var aw=["maximize","minimize"];
aq=b.map(aq,function(ax){ax=au&&ax.toLowerCase()==="pin"?"unpin":ax;
return{name:aw.indexOf(ax.toLowerCase())>-1?"window-"+ax:ax};
});
ar.html(y.render(ae.action,aq));
},setOptions:function(ar){var av=this;
var au=av.options.size;
var aq=JSON.parse(JSON.stringify(ar));
r(ar.position,av.options.position);
r(ar.position,aq.position);
aj.fn.setOptions.call(av,ar);
var at=av.options.scrollable!==false;
av.restore();
if(typeof ar.title!=="undefined"){av.title(ar.title);
}av.wrapper.removeClass(ab[au]);
av._dimensions();
av._position();
av._resizable();
av._draggable();
av._actions();
if(typeof ar.modal!=="undefined"){var aw=av.options.visible!==false;
av._enableDocumentScrolling();
av._overlay(ar.modal&&aw);
}av.element.css(T,at?"":"hidden");
},events:[Q,c,j,f,M,K,W,aa,Y,Z,n,l,p],options:{name:"Window",animation:{open:{effects:{zoom:{direction:"in"},fade:{direction:"in"}},duration:350},close:{effects:{zoom:{direction:"out",properties:{scale:0.7}},fade:{direction:"out"}},duration:350,hide:true}},title:"",actions:["Close"],autoFocus:true,modal:false,size:"auto",resizable:true,draggable:true,minWidth:90,minHeight:50,maxWidth:Infinity,maxHeight:Infinity,pinned:false,scrollable:true,position:{},content:null,visible:null,height:null,width:null,appendTo:"body",isMaximized:false,isMinimized:false},_closable:function(){return b.inArray("close",b.map(this.options.actions,function(aq){return aq.toLowerCase();
}))>-1;
},_keydown:function(ar){var aD=this,aC=aD.options,ay=y.keys,ax=ar.keyCode,aF=aD.wrapper,aB,au,aq=10,av=aC.isMaximized,aw=aC.isMinimized,aA,az,aE,at;
if(ax==ay.ESC&&aD._closable()){ar.stopPropagation();
aD._close(false);
}if(ar.target!=ar.currentTarget||aD._closing){return;
}if(ar.altKey&&ax==82){aD.refresh();
}if(ar.altKey&&ax==80){if(aD.options.pinned){aD.unpin();
}else{aD.pin();
}}if(ar.altKey&&ax==ay.UP){if(aw){aD.restore();
aD.element.focus();
}else{if(!av){aD.maximize();
aD.element.focus();
}}}else{if(ar.altKey&&ax==ay.DOWN){if(!aw&&!av){aD.minimize();
aD.wrapper.focus();
}else{if(av){aD.restore();
aD.element.focus();
}}}}aB=y.getOffset(aF);
if(aD.containment&&!aD._isPinned){aB=aD.options.position;
}if(aC.draggable&&!ar.ctrlKey&&!ar.altKey&&!av){aD._updateBoundaries();
if(ax==ay.UP){aB.top=g(aB.top-aq,aD.minTop,aD.maxTop);
au=aF.css("top",aB.top);
}else{if(ax==ay.DOWN){aB.top=g(aB.top+aq,aD.minTop,aD.maxTop);
au=aF.css("top",aB.top);
}else{if(ax==ay.LEFT){aB.left=g(aB.left-aq,aD.minLeft,aD.maxLeft);
au=aF.css("left",aB.left);
}else{if(ax==ay.RIGHT){aB.left=g(aB.left+aq,aD.minLeft,aD.maxLeft);
au=aF.css("left",aB.left);
}}}}}if(aC.resizable&&ar.ctrlKey&&!av&&!aw){if(ax==ay.UP){au=true;
az=aF.height()-aq;
}else{if(ax==ay.DOWN){au=true;
if(aD.containment&&!aD._isPinned){az=Math.min(aF.height()+aq,aD.containment.height-aB.top-ag(aF,"padding-top")-ag(aF,"borderBottomWidth")-ag(aF,"borderTopWidth"));
}else{az=aF.height()+aq;
}}}if(ax==ay.LEFT){au=true;
aA=aF.width()-aq;
}else{if(ax==ay.RIGHT){au=true;
if(aD.containment&&!aD._isPinned){aA=Math.min(aF.width()+aq,aD.containment.width-aB.left-ag(aF,"borderLeftWidth")-ag(aF,"borderRightWidth"));
}else{aA=aF.width()+aq;
}}}if(au){aE=g(aA,aC.minWidth,aC.maxWidth);
at=g(az,aC.minHeight,aC.maxHeight);
if(!isNaN(aE)){aF.width(aE);
aD.options.width=aE+"px";
}if(!isNaN(at)){aF.height(at);
aD.options.height=at+"px";
}aD.resize();
}}if(au){ar.preventDefault();
}},_overlay:function(ar){var aq=this.containment?this.containment.children(B):this.appendTo.children(B),at=this.wrapper;
if(!aq.length){aq=b("<div class='k-overlay' />");
}aq.insertBefore(at[0]).toggle(ar).css(ap,parseInt(at.css(ap),10)-1);
if(this.options.modal.preventScroll&&!this.containment){this._stopDocumentScrolling();
}return aq;
},_actionForIcon:function(aq){var ar=/\bk-i(-\w+)+\b/.exec(aq[0].className)[0];
return{"k-i-close":"_close","k-i-window-maximize":"maximize","k-i-window-minimize":"minimize","k-i-window-restore":"restore","k-i-refresh":"refresh","k-i-pin":"pin","k-i-unpin":"unpin"}[ar];
},_windowActionHandler:function(ar){if(this._closing){return;
}var at=b(ar.target).closest(".k-window-action").find(".k-icon");
var aq=this._actionForIcon(at);
if(aq){ar.preventDefault();
this[aq]();
return false;
}},_modals:function(){var aq=this;
var ar=b(E).filter(function(){var at=b(this);
var au=aq._object(at);
var av=au&&au.options;
return av&&av.modal&&av.visible&&av.appendTo===aq.options.appendTo&&at.is(ai);
}).sort(function(at,au){return +b(at).css("zIndex")-+b(au).css("zIndex");
});
aq=null;
return ar;
},_object:function(ar){var aq=ar.children(F);
var at=y.widgetInstance(aq);
if(at){return at;
}return ah;
},center:function(){var ax=this,au=ax.options.position,ay=ax.wrapper,aq=b(window),aw=0,av=0,at,ar;
if(ax.options.isMaximized){return ax;
}if(ax.options.pinned&&!ax._isPinned){ax.pin();
}if(!ax.options.pinned){aw=aq.scrollTop();
av=aq.scrollLeft();
}if(this.containment&&!ax.options.pinned){at=this.minTop+(this.maxTop-this.minTop)/2;
ar=this.minLeft+(this.maxLeft-this.minLeft)/2;
}else{ax._scrollIsAppended=true;
ar=av+Math.max(0,(aq.width()-ay.width())/2);
at=aw+Math.max(0,(aq.height()-ay.height()-ag(ay,"paddingTop"))/2);
}ay.css({left:ar,top:at});
au.top=at;
au.left=ar;
return ax;
},title:function(au){var at=this,ay,ar=true,aA=at.wrapper,av=aA.children(I),ax=av.children(H),aw,aq,az;
if(!arguments.length){return ax.html();
}if(b.isPlainObject(au)){ay=typeof au.text!=="undefined"?au.text:"";
ar=au.encoded!==false;
}else{ay=au;
}if(ay===false){aA.addClass("k-window-titleless");
aA.css("padding-top",0);
av.remove();
}else{if(!av.length){aA.prepend(ae.titlebar({title:ar?y.htmlEncode(ay):ay}));
at._actions();
av=aA.children(I);
}else{ax.html(ar?y.htmlEncode(ay):ay);
}az=aA.css("visibility");
aq=aA.css("display");
if(az===t){aA.css({display:""});
aw=parseInt(R(av),10);
aA.css({display:aq});
}else{aA.css({visibility:t,display:""});
aw=parseInt(R(av),10);
aA.css({visibility:az,display:aq});
}aA.css("padding-top",aw);
av.css("margin-top",-aw);
}at.options.title=ay;
return at;
},content:function(at,ar){var aq=this.wrapper.children(F),au=aq.children(".km-scroll-container");
aq=au[0]?au:aq;
if(!k(at)){return aq.html();
}this.angular("cleanup",function(){return{elements:aq.children()};
});
y.destroy(this.element.children());
aq.empty().html(at);
this.angular("compile",function(){var av=[];
for(var aw=aq.length;
--aw>=0;
){av.push({dataItem:ar});
}return{elements:aq.children(),data:av};
});
return this;
},open:function(){var az=this,aA=az.wrapper,au=az.options,ay=this._animationOptions("open"),ar=aA.children(F),aw,av,aq=this.containment&&!az._isPinned,at=aq?this.containment:b(document);
if(!az.trigger(Q)){if(az._closing){aA.kendoStop(true,true);
}az._closing=false;
az.toFront();
if(au.autoFocus){az.element.focus();
}au.visible=true;
if(au.modal){av=!!az._modals().length;
aw=az._overlay(av);
aw.kendoStop(true,true);
if(ay.duration&&y.effects.Fade&&!av){var ax=y.fx(aw).fadeIn();
ax.duration(ay.duration||0);
ax.endValue(0.5);
ax.play();
}else{aw.css("opacity",0.5);
}aw.show();
b(window).on("focus"+O,function(){if(ar.data("isFront")&&!b(document.activeElement).closest(ar).length){az.element.focus();
}});
}if(!aA.is(ai)){ar.css(T,t);
az.wrapper.find(af).addClass("k-bare");
aA.show().kendoStop().kendoAnimate({effects:ay.effects,duration:ay.duration,complete:V(this._activate,this)});
}}if(au.isMaximized){az._containerScrollTop=at.scrollTop();
az._containerScrollLeft=at.scrollLeft();
az._stopDocumentScrolling();
}if(this.options.pinned&&!this._isPinned){this.pin();
}return az;
},_activate:function(){var aq=this.options.scrollable!==false;
if(this.options.autoFocus){this.element.focus();
}this.element.css(T,aq?"":"hidden");
y.resize(this.element.children());
this.trigger(c);
},_removeOverlay:function(ax){var at=this._modals();
var au=this.options;
var ar=au.modal&&!at.length;
var av=au.modal?this._overlay(true):b(ah);
var aq=this._animationOptions("close");
if(ar){if(!ax&&aq.duration&&y.effects.Fade){var aw=y.fx(av).fadeOut();
aw.duration(aq.duration||0);
aw.startValue(0.5);
aw.play();
}else{this._overlay(false).remove();
}if(au.modal.preventScroll){this._enableDocumentScrolling();
}}else{if(at.length){this._object(at.last())._overlay(true);
if(au.modal.preventScroll){this._stopDocumentScrolling();
}}}},_close:function(ax){var ay=this,az=ay.wrapper,av=ay.options,aw=this._animationOptions("open"),au=this._animationOptions("close"),aq=this.containment&&!ay._isPinned,at=aq?this.containment:b(document),ar;
if(ay._closing){return;
}ar=ay.trigger(f,{userTriggered:!ax});
ay._closing=!ar;
if(az.is(ai)&&!ar){av.visible=false;
b(E).each(function(aC,aB){var aA=b(aB).children(F);
if(aB!=az&&aA.find("> ."+w).length>0){aA.children(B).remove();
}});
this._removeOverlay();
ay.wrapper.find(af).removeClass("k-bare");
az.kendoStop().kendoAnimate({effects:au.effects||aw.effects,reverse:au.reverse===true,duration:au.duration,complete:V(this._deactivate,this)});
b(window).off(O);
}if(ay.options.isMaximized){ay._enableDocumentScrolling();
if(ay._containerScrollTop&&ay._containerScrollTop>0){at.scrollTop(ay._containerScrollTop);
}if(ay._containerScrollLeft&&ay._containerScrollLeft>0){at.scrollLeft(ay._containerScrollLeft);
}}},_deactivate:function(){var ar=this;
ar.wrapper.hide().css("opacity","");
ar.trigger(j);
if(ar.options.modal){var aq=ar._object(ar._modals().last());
if(aq){aq.toFront();
}}},close:function(){this._close(true);
return this;
},_actionable:function(aq){return b(aq).is(af+","+af+" .k-icon,:input,a");
},_shouldFocus:function(at){var aq=d(),ar=this.element;
return this.options.autoFocus&&!b(aq).is(ar)&&!this._actionable(at)&&(!ar.find(aq).length||!ar.find(at).length);
},toFront:function(at){var ax=this,az=ax.wrapper,ar=az[0],aq=ax.containment&&!ax._isPinned,aA=+az.css(ap),au=aA,aw=at&&at.target||null;
b(E).each(function(aD,aC){var aE=b(aC),aF=aE.css(ap),aB=aE.children(F);
if(!isNaN(aF)){aA=Math.max(+aF,aA);
}aB.data("isFront",aC==ar);
if(aC!=ar&&aB.find("> ."+w).length>0){aB.append(ae.overlay);
}});
if(!az[0].style.zIndex||au<aA){az.css(ap,aA+2);
}ax.element.find("> .k-overlay").remove();
if(ax._shouldFocus(aw)){if(ax.isMinimized()){ax.wrapper.focus();
}else{if(b(aw).is(B)){setTimeout(function(){ax.element.focus();
});
}else{ax.element.focus();
}}var av=aq?ax.containment.scrollTop():b(window).scrollTop(),ay=parseInt(az.position().top,10);
if(!ax.options.pinned&&ay>0&&ay<av){if(av>0){b(window).scrollTop(ay);
}else{az.css("top",av);
}}}az=null;
return ax;
},toggleMaximization:function(){if(this._closing){return this;
}return this[this.options.isMaximized?"restore":"maximize"]();
},restore:function(){var aw=this;
var at=aw.options;
var ar=at.minHeight;
var au=aw.restoreOptions;
var av;
var aq=aw.containment&&!aw._isPinned?aw.containment:b(document);
if(!at.isMaximized&&!at.isMinimized){return aw;
}if(ar&&ar!=Infinity){aw.wrapper.css("min-height",ar);
}if(au&&!at.isMaximized){au.height=g(au.height,aw.options.minHeight,aw.options.maxHeight);
av=at.position.top+parseInt(au.height,10)>aw.maxTop;
if(av){at.position.top=g(at.position.top,aw.minTop,aw.maxTop-parseInt(au.height,10));
r(au,{left:at.position.left,top:at.position.top});
}}aw.wrapper.css({position:at.pinned?"fixed":"absolute",left:au.left,top:au.top,width:au.width,height:au.height}).removeClass(L).find(".k-window-content,.k-resize-handle").show().end().find(".k-window-titlebar .k-i-window-restore").parent().remove().end().end().find(N).parent().show().end().end().find(U).parent().show();
if(at.isMaximized){aw.wrapper.find(".k-i-window-maximize").parent().focus();
}else{if(at.isMinimized){aw.wrapper.find(".k-i-window-minimize").parent().focus();
}}aw.options.width=au.width;
aw.options.height=au.height;
if(!aw.options.modal.preventScroll){aw._enableDocumentScrolling();
}if(aw._containerScrollTop&&aw._containerScrollTop>0){aq.scrollTop(aw._containerScrollTop);
}if(aw._containerScrollLeft&&aw._containerScrollLeft>0){aq.scrollLeft(aw._containerScrollLeft);
}at.isMaximized=at.isMinimized=false;
aw.wrapper.removeAttr("tabindex");
aw.wrapper.removeAttr("aria-labelled-by");
aw.resize();
return aw;
},_sizingAction:function(aq,ar){var av=this,aw=av.wrapper,au=aw[0].style,at=av.options;
if(at.isMaximized||at.isMinimized){return av;
}av.restoreOptions={width:au.width,height:au.height};
aw.children(G).hide().end().children(I).find(N).parent().hide().eq(0).before(ae.action({name:"window-restore"}));
ar.call(av);
av.wrapper.children(I).find(U).parent().toggle(aq!=="maximize");
av.trigger(aq);
aw.find(".k-i-window-restore").parent().focus();
return av;
},maximize:function(){this._sizingAction("maximize",function(){var au=this,av=au.wrapper,aq=this.containment&&!au._isPinned,at=av.position(),ar=b(document);
r(au.restoreOptions,{left:at.left+(aq?this.containment.scrollLeft():0),top:at.top+(aq?this.containment.scrollTop():0)});
this._containerScrollTop=aq?this.containment.scrollTop():ar.scrollTop();
this._containerScrollLeft=aq?this.containment.scrollLeft():ar.scrollLeft();
au._stopDocumentScrolling();
av.css({top:aq?this.containment.scrollTop():0,left:aq?this.containment.scrollLeft():0,position:aq?"absolute":"fixed"}).addClass(L);
au.options.isMaximized=true;
au._onDocumentResize();
});
return this;
},_stopDocumentScrolling:function(){var au=this;
var at=au.containment;
if(at&&!au._isPinned){au._storeOverflowRule(at);
at.css(T,t);
au.wrapper.css({maxWidth:at.innerWidth(),maxHeight:at.innerHeight()});
return;
}var aq=b("body");
au._storeOverflowRule(aq);
aq.css(T,t);
var ar=b("html");
au._storeOverflowRule(ar);
ar.css(T,t);
},_enableDocumentScrolling:function(){var ar=this;
var aq=ar.containment;
if(aq&&!ar._isPinned){ar._restoreOverflowRule(aq);
ar.wrapper.css({maxWidth:aq.width,maxHeight:aq.height});
return;
}ar._restoreOverflowRule(b(document.body));
ar._restoreOverflowRule(b("html"));
},_storeOverflowRule:function(aq){if(this._isOverflowStored(aq)){return;
}var ar=aq.get(0).style.overflow;
if(typeof ar==="string"){aq.data(i,ar);
}},_isOverflowStored:function(aq){return typeof aq.data(i)==="string";
},_restoreOverflowRule:function(aq){var ar=aq.data(i);
if(ar!==null&&ar!==ah){aq.css(T,ar);
aq.removeData(i);
}else{aq.css(T,"");
}},isMaximized:function(){return this.options.isMaximized;
},minimize:function(){this._sizingAction("minimize",function(){var aq=this;
aq.wrapper.css({height:"",minHeight:""});
aq.element.hide();
aq.options.isMinimized=true;
});
this.wrapper.attr("tabindex",0);
this.wrapper.attr("aria-labelled-by",this.element.attr("aria-labelled-by"));
this._updateBoundaries();
return this;
},isMinimized:function(){return this.options.isMinimized;
},pin:function(){var au=this,aw=b(window),ax=au.wrapper,ar=au.options,at=ar.position,av=this.containment?s(ax[0]).top+ag(this.containment,"borderTopWidth"):ag(ax,"top"),aq=this.containment?s(ax[0]).left+ag(this.containment,"borderLeftWidth"):ag(ax,"left");
if(!au.options.isMaximized){at.top=av;
at.left=aq;
if(au._scrollIsAppended&&(!this.containment||this.containment.css("position")!=="fixed")){at.top-=aw.scrollTop();
at.left-=aw.scrollLeft();
au._scrollIsAppended=false;
}ax.css(r(at,{position:"fixed"}));
ax.children(I).find(C).addClass("k-i-unpin").removeClass("k-i-pin");
au._isPinned=true;
au.options.pinned=true;
if(this.containment){ar.maxWidth=ar.maxHeight=Infinity;
ax.css({maxWidth:"",maxHeight:""});
}}},unpin:function(){var av=this,ax=b(window),ay=av.wrapper,at=av.options,au=av.options.position,aq=av.containment,aw=parseInt(ay.css("top"),10)+ax.scrollTop(),ar=parseInt(ay.css("left"),10)+ax.scrollLeft();
if(!av.options.isMaximized){av._isPinned=false;
av._scrollIsAppended=true;
av.options.pinned=false;
if(aq){av._updateBoundaries();
at.maxWidth=Math.min(aq.width,at.maxWidth);
at.maxHeight=Math.min(aq.height-ag(ay,"padding-top"),at.maxHeight);
ay.css({maxWidth:at.maxWidth,maxHeight:at.maxHeight});
if(aw<aq.position.top){aw=av.minTop;
}else{if(aw>aq.position.top+aq.height){aw=av.maxTop;
}else{aw=aw+aq.scrollTop()-(aq.position.top+ag(aq,"border-top-width"));
}}if(ar<aq.position.left){ar=av.minLeft;
}else{if(ar>aq.position.left+aq.width){ar=av.maxLeft;
}else{ar=ar+aq.scrollLeft()-(aq.position.left+ag(aq,"border-left-width"));
}}}au.top=g(aw,av.minTop,av.maxTop);
au.left=g(ar,av.minLeft,av.maxLeft);
ay.css(r(au,{position:""}));
ay.children(I).find(D).addClass("k-i-pin").removeClass("k-i-unpin");
}},_onDocumentResize:function(){var aw=this,az=aw.wrapper,ay=b(window),aA=y.support.zoomLevel(),aq=az.css("box-sizing")=="content-box",ax,ar;
if(!aw.options.isMaximized){return;
}var at=aq?ag(az,"border-left-width")+ag(az,"border-right-width"):0;
var av=aq?ag(az,"border-top-width")+ag(az,"border-bottom-width"):0;
var au=aq?ag(az,"padding-top"):0;
if(aw.containment&&!aw._isPinned){ax=aw.containment.innerWidth()-at;
ar=aw.containment.innerHeight()-(av+au);
}else{ax=ay.width()/aA-at;
ar=ay.height()/aA-(av+au);
}az.css({width:ax,height:ar});
aw.options.width=ax;
aw.options.height=ar;
aw.resize();
},refresh:function(au){var aw=this,at=aw.options,aq=b(aw.element),ar,av,ax;
if(!v(au)){au={url:au};
}au=r({},at.content,au);
av=k(at.iframe)?at.iframe:au.iframe;
ax=au.url;
if(ax){if(!k(av)){av=!u(ax);
}if(!av){aw._ajaxRequest(au);
}else{ar=aq.find("."+w)[0];
if(ar){ar.src=ax||ar.src;
}else{aq.html(ae.contentFrame(r({},at,{content:au})));
}aq.find("."+w).unbind("load"+P).on("load"+P,V(this._triggerRefresh,this));
}}else{if(au.template){aw.content(ad(au.template)({}));
}aw.trigger(W);
}aq.toggleClass("k-window-iframecontent",!!av);
return aw;
},_triggerRefresh:function(){this.trigger(W);
},_ajaxComplete:function(){clearTimeout(this._loadingIconTimeout);
this.wrapper.find(X).removeClass(J);
},_ajaxError:function(ar,aq){this.trigger(p,{status:aq,xhr:ar});
},_ajaxSuccess:function(aq){return function(ar){var at=ar;
if(aq){at=ad(aq)(ar||{});
}this.content(at,ar);
this.element.prop("scrollTop",0);
this.trigger(W);
};
},_showLoading:function(){this.wrapper.find(X).addClass(J);
},_ajaxRequest:function(aq){this._loadingIconTimeout=setTimeout(V(this._showLoading,this),100);
b.ajax(r({type:"GET",dataType:"html",cache:false,error:V(this._ajaxError,this),complete:V(this._ajaxComplete,this),success:V(this._ajaxSuccess(aq.template),this)},aq));
},_destroy:function(){if(this.resizing){this.resizing.destroy();
}if(this.dragging){this.dragging.destroy();
}this.wrapper.off(P).children(F).off(P).end().find(".k-resize-handle,.k-window-titlebar").off(P);
b(window).off("resize"+P+this._marker);
b(window).off(O);
b(window).off(P);
clearTimeout(this._loadingIconTimeout);
aj.fn.destroy.call(this);
this.unbind(ah);
y.destroy(this.wrapper);
this._removeOverlay(true);
},destroy:function(){this._destroy();
this.wrapper.empty().remove();
this.wrapper=this.appendTo=this.element=b();
},_createWindow:function(){var aq=this.element,au=this.options,ar,av,at=y.support.isRtl(aq);
if(au.scrollable===false){aq.css("overflow","hidden");
}av=b(ae.wrapper(au));
ar=aq.find("iframe:not(.k-content)").map(function(){var aw=this.getAttribute("src");
this.src="";
return aw;
});
av.toggleClass("k-rtl",at).append(aq).find("iframe:not(.k-content)").each(function(aw){this.src=ar[aw];
});
if(this.containment){this.containment.prepend(av);
}else{if(this.appendTo){av.appendTo(this.appendTo);
}}av.find(".k-window-title").css(at?"left":"right",S(av.find(".k-window-actions"))+10);
aq.css("visibility","").show();
aq.find("[data-role=editor]").each(function(){var aw=b(this).data("kendoEditor");
if(aw){aw.refresh();
}});
av=aq=null;
}});
ae={wrapper:ad("<div class='k-widget k-window' />"),action:ad("<a role='button' href='\\#' class='k-button k-bare k-button-icon k-window-action' aria-label='#= name #'><span class='k-icon k-i-#= name.toLowerCase() #'></span></a>"),titlebar:ad("<div class='k-window-titlebar k-header'><span class='k-window-title'>#= title #</span><div class='k-window-actions' /></div>"),overlay:"<div class='k-overlay' />",contentFrame:ad("<iframe frameborder='0' title='#= title #' class='"+w+"' src='#= content.url #'>This page requires frames in order to show content</iframe>"),resizeHandle:ad("<div class='k-resize-handle k-resize-#= data #'></div>")};
function an(ar){var aq=this;
aq.owner=ar;
aq._preventDragging=false;
aq._draggable=new m(ar.wrapper,{filter:">"+G,group:ar.wrapper.id+"-resizing",dragstart:V(aq.dragstart,aq),drag:V(aq.drag,aq),dragend:V(aq.dragend,aq)});
aq._draggable.userEvents.bind("press",V(aq.addOverlay,aq));
aq._draggable.userEvents.bind("release",V(aq.removeOverlay,aq));
}an.prototype={addOverlay:function(){this.owner.wrapper.append(ae.overlay);
},removeOverlay:function(){this.owner.wrapper.find(B).remove();
},dragstart:function(aq){var ay=this;
var az=ay.owner;
var aA=az.wrapper;
ay._preventDragging=az.trigger(aa);
if(ay._preventDragging){return;
}ay.elementPadding=parseInt(aA.css("padding-top"),10);
ay.initialPosition=y.getOffset(aA,"position");
ay.resizeDirection=aq.currentTarget.prop("className").replace("k-resize-handle k-resize-","");
ay.initialSize={width:aA.width(),height:aA.height()};
az._updateBoundaries();
ay.containerOffset=az.containment?az.containment.position:y.getOffset(az.appendTo,"position");
var av=aA.offsetParent();
if(av.is("html")){ay.containerOffset.top=ay.containerOffset.left=0;
}else{var au=av.css("margin-top");
var at=av.css("margin-left");
var ar=!ao.test(au)||!ao.test(at);
if(ar){var aB=s(aA[0]);
var aw=aB.left-ay.containerOffset.left-ay.initialPosition.left;
var ax=aB.top-ay.containerOffset.top-ay.initialPosition.top;
ay._relativeElMarginLeft=aw>1?aw:0;
ay._relativeElMarginTop=ax>1?ax:0;
ay.initialPosition.left+=ay._relativeElMarginLeft;
ay.initialPosition.top+=ay._relativeElMarginTop;
}}aA.children(G).not(aq.currentTarget).hide();
b(e).css(h,aq.currentTarget.css(h));
},drag:function(au){if(this._preventDragging){return;
}var aF=this,aI=aF.owner,aJ=aI.wrapper,aB=aI.options,aC=aB.position,at=aF.resizeDirection,aq=aF.containerOffset,av=aF.initialPosition,aw=aF.initialSize,ar=aI.containment&&!aI._isPinned,aD=y.support.isRtl(aI.containment),ax=ar&&aD&&aI.containment.innerWidth()>aI.containment.width?y.support.scrollbar():0,aE=ar?{top:aI.containment.scrollTop(),left:aI.containment.scrollLeft()}:{top:0,left:0},az,ay,aG,aH,aK=Math.max(au.x.location,0),aL=Math.max(au.y.location,0);
if(at.indexOf("e")>=0){if(aI.containment&&aK-aw.width>=aI.maxLeft-aE.left+aq.left+ax){az=aI.maxLeft+ax-av.left+aw.width-aE.left;
}else{az=aK-av.left-aq.left;
}aJ.width(g(az,aB.minWidth,aB.maxWidth));
}else{if(at.indexOf("w")>=0){aH=av.left+aw.width+aq.left;
az=g(aH-aK,aB.minWidth,aB.maxWidth);
aC.left=aH-az-aq.left-ax-(aF._relativeElMarginLeft||0)+aE.left;
if(aI.containment&&aC.left<=aI.minLeft){aC.left=aI.minLeft;
az=g(aH-ax-aC.left-aq.left+aE.left,aB.minWidth,aB.maxWidth);
}aJ.css({left:aC.left,width:az});
}}var aA=aL;
if(aI.options.pinned){aA-=b(window).scrollTop();
}if(at.indexOf("s")>=0){ay=aA-av.top-aF.elementPadding-aq.top;
if(aA-aw.height-aF.elementPadding>=aI.maxTop+aq.top-aE.top){ay=aI.maxTop-av.top+aw.height-aE.top;
}aJ.height(g(ay,aB.minHeight,aB.maxHeight));
}else{if(at.indexOf("n")>=0){aG=av.top+aw.height+aq.top;
ay=g(aG-aA,aB.minHeight,aB.maxHeight);
aC.top=aG-ay-aq.top-(aF._relativeElMarginTop||0)+aE.top;
if(aC.top<=aI.minTop&&aI.containment){aC.top=aI.minTop;
ay=g(aG-aC.top-aq.top+aE.top,aB.minHeight,aB.maxHeight);
}aJ.css({top:aC.top,height:ay});
}}if(az){aI.options.width=az+"px";
}if(ay){aI.options.height=ay+"px";
}aI.resize();
},dragend:function(aq){if(this._preventDragging){return;
}var ar=this,at=ar.owner,au=at.wrapper;
au.children(G).not(aq.currentTarget).show();
b(e).css(h,"");
if(at.touchScroller){at.touchScroller.reset();
}if(aq.keyCode==27){au.css(ar.initialPosition).css(ar.initialSize);
}at.trigger(Z);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
function al(at,aq){var ar=this;
ar.owner=at;
ar._preventDragging=false;
ar._draggable=new m(at.wrapper,{filter:aq,group:at.wrapper.id+"-moving",dragstart:V(ar.dragstart,ar),drag:V(ar.drag,ar),dragend:V(ar.dragend,ar),dragcancel:V(ar.dragcancel,ar)});
ar._draggable.userEvents.stopPropagation=false;
}al.prototype={dragstart:function(au){var aw=this.owner,at=aw.options.draggable,av=aw.element,aq=av.find(".k-window-actions"),ar=y.getOffset(aw.appendTo);
this._preventDragging=aw.trigger(n)||!at;
if(this._preventDragging||aw.isMaximized()){return;
}aw.initialWindowPosition=y.getOffset(aw.wrapper,"position");
aw.initialPointerPosition={left:aw.options.position.left,top:aw.options.position.top};
aw.startPosition={left:au.x.client-aw.initialWindowPosition.left,top:au.y.client-aw.initialWindowPosition.top};
aw._updateBoundaries();
if(!aw.containment){if(aq.length>0){aw.minLeft=S(aq)+parseInt(aq.css("right"),10)-S(av);
}else{aw.minLeft=20-S(av);
}aw.minLeft-=ar.left;
aw.minTop=-ar.top;
}aw.wrapper.append(ae.overlay).children(G).hide();
b(e).css(h,au.currentTarget.css(h));
},drag:function(ar){var aw=this.owner;
var au=aw.options.position;
var aq=aw.options.draggable.axis;
var at;
var av;
if(this._preventDragging||aw.isMaximized()){return;
}if(!aq||aq.toLowerCase()==="x"){at=ar.x.client-aw.startPosition.left;
if(aw.containment&&!aw._isPinned){at+=aw.containment.scrollLeft();
}au.left=g(at,aw.minLeft,aw.maxLeft);
}if(!aq||aq.toLowerCase()==="y"){av=ar.y.client-aw.startPosition.top;
if(aw.containment&&!aw._isPinned){av+=aw.containment.scrollTop();
}au.top=g(av,aw.minTop,aw.maxTop);
}if(y.support.transforms){b(aw.wrapper).css("transform","translate("+(au.left-aw.initialPointerPosition.left)+"px, "+(au.top-aw.initialPointerPosition.top)+"px)");
}else{b(aw.wrapper).css(au);
}},_finishDrag:function(){var aq=this.owner;
aq.wrapper.children(G).toggle(!aq.options.isMinimized).end().find(B).remove();
b(e).css(h,"");
},dragcancel:function(aq){if(this._preventDragging){return;
}this._finishDrag();
aq.currentTarget.closest(E).css(this.owner.initialWindowPosition);
},dragend:function(){var aq=this.owner;
if(this._preventDragging||aq.isMaximized()){return;
}b(aq.wrapper).css(aq.options.position).css("transform","");
this._finishDrag();
aq.trigger(l);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
y.ui.plugin(ak);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
