(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,p){var o=this._map;
var m={key:n,value:p};
o[n]=m;
if(!this._head){this._head=this._tail=m;
}else{this._tail.newer=m;
m.older=this._tail;
this._tail=m;
}if(this._length>=this._size){o[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(n){var m=this._map[n];
if(m){if(m===this._head&&m!==this._tail){this._head=m.newer;
this._head.older=null;
}if(m!==this._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=this._tail;
m.newer=null;
this._tail.newer=m;
this._tail=m;
}return m.value;
}}});
var i=/\r?\n|\r|\t/g;
var j=" ";
function g(m){return String(m).replace(i,j);
}function h(n){var o=[];
for(var m in n){o.push(m+n[m]);
}return o.sort().join("");
}function d(o){var m=2166136261;
for(var n=0;
n<o.length;
++n){m+=(m<<1)+(m<<4)+(m<<7)+(m<<8)+(m<<24);
m^=o.charCodeAt(n);
}return m>>>0;
}function l(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: pre!important;";
}var k=kendo.Class.extend({init:function(m){this._cache=new e(1000);
this.options=a.extend({},b,m);
},measure:function(v,t,r){if(r===void 0){r={};
}if(!v){return l();
}var u=h(t);
var o=d(v+u);
var n=this._cache.get(o);
if(n){return n;
}var s=l();
var q=r.box||c;
var m=this._baselineMarker().cloneNode(false);
for(var p in t){var x=t[p];
if(typeof x!=="undefined"){q.style[p]=x;
}}var w=r.normalizeText!==false?g(v):String(v);
q.textContent=w;
q.appendChild(m);
document.body.appendChild(q);
if(w.length){s.width=q.offsetWidth-this.options.baselineMarkerSize;
s.height=q.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(o,s);
}q.parentNode.removeChild(q);
return s;
},_baselineMarker:function(){var m=document.createElement("div");
m.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return m;
}});
k.current=new k();
function f(o,n,m){return k.current.measure(o,n,m);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:k,measureText:f,objectKey:h,hashKey:d,normalizeText:g});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("dataviz/sparkline/kendo-sparkline",["kendo.dataviz.chart"],b);
}(function(){(function(){window.kendo.dataviz=window.kendo.dataviz||{};
var c=kendo.dataviz;
var b=c.constants;
var a=c.Chart;
var g=c.elementSize;
var f=c.deepExtend;
var m=-2;
var j=c.SharedTooltip.extend({_slotAnchor:function(q,s){var p=this.plotArea.categoryAxis;
var t=p.options.vertical;
var o=t?{horizontal:"left",vertical:"center"}:{horizontal:"center",vertical:"bottom"};
var r;
if(t){r=new c.Point(this.plotArea.box.x2,s.center().y);
}else{r=new c.Point(s.center().x,m);
}return{point:r,align:o};
},_defaultAnchor:function(o,p){return this._slotAnchor({},p);
}});
var d=150;
var e=150;
var i=[b.BAR,b.BULLET];
function h(p){var r=[];
for(var q=0;
q<p.length;
q++){var o=p[q];
r[q]=o.style.display;
o.style.display="none";
}return r;
}function k(o,q){for(var p=0;
p<o.length;
p++){o[p].style.display=q[p];
}}function n(o){return c.isNumber(o)?[o]:o;
}var l=a.extend({_setElementClass:function(o){c.addClass(o,"k-sparkline");
},_initElement:function(o){a.fn._initElement.call(this,o);
this._initialWidth=Math.floor(g(o).width);
},_resize:function(){var o=this.element;
var p=h(o.childNodes);
this._initialWidth=Math.floor(g(o).width);
k(o.childNodes,p);
a.fn._resize.call(this);
},_modelOptions:function(){var o=this.options;
var s=this._surfaceWrap();
var p=h(s.childNodes);
var r=document.createElement("span");
r.innerHTML="&nbsp;";
s.appendChild(r);
var q=f({width:this._autoWidth,height:g(s).height,transitions:o.transitions},o.chartArea,{inline:true,align:false});
g(s,{width:q.width,height:q.height});
s.removeChild(r);
k(s.childNodes,p);
if(this.surface){this.surface.resize();
}return q;
},_surfaceWrap:function(){if(!this.stage){var o=this.stage=document.createElement("span");
this.element.appendChild(o);
}return this.stage;
},_createPlotArea:function(p){var o=a.fn._createPlotArea.call(this,p);
this._autoWidth=this._initialWidth||this._calculateWidth(o);
return o;
},_calculateWidth:function(v){var u=this.options;
var t=c.getSpacing(u.chartArea.margin);
var p=v.charts;
var y=this._surfaceWrap();
var z=0;
for(var s=0;
s<p.length;
s++){var q=p[s];
var r=(q.options.series||[])[0];
if(!r){continue;
}if(r.type===b.BAR){return d;
}if(r.type===b.BULLET){return e;
}if(r.type===b.PIE){return g(y).height;
}var o=q.categoryAxis;
if(o){var w=o.categoriesCount()*(!q.options.isStacked&&c.inArray(r.type,[b.COLUMN,b.VERTICAL_BULLET])?q.seriesOptions.length:1);
z=Math.max(z,w);
}}var x=z*u.pointWidth;
if(x>0){x+=t.left+t.right;
}return x;
},_createSharedTooltip:function(o){return new j(this._plotArea,o);
}});
l.normalizeOptions=function(p){var o=n(p);
if(c.isArray(o)){o={seriesDefaults:{data:o}};
}else{o=f({},o);
}if(!o.series){o.series=[{data:n(o.data)}];
}f(o,{seriesDefaults:{type:o.type}});
if(c.inArray(o.series[0].type,i)||c.inArray(o.seriesDefaults.type,i)){o=f({},{categoryAxis:{crosshair:{visible:false}}},o);
}return o;
};
c.setDefaultOptions(l,{chartArea:{margin:2},axisDefaults:{visible:false,majorGridLines:{visible:false},valueAxis:{narrowRange:true}},seriesDefaults:{type:"line",area:{line:{width:0.5}},bar:{stack:true},padding:2,width:0.5,overlay:{gradient:null},highlight:{visible:false},border:{width:0},markers:{size:2,visible:false}},tooltip:{visible:true,shared:true},categoryAxis:{crosshair:{visible:true,tooltip:{visible:false}}},legend:{visible:false},transitions:false,pointWidth:5,panes:[{clip:false}]});
kendo.deepExtend(kendo.dataviz,{Sparkline:l});
}());
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("dataviz/sparkline/sparkline",["dataviz/sparkline/kendo-sparkline"],b);
}(function(){(function(a){var d=kendo.dataviz;
var b=d.ui.Chart;
var f=d.Sparkline;
var c=d.ChartInstanceObserver;
var e=a.extend;
var g=b.extend({init:function(i,k){var j=k;
if(j instanceof kendo.data.ObservableArray){j={seriesDefaults:{data:j}};
}b.fn.init.call(this,i,f.normalizeOptions(j));
},_createChart:function(i,j){this._instance=new f(this.element[0],i,j,{observer:new c(this),sender:this,rtl:this._isRtl()});
},_createTooltip:function(){return new h(this.element,e({},this.options.tooltip,{rtl:this._isRtl()}));
},options:{name:"Sparkline",chartArea:{margin:2},axisDefaults:{visible:false,majorGridLines:{visible:false},valueAxis:{narrowRange:true}},seriesDefaults:{type:"line",area:{line:{width:0.5}},bar:{stack:true},padding:2,width:0.5,overlay:{gradient:null},highlight:{visible:false},border:{width:0},markers:{size:2,visible:false}},tooltip:{visible:true,shared:true},categoryAxis:{crosshair:{visible:true,tooltip:{visible:false}}},legend:{visible:false},transitions:false,pointWidth:5,panes:[{clip:false}]}});
d.ui.plugin(g);
var h=d.Tooltip.extend({options:{animation:{duration:0}},_hideElement:function(){if(this.element){this.element.hide().remove();
}}});
d.SparklineTooltip=h;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.dataviz.sparkline",["dataviz/sparkline/kendo-sparkline","dataviz/sparkline/sparkline"],b);
}(function(){var a={id:"dataviz.sparkline",name:"Sparkline",category:"dataviz",description:"Sparkline widgets.",depends:["dataviz.chart"]};
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
