(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,p){var o=this._map;
var m={key:n,value:p};
o[n]=m;
if(!this._head){this._head=this._tail=m;
}else{this._tail.newer=m;
m.older=this._tail;
this._tail=m;
}if(this._length>=this._size){o[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(n){var m=this._map[n];
if(m){if(m===this._head&&m!==this._tail){this._head=m.newer;
this._head.older=null;
}if(m!==this._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=this._tail;
m.newer=null;
this._tail.newer=m;
this._tail=m;
}return m.value;
}}});
var i=/\r?\n|\r|\t/g;
var j=" ";
function g(m){return String(m).replace(i,j);
}function h(n){var o=[];
for(var m in n){o.push(m+n[m]);
}return o.sort().join("");
}function d(o){var m=2166136261;
for(var n=0;
n<o.length;
++n){m+=(m<<1)+(m<<4)+(m<<7)+(m<<8)+(m<<24);
m^=o.charCodeAt(n);
}return m>>>0;
}function l(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: pre!important;";
}var k=kendo.Class.extend({init:function(m){this._cache=new e(1000);
this.options=a.extend({},b,m);
},measure:function(v,t,r){if(r===void 0){r={};
}if(!v){return l();
}var u=h(t);
var o=d(v+u);
var n=this._cache.get(o);
if(n){return n;
}var s=l();
var q=r.box||c;
var m=this._baselineMarker().cloneNode(false);
for(var p in t){var x=t[p];
if(typeof x!=="undefined"){q.style[p]=x;
}}var w=r.normalizeText!==false?g(v):String(v);
q.textContent=w;
q.appendChild(m);
document.body.appendChild(q);
if(w.length){s.width=q.offsetWidth-this.options.baselineMarkerSize;
s.height=q.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(o,s);
}q.parentNode.removeChild(q);
return s;
},_baselineMarker:function(){var m=document.createElement("div");
m.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return m;
}});
k.current=new k();
function f(o,n,m){return k.current.measure(o,n,m);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:k,measureText:f,objectKey:h,hashKey:d,normalizeText:g});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("dataviz/stock/kendo-stock-chart",["kendo.dataviz.chart"],b);
}(function(){(function(){window.kendo.dataviz=window.kendo.dataviz||{};
var g=kendo.dataviz;
var k=g.elementStyles;
var i=g.deepExtend;
var r=g.toTime;
var h=g.constants;
var b=g.Chart;
var j=kendo.drawing;
var l=j.Animation.extend({setup:function(){this._initialOpacity=parseFloat(k(this.element,"opacity").opacity);
},step:function(t){k(this.element,{opacity:String(g.interpolateValue(this._initialOpacity,0,t))});
},abort:function(){j.Animation.fn.abort.call(this);
k(this.element,{display:"none",opacity:String(this._initialOpacity)});
},cancel:function(){j.Animation.fn.abort.call(this);
k(this.element,{opacity:String(this._initialOpacity)});
}});
function f(t,v){var u=document.createElement("div");
u.className=t;
if(v){u.style.cssText=v;
}return u;
}var p=g.Class.extend({init:function(u,t,v){this.options=i({},this.options,v);
this.container=u;
this.chartService=t;
var w=k(u,["paddingLeft","paddingTop"]);
this.chartPadding={top:w.paddingTop,left:w.paddingLeft};
this.createElements();
u.appendChild(this.element);
},createElements:function(){var t=this.element=f("k-navigator-hint","display: none; position: absolute; top: 1px; left: 1px;");
var v=this.tooltip=f("k-tooltip k-chart-tooltip");
var u=this.scroll=f("k-scroll");
v.innerHTML="&nbsp;";
t.appendChild(v);
t.appendChild(u);
},show:function(v,J,t){var D=this;
var u=D.element;
var A=D.options;
var F=D.scroll;
var K=D.tooltip;
var x=g.toDate(r(v)+r(J-v)/2);
var G=t.width()*0.4;
var y=t.center().x-G;
var w=t.center().x;
var B=w-y;
var C=A.max-A.min;
var E=B/C;
var z=x-A.min;
var I=this.chartService.intl.format(A.format,v,J);
var H=g.getTemplate(A);
this.clearHideTimeout();
if(!this._visible){k(u,{visibility:"hidden",display:"block"});
this._visible=true;
}if(H){I=H({from:v,to:J});
}K.innerHTML=I;
k(K,{left:t.center().x-K.offsetWidth/2,top:t.y1});
var L=k(K,["marginTop","borderTopWidth","height"]);
k(F,{width:G,left:y+z*E,top:t.y1+L.marginTop+L.borderTopWidth+L.height/2});
k(u,{visibility:"visible"});
},clearHideTimeout:function(){if(this._hideTimeout){clearTimeout(this._hideTimeout);
}if(this._hideAnimation){this._hideAnimation.cancel();
}},hide:function(){var t=this;
this.clearHideTimeout();
this._hideTimeout=setTimeout(function(){t._visible=false;
t._hideAnimation=new l(t.element);
t._hideAnimation.setup();
t._hideAnimation.play();
},this.options.hideDelay);
},destroy:function(){this.clearHideTimeout();
if(this.container){this.container.removeChild(this.element);
}delete this.container;
delete this.chartService;
delete this.element;
delete this.tooltip;
delete this.scroll;
}});
g.setDefaultOptions(p,{format:"{0:d} - {1:d}",hideDelay:500});
var o="_navigator";
var n=o;
var e={NAVIGATOR_AXIS:n,NAVIGATOR_PANE:o};
var s=3;
var m=g.Class.extend({init:function(t){this.chart=t;
var v=this.options=i({},this.options,t.options.navigator);
var w=v.select;
if(w){w.from=this.parseDate(w.from);
w.to=this.parseDate(w.to);
}if(!g.defined(v.hint.visible)){v.hint.visible=v.visible;
}var u;
this.chartObserver=new g.InstanceObserver(this,(u={},u[h.DRAG]="_drag",u[h.DRAG_END]="_dragEnd",u[h.ZOOM]="_zoom",u[h.ZOOM_END]="_zoomEnd",u));
t.addObserver(this.chartObserver);
},parseDate:function(t){return g.parseDate(this.chart.chartService.intl,t);
},clean:function(){if(this.selection){this.selection.destroy();
this.selection=null;
}if(this.hint){this.hint.destroy();
this.hint=null;
}},destroy:function(){if(this.chart){this.chart.removeObserver(this.chartObserver);
delete this.chart;
}this.clean();
},redraw:function(){this._redrawSelf();
this.initSelection();
},initSelection:function(){var B=this;
var v=B.chart;
var A=B.options;
var t=this.mainAxis();
var C=t.roundedRange();
var y=C.min;
var x=C.max;
var D=A.select;
var w=D.from;
var E=D.to;
var z=D.mousewheel;
var u=c(t);
if(t.categoriesCount()===0){return;
}this.clean();
u.box=t.box;
this.selection=new g.Selection(v,u,{min:y,max:x,from:w||y,to:E||x,mousewheel:g.valueOrDefault(z,{zoom:"left"}),visible:A.visible},new g.InstanceObserver(this,{selectStart:"_selectStart",select:"_select",selectEnd:"_selectEnd"}));
if(A.hint.visible){this.hint=new p(v.element,v.chartService,{min:y,max:x,template:g.getTemplate(A.hint),format:A.hint.format});
}},setRange:function(){var x=this.chart._createPlotArea(true);
var t=x.namedCategoryAxes[n];
var y=t.roundedRange();
var w=y.min;
var v=y.max;
var z=this.options.select||{};
var u=z.from||w;
if(u<w){u=w;
}var A=z.to||v;
if(A>v){A=v;
}this.options.select=i({},z,{from:u,to:A});
this.filterAxes();
},_redrawSelf:function(u){var t=this.chart._plotArea;
if(t){t.redraw(g.last(t.panes),u);
}},redrawSlaves:function(){var t=this.chart;
var u=t._plotArea;
var v=u.panes.slice(0,-1);
u.srcSeries=t.options.series;
u.options.categoryAxis=t.options.categoryAxis;
u.clearSeriesPointsCache();
u.redraw(v);
},_drag:function(x){var D=this;
var u=D.chart;
var F=D.selection;
var v=u._eventCoordinates(x.originalEvent);
var A=this.mainAxis();
var B=A.roundedRange();
var z=A.pane.box.containsPoint(v);
var t=u._plotArea.categoryAxis;
var C=x.axisRanges[t.options.name];
var E=this.options.select;
var w;
if(!C||z||!F){return;
}if(E.from&&E.to){w=r(E.to)-r(E.from);
}else{w=r(F.options.to)-r(F.options.from);
}var y=g.toDate(g.limitValue(r(C.min),B.min,r(B.max)-w));
var G=g.toDate(g.limitValue(r(y)+w,r(B.min)+w,B.max));
this.options.select={from:y,to:G};
if(this.options.liveDrag){this.filterAxes();
this.redrawSlaves();
}F.set(y,G);
this.showHint(y,G);
},_dragEnd:function(){this.filterAxes();
this.filter();
this.redrawSlaves();
if(this.hint){this.hint.hide();
}},readSelection:function(){var u=this;
var v=u.selection.options;
var t=v.from;
var x=v.to;
var w=u.options.select;
w.from=t;
w.to=x;
},filterAxes:function(){var y=this;
var z=y.options.select;
if(z===void 0){z={};
}var v=y.chart;
var t=v.options.categoryAxis;
var w=z.from;
var A=z.to;
for(var x=0;
x<t.length;
x++){var u=t[x];
if(u.pane!==o){u.min=w;
u.max=A;
}}},filter:function(){var x=this;
var v=x.chart;
var y=x.options.select;
if(!v.requiresHandlers(["navigatorFilter"])){return;
}var w=this.mainAxis();
var t={from:y.from,to:y.to};
if(w.options.type!=="category"){var u=new g.DateCategoryAxis(i({baseUnit:"fit"},v.options.categoryAxis[0],{categories:[y.from,y.to]}),v.chartService).options;
t.from=g.addDuration(u.min,-u.baseUnitStep,u.baseUnit);
t.to=g.addDuration(u.max,u.baseUnitStep,u.baseUnit);
}this.chart.trigger("navigatorFilter",t);
},_zoom:function(v){var z=this;
var t=z.chart._plotArea.categoryAxis;
var C=z.selection;
var A=z.options;
var B=A.select;
var x=A.liveDrag;
var y=this.mainAxis();
var u=v.delta;
if(!C){return;
}var w=y.categoryIndex(C.options.from);
var D=y.categoryIndex(C.options.to);
v.originalEvent.preventDefault();
if(Math.abs(u)>1){u*=s;
}if(D-w>1){C.expand(u);
this.readSelection();
}else{t.options.min=B.from;
B.from=t.scaleRange(-v.delta).min;
}if(x){this.filterAxes();
this.redrawSlaves();
}C.set(B.from,B.to);
this.showHint(this.options.select.from,this.options.select.to);
},_zoomEnd:function(t){this._dragEnd(t);
},showHint:function(t,v){var u=this.chart._plotArea;
if(this.hint){this.hint.show(t,v,u.backgroundBox());
}},_selectStart:function(t){return this.chart._selectStart(t);
},_select:function(t){this.showHint(t.from,t.to);
return this.chart._select(t);
},_selectEnd:function(t){if(this.hint){this.hint.hide();
}this.readSelection();
this.filterAxes();
this.filter();
this.redrawSlaves();
return this.chart._selectEnd(t);
},mainAxis:function(){var t=this.chart._plotArea;
if(t){return t.namedCategoryAxes[n];
}},select:function(t,v){var u=this.options.select;
if(t&&v){u.from=this.parseDate(t);
u.to=this.parseDate(v);
this.filterAxes();
this.filter();
this.redrawSlaves();
this.selection.set(t,v);
}return{from:u.from,to:u.to};
}});
m.setup=function(u,x){if(u===void 0){u={};
}if(x===void 0){x={};
}if(u.__navi){return;
}u.__navi=true;
var t=i({},x.navigator,u.navigator);
var w=u.panes=[].concat(u.panes);
var v=i({},t.pane,{name:o});
if(!t.visible){v.visible=false;
v.height=0.1;
}w.push(v);
m.attachAxes(u,t);
m.attachSeries(u,t,x);
};
m.attachAxes=function(y,x){var z=x.series||[];
var u=y.categoryAxis=[].concat(y.categoryAxis);
var B=y.valueAxis=[].concat(y.valueAxis);
var v=g.filterSeriesByType(z,h.EQUALLY_SPACED_SERIES);
var w=v.length===0;
var t=i({type:"date",pane:o,roundToBaseUnit:!w,justified:w,_collapse:false,majorTicks:{visible:true},tooltip:{visible:false},labels:{step:1},autoBind:x.autoBindElements,autoBaseUnitSteps:{minutes:[1],hours:[1,2],days:[1,2],weeks:[],months:[1],years:[1]}});
var A=x.categoryAxis;
u.push(i({},t,{maxDateGroups:200},A,{name:n,title:null,baseUnit:"fit",baseUnitStep:"auto",labels:{visible:false},majorTicks:{visible:false}}),i({},t,A,{name:n+"_labels",maxDateGroups:20,baseUnitStep:"auto",labels:{position:""},plotBands:[],autoBaseUnitSteps:{minutes:[]},_overlap:true}),i({},t,A,{name:n+"_ticks",maxDateGroups:200,majorTicks:{width:0.5},plotBands:[],title:null,labels:{visible:false,mirror:true},_overlap:true}));
B.push(i({name:n,pane:o,majorGridLines:{visible:false},visible:false},x.valueAxis));
};
m.attachSeries=function(x,w,A){var y=x.series=x.series||[];
var v=[].concat(w.series||[]);
var z=A.seriesColors;
var t=w.seriesDefaults;
for(var u=0;
u<v.length;
u++){y.push(i({color:z[u%z.length],categoryField:w.dateField,visibleInLegend:false,tooltip:{visible:false}},t,v[u],{axis:n,categoryAxis:n,autoBind:w.autoBindElements}));
}};
function d(){}function c(t){d.prototype=t;
return new d();
}var a=28;
var q=b.extend({applyDefaults:function(t,w){var x=g.elementSize(this.element).width||h.DEFAULT_WIDTH;
var v=w;
var u={seriesDefaults:{categoryField:t.dateField},axisDefaults:{categoryAxis:{name:"default",majorGridLines:{visible:false},labels:{step:2},majorTicks:{visible:false},maxDateGroups:Math.floor(x/a)}}};
if(v){v=i({},v,u);
}m.setup(t,v);
b.fn.applyDefaults.call(this,t,v);
},_setElementClass:function(t){g.addClass(t,"k-chart k-stockchart");
},setOptions:function(t){this.destroyNavigator();
b.fn.setOptions.call(this,t);
},noTransitionsRedraw:function(){var t=this.options.transitions;
this.options.transitions=false;
this._fullRedraw();
this.options.transitions=t;
},_resize:function(){this.noTransitionsRedraw();
},_redraw:function(){var t=this.navigator;
if(!this._dirty()&&t&&t.options.partialRedraw){t.redrawSlaves();
}else{this._fullRedraw();
}},_dirty:function(){var u=this.options;
var v=[].concat(u.series,u.navigator.series);
var w=g.grep(v,function(x){return x&&x.visible;
}).length;
var t=this._seriesCount!==w;
this._seriesCount=w;
return t;
},_fullRedraw:function(){var t=this.navigator;
if(!t){t=this.navigator=new m(this);
this.trigger("navigatorCreated",{navigator:t});
}t.clean();
t.setRange();
b.fn._redraw.call(this);
t.initSelection();
},_trackSharedTooltip:function(t){var v=this._plotArea;
var u=v.paneByPoint(t);
if(u&&u.options.name===o){this._unsetActivePoint();
}else{b.fn._trackSharedTooltip.call(this,t);
}},bindCategories:function(){b.fn.bindCategories.call(this);
this.copyNavigatorCategories();
},copyNavigatorCategories:function(){var w=[].concat(this.options.categoryAxis);
var v;
for(var u=0;
u<w.length;
u++){var t=w[u];
if(t.name===n){v=t.categories;
}else{if(v&&t.pane===o){t.categories=v;
}}}},destroyNavigator:function(){if(this.navigator){this.navigator.destroy();
this.navigator=null;
}},destroy:function(){this.destroyNavigator();
b.fn.destroy.call(this);
},_stopChartHandlers:function(u){var t=this._eventCoordinates(u);
var v=this._plotArea.paneByPoint(t);
return b.fn._stopChartHandlers.call(this,u)||v&&v.options.name===o;
}});
g.setDefaultOptions(q,{dateField:"date",axisDefaults:{categoryAxis:{type:"date",baseUnit:"fit",justified:true},valueAxis:{narrowRange:true,labels:{format:"C"}}},navigator:{select:{},seriesDefaults:{markers:{visible:false},tooltip:{visible:true},line:{width:2}},hint:{},visible:true},tooltip:{visible:true},legend:{visible:false}});
kendo.deepExtend(kendo.dataviz,{constants:e,Navigator:m,NavigatorHint:p,StockChart:q});
}());
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("dataviz/stock/stock-chart",["dataviz/stock/kendo-stock-chart"],b);
}(function(){(function(a){var j=window.kendo;
var g=j.dataviz;
var e=g.ChartInstanceObserver;
var d=g.ui.Chart;
var k=g.StockChart;
var f=g.constants;
var l=f.NAVIGATOR_AXIS;
var m=f.NAVIGATOR_PANE;
var h=j.deepExtend;
var i=g.defined;
var n=a.proxy;
var c="change";
var p=e.extend({handlerMap:{navigatorFilter:"_onNavigatorFilter",navigatorCreated:"_onNavigatorCreated"}});
var o=d.extend({options:{name:"StockChart",dateField:"date",axisDefaults:{categoryAxis:{type:"date",baseUnit:"fit",justified:true},valueAxis:{narrowRange:true,labels:{format:"C"}}},navigator:{select:{},seriesDefaults:{markers:{visible:false},tooltip:{visible:true,template:"#= kendo.toString(category, 'd') #"},line:{width:2}},hint:{},visible:true},tooltip:{visible:true},legend:{visible:false},persistSeriesVisibility:true},_createChart:function(q,r){this._initNavigatorOptions(q);
this._instance=new k(this.element[0],q,r,{observer:new p(this),sender:this,rtl:this._isRtl()});
},_initNavigatorOptions:function(t){var s=t.navigator||{};
var u=j.support;
var r=u.touch;
var q=u.browser.mozilla;
h(s,{autoBindElements:!s.dataSource,partialRedraw:s.dataSource,liveDrag:!r&&!q});
},_initDataSource:function(B){var y=B||{},q=y.dataSource,v=q&&q.serverFiltering,w=[].concat(y.categoryAxis)[0],x=y.navigator||{},z=x.select,u=z&&z.from&&z.to;
if(v&&u){var s=[].concat(q.filter||[]);
var t=j.parseDate(z.from);
var A=j.parseDate(z.to);
var r=new g.DateCategoryAxis(h({baseUnit:"fit"},w,{categories:[t,A]}),j);
q.filter=b(r.range().min,A).concat(s);
}d.fn._initDataSource.call(this,B);
},_onNavigatorCreated:function(q){this._instance=q.sender;
this.options=q.sender.options;
this._navigator=this.navigator=q.navigator;
this._initNavigatorDataSource();
},_initNavigatorDataSource:function(){var s=this.options.navigator;
var q=s.autoBind;
var r=s.dataSource;
if(r){this._navigatorDataChangedHandler=this._navigatorDataChangedHandler||n(this._onNavigatorDataChanged,this);
this._navigatorDataSource=j.data.DataSource.create(r).bind(c,this._navigatorDataChangedHandler);
if(!i(q)){q=this.options.autoBind;
}if(q){this._navigatorDataSource.fetch();
}}},_bindNavigatorSeries:function(s,r){var t,q,u=s.length;
for(t=0;
t<u;
t++){q=s[t];
if(q.axis==l&&this._isBindable(q)){q.data=r;
}}},_onNavigatorDataChanged:function(){var t=this,w=t._instance,s=t.options.categoryAxis,r,q=s.length,v=t._navigatorDataSource.view(),u,x;
this._bindNavigatorSeries(t.options.series,v);
if(t._sourceSeries){this._bindNavigatorSeries(t._sourceSeries,v);
}for(r=0;
r<q;
r++){u=s[r];
if(u.pane==m){if(u.name==l){t._bindCategoryAxis(u,v,r);
x=u.categories;
}else{u.categories=x;
}}}if(w._model){var y=this.navigator;
y.redraw();
y.setRange();
if(!t.options.dataSource||t.options.dataSource&&t._dataBound){y.redrawSlaves();
}}},_bindCategories:function(){d.fn._bindCategories.call(this);
if(this._instance){this._instance.copyNavigatorCategories();
}},_onDataChanged:function(){d.fn._onDataChanged.call(this);
this._dataBound=true;
},setOptions:function(q){this._removeNavigatorDataSource();
this._initNavigatorOptions(q);
this._instance.destroyNavigator();
d.fn.setOptions.call(this,q);
},_onNavigatorFilter:function(q){this.dataSource.filter(b(q.from,q.to));
},requiresHandlers:function(s){if(g.inArray("navigatorFilter",s)){var q=this.dataSource;
var r=q&&q.options.serverFiltering;
return r&&this.options.navigator.dataSource;
}return d.fn.requiresHandlers.call(this,s);
},_removeNavigatorDataSource:function(){var q=this._navigatorDataSource;
if(q){q.unbind(c,this._navigatorDataChangedHandler);
delete this._navigatorDataSource;
}},destroy:function(){d.fn.destroy.call(this);
this._removeNavigatorDataSource();
}});
g.ui.plugin(o);
function b(q,r){return[{field:"Date",operator:"gte",value:q},{field:"Date",operator:"lt",value:r}];
}}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.dataviz.stock",["dataviz/stock/kendo-stock-chart","dataviz/stock/stock-chart"],b);
}(function(){var a={id:"dataviz.stockchart",name:"StockChart",category:"dataviz",description:"StockChart widget and associated financial series.",depends:["dataviz.chart"]};
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
