(function(a,b,n){var e=a.extend;
var d=a.each;
var g=window.kendo;
var f="initialize";
var h="load";
var m="typingStart";
var l="typingEnd";
var i="post";
var j="sendMessage";
var c="actionClick";
var k="toolClick";
b.RadChat=function(o){var p=this;
b.RadChat.initializeBase(p,[o]);
p._options={};
p.kendoWidget=null;
};
b.RadChat.prototype={initialize:function(){var o=this;
o.raiseEvent(f);
o._initializeKendoWidget();
o.raiseEvent(h);
},dispose:function(){var o=this;
if(o.kendoWidget){o.kendoWidget.destroy();
}delete o.kendoWidget;
delete o._options;
b.RadChat.callBaseMethod(o,"dispose");
},postMessage:function(o){this.kendoWidget.postMessage(o);
},renderMessage:function(o,p){this.kendoWidget.renderMessage(o,p);
},renderSuggestedActions:function(o){this.kendoWidget.renderSuggestedActions(o);
},renderAttachments:function(o,p){this.kendoWidget.renderAttachments(o,p);
},renderUserTypingIndicator:function(o){this.kendoWidget.renderUserTypingIndicator(o);
},clearUserTypingIndicator:function(o){this.kendoWidget.clearUserTypingIndicator(o);
},removeTypingIndicator:function(){this.kendoWidget.removeTypingIndicator();
},get_kendoWidget:function(){return this.kendoWidget;
},_initializeKendoWidget:function(){var o=this;
o.kendoWidget=a(o._element).kendoChat($telerik.$.extend({},o._options,{typingStart:function(p){a.raiseControlEvent(o,"typingStart",p);
},typingEnd:function(p){a.raiseControlEvent(o,"typingEnd",p);
},post:function(p){a.raiseControlEvent(o,"post",p);
},sendMessage:function(p){a.raiseControlEvent(o,"sendMessage",p);
},actionClick:function(p){a.raiseControlEvent(o,"actionClick",p);
},toolClick:function(p){a.raiseControlEvent(o,"toolClick",p);
}})).getKendoChat();
}};
b.RadChat.registerClass("Telerik.Web.UI.RadChat",b.RadWebControl);
b.RadChat._getWidgetOptions=function(){var p=e(true,{},g.ui.Chat.fn.options);
var o=["name","prefix"];
d(o,function(q,r){delete p[r];
});
return p;
};
b.RadChat._registerControlProperties=function(o){d(o,function(q,p){b.RadChat.prototype["get_"+q]=function(){return this.kendoWidget?this.kendoWidget.options[q]:n;
};
b.RadChat.prototype["set_"+q]=function(s){var t=this.kendoWidget;
var r={};
r[q]=s;
if(t){t.setOptions(e(true,{},t.options,r));
}};
});
};
b.RadChat._extendStyles=function(){g.ui.Chat.styles={wrapper:"t-widget t-chat",canvas:"t-chat-canvas",viewWrapper:"t-message-list",messageBoxWrapper:"t-message-box",toolbarBoxWrapper:"t-toolbar-box"};
g.chat.ChatMessageBox.styles={input:"t-input",button:"t-button",buttonFlat:"t-flat",buttonIcon:"t-button-icon",buttonSend:"t-button-send",buttonToggle:"t-button-toggle",iconAdd:"t-icon t-i-add",hidden:"t-hidden"};
g.chat.ChatView.styles={wrapper:"t-widget t-chat",messageList:"t-avatars",messageListContent:"t-message-list-content",messageTime:"t-message-time",messageGroup:"t-message-group",message:"t-message",only:"t-only",first:"t-first",middle:"t-middle",last:"t-last",author:"t-author",avatar:"t-avatar",noAvatar:"t-no-avatar",self:"t-alt",button:"t-button",iconButton:"t-button-icon",buttonPrimary:"t-flat t-primary",scrollButtonIcon:"t-icon",scrollButtonIconLeft:"t-i-arrow-chevron-left",scrollButtonIconRight:"t-i-arrow-chevron-right",typingIndicator:"t-typing-indicator",typingIndicatorBubble:"k-typing-indicator-bubble",bubble:"t-bubble",suggestedActions:"t-quick-replies",suggestedAction:"t-quick-reply",cardWrapper:"t-card-container",cardDeckScrollWrap:"t-card-deck-scrollwrap",cardDeck:"t-card-deck",cardList:"t-card-list",card:"t-card",cardRich:"t-card-type-rich",cardBody:"t-card-body",cardImage:"t-card-image",cardTitle:"t-card-title",cardSubtitle:"t-card-subtitle",cardActions:"t-card-actions",cardActionsVertical:"t-card-actions-vertical",cardAction:"t-card-action",selected:"t-state-selected"};
g.chat.ChatToolBar.styles={button:"t-button",buttonFlat:"t-flat",buttonList:"t-button-list",scrollButton:"t-scroll-button",scrollButtonLeft:"t-scroll-button-left",scrollButtonRight:"t-scroll-button-right",scrollButtonLeftIcon:"t-icon t-i-arrow-chevron-left",scrollButtonRightIcon:"t-icon t-i-arrow-chevron-right",buttonIcon:"t-button-icon"};
};
a.registerControlEvents(b.RadChat,[f,h,m,l,i,j,c,k]);
a.registerControlProperties(b.RadChat,{skin:""});
b.RadChat._registerControlProperties(b.RadChat._getWidgetOptions());
b.RadChat._extendStyles();
})($telerik.$,Telerik.Web.UI);
