(function(a){var k=window.kendo;
var p=k.ui;
var f=a.extend;
var b=Telerik.Web.UI;
var c={wrapper:"RadSpreadsheet"};
f(true,p.Spreadsheet,{classNames:c});
var d={wrapper:"k-spreadsheet-filter-menu"};
f(true,k.spreadsheet.FilterMenu,{classNames:d});
var h={wrapper:"rssFormulaBar"};
a.extend(true,k.spreadsheet.FormulaBar,{classNames:h});
var g={wrapper:"rssFormulaInput",listWrapper:"rssFormulaList"};
a.extend(true,k.spreadsheet.FormulaInput,{classNames:g});
var o={sheetsBarWrapper:"k-widget k-header",sheetsBarSheetsWrapper:"t-tabstrip t-tabstrip-bottom",sheetsBarActive:"t-spreadsheet-sheets-bar-active",sheetsBarInactive:"t-spreadsheet-sheets-bar-inactive",sheetsBarAdd:"t-spreadsheet-sheets-bar-add",sheetsBarRemove:"t-spreadsheet-sheets-remove",sheetsBarItems:"t-spreadsheet-sheets-items",sheetsBarEditor:"t-spreadsheet-sheets-editor",sheetsBarScrollable:"k-spreadsheet-sheets-scrollable",sheetsBarNext:"t-spreadsheet-sheets-next",sheetsBarPrev:"t-spreadsheet-sheets-prev",sheetsBarKItem:"t-item t-state-default",sheetsBarKActive:"t-state-active k-state-tab-on-top",sheetsBarKTextbox:"t-textbox",sheetsBarKLink:"t-link",sheetsBarKIcon:"t-icon",sheetsBarKFontIcon:"t-font-icon",sheetsBarKButton:"t-button t-button-icon",sheetsBarKButtonBare:"t-button-bare",sheetsBarKArrowW:"t-i-arrow-w",sheetsBarKArrowE:"t-i-arrow-e",sheetsBarKReset:"t-reset t-tabstrip-items",sheetsBarKIconX:"t-i-x",sheetsBarKSprite:"t-sprite",sheetsBarKIconPlus:"t-i-plus",sheetsBarHintWrapper:"k-widget t-tabstrip t-tabstrip-bottom t-spreadsheet-sheets-items-hint",sheetsBarKResetItems:"t-reset t-tabstrip-items",sheetsBarHovered:"t-state-hover",sheetsBarKItemBase:"t-item"};
a.extend(true,k.spreadsheet.SheetsBar,{classNames:o});
var q={view:"rssView",fixedContainer:"rssFixedContainer",scroller:"rssScroller",viewSize:"rssViewSize",clipboard:"k-spreadsheet-clipboard",cellEditor:"rssCellEditor",barEditor:"k-spreadsheet-editor",topCorner:"rssTopCorner",filterHeadersWrapper:"k-filter-headers",filterButton:"k-spreadsheet-filter",icon:"k-icon k-font-icon",iconFilterDefault:"k-i-arrow-s",sheetsBar:"rssSheetsbar",sheetsBarActive:"k-spreadsheet-sheets-bar-active",sheetsBarInactive:"k-spreadsheet-sheets-bar-inactive",cellContextMenu:"k-spreadsheet-cell-context-menu",rowHeaderContextMenu:"k-spreadsheet-row-header-context-menu",colHeaderContextMenu:"k-spreadsheet-col-header-context-menu"};
a.extend(true,k.spreadsheet.View,{classNames:q});
var n={rowHeader:"rssRowHeader",columnHeader:"rssColumnHeader",pane:"rssPane",data:"rssData",mergedCell:"rssMergedCell",mergedCellsWrapper:"rssMergedCellsWrapper",activeCell:"rssActiveCell",selection:"rssSelection",selectionWrapper:"rssSelectionWrapper",single:"k-single",top:"k-top",right:"k-right",bottom:"k-bottom",left:"k-left",resizeHandle:"k-resize-handle",resizeHint:"k-resize-hint",resizeHintHandle:"k-resize-hint-handle",resizeHintMarker:"k-resize-hint-marker",resizeHintVertical:"k-resize-hint-vertical",selectionHighlight:"k-spreadsheet-selection-highlight",series:["k-series-a","k-series-b","k-series-c","k-series-d","k-series-e","k-series-f"]};
a.extend(true,k.spreadsheet.Pane,{classNames:n});
function i(){return b.MaterialRippleManager.getInstance();
}function j(t,r){var s=i();
var u;
if(s){u=s._rippleDelegatedZones;
if(u.indexOf(t.element.get(0))!==-1&&u.indexOf(r)===-1){s.initializeRippleZone({element:r,rippleConfigurations:[{containerSelector:".rssButton, .rssLink"},{containerSelector:".rssIconExpand, .rssIconCollapse, .rssIconClose",rippleType:b.MaterialRippleType.Icon,maxRippleSize:60,cancelBubble:true}]});
}}}var l=k.spreadsheet.Controller.fn.objectAt;
k.spreadsheet.Controller.fn.objectAt=function(r){if(!this.container[0].parentElement){return this.view.objectAt(r.clientX,r.clientY);
}return l.call(this,r);
};
var e=k.spreadsheet.View.fn.createFilterMenu;
k.spreadsheet.View.fn.createFilterMenu=function(r){var s=e.call(this,r);
j(this,this._filterMenu._dropDown._element);
return s;
};
var m=k.spreadsheet.View.fn.openDialog;
k.spreadsheet.View.fn.openDialog=function(s,t){var r=m.call(this,s,t);
j(this,this._dialogs[0]._dialog._wrapper);
return r;
};
k.spreadsheet.NameEditor=k.ui.Widget.extend({init:function(r,s){k.ui.Widget.call(this,r,s);
r.remove();
},value:function(){}});
k.spreadsheet.registerEditor("_validation_date",function(){var s,r,u=true;
function t(){var w=a("[id$='SpreadsheetCalendarDropDown']");
var y=w.closest(".rssPopup");
r=$find(w.attr("id"));
if(!this._calendardropdown){var x=new k.spreadsheet.DropDown(y);
this._calendardropdown=x;
x._additionalSelector=".RadCalendarFastNavPopup";
r.add_dateSelected(function(A,z){if(u){x.close();
var B=A.get_selectedDates()[0];
if(B){if(!s.range.format()){s.range.format("yyyy-mm-dd");
}s.callback(k.spreadsheet.dateToNumber(new Date(B[0],B[1]-1,B[2])));
}}});
}this._calendardropdown.openFor(s.view.element.find(".k-spreadsheet-editor-button"));
}function v(){t();
var y=s.range.value();
if(y!=null){var w=k.spreadsheet.numberToDate(y);
if(w instanceof Date){var x=[w.getFullYear(),w.getMonth()+1,w.getDate()];
u=false;
var z=r.get_selectedDates();
r.unselectDates(z);
r.selectDate(x,true);
u=true;
}}var E=s.validation;
if(E){var C=null,A=null;
if(/^(?:greaterThan|between)/.test(E.comparerType)){C=k.spreadsheet.numberToDate(E.from.value);
}if(E.comparerType=="between"){A=k.spreadsheet.numberToDate(E.to.value);
}if(E.comparerType=="lessThan"){A=k.spreadsheet.numberToDate(E.from.value);
}if(C instanceof Date){var D=[C.getFullYear(),C.getMonth()+1,C.getDate()];
r.set_rangeMinDate(D);
}if(A instanceof Date){var B=[A.getFullYear(),A.getMonth()+1,A.getDate()];
r.set_rangeMaxDate(B);
}}}return{edit:function(w){s=w;
v();
},icon:"p-icon p-i-calendar"};
});
k.spreadsheet.registerEditor("_validation_list",function(){var r,t;
function s(){var v=a("[id$='SpreadsheetListBoxDropDown']");
var x=v.closest(".rssPopup");
t=$find(v.attr("id"));
if(!this._listdropdown){var w=new k.spreadsheet.DropDown(x);
this._listdropdown=w;
t.add_selectedIndexChanged(function(A,y){w.close();
var z=t.get_selectedItem();
if(z){r.callback(z.get_value());
}});
}this._listdropdown.openFor(r.view.element.find(".k-spreadsheet-editor-button"));
}function u(){s();
var w=r.validation.from.value;
if(w){var v=t.get_items();
v.clear();
w.each(function(x){var y=new Telerik.Web.UI.RadListBoxItem();
y.set_text(x);
v.add(y);
});
}}return{edit:function(v){r=v;
u();
},icon:"p-icon p-i-arrow-60-down"};
});
})($telerik.$);
(function(a,f){var d=12;
var c="Arial";
var b=Telerik.Web.UI;
kendo.spreadsheet.TabStrip=kendo.Observable.extend({init:function(g,h){this.element=g;
kendo.Observable.fn.init.call(this);
var i=g.parents(".RadSpreadsheet").find("[id$='SpreadsheetToolbarWrapper']");
a(g).append(i);
this._tabStrip=$find(i.children()[0].id);
this._initToolBars();
},select:function(){},quickAccessAdjust:function(){},refreshTools:function(j){var k=this.toolBars;
for(var h=0,g=k.length;
h<g;
h++){k[h].refreshTools(j);
}},destroy:function(){var j=this.toolBars;
for(var h=0,g=j.length;
h<g;
h++){j[h].destroy();
}this.element=null;
this._tabStrip=null;
this._toolBars=null;
},_initToolBars:function(){var k=this._tabStrip.get_tabs();
var n=this.toolBars=[];
var j;
var l;
var m;
for(var h=0,g=k.get_count();
h<g;
h++){j=k.getTab(h).get_pageView();
m=a(j.get_element()).find(".RadToolBar");
l=new e(m);
l.bind("action",a.proxy(this._triggerAction,this));
l.bind("dialog",a.proxy(this._triggerDialog,this));
l.bind("toolBarCommand",a.proxy(this._triggerCommand,this));
n.push(l);
}},_triggerAction:function(g){this.trigger("action",g);
},_triggerDialog:function(g){if(g.name=="insertComment"||g.name=="insertImage"||g.name=="exportAsDialog"){delete g.options.wrapper;
}if(g.name=="exportAsDialog"){g.name="exportAs";
}this.trigger("dialog",g);
},_triggerCommand:function(g){this.trigger("toolBarCommand",g);
}});
var e=kendo.Observable.extend({init:function(h){this.element=h;
kendo.Observable.fn.init.call(this);
this._borderType="allBorders";
this._borderColor="#000";
this._borderSize=1;
var n=this._toolbar=$find(h.attr("id"));
n._shouldUpdateClientState=false;
n.add_buttonClicked(a.proxy(this._onButtonClicked,this));
var l=n.get_items();
for(var j=0,m=l.get_count();
j<m;
j++){var k=l.getItem(j);
if(a(k.get_element()).hasClass("rtbTemplate")){var g=k.findControl(k.get_commandArgument());
if(b.RadComboBox&&g instanceof b.RadComboBox){g.add_selectedIndexChanged(a.proxy(this._onComboBoxSelectedIndexChanged,this));
}else{if(b.RadDropDownList&&g instanceof b.RadDropDownList){g.add_selectedIndexChanged(a.proxy(this._onDropDownListSelectedIndexChanged,this));
}else{if(b.RadColorPicker&&g instanceof b.RadColorPicker){g.add_colorChange(a.proxy(this._onColorPickerColorChanged,this));
}}}}else{if(k.get_attributes().getAttribute("gallery")==="true"){a(k.get_dropDownElement()).addClass("rssGallery");
}}if(k.get_value()=="open"){this.initializeOpenItem(k);
}}},initializeOpenItem:function(j){var g=a(j.get_linkElement());
var k=this;
i();
function i(){g.find("input").remove();
a("<input type='file' autocomplete='off' accept='.xlsx'/>").attr("title",j.get_toolTip()).attr("aria-label",j.get_toolTip()).one("change",h).appendTo(g);
}function h(l){k.trigger("action",{command:"OpenCommand",options:{file:l.target.files[0]}});
i();
}},refreshTools:function(m){var j=this._toolbar.get_items();
for(var g=0,k=j.get_count();
g<k;
g++){var h=j.getItem(g);
if(h instanceof b.RadToolBarDropDown){if(h.get_attributes().getAttribute("toggle")==="true"){this._setDropDownButtonValue(h,m);
}continue;
}if(h.get_isSeparator&&h.get_isSeparator()){continue;
}var l=h.get_commandArgument();
var n;
if(!l){continue;
}if(l=="gridLines"){n=m.sheet().showGridLines();
}else{if(l=="insertComment"){l="comment";
n=!!(kendo.isFunction(m[l])?m[l]():m);
}else{n=kendo.isFunction(m[l])?m[l]():m;
}}this._suppressEvents=true;
this._setItemValue(h,n);
this._suppressEvents=false;
}},destroy:function(){this.element=null;
this._toolbar=null;
},_setItemValue:function(h,k){function j(l,m){if(m===null||m===true||m===false){l.set_checked(m);
return;
}l.set_checked(l.get_value()===m);
}if(a(h.get_element()).hasClass("rtbTemplate")){var g=h.findControl(h.get_commandArgument());
if(b.RadComboBox&&g instanceof b.RadComboBox){g.set_text(""+(kendo.parseInt(k)||d));
}else{if(b.RadDropDownList&&g instanceof b.RadDropDownList){var i=g.findItemByText(k);
if(i){i.select();
}else{g.findItemByText(c).select();
}}else{if(b.RadColorPicker&&g instanceof b.RadColorPicker){g.set_selectedColor(k);
}}}}else{j(h,k);
}},_setDropDownButtonValue:function(k,n){var h=k.get_buttons();
var g;
for(var j=0,l=h.get_count();
j<l;
j++){g=h.getButton(j);
var m=g.get_commandArgument();
if(!m){continue;
}var o=kendo.isFunction(n[m])?n[m]():n;
a(g.get_element()).toggleClass("rtbSelected",g.get_value()===o);
}},_onButtonClicked:function(i,g){var h=g.get_item();
var j=h.get_value();
if(j==="true"||j==="false"){j=h.get_checked()?true:null;
}this._triggerAction(h,j);
},_onComboBoxSelectedIndexChanged:function(i,g){var h=this._toolbar._extractItemFromDomElement(i.get_element());
var j=kendo.parseInt(i.get_selectedItem().get_text());
this._triggerAction(h,j);
},_onDropDownListSelectedIndexChanged:function(i,g){if(this._suppressEvents){return;
}var h=this._toolbar._extractItemFromDomElement(i.get_element());
var j=i.get_selectedItem().get_text();
this._triggerAction(h,j);
},_onColorPickerColorChanged:function(i,g){if(this._suppressEvents){return;
}var h=this._toolbar._extractItemFromDomElement(i.get_element());
var j=i.get_selectedColor();
this._triggerAction(h,j);
},_triggerAction:function(j,k){var i=j.get_commandName();
var h=j.get_commandArgument();
if(!i){return;
}if(i==="AdjustDecimalsCommand"){k=parseInt(k,10);
}if(i==="DialogCommand"){this.trigger("dialog",{name:h,options:{wrapper:this.element.parents(".RadSpreadsheet")}});
return;
}if(i==="ToolBarCommand"){this.trigger("toolBarCommand",{value:k});
return;
}if(i==="Action"){this.trigger("action",{action:k});
return;
}var g={command:i,options:{property:h||null,value:k||null}};
if(i==="SortCommand"){g.options.sheet=false;
}if(i==="BorderChangeCommand"){if(h=="borderColor"){this._borderColor=k;
}else{this._borderType=k;
}g.options={border:this._borderType,style:{color:this._borderColor,size:this._borderSize}};
}this.trigger("action",g);
}});
})($telerik.$);
(function(a,c){var b={CommandCut:"cut",CommandCopy:"copy",CommandPaste:"paste",CommandHideRow:"hide-row",CommandUnhideRow:"unhide-row",CommandHideColumn:"hide-column",CommandUnhideColumn:"unhide-column",CommandDeleteRow:"delete-row",CommandDeleteColumn:"delete-column"};
kendo.spreadsheet.ContextMenu=kendo.Observable.extend({init:function(d,e){this.element=d;
d.hide();
kendo.Observable.fn.init.call(this);
},destroy:function(){this.element.remove();
this.element=null;
if(this._menu){this._menu.dispose();
this._menu=null;
}},open:function(d,e){if(this._menu){this._menu.showAt(d,e);
}},close:function(){if(this._menu){this._menu.hide();
}},_initContextMenu:function(d){if(!d){return;
}var e=this._menu=$find(a("[id$='"+d+"']").attr("id"));
if(e){e.add_itemClicked(a.proxy(this._onItemClick,this));
}},_onItemClick:function(i,g){var h=g.get_item();
var f=h.get_element();
var d=b[h.get_value()];
a(f).data("action",d);
var e={item:f};
this.trigger("select",e);
}});
})($telerik.$);
(function(a,h){Type.registerNamespace("Telerik.Web.UI.Spreadsheet");
var d=Telerik.Web.UI;
var f=".spreadsheetDropDown";
var g="mousedown";
var b=a.extend;
var c=a.proxy;
function e(i,j){return i===j||a.contains(i,j);
}kendo.spreadsheet.DropDown=kendo.Observable.extend({init:function(i,j){kendo.Observable.fn.init.call(this);
if(!this.element){this.element=i;
}this.options=b(true,{},j);
this.container=i.parent();
this.animationContainer=this.element.parents(".rssSlide")[0];
this._initDropDown(this.animationContainer);
},destroy:function(){this.close();
this.container.append(this.animationContainer);
this.animationContainer=this.element=this.container=null;
a(this._dropDown._animationContainer).attr("style","display: none;");
this._dropDown._animationContainer=null;
this._dropDown.dispose();
this._dropDown=null;
this.options={};
},openFor:function(i){this._dropDown.set_anchor(i);
this._dropDown.show();
a(document.documentElement).on(g+f,c(this._mousedown,this));
},close:function(){if(this._dropDown){this._dropDown.hide();
}a(document.documentElement).off(f);
},clear:function(){this.close();
},_initDropDown:function(i){var j=this._dropDown=new d.DropDown(i,{direction:2,enableScreenBoundaryDetection:false,enableDirectionDetection:false});
j.initialize();
j.updateSize();
},_mousedown:function(l){var m=l.target;
var k=this._dropDown._element;
var j=this._dropDown.get_anchor();
var i=this._additionalSelector;
if(!e(k,m)&&!e(j,m)&&!a(m).closest(".k-spreadsheet-editor-button").length&&!a(m).closest(i).length){this.close();
}}});
})($telerik.$);
(function(a,k){Type.registerNamespace("Telerik.Web.UI.Spreadsheet");
var d=Telerik.Web.UI;
var l=".spreadsheetFilterMenuView";
var i="mouseenter";
var j="mouseleave";
var e="click";
var h="input";
var g=kendo.spreadsheet.FilterMenuController;
var b=a.extend;
var c=a.proxy;
function f(m,n){return m===n||a.contains(m,n);
}kendo.spreadsheet.FilterMenu=kendo.spreadsheet.DropDown.extend({init:function(m,n){this.element=m.parent().find(".rssFilterMenu");
kendo.spreadsheet.DropDown.fn.init.call(this,m,n);
this._initView();
this._initFilter();
},destroy:function(){kendo.spreadsheet.DropDown.fn.destroy.call(this);
this._view.destroy();
this._view=null;
},_initView:function(){var m=g.valuesTree(this.options.range,this.options.column);
this._view=new d.Spreadsheet.FilterMenuView(this.element);
this._view.init();
this._view.on({action:this._viewAction},this);
this._view.populateValueListBox(m[0].items);
},_initFilter:function(){var n=this.options;
var m=g.filter(n.column,n.range.sheet());
if(m){this._view.setFilter(m);
}else{this._view.reset();
}},_viewAction:function(m){var n=this.options.range;
if(m.command==="SortCommand"){n=n.resize({top:1});
if(!n.isSortable()){this.close();
return;
}}else{if(m.command==="ApplyFilterCommand"&&!m.options.valueFilter&&!m.options.customFilter){return;
}}b(m.options,{sheet:false,operatingRange:n,column:this.options.column});
this.trigger("action",b({},m));
},_mousedown:function(o){var p=o.target;
var n=this._dropDown._element;
var m=this._dropDown.get_anchor();
if(!f(n,p)&&!f(m,p)&&!a(p).parents(".RadCalendar").length){this.close();
}}});
d.Spreadsheet.FilterMenuView=function(m,n){a.observable(this);
this.options=b({},n);
this.element=m;
this._animationType=d.AnimationType.toEasing(1);
this._animationDuration=200;
};
d.Spreadsheet.FilterMenuView.prototype={init:function(){this.initControls();
this.initEvents();
this.initPanelBar();
this.initSort();
this.initFilterByCondition();
this.initFilterByValue();
this.initButtons();
},destroy:function(){this.element.find(".rssHovered").removeClass("rssHovered");
this.element.off(l);
this.element=null;
this.controls.conditionDropDownList.get_events()._list={};
this.controls.valueListBox.get_events()._list={};
this.controls={};
},action:function(m){this.trigger("action",b({},m));
},initControls:function(){var m=this.controls={};
var n=function(o){return $find(a("[id$='"+o+"']").attr("id"));
};
m.conditionDropDownList=n("_ConditionDropDownList");
m.conditionTextBox=n("_ConditionTextBox");
m.conditionNumericTextBox=n("_ConditionNumericTextBox");
m.conditionDatePicker=n("_ConditionDatePicker");
m.valueListBox=n("_ValueListBox");
},initEvents:function(){var m=function(n,o){a(n).toggleClass("rssHovered",o);
};
a(this.element).on(i+l,".rssLI, .rssButtons .rssButton",function(n){m(this,true);
}).on(j+l,".rssLI, .rssButtons .rssButton",function(n){m(this,false);
});
},initPanelBar:function(){var m=this;
a(this.element).on(e+l,".rssCollapsibleList .rssLI.rssCollapsed",function(n){m._selectPanel(a(this).attr("data-value"),true);
});
},initSort:function(){var m=this;
a(this.element).on(e+l,".rssMenu .rssLink",function(n){var o={value:a(this).attr("data-command")};
m.action({command:"SortCommand",options:o});
});
},initFilterByCondition:function(){this.controls.conditionDropDownList.add_selectedIndexChanged(c(this._onConditionCategoryChange,this));
},initFilterByValue:function(){this.controls.valueListBox.add_selectedIndexChanging(c(this._onValueSelectionChange,this));
this.initSearchBoxFilter();
},initButtons:function(){var m=this;
a(this.element).on(e+l,".rssButtons .rssButton",function(p){p.preventDefault();
var n=a(this).attr("data-command");
var o="";
var q={};
if(n==="apply"){o="ApplyFilterCommand";
q=m.getFilter();
}else{o="ClearFilterCommand";
}m.action({command:o,options:q});
});
},initSearchBoxFilter:function(){var m=this;
a(this.element).find("#ValueSearchBox .rssFakeInput").val("");
a(this.element).on(h+l,"#ValueSearchBox .rssFakeInput",function(n){m.filterValueListBox(this.value);
});
},populateValueListBox:function(n){var o=this.controls.valueListBox;
var q=o.get_items();
q.clear();
for(var m=0;
m<n.length;
m++){var p=new d.RadListBoxItem();
p.set_text(n[m].text.toString());
p.set_value(n[m].value);
p.set_checked(n[m].checked);
q.add(p);
}},filterValueListBox:function(t){var s=this.controls.valueListBox;
var r=s.get_items();
var m=r.get_count();
var q;
var p;
var n=false;
for(var o=0;
o<m;
o++){q=r.getItem(o);
p=q.get_text().indexOf(t)>-1;
q.set_visible(p);
n=n||p;
}a(s.get_element()).find(".rlbCheckAllItems").toggle(n);
},getFilter:function(){var m=a(this.element).find(".rssCollapsibleList .rssLI.rssExpanded").attr("data-value");
var n={};
if(m==="customFilter"){n.customFilter=this.getCustomFilter();
}else{n.valueFilter=this.getValueFilter();
}return n;
},getCustomFilter:function(){var m=this.controls;
var n=m.conditionDropDownList;
var o=n.get_selectedItem();
var p=o.get_value();
var r=o.get_attributes().getAttribute("category");
var s;
var q={criteria:[],logic:"and"};
switch(r){case"string":s=m.conditionTextBox.get_value();
break;
case"number":s=m.conditionNumericTextBox.get_value();
break;
case"date":s=m.conditionDatePicker.get_selectedDate();
break;
default:return;
}q.criteria.push({operator:p,type:r,value:s});
return q;
},getValueFilter:function(){var o=this.controls.valueListBox;
var n=o.get_checkedItems();
var r=n.filter(function(s){return s.get_visible();
});
var q=a.map(r,function(s){return s.get_value();
});
var m=q.filter(function(s){return s==="(Blanks)";
});
q=q.filter(function(s){return s!=="(Blanks)";
});
m=m.length>0;
var p={blanks:m,values:q};
return p;
},setFilter:function(m){var n=m.type+"Filter";
this._selectPanel(n,false);
if(m.type=="custom"){this.setCustomFilter(m.options);
}},setCustomFilter:function(o){var m=this.controls;
var n=o.criteria[0];
this._setConditionCategory(n.type,n.operator);
this._resetConditionControls();
switch(n.type){case"string":m.conditionTextBox.set_value(n.value);
break;
case"number":m.conditionNumericTextBox.set_value(n.value);
break;
case"date":m.conditionDatePicker.set_selectedDate(n.value);
break;
}},reset:function(){this._selectPanel("valueFilter",false);
this._setConditionCategory("","");
this._resetConditionControls();
},_resetConditionControls:function(){var m=this.controls;
m.conditionTextBox.set_value("");
m.conditionNumericTextBox.set_value("");
m.conditionDatePicker.set_selectedDate("");
},_setConditionCategory:function(m,t){var o=this.controls.conditionDropDownList;
var s=o.get_items();
var n=s.get_count();
var q=0;
var r;
for(var p=0;
p<n;
p++){r=s.getItem(p);
if(r.get_value()===t&&r.get_attributes().getAttribute("category")===m){q=r.get_index();
break;
}}o.getItem(q).select();
this._onConditionCategoryChange();
},_onConditionCategoryChange:function(){var n=this.controls;
var p=n.conditionDropDownList.get_selectedItem();
var m=p.get_attributes().getAttribute("category");
var o;
a(this.element).find(".rssFormListOption").hide();
switch(m){case"string":o=n.conditionTextBox;
break;
case"number":o=n.conditionNumericTextBox;
break;
case"date":o=n.conditionDatePicker;
break;
}if(o){a(o.get_element()).parents(".rssFormListOption").show();
}},_onValueSelectionChange:function(n,m){m.set_cancel(true);
m.get_item().set_checked(!m.get_item().get_checked());
},_selectPanel:function(p,m){var q=this;
var o=a(this.element).find(".rssCollapsibleList .rssLI");
var s=o.filter("[data-value='valueFilter']");
var n=o.filter("[data-value='customFilter']");
var r=function(u,v,t){a(u).toggleClass("rssExpanded",v).toggleClass("rssCollapsed",!v).find(".rssSummary > .rssIcon").toggleClass("rssIconCollapse",v).toggleClass("rssIconExpand",!v);
q._toggleElement(a(u).find(".rssDetails"),v,t);
};
r(s,(p==="valueFilter"),m);
r(n,(p==="customFilter"),m);
},_toggleElement:function(o,r,m){var q=r?"":0;
var n=q;
if(m){if(r){n=o.height("").height();
o.height(0);
}else{o.height(o.height());
}var p={height:n};
$telerik.stopTransition(o,false);
$telerik.transition(o,p,this._animationDuration,this._animationType,function(){this.height(q);
});
}else{o.height(q);
}}};
})($telerik.$);
(function(a,e){var b=Telerik.Web.UI;
var c={zIndex:4000,draggable:true,modal:true,minTop:10,minBottom:10,minLeft:10,minRight:10,maxHeight:550};
var d='<div class="rssWindow rssSkin"><div class="rssWindowTitlebar"><span class="rssWindowTitle">{0}</span><span class="rssWindowActions"><span class="rssWindowAction" data-command="close" title="Close"><span class="rssIcon rssIconClose"></span></span></span></div><div class="rssWindowContent"></div></div>")';
b.Spreadsheet.PopupDialog=function(h,g){a.observable(this);
this._element=h;
this._eventsNamespace="."+(h.id||"SpreadsheetPopupDialog");
this.options=a.extend({},c,g);
var f=a(String.format(d,g.title));
a(h).parent().append(f);
f.find(".rssWindowContent").append(h);
this._wrapper=f[0];
if(b.Calendar){this._originalCalendarZIndex=b.Calendar.Popup.zIndex;
}};
b.Spreadsheet.PopupDialog.prototype={open:function(){var h=this;
var f=this._wrapper;
var g="fixed";
this._modalExtender=new Telerik.Web.UI.ModalExtender(f);
f.style.position=g;
if(this.options.modal){a(this._modalExtender._getModalOverlay()).css({position:g,zIndex:this.options.zIndex});
this._modalExtender.show();
}a(f).css({display:"block",zIndex:this.options.zIndex+1});
if(b.Calendar){b.Calendar.Popup.zIndex=this.options.zIndex+2;
}a(f).on("click"+this._eventsNamespace,".rssWindowAction",function(i){if(a(this).attr("data-command")==="close"){h.close();
}});
a(window).on("resize"+this._eventsNamespace,function(){h._resizeForm();
h._positionForm();
});
a(window).trigger("resize"+this._eventsNamespace);
},close:function(){if(this._modalExtender){this._modalExtender.dispose();
}a(this._wrapper).hide().off(this._eventsNamespace);
a(window).off(this._eventsNamespace);
if(b.Calendar){b.Calendar.Popup.zIndex=this._originalCalendarZIndex;
}this.trigger("close");
},_positionForm:function(){var k=a(window);
var j=0;
var i=0;
var h=0;
var g=0;
var f=a(this._wrapper);
i+=(k.width()-f.outerWidth())/2;
j+=(k.height()-parseInt(f.outerHeight(),10))/2;
i=Math.max(i,g);
j=Math.max(j,h);
f.css({top:j,left:i});
},_resizeForm:function(){var f=a(this._wrapper);
var g=f.find(".rssWindowContent");
var h=a(window).height()-(f.outerHeight(true)-g.outerHeight(true));
var i=Math.min(h,this.options.maxHeight);
f.css({width:this.options.width,minWidth:this.options.minWidth});
g.css({"max-height":i});
}};
})($telerik.$);
(function(a,v){Type.registerNamespace("Telerik.Web.UI.Spreadsheet");
var d=Telerik.Web.UI;
var k=".spreadsheet";
var m=".spreadsheetFormatCellsView";
var x=".spreadsheetValidationView";
var o=".spreadsheetHyperlinkView";
var f="click";
var j='DATEVALUE("{0}")';
var s="mouseenter";
var t="mouseleave";
var e="change";
var q="keypress";
var b=a.extend;
var c=a.proxy;
var u=kendo.Observable.extend({init:function(A){kendo.Observable.fn.init.call(this);
this.options=b(true,{},this.options,{messages:d.Spreadsheet.Localization},A);
this.bind(this.events,A);
this._initPopup();
},events:["close"],destroy:function(){this.element=null;
},open:function(){this._dialog.open();
},close:function(){this._dialog.close();
},apply:function(){this.close();
},_initPopup:function(){this.element.show();
this._dialog=new d.Spreadsheet.PopupDialog(this.element[0],{zIndex:5001,title:this.options.title,width:this.options.width,minWidth:this.options.minWidth});
this._dialog.on({close:this._dialogClose},this);
},_dialogClose:function(){var C=this.options.wrapper;
var B=d.MaterialRippleManager.getInstance();
var A=this._dialog._wrapper;
this.element.hide();
if(C){C.append(this.element);
}if(A&&B){B.disposeRippleZone(A);
}a(A).remove();
this._dialog=null;
this.trigger("deactivate");
this.trigger("close");
this.destroy();
}});
var g=u.extend({init:function(A){this.initTemplate();
u.fn.init.call(this,A);
this.initButtons();
},destroy:function(){this.element.off(k);
u.fn.destroy.call(this);
},options:{width:350,template:"<div class='rssMessage'><div class='rssMessageText'></div><div class='rssButtons'><span class='rssButton rssPrimary' data-command='ok'></span></div></div>"},initTemplate:function(){var A=this.options;
this.element=a(A.template).hide().appendTo(document.documentElement);
},initButtons:function(){var A=this;
this.element.on(f+k,".rssButtons .rssButton",function(C){var B=a(this).attr("data-command");
C.preventDefault();
if(B==="ok"){A.confirm();
}else{if(B==="cancel"){A.cancel();
}}A.close();
}).on(s+k,".rssButtons .rssButton",function(B){a(this).addClass("rssHovered");
}).on(t+k,".rssButtons .rssButton",function(B){a(this).removeClass("rssHovered");
});
},confirm:function(){},cancel:function(){}});
var r=g.extend({init:function(A){g.fn.init.call(this,A);
},open:function(){var B=this.options;
var A=B.messages.messageDialog;
this.element.find(".rssMessageText").text(B.text).end().find(".rssButton[data-command='ok']").text(A.useKeyboardOK);
u.fn.open.call(this);
}});
kendo.spreadsheet.dialogs.register("message",r);
var z=r.extend({init:function(A){r.fn.init.call(this,A);
}});
kendo.spreadsheet.dialogs.register("validationError",z);
function i(A,B){kendo.spreadsheet.dialogs.register(A,r.extend({init:function(D){var C=d.Spreadsheet.Localization.messageDialog[B];
D=b({},D,{text:C});
r.fn.init.call(this,D);
}}));
}i("modifyMerged","modifyMerged");
i("rangeDisabled","rangeDisabled");
i("overflow","overflow");
i("unsupportedSelection","unsupportedSelection");
i("incompatibleRanges","incompatibleRanges");
i("noFillDirection","noFillDirection");
i("duplicateSheetName","duplicateSheetName");
var w=g.extend({init:function(){var A=d.Spreadsheet.Localization.messageDialog.useKeyboardTitle;
g.fn.init.call(this,{title:A});
},open:function(){var A=this.options.messages.messageDialog;
this.element.find(".rssMessageText").text(A.useKeyboardText).end().find(".rssButton[data-command='ok']").text(A.useKeyboardOK);
u.fn.open.call(this);
}});
kendo.spreadsheet.dialogs.register("useKeyboard",w);
var h=g.extend({init:function(A){var B=d.Spreadsheet.Localization.confirmationDialog.title;
g.fn.init.call(this,{title:B,close:A.close});
},options:{template:"<div class='rssMessage'><div class='rssMessageText'></div><div class='rssButtons'><span class='rssButton rssPrimary' data-command='ok'></span><span class='rssButton' data-command='cancel'></span></div></div>"},isConfirmed:function(){return this._confirmed;
},open:function(){var A=this.options.messages.confirmationDialog;
this._confirmed=false;
this.element.find(".rssMessageText").text(A.text).end().find(".rssButton[data-command='ok']").text(A.ok).end().find(".rssButton[data-command='cancel']").text(A.cancel);
u.fn.open.call(this);
},confirm:function(){this._confirmed=true;
}});
kendo.spreadsheet.dialogs.register("confirmation",h);
var n=u.extend({init:function(A){this.element=A.wrapper.find(".rssCustomFormatTemplate");
A.title=d.Spreadsheet.Localization.messageDialog.formatTitle;
u.fn.init.call(this,A);
this._initView();
},destroy:function(){u.fn.destroy.call(this);
this._view.destroy();
this._view=null;
},options:{width:400},apply:function(A){this.trigger("action",{command:"PropertyChangeCommand",options:{property:"format",value:A.format}});
u.fn.apply.call(this);
},open:function(A){u.fn.open.call(this);
this._view._value=A.value();
this._view.init();
},_initView:function(){this._view=new d.Spreadsheet.FormatCellsView(this.element);
this._view.on({action:this._viewAction},this);
},_viewAction:function(A){switch(A.command){case"save":this.apply(A.options);
break;
case"cancel":this.close();
break;
}}});
kendo.spreadsheet.dialogs.register("formatCells",n);
var y=u.extend({init:function(A){this.element=A.wrapper.find(".rssValidationTemplate");
A.title=d.Spreadsheet.Localization.messageDialog.validationTitle;
u.fn.init.call(this,A);
this._initView();
},destroy:function(){u.fn.destroy.call(this);
this._view.destroy();
this._view=null;
},options:{minWidth:460},apply:function(A){this.trigger("action",{command:"EditValidationCommand",options:{value:A.value}});
u.fn.apply.call(this);
},open:function(A){u.fn.open.call(this);
this._view._validation=A.validation();
this._view.options.messages=this.options.messages;
this._view.init();
},_initView:function(){this._view=new d.Spreadsheet.ValidationView(this.element);
this._view.on({action:this._viewAction},this);
},_viewAction:function(A){switch(A.command){case"save":this.apply(A.options);
break;
case"remove":this.apply({value:null});
break;
case"cancel":this.close();
break;
}}});
kendo.spreadsheet.dialogs.register("validation",y);
var p=u.extend({init:function(A){this.element=A.wrapper.find(".rssHyperlinkTemplate");
A.title=d.Spreadsheet.Localization.hyperlinkDialog.hyperlinkTitle;
u.fn.init.call(this,A);
this._initView();
},destroy:function(){u.fn.destroy.call(this);
this._view.destroy();
this._view=null;
},options:{width:460},apply:function(A){this.trigger("action",{command:"HyperlinkCommand",options:{link:A.url}});
u.fn.apply.call(this);
},open:function(A){u.fn.open.call(this);
this._view.init(A.link());
},_initView:function(){this._view=new d.Spreadsheet.HyperlinkView(this.element);
this._view.on({action:this._viewAction},this);
},_viewAction:function(A){switch(A.command){case"save":this.apply(A.options);
break;
case"remove":this.apply({url:null});
break;
case"cancel":this.close();
break;
}}});
kendo.spreadsheet.dialogs.register("hyperlink",p);
function l(A){return $find(a(A).attr("id"));
}d.Spreadsheet.FormatText=function(B,A){return kendo.spreadsheet.formatting.text(B,A);
};
d.Spreadsheet.FormatCellsView=function(A,B){a.observable(this);
this.options=b({},B);
this.element=A;
};
d.Spreadsheet.FormatCellsView.prototype={init:function(){this.initControls();
this.initTabStrip();
this.initButtons();
},destroy:function(){this._activeListBox=null;
this.tabStrip.remove_tabSelected(this._tabSelectedHandler);
this.tabStrip=null;
this._tabSelectedHandler=null;
for(var A=0,B=this.listBoxes.length;
A<B;
A++){this.listBoxes[A].remove_selectedIndexChanged(this._listBoxItemSelectedHandler);
}this.listBoxes=[];
this.element.find(".rssHovered").removeClass("rssHovered");
this.element.off(m);
this.element=null;
},action:function(A){this.trigger("action",b({},A));
},initControls:function(){this.tabStrip=l(this.element.find("[id$='_FormatsTabStrip']"));
this.initListBoxes();
},initListBoxes:function(){var E=this.listBoxes=[];
var H=this.tabStrip.get_tabs();
var A=H.get_count();
var G;
var F;
var D;
var C;
this._listBoxItemSelectedHandler=c(this._onListBoxItemSelected,this);
for(var B=0;
B<A;
B++){G=H.getTab(B);
F=G.get_pageView();
D=a(F.get_element()).find(".RadListBox");
C=l(D);
E.push(C);
C.add_selectedIndexChanged(this._listBoxItemSelectedHandler);
}},initTabStrip:function(){var A=this.tabStrip;
this._tabSelectedHandler=c(this._onTabSelected,this);
A.add_tabSelected(this._tabSelectedHandler);
A.set_selectedIndex(-1);
A.set_selectedIndex(0);
},initButtons:function(){var A=this;
a(this.element).on(f+m,".rssButtons .rssButton",function(C){C.preventDefault();
var B=a(this).attr("data-command");
var D={};
if(B==="save"){D.format=A._getFormat();
}A.action({command:B,options:D});
}).on(s+m,".rssButtons .rssButton",function(B){a(this).addClass("rssHovered");
}).on(t+m,".rssButtons .rssButton",function(B){a(this).removeClass("rssHovered");
});
},_getFormat:function(){var B=this._activeListBox.get_selectedItem();
var A=B.get_value();
return A;
},_onTabSelected:function(D,A){var C=A.get_tab();
var B=this._activeListBox=this.listBoxes[C.get_index()];
B.get_items().getItem(0).select();
},_onListBoxItemSelected:function(C,A){var B=C.get_selectedItem().get_value();
var E=this._value||100;
var D=d.Spreadsheet.FormatText(E,this._convertFormat(B));
a(C.get_element()).siblings(".rssFormatPreview").text(D);
},_convertFormat:function(A){if((/T|Z/).test(A)){return"";
}return A.toLowerCase().replace(/tt/g,"AM/PM").replace(/'/g,'"');
}};
d.Spreadsheet.ValidationView=function(A,B){a.observable(this);
this.options=b({},B);
this.element=A;
};
d.Spreadsheet.ValidationView.prototype={init:function(){this.initControls();
this.initControlsValues();
this.initControlEvents();
this.initButtons();
},destroy:function(){this.element.find(".rssHovered").removeClass("rssHovered");
this.disposeControlEvents();
this.controls={};
this.element.off(x);
this.element=null;
},disposeControlEvents:function(){var A=this.controls;
A.criteria.remove_selectedIndexChanged(this._criteriaChangedHandler);
A.numberCriteria.remove_selectedIndexChanged(this._comparerTypeChangedHandler);
A.dateCriteria.remove_selectedIndexChanged(this._comparerTypeChangedHandler);
a(A.hint).off(x);
this._getFormInputElements().off(x);
},action:function(A){this.trigger("action",b({},A));
},initControls:function(){var C=this;
var A=this.controls={};
var B=function(D){return l(C.element.find("[id$='"+D+"']"));
};
A.criteria=B("_CriteriaDropDownList");
A.numberCriteria=B("_NumberCriteriaDropDownList");
A.textCriteria=B("_TextCriteriaDropDownList");
A.dateCriteria=B("_DateCriteriaDropDownList");
A.numberCriteriaFrom=B("_NumberCriteriaNumericMin");
A.numberCriteriaTo=B("_NumberCriteriaNumericMax");
A.textCriteriaFrom=B("_TextCriteriaTextBox");
A.dateCriteriaFrom=B("_DateCriteriaDatePickerMin");
A.dateCriteriaTo=B("_DateCriteriaDatePickerMax");
A.customCriteriaFrom=B("_CustomCriteriaTextBox");
A.showButton=this.element.find("[id$='_CriteriaShowButtonCheckBox']")[0];
A.ignoreBlanks=this.element.find("[id$='_CriteriaIgnoreCheckBox']")[0];
A.invalidButtonList=this.element.find("[id$='_InvalidDataRadioButtonList']")[0];
A.hint=this.element.find("[id$='_HintCheckBox']")[0];
A.hintMessage=B("_HintTextBox");
},initControlsValues:function(){var A=this.controls;
A.criteria.getItem(0).select();
A.numberCriteria.getItem(0).select();
A.textCriteria.getItem(0).select();
A.dateCriteria.getItem(0).select();
A.numberCriteriaFrom.set_value("");
A.numberCriteriaTo.set_value("");
A.textCriteriaFrom.set_value("");
A.dateCriteriaFrom.set_selectedDate("");
A.dateCriteriaTo.set_selectedDate("");
A.customCriteriaFrom.set_value("");
this._setValidation(this._validation);
},initControlEvents:function(){var A=this.controls;
this._criteriaChangedHandler=c(this._onCriteriaChanged,this);
A.criteria.add_selectedIndexChanged(this._criteriaChangedHandler);
this._comparerTypeChangedHandler=c(this._onComparerTypeChanged,this);
A.numberCriteria.add_selectedIndexChanged(this._comparerTypeChangedHandler);
A.dateCriteria.add_selectedIndexChanged(this._comparerTypeChangedHandler);
this._onCriteriaChanged(A.criteria);
this._onComparerTypeChanged(A.numberCriteria);
this._onComparerTypeChanged(A.dateCriteria);
a(A.hint).on(e+x,c(this._onHintToggled,this));
this._getFormInputElements().on(q+x,function(B){return B.keyCode!==13;
});
},initButtons:function(){var A=this;
a(this.element).on(f+x,".rssButtons .rssButton",function(C){C.preventDefault();
var B=a(this).attr("data-command");
var D={};
var E=A._getValidation();
if(E!==null){E=b({},E);
}if(B==="save"){if(!A.isValid()){return;
}D.value=E;
}A.action({command:B,options:D});
}).on(s+x,".rssButtons .rssButton",function(B){a(this).addClass("rssHovered");
}).on(t+x,".rssButtons .rssButton",function(B){a(this).removeClass("rssHovered");
});
},isValid:function(){var B=this._getCriteria();
var A=this._getComparerType();
var C=true;
switch(B){case"number":C=Page_ClientValidate("NumberCriteriaMin");
if(A==="between"||A==="notBetween"){C=C&&Page_ClientValidate("NumberCriteriaMax");
}break;
case"text":C=Page_ClientValidate("TextCriteria");
break;
case"date":C=Page_ClientValidate("DateCriteriaMin");
if(A==="between"||A==="notBetween"){C=C&&Page_ClientValidate("DateCriteriaMax");
}break;
case"custom":case"list":C=Page_ClientValidate("CustomCriteria");
break;
}return C;
},_onCriteriaChanged:function(C){var A=C.get_selectedItem().get_value();
var B=this.element.find(".rssFormListOption");
B.hide();
var D=this.element.find("[id$='_CriteriaShowButtonCheckBox']");
D.toggle(A==="list"||A==="date");
var E=this.element.find(".showCalendarButton");
E.toggle(A==="date");
var F=this.element.find(".showListButton");
F.toggle(A==="list");
if(A==="list"){A="custom";
}B.filter("[data-value='"+A+"']").show();
},_onComparerTypeChanged:function(B){var D=B.get_selectedItem().get_value();
var A=a(B.get_element()).parents(".rssFormList").first();
var C=(D==="between"||D==="notBetween");
A.find("li").last().toggle(C);
},_onHintToggled:function(){var A=this.controls;
if(A.hint.checked){A.hintMessage.enable();
}else{A.hintMessage.disable();
}},_getFormInputElements:function(){var A=this.controls;
return a(A.numberCriteriaFrom.get_element()).add(A.numberCriteriaTo.get_element()).add(A.textCriteriaFrom.get_element()).add(A.dateCriteriaFrom.get_dateInput().get_element()).add(A.dateCriteriaTo.get_dateInput().get_element()).add(A.customCriteriaFrom.get_element()).add(A.hintMessage.get_element());
},_getValidation:function(){var A=this.controls;
var B=this._getCriteria();
if(B==="any"){return null;
}var C={allowNulls:this._getIgnoreBlanks(),showButton:this._getShowButton(),comparerType:this._getComparerType(),dataType:B,from:this._getFrom(),to:this._getTo(),type:this._getInvalidType()};
if(A.hint.checked){C.messageTemplate=this._getHint();
}return C;
},_getCriteria:function(){return this.controls.criteria.get_selectedItem().get_value();
},_getComparerType:function(){var C=null;
var A=this.controls;
var B=this._getCriteria();
switch(B){case"number":C=A.numberCriteria.get_selectedItem().get_value();
break;
case"text":C=A.textCriteria.get_selectedItem().get_value();
break;
case"date":C=A.dateCriteria.get_selectedItem().get_value();
break;
}return C;
},_getFrom:function(){var C=null;
var A=this.controls;
var B=this._getCriteria();
switch(B){case"number":C=A.numberCriteriaFrom.get_value();
break;
case"text":C=A.textCriteriaFrom.get_value();
break;
case"date":C=kendo.format(j,A.dateCriteriaFrom.get_selectedDate());
break;
case"custom":case"list":C=A.customCriteriaFrom.get_value();
break;
}return C;
},_getTo:function(){var C=null;
var A=this.controls;
var B=this._getCriteria();
switch(B){case"number":C=A.numberCriteriaTo.get_value();
break;
case"date":C=kendo.format(j,A.dateCriteriaTo.get_selectedDate());
break;
}return C;
},_getInvalidType:function(){var A=a(this.controls.invalidButtonList).find("input:checked").attr("value");
return A;
},_getHint:function(){return this.controls.hintMessage.get_value();
},_getIgnoreBlanks:function(){return this.controls.ignoreBlanks.checked;
},_getShowButton:function(){return this.controls.showButton.checked;
},_setValidation:function(A){if(A===null){A={dataType:"any"};
}this._setCriteria(A.dataType);
this._setComparerType(A.comparerType);
this._setFrom(A.from);
this._setTo(A.to);
this._setInvalidType(A.type);
this._setHint(A.messageTemplate);
this._setIgnoreBlanks(A.allowNulls);
this._setShowButton(A.showButton);
},_setCriteria:function(A){var B=this.controls.criteria;
var C=B.findItemByValue(A);
if(!C){C=B.getItem(0);
}C.select();
},_setComparerType:function(A){var B=this.controls;
var C=this._getCriteria();
var D=null;
switch(C){case"number":D=B.numberCriteria.findItemByValue(A);
break;
case"text":D=B.textCriteria.findItemByValue(A);
break;
case"date":D=B.dateCriteria.findItemByValue(A);
break;
}if(D){D.select();
}},_setFrom:function(D){var A=this.controls;
var B=this._getCriteria();
if(!D){return;
}switch(B){case"number":A.numberCriteriaFrom.set_value(D);
break;
case"text":D=A.textCriteriaFrom.set_value(D);
break;
case"date":var C=this._parseDate(D);
A.dateCriteriaFrom.set_selectedDate(C);
break;
case"custom":case"list":A.customCriteriaFrom.set_value(D);
break;
}},_setTo:function(D){var A=this.controls;
var B=this._getCriteria();
if(!D){return;
}switch(B){case"number":A.numberCriteriaTo.set_value(D);
break;
case"date":var C=this._parseDate(D);
A.dateCriteriaTo.set_selectedDate(C);
break;
}},_setInvalidType:function(B){var A=this.controls.invalidButtonList;
if(B!=="warning"){B="reject";
}a(A).find("input[value='"+B+"']")[0].checked=true;
},_setHint:function(C){var A=this.controls;
var B=this.options.messages.validationDialog.hyperlinkTitle;
A.hint.checked=!!C;
A.hintMessage.set_value(C||B);
this._onHintToggled();
},_setIgnoreBlanks:function(A){this.controls.ignoreBlanks.checked=(A!==v)?A:true;
},_setShowButton:function(A){this.controls.showButton.checked=(A!==v)?A:true;
},_parseDate:function(A){return new Date(A.substring("DATEVALUE(".length+1,A.length-2));
}};
d.Spreadsheet.HyperlinkView=function(A,B){a.observable(this);
this.options=b({},B);
this.element=A;
};
d.Spreadsheet.HyperlinkView.prototype={init:function(A){this.initControls(A);
this.initButtons();
this.urlTextBox.focus();
},destroy:function(){this.urlTextBox.remove_keyPress(this._textBoxKeyPressHandler);
this.urlTextBox=null;
this.element.find(".rssHovered").removeClass("rssHovered");
this.element.off(o);
this.element=null;
},initControls:function(A){this.urlTextBox=l(this.element.find("[id$='_UrlTextBox']"));
this._textBoxKeyPressHandler=c(this._textBoxKeyPress,this);
this.urlTextBox.add_keyPress(this._textBoxKeyPressHandler);
this.urlTextBox.set_value(A);
},action:function(A){this.trigger("action",b({},A));
},initButtons:function(){var A=this;
a(this.element).on(f+o,".rssButtons .rssButton",function(C){C.preventDefault();
var B=a(this).attr("data-command");
A._triggerAction(B);
}).on(s+o,".rssButtons .rssButton",function(B){a(this).addClass("rssHovered");
}).on(t+o,".rssButtons .rssButton",function(B){a(this).removeClass("rssHovered");
});
},_textBoxKeyPress:function(C,A){var D=this;
var B=A.get_keyCode();
if(B===13){A.get_domEvent().preventDefault();
A.get_domEvent().stopPropagation();
setTimeout(function(){D._triggerAction("save");
},10);
}},_triggerAction:function(A){var B={};
var C=this._getUrl();
if(A==="save"&&/\S/.test(C)){B.url=C;
}this.action({command:A,options:B});
},_getUrl:function(){return this.urlTextBox.get_value();
}};
})($telerik.$);
(function(a,e){var b=Telerik.Web.UI;
b.SpreadsheetSheet=function(){this._sheet=null;
};
b.SpreadsheetSheet.prototype={get_range:function(h){var f=this._sheet.range(h);
var g=this._getRange(f);
return g;
},get_selection:function(){var f=this._sheet.selection();
var g=this._getRange(f);
return g;
},get_columnWidth:function(f){return this._sheet.columnWidth(f);
},set_columnWidth:function(f,g){this._sheet.columnWidth(f,g);
},get_rowHeight:function(f){return this._sheet.rowHeight(f);
},set_rowHeight:function(g,f){this._sheet.rowHeight(g,f);
},_getRange:function(f){var g=new b.SpreadsheetRange();
g._range=f;
return g;
}};
function c(f,g){a.each(g,function(h,i){f.prototype[i]=function(){this._sheet[i].apply(this._sheet,arguments);
};
});
}c(b.SpreadsheetSheet,["clearFilter","deleteColumn","deleteRow","hideColumn","hideRow","unhideColumn","unhideRow","insertColumn","insertRow"]);
function d(i,h,j){var f=function(k){return function(){var l=this._sheet[k]();
return l;
};
};
var g=function(k){return function(l){this._sheet[k](l);
};
};
a.each(i,function(k,l){h=h||f;
j=j||g;
b.SpreadsheetSheet.prototype["get_"+l]=h(l);
b.SpreadsheetSheet.prototype["set_"+l]=j(l);
});
}d(["frozenColumns","frozenRows","showGridLines"]);
})($telerik.$);
(function(a,g){var b=Telerik.Web.UI;
b.SpreadsheetRange=function(){this._range=null;
};
b.SpreadsheetRange.prototype={get_enabled:function(){return this._range.enable();
},set_enabled:function(h){this._range.enable(h);
},set_filter:function(h){this._range.filter(h);
},hasFilter:function(){return this._range.hasFilter();
},get_isSortable:function(){return this._range.isSortable();
},get_isFilterable:function(){return this._range.isFilterable();
},get_selections:function(){var h=this._range._ref;
if(!h){return[];
}if(h.bottomRight){return this._getSingleAreaSelection(h);
}else{if(h.col||h.col===0){return this._getSingleCellSelection(h);
}else{if(h.refs){return this._getMultipleAreaSelection(h);
}}}},_getSingleCellSelection:function(j){var h=[],i={col:j.col,row:j.row};
h.push({topLeftCell:i,bottomRightCell:i});
return h;
},_getSingleAreaSelection:function(i){var h=[];
h.push({topLeftCell:{col:i.topLeft.col,row:i.topLeft.row},bottomRightCell:{col:i.bottomRight.col,row:i.bottomRight.row}});
return h;
},_getMultipleAreaSelection:function(i){var h=i.refs.map(function(j){return{topLeftCell:{col:j.topLeft.col,row:j.topLeft.row},bottomRightCell:{col:j.bottomRight.col,row:j.bottomRight.row}};
});
return h;
}};
function e(h){a.each(h,function(i,j){b.SpreadsheetRange.prototype[j]=function(){this._range[j].apply(this._range,arguments);
};
});
}e(["merge","unmerge","select","fillFrom","clear","clearFilter"]);
function f(k,j,l){var h=function(m){return function(){var n=this._range[m]();
return n;
};
};
var i=function(m){return function(n){this._range[m](n);
};
};
a.each(k,function(m,n){j=j||h;
l=l||i;
b.SpreadsheetRange.prototype["get_"+n]=j(n);
b.SpreadsheetRange.prototype["set_"+n]=l(n);
});
}f(["background","bold","color","fontFamily","fontSize","format","formula","input","italic","link","textAlign","underline","value","values","validation","verticalAlign","wrap","comment"]);
function d(j,k){var h={};
var i=[];
a.each(j,function(m,n){var l=n+k;
h[l]=n;
i.push(l);
});
f(i,function(l){return function(){var m=this._range[h[l]]();
return m?(m[k.toLowerCase()]||null):null;
};
},function(l){return function(n){var m={};
m[k.toLowerCase()]=n;
this._range[h[l]](m);
};
});
}var c=["borderBottom","borderLeft","borderRight","borderTop"];
d(c,"Color");
d(c,"Size");
})($telerik.$);
(function(a,D){Type.registerNamespace("Telerik.Web.UI");
var e=Telerik.Web.UI;
var c=Sys.Serialization.JavaScriptSerializer;
var d=a.proxy;
var b=a.extend;
var m=".";
var u="mouseenter";
var v="mouseleave";
var A="render",f="change",B="select",h="changing",g="changeFormat",t="insertSheet",y="removeSheet",z="renameSheet",C="selectSheet",E="unhideColumn",F="unhideRow",p="hideColumn",q="hideRow",k="deleteColumn",l="deleteRow",r="insertColumn",s="insertRow",n="excelExport",o="excelImport",x="pdfExport",i="copy",j="cut",w="paste";
e.Spreadsheet.Localization={messageDialog:{useKeyboardTitle:"Copying and pasting",useKeyboardText:"These actions cannot be invoked through the menu. Please use the keyboard shortcuts instead",useKeyboardOK:"OK",validationTitle:"Data Validation",formatTitle:"Format",modifyMerged:"Cannot change part of a merged cell.",rangeDisabled:"Destination range contains disabled cells.",overflow:"Cannot paste, because the copy area and the paste area are not the same size and shape.",unsupportedSelection:"That action cannot be performed on multiple selection.",incompatibleRanges:"Incompatible ranges",noFillDirection:"Cannot determine fill direction",duplicateSheetName:"Duplicate sheet name"},hyperlinkDialog:{hyperlinkTitle:"Hyperlink"},validationDialog:{hyperlinkTitle:"Enter a value that satisfies the formula:"},confirmationDialog:{ok:"OK",cancel:"Cancel",title:"Sheet remove",text:"Are you sure you want to remove this sheet?"}};
e.RadSpreadsheet=function(G){e.RadSpreadsheet.initializeBase(this,[G]);
this._widget=null;
this._uniqueId=null;
this._cellContextMenuID=null;
this._rowHeaderContextMenuID=null;
this._columnHeaderContextMenuID=null;
};
e.RadSpreadsheet.prototype={initialize:function(){this.initializeLocalization();
this._registerToMaterialRippleManager();
this.initializeWidget();
},initializeLocalization:function(){b(true,e.Spreadsheet.Localization,this.get_localization());
},initializeWidget:function(){var I=this;
var H=this.get_sheetsData();
var G={columns:this.get_columnsCount(),columnWidth:this.get_columnWidth(),headerHeight:this.get_columnHeaderHeight(),headerWidth:this.get_rowHeaderWidth(),rows:this.get_rowsCount(),rowHeight:this.get_rowHeight(),render:function(K){var J={widget:K.sender};
a.raiseControlEvent(I,A,J);
},change:function(K){var J={widget:K.sender,range:I.get_activeSheet()._getRange(K.range)};
a.raiseControlEvent(I,f,J);
},select:function(K){var J={widget:K.sender,range:I.get_activeSheet()._getRange(K.range)};
a.raiseControlEvent(I,B,J);
},changeFormat:function(K){var J={widget:K.sender,range:I.get_activeSheet()._getRange(K.range)};
a.raiseControlEvent(I,g,J);
},changing:function(K){var J={widget:K.sender,range:I.get_activeSheet()._getRange(K.range),changeType:K.changeType,data:K.data};
if(a.raiseCancellableControlEvent(I,h,J)){K.preventDefault();
}},insertSheet:function(K){var J={widget:K.sender};
if(a.raiseCancellableControlEvent(I,t,J)){K.preventDefault();
}},removeSheet:function(K){var J={widget:K.sender,sheet:K.sheet};
if(a.raiseCancellableControlEvent(I,y,J)){K.preventDefault();
}},renameSheet:function(K){var J={widget:K.sender,sheet:K.sheet,newSheetName:K.newSheetName};
if(a.raiseCancellableControlEvent(I,z,J)){K.preventDefault();
}},selectSheet:function(K){var J={widget:K.sender,sheet:K.sheet};
if(a.raiseCancellableControlEvent(I,C,J)){K.preventDefault();
}},unhideColumn:function(K){var J={widget:K.sender,sheet:K.sheet,index:K.index};
if(a.raiseCancellableControlEvent(I,E,J)){K.preventDefault();
}},unhideRow:function(K){var J={widget:K.sender,sheet:K.sheet,index:K.index};
if(a.raiseCancellableControlEvent(I,F,J)){K.preventDefault();
}},hideColumn:function(K){var J={widget:K.sender,sheet:K.sheet,index:K.index};
if(a.raiseCancellableControlEvent(I,p,J)){K.preventDefault();
}},hideRow:function(K){var J={widget:K.sender,sheet:K.sheet,index:K.index};
if(a.raiseCancellableControlEvent(I,q,J)){K.preventDefault();
}},deleteColumn:function(K){var J={widget:K.sender,sheet:K.sheet,index:K.index};
if(a.raiseCancellableControlEvent(I,k,J)){K.preventDefault();
}},deleteRow:function(K){var J={widget:K.sender,sheet:K.sheet,index:K.index};
if(a.raiseCancellableControlEvent(I,l,J)){K.preventDefault();
}},insertColumn:function(K){var J={widget:K.sender,sheet:K.sheet,index:K.index};
if(a.raiseCancellableControlEvent(I,r,J)){K.preventDefault();
}},insertRow:function(K){var J={widget:K.sender,sheet:K.sheet,index:K.index};
if(a.raiseCancellableControlEvent(I,s,J)){K.preventDefault();
}},excelExport:function(K){var J={widget:K.sender,data:K.data,workbook:K.workbook};
if(a.raiseCancellableControlEvent(I,n,J)){K.preventDefault();
}},excelImport:function(K){var J={widget:K.sender,file:K.file,promise:K.promise};
if(a.raiseCancellableControlEvent(I,o,J)){K.preventDefault();
}},pdfExport:function(K){var J={widget:K.sender,promise:K.promise};
if(a.raiseCancellableControlEvent(I,x,J)){K.preventDefault();
}},copy:function(K){var J={widget:K.sender,range:I.get_activeSheet()._getRange(K.range)};
if(a.raiseCancellableControlEvent(I,i,J)){K.preventDefault();
}},cut:function(K){var J={widget:K.sender,range:I.get_activeSheet()._getRange(K.range)};
if(a.raiseCancellableControlEvent(I,j,J)){K.preventDefault();
}},paste:function(K){var J={widget:K.sender,range:I.get_activeSheet()._getRange(K.range),clipboardContent:K.clipboardContent};
if(a.raiseCancellableControlEvent(I,w,J)){K.preventDefault();
}}};
if(H.length){G.sheets=H;
}this._widget=a(this.get_element()).kendoSpreadsheet(G).data("kendoSpreadsheet");
this._widget._workbook.unbind("excelImport");
this.initializeToolbar();
this.initializeContextMenus();
this._initializeHoveredStates();
},initializeToolbar:function(){this._widget._view.tabstrip.bind("toolBarCommand",d(this._onToolbarCommand,this));
},initializeContextMenus:function(){var G=this._widget._view;
G.cellContextMenu._initContextMenu(this._cellContextMenuID);
G.rowHeaderContextMenu._initContextMenu(this._rowHeaderContextMenuID);
G.colHeaderContextMenu._initContextMenu(this._columnHeaderContextMenuID);
},get_kendoWidget:function(){return this._widget;
},save:function(){var G=c.serialize(this._widget.toJSON());
this._doCallback(G);
},saveAsExcel:function(){this._widget.saveAsExcel();
},fromFile:function(G){this._widget.fromFile(G);
},get_activeSheet:function(){var G=this._widget.activeSheet();
var H=this._getSheet(G);
return H;
},get_sheets:function(){var I=this;
var G=this._widget.sheets();
var H=a.map(G,function(J){return I._getSheet(J);
});
return H;
},findSheetByName:function(H){var G=this._widget.sheetByName(H);
var I=this._getSheet(G);
return I;
},findSheetByIndex:function(G){var H=this._widget.sheetByIndex(G);
var I=this._getSheet(H);
return I;
},insertSheet:function(){this._widget.insertSheet();
},removeSheet:function(G){this._widget.removeSheet(G._sheet);
},renameSheet:function(H,G){this._widget.renameSheet(H._sheet,G);
},get_rippleZonesConfiguration:function(){return[{element:this.get_element(),rippleConfigurations:[{containerSelector:".t-spreadsheet-sheets-bar-add, .t-item, .rssButton"},{containerSelector:".rssIconClose",rippleType:e.MaterialRippleType.Icon}]}];
},_getSheet:function(G){if(!G){return null;
}var H=new e.SpreadsheetSheet();
H._sheet=G;
return H;
},_onToolbarCommand:function(G){switch(G.value){case"save":this.save();
break;
}},_doCallback:function(G){var H=d(this._onCallbackResponse,this);
var I=d(this._onCallbackError,this);
WebForm_DoCallback(this._uniqueId,G,H,this,I,true);
},_onCallbackResponse:function(){},_onCallbackError:function(G){var H=this._extractErrorMessage(G);
alert(H);
},_extractErrorMessage:function(G){if(G.get_message){return G.get_message();
}else{return G.replace(/(\d*\|.*)/,"");
}},_initializeHoveredStates:function(){var G=kendo.spreadsheet.SheetsBar.classNames;
var H=m+kendo.spreadsheet.View.classNames.sheetsBar;
var J=m+G.sheetsBarItems+" "+m+G.sheetsBarKItemBase;
var I=m+G.sheetsBarRemove;
this._applyHoveredState(H,J);
this._applyHoveredState(H,I);
},_applyHoveredState:function(G,I){var H=kendo.spreadsheet.SheetsBar.classNames.sheetsBarHovered;
a(G).on(u,I,function(J){a(J.currentTarget).addClass(H);
}).on(v,I,function(J){a(J.currentTarget).removeClass(H);
});
}};
a.registerControlProperties(e.RadSpreadsheet,{sheetsData:[],localization:{},columnsCount:50,columnWidth:64,columnHeaderHeight:20,rowsCount:200,rowHeight:20,rowHeaderWidth:32});
a.registerControlEvents(e.RadSpreadsheet,[A,f,B,h,g,t,y,z,C,E,F,p,q,k,l,r,s,n,o,x,i,j,w]);
e.RadSpreadsheet.registerClass("Telerik.Web.UI.RadSpreadsheet",e.RadWebControl);
})($telerik.$);
