INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.01','',1,1,N'Skrining Pertumbuhan sesuai umur','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.02','',2,1,N'Skrining perkembangan sesuai umur','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.03','',3,1,N'Skrining keterlambatan bicara dan bahasa','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.04','',4,1,N'Assessment kelainan motoric','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.05','',5,1,N'Skrining Kelainan Perilaku','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.06','',6,1,N'Skrining Gangguan Pendengaran','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.07','',7,1,N'Skrining Gangguan Penglihatan','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.08','',8,1,N'Hb 0','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.09','',9,1,N'BCG','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.10','',10,1,N'Polio 1,2,3','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.11','',11,1,N'DPT-HB-HiB 1, 2,3,4','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.12','',12,1,N'IPV','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.13','',13,1,N'Campak-Rubella','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.14','',14,1,N'Vitamin A 100.000 SI (1 kali dalam setahun)','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.15','',15,1,N'Pemberian Komunikasi, Informasi dan Edukasi (KIE)','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.16','',16,1,N'Pemeriksaan Early Infant Diagnosis (EID)','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.17','',17,1,N'Pengobatan ARV bagi balita HIV+','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.18','',18,1,N'Pengobatan profilaksis kotrimoksazol','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.19','',19,1,N'Pemeriksaan Titer RPR','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.20','',20,1,N'Pengobatan dosis tunggal Benzatin Penicilin G','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.21','',21,1,N'Pemeriksaan serologis HBs Ag','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.22','',22,1,N'Pemberian Hb 0','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.23','',23,1,N'Pemberian Hb Ig','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.24','',24,1,N'Campak-Rubela','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.25','',25,1,N'Vitamin A 200.000 SI (2kali dalam setahun)','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.26','',26,1,N'Anak balita mendapat obat pencegahan kecacingan 1 kali setahun','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.27','',27,1,N'Balita (0-59 bulan) terduga TBC/ kontak erat mendapat TPT (Terapi Pencegahan TBC)','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.28','',28,1,N'Balita (0-59 bulan) TBC mendapatkan OAT','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
INSERT INTO [Question]([QuestionID],[ParentQuestionID],[IndexNo],[QuestionLevel],[QuestionText],[QuestionShortText],[SRAnswerType],[AnswerDecimalDigit],[AnswerPrefix],[AnswerSuffix],[IsActive],[AnswerWidth],[AnswerWidth2],[QuestionAnswerSelectionID],[QuestionAnswerDefaultSelectionID],[QuestionAnswerSelectionID2],[QuestionAnswerDefaultSelectionID2],[Formula],[IsAlwaysPrint],[LastUpdateDateTime],[LastUpdateByUserID],[IsMandatory],[ReferenceQuestionID],[VitalSignID],[BodyID],[RelatedEntityName],[RelatedColumnName],[LookUpID],[IsUpdateRelatedEntity],[IsReadOnly],[NursingDisplayAs],[EquivalentQuestionID],[IsEmptyDefault],[IsNotOverWriteRelatedEntity])
VALUES(N'RL3.7.29','',29,1,N'Pemberian Komunikasi, Informasi dan Edukasi (KIE)','',N'CHK',0,'','',1,NULL,NULL,'','','','','',1,'2025-02-17 21:57:00.000',N'Cale',0,'','','','','','',NULL,NULL,'','',NULL,NULL);
