(function(b,a){a("kendo.gantt.list",["kendo.dom","kendo.touch","kendo.draganddrop","kendo.columnsorter","kendo.datetimepicker","kendo.editable"],b);
}(function(){var a={id:"gantt.list",name:"Gantt List",category:"web",description:"The Gantt List",depends:["dom","touch","draganddrop","columnsorter","datetimepicker","editable"],hidden:true};
(function(b){var k=window.kendo;
var l=k.dom;
var m=l.element;
var n=l.text;
var d=k.support.browser;
var r=k.support.mobileOS;
var z=k.ui;
var A=z.Widget;
var h=b.extend;
var v=k._outerWidth;
var u=k._outerHeight;
var q=b.map;
var j=b.isFunction;
var t=d.msie&&d.version<9;
var o=k.keys;
var y={title:"Title",start:"Start Time",end:"End Time",percentComplete:"% Done",parentId:"Predecessor ID",id:"ID",orderId:"Order ID"};
var x="string";
var s=".kendoGanttList";
var e="click";
var g=".";
var w="<table style='visibility: hidden;'><tbody><tr style='height:{0}'><td>&nbsp;</td></tr></tbody></table>";
var p={wrapper:"k-treelist k-grid k-widget",header:"k-header",alt:"k-alt",rtl:"k-rtl",editCell:"k-edit-cell",group:"k-treelist-group",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",gridContentWrap:"k-grid-content",selected:"k-state-selected",icon:"k-icon",iconCollapse:"k-i-collapse",iconExpand:"k-i-expand",iconHidden:"k-i-none",iconPlaceHolder:"k-icon k-i-none",input:"k-input",link:"k-link",resizeHandle:"k-resize-handle",resizeHandleInner:"k-resize-handle-inner",dropPositions:"k-i-insert-up k-i-insert-down k-i-plus k-i-insert-middle",dropTop:"k-i-insert-up",dropBottom:"k-i-insert-down",dropAdd:"k-i-plus",dropMiddle:"k-i-insert-middle",dropDenied:"k-i-cancel",dragStatus:"k-drag-status",dragClue:"k-drag-clue",dragClueText:"k-clue-text"};
function f(E){var F=[];
var B=E.className;
for(var C=0,D=E.level;
C<D;
C++){F.push(m("span",{className:B}));
}return F;
}function c(){var B=k._activeElement();
if(B&&B.nodeName.toLowerCase()!=="body"){b(B).blur();
}}var i=z.GanttList=A.extend({init:function(B,C){A.fn.init.call(this,B,C);
if(this.options.columns.length===0){this.options.columns.push("title");
}this.dataSource=this.options.dataSource;
this._columns();
this._layout();
this._domTrees();
this._header();
this._sortable();
this._editable();
this._selectable();
this._draggable();
this._resizable();
this._attachEvents();
this._adjustHeight();
this.bind("render",function(){var D;
var E;
if(this.options.resizable){D=this.header.find("col");
E=this.content.find("col");
this.header.find("th").not(":last").each(function(F){var G=v(b(this));
D.eq(F).width(G);
E.eq(F).width(G);
});
D.last().css("width","auto");
E.last().css("width","auto");
}},true);
},_adjustHeight:function(){if(this.content){this.content.height(this.element.height()-u(this.header.parent()));
}},destroy:function(){A.fn.destroy.call(this);
if(this._reorderDraggable){this._reorderDraggable.destroy();
}if(this._tableDropArea){this._tableDropArea.destroy();
}if(this._contentDropArea){this._contentDropArea.destroy();
}if(this._columnResizable){this._columnResizable.destroy();
}if(this.touch){this.touch.destroy();
}if(this.timer){clearTimeout(this.timer);
}this.content.off(s);
this.header.find("thead").off(s);
this.header.find(g+i.link).off(s);
this.header=null;
this.content=null;
this.levels=null;
k.destroy(this.element);
},options:{name:"GanttList",selectable:true,editable:true,resizable:false},_attachEvents:function(){var C=this;
var B=i.styles;
C.content.on(e+s,"td > span."+B.icon+":not(."+B.iconHidden+")",function(D){var E=b(this);
var F=C._modelFromElement(E);
F.set("expanded",!F.get("expanded"));
D.stopPropagation();
});
},_domTrees:function(){this.headerTree=new l.Tree(this.header[0]);
this.contentTree=new l.Tree(this.content[0]);
},_columns:function(){var B=this.options.columns;
var C=function(){this.field="";
this.title="";
this.editable=false;
this.sortable=false;
};
this.columns=q(B,function(D){D=typeof D===x?{field:D,title:y[D]}:D;
return h(new C(),D);
});
},_layout:function(){var F=this;
var E=this.options;
var C=this.element;
var D=i.styles;
var B=function(){var H=typeof E.rowHeight===x?E.rowHeight:E.rowHeight+"px";
var I=b(k.format(w,H));
var G;
F.content.append(I);
G=u(I.find("tr"));
I.remove();
return G;
};
C.addClass(D.wrapper).append("<div class='"+D.gridHeader+"'><div class='"+D.gridHeaderWrap+"'></div></div>").append("<div class='"+D.gridContentWrap+"'></div>");
this.header=C.find(g+D.gridHeaderWrap);
this.content=C.find(g+D.gridContent);
if(E.rowHeight){this._rowHeight=B();
}},_header:function(){var C=this.headerTree;
var B;
var E;
var D;
B=m("colgroup",null,this._cols());
E=m("thead",{role:"rowgroup"},[m("tr",{role:"row"},this._ths())]);
D=m("table",{style:{minWidth:this.options.listWidth+"px"},role:"grid"},[B,E]);
C.render([D]);
},_render:function(E){var B;
var F;
var C;
var D={style:{minWidth:this.options.listWidth+"px"},tabIndex:0,role:"treegrid"};
if(this._rowHeight){D.style.height=E.length*this._rowHeight+"px";
}this.levels=[{field:null,value:0}];
B=m("colgroup",null,this._cols());
F=m("tbody",{role:"rowgroup"},this._trs(E));
C=m("table",D,[B,F]);
this.contentTree.render([C]);
this.trigger("render");
},_ths:function(){var D=this.columns;
var C;
var B;
var G=[];
for(var E=0,F=D.length;
E<F;
E++){C=D[E];
B={"data-field":C.field,"data-title":C.title,className:i.styles.header,role:"columnheader"};
G.push(m("th",B,[n(C.title)]));
}if(this.options.resizable){G.push(m("th",{className:i.styles.header,role:"columnheader"}));
}return G;
},_cols:function(){var D=this.columns;
var C;
var G;
var H;
var B=[];
for(var E=0,F=D.length;
E<F;
E++){C=D[E];
H=C.width;
if(H&&parseInt(H,10)!==0){G={style:{width:typeof H===x?H:H+"px"}};
}else{G=null;
}B.push(m("col",G,[]));
}if(this.options.resizable){B.push(m("col",{style:{width:"1px"}}));
}return B;
},_trs:function(J){var I;
var H=[];
var B;
var C=[];
var F;
var G=i.styles;
for(var D=0,E=J.length;
D<E;
D++){I=J[D];
F=this._levels({idx:I.parentId,id:I.id,summary:I.summary});
B={"data-uid":I.uid,"data-level":F,role:"row"};
if(I.summary){B["aria-expanded"]=I.expanded;
}if(D%2!==0){C.push(G.alt);
}if(I.summary){C.push(G.group);
}if(C.length){B.className=C.join(" ");
}H.push(this._tds({task:I,attr:B,level:F}));
C=[];
}return H;
},_tds:function(G){var B=[];
var D=this.columns;
var C;
for(var E=0,F=D.length;
E<F;
E++){C=D[E];
B.push(this._td({task:G.task,column:C,level:G.level}));
}if(this.options.resizable){B.push(m("td",{role:"gridcell"}));
}return m("tr",G.attr,B);
},_td:function(H){var B=[];
var I=this.options.resourcesField;
var G=i.styles;
var J=H.task;
var C=H.column;
var K=J.get(C.field);
var D;
var F;
if(C.field==I){K=K||[];
D=[];
for(var E=0;
E<K.length;
E++){D.push(k.format("{0} [{1}]",K[E].get("name"),K[E].get("formatedValue")));
}D=D.join(", ");
}else{D=C.format?k.format(C.format,K):K;
}if(C.field==="title"){B=f({level:H.level,className:G.iconPlaceHolder});
B.push(m("span",{className:G.icon+" "+(J.summary?J.expanded?G.iconCollapse:G.iconExpand:G.iconHidden)}));
F=k.format("{0}, {1:P0}",D,J.percentComplete);
}B.push(m("span",{"aria-label":F},[n(D)]));
return m("td",{role:"gridcell"},B);
},_levels:function(H){var G=this.levels;
var F;
var I=H.summary;
var D=H.idx;
var C=H.id;
for(var B=0,E=G.length;
B<E;
B++){F=G[B];
if(F.field==D){if(I){G.push({field:C,value:F.value+1});
}return F.value;
}}},_sortable:function(){var K=this;
var I=this.options.resourcesField;
var F=this.columns;
var E;
var J;
var C=this.header.find("th["+k.attr("field")+"]");
var B;
var D=function(L){if(K.dataSource.total()===0||K.editable&&K.editable.trigger("validate")){L.preventDefault();
}};
for(var G=0,H=C.length;
G<H;
G++){E=F[G];
if(E.sortable&&E.field!==I){B=C.eq(G);
J=B.data("kendoColumnSorter");
if(J){J.destroy();
}B.attr("data-"+k.ns+"field",E.field).kendoColumnSorter({dataSource:this.dataSource,change:D});
}}C=null;
},_selectable:function(){var C=this;
var B=this.options.selectable;
if(B){this.content.on(e+s,"tr",function(D){var E=b(this);
if(C.editable){C.editable.trigger("validate");
}if(!D.ctrlKey){C.select(E);
}else{C.clearSelection();
}});
}},select:function(D){var B=this.content.find(D);
var C=i.styles.selected;
if(B.length){B.siblings(g+C).removeClass(C).attr("aria-selected",false).end().addClass(C).attr("aria-selected",true);
this.trigger("change");
return;
}return this.content.find(g+C);
},clearSelection:function(){var B=this.select();
if(B.length){B.removeClass(i.styles.selected);
this.trigger("change");
}},_setDataSource:function(B){this.dataSource=B;
this._sortable();
},_editable:function(){var G=this;
var B=this.options.editable;
var E=i.styles;
var D="span."+E.icon+":not("+E.iconHidden+")";
var C=function(){var H=G.editable;
if(H){if(H.end()){G._closeCell();
}else{H.trigger("validate");
}}};
var F=function(I){var H=b(I.currentTarget);
if(!H.hasClass(E.editCell)){c();
}};
if(!B||B.update===false){return;
}this._startEditHandler=function(I){var J=I.currentTarget?b(I.currentTarget):I;
var H=G._columnFromElement(J);
if(G.editable){return;
}if(H&&H.editable){G._editCell({cell:J,column:H});
}};
G.content.on("focusin"+s,function(){clearTimeout(G.timer);
G.timer=null;
}).on("focusout"+s,function(){G.timer=setTimeout(C,1);
}).on("keydown"+s,function(H){if(H.keyCode===o.ENTER){H.preventDefault();
}}).on("keyup"+s,function(I){var J=I.keyCode;
var H;
var K;
switch(J){case o.ENTER:c();
C();
break;
case o.ESC:if(G.editable){H=G._editableContainer;
K=G._modelFromElement(H);
if(!G.trigger("cancel",{model:K,cell:H})){G._closeCell(true);
}}break;
}});
if(!r){G.content.on("mousedown"+s,"td",function(H){F(H);
}).on("dblclick"+s,"td",function(H){if(!b(H.target).is(D)){G._startEditHandler(H);
}});
}else{G.touch=G.content.kendoTouch({filter:"td",touchstart:function(H){F(H.touch);
},doubletap:function(H){if(!b(H.touch.initialTouch).is(D)){G._startEditHandler(H.touch);
}}}).data("kendoTouch");
}},_editCell:function(M){var N=this.options.resourcesField;
var J=i.styles;
var D=M.cell;
var E=M.column;
var K=this._modelFromElement(D);
var L=this.dataSource._createNewModel(K.toJSON());
var H=L.fields[E.field]||L[E.field];
var O=H.validation;
var F=k.attr("type");
var C=k.attr("bind");
var I=k.attr("format");
var B={name:E.field,required:H.validation?H.validation.required===true:false};
var G;
if(E.field===N){E.editor(D,L);
return;
}this._editableContent=D.children().detach();
this._editableContainer=D;
D.data("modelCopy",L);
if((H.type==="date"||b.type(H)==="date")&&(!E.format||/H|m|s|F|g|u/.test(E.format))){B[C]="value:"+E.field;
B[F]="date";
if(E.format){B[I]=k._extractFormat(E.format);
}G=function(P,Q){b('<input type="text"/>').attr(B).appendTo(P).kendoDateTimePicker({format:Q.format});
};
}this.editable=D.addClass(J.editCell).kendoEditable({fields:{field:E.field,format:E.format,editor:E.editor||G},model:L,clearContainer:false}).data("kendoEditable");
if(O&&O.dateCompare&&j(O.dateCompare)&&O.message){b("<span "+k.attr("for")+'="'+E.field+'" class="k-invalid-msg"/>').hide().appendTo(D);
D.find("[name="+E.field+"]").attr(k.attr("dateCompare-msg"),O.message);
}this.editable.bind("validate",function(P){var Q=this.element.find(":kendoFocusable:first").focus();
if(t){Q.focus();
}P.preventDefault();
});
if(this.trigger("edit",{model:K,cell:D})){this._closeCell(true);
}},_closeCell:function(B){var G=i.styles;
var C=this._editableContainer;
var H=this._modelFromElement(C);
var D=this._columnFromElement(C);
var F=D.field;
var E=C.data("modelCopy");
var I={};
I[F]=E.get(F);
C.empty().removeData("modelCopy").removeClass(G.editCell).append(this._editableContent);
this.editable.unbind();
this.editable.destroy();
this.editable=null;
this._editableContainer=null;
this._editableContent=null;
if(!B){if(F==="start"){I.end=new Date(I.start.getTime()+H.duration());
}this.trigger("update",{task:H,updateInfo:I});
}},_draggable:function(){var O=this;
var G=null;
var H=true;
var I;
var L=i.styles;
var K=k.support.isRtl(this.element);
var M="tr["+k.attr("level")+" = 0]:last";
var B={};
var J=this.options.editable;
var D=function(){G=null;
I=null;
H=true;
B={};
};
var C=function(Q){var P=Q;
while(P){if(G.get("id")===P.get("id")){H=false;
break;
}P=O.dataSource.taskParent(P);
}};
var F=function(){var P=b(I).height();
var Q=k.getOffset(I).top;
h(I,{beforeLimit:Q+P*0.25,afterLimit:Q+P*0.75});
};
var E=function(R){if(!I){return;
}var T=R.location;
var P=L.dropAdd;
var Q="add";
var S=parseInt(I.attr(k.attr("level")),10);
var U;
if(T<=I.beforeLimit){U=I.prev();
P=L.dropTop;
Q="insert-before";
}else{if(T>=I.afterLimit){U=I.next();
P=L.dropBottom;
Q="insert-after";
}}if(U&&parseInt(U.attr(k.attr("level")),10)===S){P=L.dropMiddle;
}B.className=P;
B.command=Q;
};
var N=function(){return O._reorderDraggable.hint.children(g+L.dragStatus).removeClass(L.dropPositions);
};
if(!J||J.reorder===false||J.update===false){return;
}this._reorderDraggable=this.content.kendoDraggable({distance:10,holdToDrag:r,group:"listGroup",filter:"tr[data-uid]",ignore:g+L.input,hint:function(P){return b('<div class="'+L.header+" "+L.dragClue+'"/>').css({width:300,paddingLeft:P.css("paddingLeft"),paddingRight:P.css("paddingRight"),lineHeight:P.height()+"px",paddingTop:P.css("paddingTop"),paddingBottom:P.css("paddingBottom")}).append('<span class="'+L.icon+" "+L.dragStatus+'" /><span class="'+L.dragClueText+'"/>');
},cursorOffset:{top:-20,left:0},container:this.content,dragstart:function(P){var Q=O.editable;
if(Q&&Q.reorder!==false&&Q.trigger("validate")){P.preventDefault();
return;
}G=O._modelFromElement(P.currentTarget);
this.hint.children(g+L.dragClueText).text(G.get("title"));
if(K){this.hint.addClass(L.rtl);
}},drag:function(P){if(H){E(P.y);
N().addClass(B.className);
}},dragend:function(){D();
},dragcancel:function(){D();
}}).data("kendoDraggable");
this._tableDropArea=this.content.kendoDropTargetArea({distance:0,group:"listGroup",filter:"tr[data-uid]",dragenter:function(P){I=P.dropTarget;
C(O._modelFromElement(I));
F();
N().toggleClass(L.dropDenied,!H);
},dragleave:function(){H=true;
N();
},drop:function(){var Q=O._modelFromElement(I);
var P=Q.orderId;
var R={parentId:Q.parentId};
if(H){switch(B.command){case"add":R.parentId=Q.id;
break;
case"insert-before":if(Q.parentId===G.parentId&&Q.orderId>G.orderId){R.orderId=P-1;
}else{R.orderId=P;
}break;
case"insert-after":if(Q.parentId===G.parentId&&Q.orderId>G.orderId){R.orderId=P;
}else{R.orderId=P+1;
}break;
}O.trigger("update",{task:G,updateInfo:R});
}}}).data("kendoDropTargetArea");
this._contentDropArea=this.element.kendoDropTargetArea({distance:0,group:"listGroup",filter:g+L.gridContent,drop:function(){var Q=O._modelFromElement(O.content.find(M));
var P=Q.orderId;
var R={parentId:null,orderId:G.parentId!==null?P+1:P};
O.trigger("update",{task:G,updateInfo:R});
}}).data("kendoDropTargetArea");
},_resizable:function(){var D=this;
var B=i.styles;
var C=function(I){var O=b(I.currentTarget);
var M=D.resizeHandle;
var L=O.position();
var K=L.left;
var F=v(O);
var H=O.closest("div");
var G=I.clientX+b(window).scrollLeft();
var J=D.options.columnResizeHandleWidth;
K+=H.scrollLeft();
if(!M){M=D.resizeHandle=b('<div class="'+B.resizeHandle+'"><div class="'+B.resizeHandleInner+'" /></div>');
}var E=O.offset().left+F;
var N=G>E-J&&G<E+J;
if(!N){M.hide();
return;
}H.append(M);
M.show().css({top:L.top,left:K+F-J-1,height:u(O),width:J*3}).data("th",O);
};
if(!this.options.resizable){return;
}if(this._columnResizable){this._columnResizable.destroy();
}this.header.find("thead").on("mousemove"+s,"th",C);
this._columnResizable=this.header.kendoResizable({handle:g+B.resizeHandle,start:function(G){var I=b(G.currentTarget).data("th");
var E="col:eq("+I.index()+")";
var H=D.header.find("table");
var F=D.content.find("table");
D.element.addClass("k-grid-column-resizing");
this.col=F.children("colgroup").find(E).add(H.find(E));
this.th=I;
this.startLocation=G.x.location;
this.columnWidth=v(I);
this.table=H.add(F);
this.totalWidth=this.table.width()-v(H.find("th:last"));
},resize:function(F){var G=11;
var E=F.x.location-this.startLocation;
if(this.columnWidth+E<G){E=G-this.columnWidth;
}this.table.css({minWidth:this.totalWidth+E});
this.col.width(this.columnWidth+E);
},resizeend:function(){D.element.removeClass("k-grid-column-resizing");
var G=Math.floor(this.columnWidth);
var F=Math.floor(v(this.th));
var E=D.columns[this.th.index()];
D.trigger("columnResize",{column:E,oldWidth:G,newWidth:F});
this.table=this.col=this.th=null;
}}).data("kendoResizable");
},_modelFromElement:function(B){var D=B.closest("tr");
var C=this.dataSource.getByUid(D.attr(k.attr("uid")));
return C;
},_columnFromElement:function(B){var D=B.closest("td");
var E=D.parent();
var C=E.children().index(D);
return this.columns[C];
}});
h(true,z.GanttList,{styles:p});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
