(function(b,a){a("kendo.gantt.timeline",["kendo.dom","kendo.touch","kendo.draganddrop"],b);
}(function(){var a={id:"gantt.timeline",name:"Gantt Timeline",category:"web",description:"The Gantt Timeline",depends:["dom","touch","draganddrop"],hidden:true};
(function(b){var O=kendo.ui.Widget;
var p=kendo.dom.element;
var r=kendo.dom.text;
var q=kendo.dom.html;
var n=b.isPlainObject;
var A=kendo._outerWidth;
var z=kendo._outerHeight;
var j=b.extend;
var C=b.proxy;
var d=kendo.support.browser;
var o=false;
var t=kendo.keys;
var D=kendo.data.Query;
var H="string";
var y=".kendoGanttTimeline";
var e="click";
var g="dblclick";
var x="mousemove";
var v="mouseenter";
var w="mouseleave";
var s="keydown";
var i=".";
var J=kendo.template("#=kendo.toString(start, 't')#");
var f=kendo.template("#=kendo.toString(start, 'ddd M/dd')#");
var N=kendo.template("#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#");
var u=kendo.template("#=kendo.toString(start, 'MMM')#");
var P=kendo.template("#=kendo.toString(start, 'yyyy')#");
var E=kendo.template('<div class="#=styles.marquee#"><div class="#=styles.marqueeColor#"></div></div>');
var F=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#"><div class="#=styles.tooltipContent#"><div>#=messages.start#: #=kendo.toString(start, format)#</div><div>#=messages.end#: #=kendo.toString(end, format)#</div></div></div>');
var B=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#" ><div class="#=styles.tooltipContent#">#=text#%</div><div class="#=styles.tooltipCallout#" style="left:13px;"></div></div>');
var I=kendo.template('<div class="#=kendo.htmlEncode(styles.taskDetails)#"><strong>#=kendo.htmlEncode(task.title)#</strong><div class="#=styles.taskDetailsPercent#">#=kendo.toString(task.percentComplete, "p0")#</div><ul class="#=styles.reset#"><li>#=messages.start#: #=kendo.toString(task.start, "h:mm tt ddd, MMM d")#</li><li>#=messages.end#: #=kendo.toString(task.end, "h:mm tt ddd, MMM d")#</li></ul></div>');
var G="<table style='visibility: hidden;'><tbody><tr style='height:{0}'><td>&nbsp;</td></tr></tbody></table>";
var h={day:{type:"kendo.ui.GanttDayView"},week:{type:"kendo.ui.GanttWeekView"},month:{type:"kendo.ui.GanttMonthView"},year:{type:"kendo.ui.GanttYearView"}};
function L(Q){delete Q.name;
delete Q.prefix;
delete Q.views;
return Q;
}function m(R){var S=[];
var Q=R.workWeekStart;
S.push(Q);
while(R.workWeekEnd!=Q){if(Q>6){Q-=7;
}else{Q++;
}S.push(Q);
}return S;
}function c(){var Q=kendo._activeElement();
if(Q&&Q.nodeName.toLowerCase()!=="body"){b(Q).blur();
}}var M={alt:"k-alt",reset:"k-reset",nonWorking:"k-nonwork-hour",header:"k-header",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",tasksWrapper:"k-gantt-tables",rowsTable:"k-gantt-rows",columnsTable:"k-gantt-columns",tasksTable:"k-gantt-tasks",dependenciesWrapper:"k-gantt-dependencies",resource:"k-resource",resourceAlt:"k-resource k-alt",task:"k-task",taskSingle:"k-task-single",taskMilestone:"k-task-milestone",taskSummary:"k-task-summary",taskWrap:"k-task-wrap",taskMilestoneWrap:"k-milestone-wrap",resourcesWrap:"k-resources-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",taskDragHandle:"k-task-draghandle",taskContent:"k-task-content",taskTemplate:"k-task-template",taskActions:"k-task-actions",taskDelete:"k-task-delete",taskComplete:"k-task-complete",taskDetails:"k-task-details",taskDetailsPercent:"k-task-pct",link:"k-link",icon:"k-icon",iconDelete:"k-i-close",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskResizeHandleEast:"k-resize-e",taskSummaryProgress:"k-task-summary-progress",taskSummaryComplete:"k-task-summary-complete",line:"k-line",lineHorizontal:"k-line-h",lineVertical:"k-line-v",arrowWest:"k-arrow-w",arrowEast:"k-arrow-e",dragHint:"k-drag-hint",dependencyHint:"k-dependency-hint",tooltipWrapper:"k-widget k-tooltip k-popup k-group k-reset",tooltipContent:"k-tooltip-content",tooltipCallout:"k-callout k-callout-s",callout:"k-callout",marquee:"k-marquee k-gantt-marquee",marqueeColor:"k-marquee-color"};
var l=kendo.ui.GanttView=O.extend({init:function(Q,R){O.fn.init.call(this,Q,R);
this.title=this.options.title||this.options.name;
this.header=this.element.find(i+l.styles.gridHeader);
this.content=this.element.find(i+l.styles.gridContent);
this.contentWidth=this.content.width();
this._workDays=m(this.options);
this._headerTree=R.headerTree;
this._taskTree=R.taskTree;
this._taskTemplate=R.taskTemplate?kendo.template(R.taskTemplate,j({},kendo.Template,R.templateSettings)):null;
this._dependencyTree=R.dependencyTree;
this._taskCoordinates={};
this._currentTime();
},destroy:function(){O.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
this.headerRow=null;
this.header=null;
this.content=null;
this._dragHint=null;
this._resizeHint=null;
this._resizeTooltip=null;
this._taskTooltip=null;
this._percentCompleteResizeTooltip=null;
this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
},options:{showWorkHours:false,showWorkDays:false,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,slotSize:100,currentTimeMarker:{updateInterval:10000}},renderLayout:function(){this._slots=this._createSlots();
this._tableWidth=this._calculateTableWidth();
this.createLayout(this._layout());
this._slotDimensions();
this._adjustHeight();
this.content.find(i+l.styles.dependenciesWrapper).width(this._tableWidth);
},_adjustHeight:function(){if(this.content){this.content.height(this.element.height()-z(this.header));
}},createLayout:function(T){var S=this._headers(T);
var Q=this._colgroup();
var V=this._headerTree;
var R=p("tbody",null,S);
var U=p("table",{style:{width:this._tableWidth+"px"},role:"presentation"},[Q,R]);
V.render([U]);
this.headerRow=this.header.find("table:first tr").last();
},_slotDimensions:function(){var R=this.headerRow[0].children;
var V=this._timeSlots();
var U;
var Q;
for(var S=0,T=R.length;
S<T;
S++){Q=R[S];
U=V[S];
U.offsetLeft=Q.offsetLeft;
U.offsetWidth=Q.offsetWidth;
}},render:function(X){var W=X.length;
var V=l.styles;
var S;
var U=this._rowsTable(W);
var R=this._columnsTable(W);
var Y=this._tasksTable(X);
var T=this.options.currentTimeMarker;
var Q=this.options.calculatedSize;
var Z;
this._taskTree.render([U,R,Y]);
S=this.content.find(i+V.rowsTable);
if(Q){Z=Q.row*X.length;
this.content.find(i+V.tasksTable).height(Z);
S.height(Z);
}this._contentHeight=S.height();
this._rowHeight=Q?Q.row:this._contentHeight/S.find("tr").length;
this.content.find(i+V.columnsTable).height(this._contentHeight);
if(T!==false&&T.updateInterval!==undefined){this._renderCurrentTime();
}},_rowsTable:function(T){var U=[];
var S;
var V=l.styles;
var Q=[null,{className:V.alt}];
for(var R=0;
R<T;
R++){S=p("tr",Q[R%2],[p("td",null,[r("\xA0")])]);
U.push(S);
}return this._createTable(1,U,{className:V.rowsTable});
},_columnsTable:function(){var R=[];
var T;
var Y=l.styles;
var V=this._timeSlots();
var W=V.length;
var U;
var X;
var Z=0;
var Q;
for(var S=0;
S<W;
S++){U=V[S];
Q={};
X=U.span;
Z+=X;
if(X!==1){Q.colspan=X;
}if(U.isNonWorking){Q.className=Y.nonWorking;
}R.push(p("td",Q,[r("\xA0")]));
}T=p("tr",null,R);
return this._createTable(Z,[T],{className:Y.columnsTable});
},_tasksTable:function(aj){var ae=[];
var ad;
var S;
var Y;
var ah;
var ag=l.styles;
var U=this._taskCoordinates={};
var af=this._calculateMilestoneWidth();
var X=Math.round(af.width);
var Z=this.options.resourcesField;
var T=[ag.resource,ag.resourceAlt];
var R=this.options.calculatedSize;
var ab;
var aa=this._calculateResourcesMargin();
var ai=this._calculateTaskBorderWidth();
var ac;
var Q=function(ak){var al;
var am;
al=Y.left;
am=al+Y.width;
if(ah.isMilestone()){al-=X/2;
am=al+X;
}U[ah.id]={start:al,end:am,rowIndex:ak};
};
for(var V=0,W=aj.length;
V<W;
V++){ah=aj[V];
Y=this._taskPosition(ah);
Y.borderWidth=ai;
ad=p("tr",null);
S=p("td");
if(ah.start<=this.end&&ah.end>=this.start){S.children.push(this._renderTask(aj[V],Y));
if(ah[Z]&&ah[Z].length){if(o){ab=this._tableWidth-Y.left;
}else{ab=Math.max(Y.width||af.clientWidth,0)+Y.left;
}ac={width:this._tableWidth-(ab+aa)+"px"};
ac[o?"right":"left"]=ab+"px";
if(R){ac.height=R.cell+"px";
}S.children.push(p("div",{className:ag.resourcesWrap,style:ac},this._renderResources(ah[Z],T[V%2])));
}Q(V);
}ad.children.push(S);
ae.push(ad);
}return this._createTable(1,ae,{className:l.styles.tasksTable});
},_createTable:function(S,U,V){var R=[];
var Q;
var W;
for(var T=0;
T<S;
T++){R.push(p("col"));
}Q=p("colgroup",null,R);
W=p("tbody",null,U);
if(!V.style){V.style={};
}V.style.width=this._tableWidth+"px";
V.role="presentation";
return p("table",V,[Q,W]);
},_calculateTableWidth:function(){var U=this._timeSlots();
var T=0;
var W=0;
var Q;
var V;
for(var R=0,S=U.length;
R<S;
R++){Q=U[R].span;
W+=Q;
if(Q>T){T=Q;
}}V=Math.round(W*this.options.slotSize/T);
return V;
},_calculateMilestoneWidth:function(){var T;
var R=l.styles.task+" "+l.styles.taskMilestone;
var S=b("<div class='"+R+"' style='visibility: hidden; position: absolute'>");
var Q;
this.content.append(S);
Q=S[0].getBoundingClientRect();
T={width:Q.right-Q.left,clientWidth:S[0].clientWidth};
S.remove();
return T;
},_calculateResourcesMargin:function(){var Q;
var R=b("<div class='"+l.styles.resourcesWrap+"' style='visibility: hidden; position: absolute'>");
this.content.append(R);
Q=parseInt(R.css(o?"margin-right":"margin-left"),10);
R.remove();
return Q;
},_calculateTaskBorderWidth:function(){var T;
var Q=l.styles.task+" "+l.styles.taskSingle;
var S=b("<div class='"+Q+"' style='visibility: hidden; position: absolute'>");
var R;
this.content.append(S);
R=kendo.getComputedStyles(S[0],["border-left-width"]);
T=parseFloat(R["border-left-width"],10);
S.remove();
return T;
},_renderTask:function(W,T){var aa;
var X;
var S=this.options.editable;
var U;
var Y=T.left;
var V=l.styles;
var ab=V.taskWrap;
var Q=this.options.calculatedSize;
var R={};
var Z={className:ab,style:{left:Y+"px"}};
if(Q){Z.style.height=Q.cell+"px";
}if(W.summary){X=this._renderSummary(W,T);
}else{if(W.isMilestone()){X=this._renderMilestone(W,T);
Z.className+=" "+V.taskMilestoneWrap;
}else{X=this._renderSingleTask(W,T);
}}aa=p("div",Z,[X]);
if(S&&S.dependencyCreate!==false){aa.children.push(p("div",{className:V.taskDot+" "+V.taskDotStart}));
aa.children.push(p("div",{className:V.taskDot+" "+V.taskDotEnd}));
}if(!W.summary&&!W.isMilestone()&&S&&S.dragPercentComplete!==false&&S.update!==false&&this._taskTemplate===null){U=Math.round(T.width*W.percentComplete);
R[o?"right":"left"]=U+"px";
aa.children.push(p("div",{className:V.taskDragHandle,style:R}));
}return aa;
},_renderSingleTask:function(W,T){var V=l.styles;
var U=Math.round(T.width*W.percentComplete);
var X=[];
var Y;
var R=this.options.editable;
if(this._taskTemplate!==null){Y=q(this._taskTemplate(W));
}else{Y=r(W.title);
X.push(p("div",{className:V.taskComplete,style:{width:U+"px"}}));
}var Q=p("div",{className:V.taskContent},[p("div",{className:V.taskTemplate},[Y])]);
X.push(Q);
if(R){if(R.destroy!==false){Q.children.push(p("span",{className:V.taskActions},[p("a",{className:V.link+" "+V.taskDelete,href:"#","aria-label":"Delete"},[p("span",{className:V.icon+" "+V.iconDelete})])]));
}if(R.resize!==false&&R.update!==false){Q.children.push(p("span",{className:V.taskResizeHandle+" "+V.taskResizeHandleWest}));
Q.children.push(p("span",{className:V.taskResizeHandle+" "+V.taskResizeHandleEast}));
}}var S=p("div",{className:V.task+" "+V.taskSingle,"data-uid":W.uid,style:{width:Math.max(T.width-T.borderWidth*2,0)+"px"}},X);
return S;
},_renderMilestone:function(S){var R=l.styles;
var Q=p("div",{className:R.task+" "+R.taskMilestone,"data-uid":S.uid});
return Q;
},_renderSummary:function(U,R){var T=l.styles;
var S=Math.round(R.width*U.percentComplete);
var Q=p("div",{className:T.task+" "+T.taskSummary,"data-uid":U.uid,style:{width:R.width+"px"}},[p("div",{className:T.taskSummaryProgress,style:{width:S+"px"}},[p("div",{className:T.taskSummaryComplete,style:{width:R.width+"px"}})])]);
return Q;
},_renderResources:function(V,R){var Q=[];
var U;
for(var S=0,T=V.length;
S<T;
S++){U=V[S];
Q.push(p("span",{className:R,style:{color:U.get("color")}},[r(U.get("name"))]));
}if(o){Q.reverse();
}return Q;
},_taskPosition:function(T){var R=Math.round;
var S=R(this._offset(o?T.end:T.start));
var Q=R(this._offset(o?T.start:T.end));
return{left:S,width:Q-S};
},_offset:function(Q){var U=this._timeSlots();
var R;
var W;
var S;
var T=0;
var V;
if(!U.length){return 0;
}V=this._slotIndex("start",Q);
R=U[V];
if(R.end<Q){T=R.offsetWidth;
}else{if(R.start<=Q){W=Q-R.start;
S=R.end-R.start;
T=W/S*R.offsetWidth;
}}if(o){T=R.offsetWidth+1-T;
}return R.offsetLeft+T;
},_slotIndex:function(R,W,T){var U=this._timeSlots();
var V=0;
var Q=U.length-1;
var S;
if(T){U=[].slice.call(U).reverse();
}do{S=Math.ceil((Q+V)/2);
if(U[S][R]<W){V=S;
}else{if(S===Q){S--;
}Q=S;
}}while(V!==Q);
if(T){V=U.length-1-V;
}return V;
},_timeByPosition:function(W,U,V){var S=this._slotByPosition(W);
if(U){return V?S.end:S.start;
}var R=W-b(i+l.styles.tasksTable).offset().left;
var Q=S.end-S.start;
var T=R-S.offsetLeft;
if(o){T=S.offsetWidth-T;
}return new Date(S.start.getTime()+Q*(T/S.offsetWidth));
},_slotByPosition:function(S){var Q=S-b(i+l.styles.tasksTable).offset().left;
var R=this._slotIndex("offsetLeft",Q,o);
return this._timeSlots()[R];
},_renderDependencies:function(Q){var R=[];
var U=this._dependencyTree;
for(var S=0,T=Q.length;
S<T;
S++){R.push.apply(R,this._renderDependency(Q[S]));
}U.render(R);
},_renderDependency:function(Q){var V=this._taskCoordinates[Q.predecessorId];
var W=this._taskCoordinates[Q.successorId];
var R;
var U;
if(!V||!W){return[];
}U="_render"+["FF","FS","SF","SS"][o?3-Q.type:Q.type];
R=this[U](V,W);
for(var S=0,T=R.length;
S<T;
S++){R[S].attr["data-uid"]=Q.uid;
}return R;
},_renderFF:function(Q,S){var R=this._dependencyFF(Q,S,false);
R[R.length-1].children[0]=this._arrow(true);
return R;
},_renderSS:function(Q,S){var R=this._dependencyFF(S,Q,true);
R[0].children[0]=this._arrow(false);
return R.reverse();
},_renderFS:function(Q,S){var R=this._dependencyFS(Q,S,false);
R[R.length-1].children[0]=this._arrow(false);
return R;
},_renderSF:function(Q,S){var R=this._dependencyFS(S,Q,true);
R[0].children[0]=this._arrow(true);
return R.reverse();
},_dependencyFF:function(V,ag,ac){var af=this;
var Z=[];
var Y=0;
var ah=0;
var aj=0;
var X=0;
var U=ac?"start":"end";
var T;
var ab=2;
var S=1;
var ad=this._rowHeight;
var aa=10;
var W=V.rowIndex*ad+Math.floor(ad/2)-1;
var ai=ag.rowIndex*ad+Math.floor(ad/2)-1;
var ae=l.styles;
var Q=function(){Z.push(af._line(ae.line+" "+ae.lineHorizontal,{left:Y+"px",top:ah+"px",width:aj+"px"}));
};
var R=function(){Z.push(af._line(ae.line+" "+ae.lineVertical,{left:Y+"px",top:ah+"px",height:X+"px"}));
};
Y=V[U];
ah=W;
aj=aa;
T=ag[U]-V[U];
if(T>0!==ac){aj=Math.abs(T)+aa;
}if(ac){Y-=aj;
aj-=S;
Q();
}else{Q();
Y+=aj-ab;
}if(ai<ah){X=ah-ai;
X+=ab;
ah=ai;
R();
}else{X=ai-ah;
X+=ab;
R();
ah+=X-ab;
}aj=Math.abs(Y-ag[U]);
if(!ac){aj-=S;
Y-=aj;
}Q();
return Z;
},_dependencyFS:function(U,ah,ad){var ag=this;
var Y=[];
var X=0;
var ai=0;
var ak=0;
var W=0;
var ae=this._rowHeight;
var aa=Math.floor(ae/2);
var ab=10;
var Z=2*ab;
var T=ah.start-U.end;
var ac=2;
var S=1;
var V=U.rowIndex*ae+Math.floor(ae/2)-1;
var aj=ah.rowIndex*ae+Math.floor(ae/2)-1;
var af=l.styles;
var Q=function(){Y.push(ag._line(af.line+" "+af.lineHorizontal,{left:X+"px",top:ai+"px",width:ak+"px"}));
};
var R=function(){Y.push(ag._line(af.line+" "+af.lineVertical,{left:X+"px",top:ai+"px",height:W+"px"}));
};
X=U.end;
ai=V;
ak=ab;
if(ad){X+=S;
if(T>Z){ak=T-(ab-ac);
}ak-=S;
}Q();
X+=ak-ac;
if(T<=Z){W=ad?Math.abs(aj-V)-aa:aa;
if(aj<V){ai-=W;
W+=ac;
R();
}else{R();
ai+=W;
}ak=U.end-ah.start+Z;
if(ak<ab){ak=ab;
}X-=ak-ac;
Q();
}if(aj<V){W=ai-aj;
ai=aj;
W+=ac;
R();
}else{W=aj-ai;
R();
ai+=W;
}ak=ah.start-X;
if(!ad){ak-=S;
}Q();
return Y;
},_line:function(Q,R){return p("div",{className:Q,style:R});
},_arrow:function(Q){return p("span",{className:Q?l.styles.arrowWest:l.styles.arrowEast});
},_colgroup:function(){var V=this._timeSlots();
var R=V.length;
var Q=[];
for(var S=0;
S<R;
S++){for(var T=0,U=V[S].span;
T<U;
T++){Q.push(p("col"));
}}return p("colgroup",null,Q);
},_createDragHint:function(Q){this._dragHint=Q.clone().addClass(l.styles.dragHint).css("cursor","move");
Q.parent().append(this._dragHint);
},_updateDragHint:function(R){var Q=this._offset(R);
this._dragHint.css({left:Q});
},_removeDragHint:function(){this._dragHint.remove();
this._dragHint=null;
},_createResizeHint:function(T){var S=l.styles;
var U=this._taskCoordinates[T.id].rowIndex*this._rowHeight;
var V;
var W;
var R=this.options;
var Q=R.messages;
this._resizeHint=b(E({styles:S})).css({top:0,height:this._contentHeight});
this.content.append(this._resizeHint);
this._resizeTooltip=b(F({styles:S,start:T.start,end:T.end,messages:Q.views,format:R.resizeTooltipFormat})).css({top:0,left:0});
this.content.append(this._resizeTooltip);
this._resizeTooltipWidth=A(this._resizeTooltip);
V=z(this._resizeTooltip);
W=U-V;
if(W<0){W=U+this._rowHeight;
}this._resizeTooltipTop=W;
},_updateResizeHint:function(W,Q,U){var R=this._offset(o?Q:W);
var V=this._offset(o?W:Q);
var ab=V-R;
var Z=U!==o?R:V;
var Y=this._tableWidth-kendo.support.scrollbar();
var aa=this._resizeTooltipWidth;
var T=this.options;
var S=T.messages;
var X=b(i+l.styles.tasksTable).offset().left-b(i+l.styles.tasksWrapper).offset().left;
if(o){R+=X;
}this._resizeHint.css({left:R,width:ab});
if(this._resizeTooltip){this._resizeTooltip.remove();
}Z-=Math.round(aa/2);
if(Z<0){Z=0;
}else{if(Z+aa>Y){Z=Y-aa;
}}if(o){Z+=X;
}this._resizeTooltip=b(F({styles:l.styles,start:W,end:Q,messages:S.views,format:T.resizeTooltipFormat})).css({top:this._resizeTooltipTop,left:Z,"min-width":aa}).appendTo(this.content);
},_removeResizeHint:function(){this._resizeHint.remove();
this._resizeHint=null;
this._resizeTooltip.remove();
this._resizeTooltip=null;
},_updatePercentCompleteTooltip:function(W,S,T){this._removePercentCompleteTooltip();
var U=this._percentCompleteResizeTooltip=b(B({styles:l.styles,text:T})).appendTo(this.element);
var V=Math.round(A(U)/2);
var Q=U.find(i+l.styles.callout);
var R=Math.round(A(Q)/2);
U.css({top:W-(z(U)+R),left:S-V});
Q.css("left",V-R);
},_removePercentCompleteTooltip:function(){if(this._percentCompleteResizeTooltip){this._percentCompleteResizeTooltip.remove();
}this._percentCompleteResizeTooltip=null;
},_updateDependencyDragHint:function(Q,R,S){this._removeDependencyDragHint();
if(S){this._creteVmlDependencyDragHint(Q,R);
}else{this._creteDependencyDragHint(Q,R);
}},_creteDependencyDragHint:function(T,V){var U=l.styles;
var R=V.x-T.x;
var S=V.y-T.y;
var W=Math.sqrt(R*R+S*S);
var Q=Math.atan(S/R);
if(R<0){Q+=Math.PI;
}b("<div class='"+U.line+" "+U.lineHorizontal+" "+U.dependencyHint+"'></div>").css({top:T.y,left:T.x,width:W,"transform-origin":"0% 0","-ms-transform-origin":"0% 0","-webkit-transform-origin":"0% 0",transform:"rotate("+Q+"rad)","-ms-transform":"rotate("+Q+"rad)","-webkit-transform":"rotate("+Q+"rad)"}).appendTo(this.content);
},_creteVmlDependencyDragHint:function(Q,S){var R=b("<kvml:line class='"+l.styles.dependencyHint+"' style='position:absolute; top: 0px; left: 0px;' strokecolor='black' strokeweight='2px' from='"+Q.x+"px,"+Q.y+"px' to='"+S.x+"px,"+S.y+"px'></kvml:line>").appendTo(this.content);
R[0].outerHTML=R[0].outerHTML;
},_removeDependencyDragHint:function(){this.content.find(i+l.styles.dependencyHint).remove();
},_createTaskTooltip:function(ab,U,W){var aa=l.styles;
var X=this.options;
var Q=this.content;
var R=Q.offset();
var T=Q.width();
var S=kendo.scrollLeft(Q);
var Y=b(U).parents("tr").first();
var Z=Y.offset();
var ac=X.tooltip&&X.tooltip.template?kendo.template(X.tooltip.template):I;
var V=o?W-(R.left+S+kendo.support.scrollbar()):W-(R.left-S);
var af=Z.top+z(Y)-R.top+Q.scrollTop();
var ad=this._taskTooltip=b('<div style="z-index: 100002;" class="'+aa.tooltipWrapper+'" ><div class="'+aa.taskContent+'"></div></div>');
var ae;
ad.css({left:V,top:af}).appendTo(Q).find(i+aa.taskContent).append(ac({styles:aa,task:ab,messages:X.messages.views}));
if(z(ad)<Z.top-R.top){ad.css("top",Z.top-R.top-z(ad)+Q.scrollTop());
}ae=A(ad);
if(ae+V-S>T){V-=ae;
if(V<S){V=S+T-(ae+17);
}ad.css("left",V);
}},_removeTaskTooltip:function(){if(this._taskTooltip){this._taskTooltip.remove();
}this._taskTooltip=null;
},_scrollTo:function(Y){var Z=Y.offset().left;
var ab=Y.width();
var aa=Z+ab;
var ac=Y.closest("tr");
var af=ac.offset().top;
var ae=ac.height();
var ad=af+ae;
var Q=this.content;
var U=Q.offset();
var W=U.top;
var S=Q.height();
var R=W+S;
var T=U.left;
var X=Q.width();
var V=T+X;
var ag=kendo.support.scrollbar();
if(af<W){Q.scrollTop(Q.scrollTop()+(af-W));
}else{if(ad>R){Q.scrollTop(Q.scrollTop()+(ad+ag-R));
}}if(Z<T&&ab>X&&aa<V||aa>V&&ab<X){Q.scrollLeft(Q.scrollLeft()+(aa+ag-V));
}else{if(aa>V&&ab>X&&Z>T||Z<T&&ab<X){Q.scrollLeft(Q.scrollLeft()+(Z-T));
}}},_scrollToDate:function(Q){var T=this.start;
var S=this.end;
var R;
if(Q>=T&&Q<S){R=this._offset(Q);
if(kendo.support.isRtl(this.element)){R=this._tableWidth-R;
}kendo.scrollLeft(this.content,R);
}},_timeSlots:function(){if(!this._slots||!this._slots.length){return[];
}return this._slots[this._slots.length-1];
},_headers:function(T){var Z=[];
var W;
var U;
var Q;
var V;
var aa=l.styles;
for(var Y=0,X=T.length;
Y<X;
Y++){W=T[Y];
U=[];
for(var S=0,R=W.length;
S<R;
S++){Q=W[S];
V=q(Q.text);
U.push(p("td",{colspan:Q.span,className:aa.header+(Q.isNonWorking?" "+aa.nonWorking:"")},[V]));
}Z.push(p("tr",null,U));
}return Z;
},_hours:function(X,Q){var V;
var W=[];
var U=this.options;
var Z=U.workDayStart.getHours();
var Y=U.workDayEnd.getHours();
var T;
var R;
var S=U.hourSpan;
X=new Date(X);
Q=new Date(Q);
if(U.showWorkHours){X.setHours(Z);
}while(X<Q){V=new Date(X);
R=V.getHours();
T=R>=Z&&R<Y;
V.setHours(V.getHours()+S);
if(R==V.getHours()){V.setHours(V.getHours()+2*S);
}if(!U.showWorkHours||T){W.push({start:X,end:V,isNonWorking:!T,span:1});
}X=V;
}return W;
},_days:function(U,Q){var S;
var T=[];
var R;
U=new Date(U);
Q=new Date(Q);
while(U<Q){S=Q<kendo.date.nextDay(U)?Q:kendo.date.nextDay(U);
R=this._isWorkDay(U);
if(!this.options.showWorkDays||R){T.push({start:U,end:S,isNonWorking:!R,span:1});
}U=S;
}return T;
},_weeks:function(W,R){var T;
var U=[];
var S=this.calendarInfo().firstDay;
var Q;
var V;
W=new Date(W);
R=new Date(R);
while(W<R){T=kendo.date.dayOfWeek(kendo.date.addDays(W,1),S,1);
if(T>R){T=R;
}Q=this._days(W,T);
V=Q.length;
if(V>0){U.push({start:Q[0].start,end:Q[V-1].end,span:V});
}W=T;
}return U;
},_months:function(W,R){var T;
var S;
var U=[];
var Q;
var V;
W=new Date(W);
R=new Date(R);
while(W<R){T=new Date(W);
S=kendo.date.firstDayOfMonth(new Date(T.setMonth(T.getMonth()+1)));
T=R<S?R:S;
Q=this._days(W,T);
V=Q.length;
if(V>0){U.push({start:Q[0].start,end:Q[V-1].end,span:V});
}W=T;
}return U;
},_years:function(V,Q){var T;
var S;
var R;
var U=[];
V=new Date(V);
Q=new Date(Q);
while(V<Q){T=new Date(V);
T=kendo.date.firstDayOfMonth(new Date(T.setMonth(12)));
if(T>=Q){T=Q;
}R=T.getMonth()||12;
S=R-V.getMonth();
U.push({start:V,end:T,span:S});
V=T;
}return U;
},_slotHeaders:function(U,V){var Q=[];
var T;
for(var R=0,S=U.length;
R<S;
R++){T=U[R];
Q.push({text:V(T),isNonWorking:!!T.isNonWorking,span:T.span});
}return Q;
},_isWorkDay:function(Q){var R=Q.getDay();
var U=this._workDays;
for(var S=0,T=U.length;
S<T;
S++){if(U[S]===R){return true;
}}return false;
},calendarInfo:function(){return kendo.getCulture().calendars.standard;
},_renderCurrentTime:function(){var Q=this._getCurrentTime();
var V=this._offset(Q);
var R=b("<div class='k-current-time'></div>");
var W=l.styles;
var T=b(i+W.tasksWrapper);
var U=b(i+W.tasksTable);
var S;
if(!this.content||!this._timeSlots().length){return;
}this.content.find(".k-current-time").remove();
S=this._timeSlots()[this._slotIndex("start",Q)];
if(Q<S.start||Q>S.end){return;
}if(T.length&&U.length){V+=U.offset().left-T.offset().left;
}R.css({left:V+"px",top:"0px",width:"1px",height:this._contentHeight+"px"}).appendTo(this.content);
},_getCurrentTime:function(){return new Date();
},_currentTime:function(){var Q=this.options.currentTimeMarker;
if(Q!==false&&Q.updateInterval!==undefined){this._renderCurrentTime();
this._currentTimeUpdateTimer=setInterval(C(this._renderCurrentTime,this),Q.updateInterval);
}}});
j(true,l,{styles:M});
kendo.ui.GanttDayView=l.extend({name:"day",options:{timeHeaderTemplate:J,dayHeaderTemplate:f,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(R){var Q=this.options.range;
this.start=kendo.date.getDate(R.start);
this.end=kendo.date.getDate(R.end);
if(kendo.date.getMilliseconds(R.end)>0||this.end.getTime()===this.start.getTime()){this.end=kendo.date.addDays(this.end,1);
}if(Q&&Q.start){this.start=kendo.date.getDate(Q.start);
this.start.setHours(Q.start.getHours());
}if(Q&&Q.end){this.end=kendo.date.getDate(Q.end);
this.end.setHours(Q.end.getHours());
}},_createSlots:function(){var R;
var Q;
var T;
var S;
var W=[];
R=this._days(this.start,this.end);
T=[];
for(var U=0,V=R.length;
U<V;
U++){Q=R[U];
S=this._hours(Q.start,Q.end);
Q.span=S.length;
T.push.apply(T,S);
}W.push(R);
W.push(T);
return W;
},_layout:function(){var R=[];
var Q=this.options;
R.push(this._slotHeaders(this._slots[0],kendo.template(Q.dayHeaderTemplate)));
R.push(this._slotHeaders(this._slots[1],kendo.template(Q.timeHeaderTemplate)));
return R;
}});
kendo.ui.GanttWeekView=l.extend({name:"week",options:{dayHeaderTemplate:f,weekHeaderTemplate:N,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(U){var T=this.options.range;
var Q=this.calendarInfo();
var S=Q.firstDay;
var V=U.end;
var R;
if(S===V.getDay()){V.setDate(V.getDate()+7);
}this.start=kendo.date.getDate(kendo.date.dayOfWeek(U.start,S,-1));
this.end=kendo.date.getDate(kendo.date.dayOfWeek(V,S,1));
if(T&&T.start){this.start=kendo.date.getDate(T.start);
}if(T&&T.end){R=new Date(T.end);
if(kendo.date.getDate(R)<T.end){this.end=kendo.date.getDate(new Date(R.setDate(R.getDate()+1)));
}else{this.end=kendo.date.getDate(R);
}}},_createSlots:function(){var Q=[];
Q.push(this._weeks(this.start,this.end));
Q.push(this._days(this.start,this.end));
return Q;
},_layout:function(){var R=[];
var Q=this.options;
R.push(this._slotHeaders(this._slots[0],kendo.template(Q.weekHeaderTemplate)));
R.push(this._slotHeaders(this._slots[1],kendo.template(Q.dayHeaderTemplate)));
return R;
}});
kendo.ui.GanttMonthView=l.extend({name:"month",options:{weekHeaderTemplate:N,monthHeaderTemplate:u,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(S){var R=this.options.range;
var Q;
this.start=kendo.date.firstDayOfMonth(S.start);
this.end=kendo.date.addDays(kendo.date.getDate(kendo.date.lastDayOfMonth(S.end)),1);
if(R&&R.start){this.start=kendo.date.getDate(R.start);
}if(R&&R.end){Q=new Date(R.end);
if(kendo.date.getDate(Q)<R.end){this.end=kendo.date.getDate(new Date(Q.setDate(Q.getDate()+1)));
}else{this.end=kendo.date.getDate(Q);
}}},_createSlots:function(){var Q=[];
Q.push(this._months(this.start,this.end));
Q.push(this._weeks(this.start,this.end));
return Q;
},_layout:function(){var R=[];
var Q=this.options;
R.push(this._slotHeaders(this._slots[0],kendo.template(Q.monthHeaderTemplate)));
R.push(this._slotHeaders(this._slots[1],kendo.template(Q.weekHeaderTemplate)));
return R;
}});
kendo.ui.GanttYearView=l.extend({name:"year",options:{yearHeaderTemplate:P,monthHeaderTemplate:u,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(S){var R=this.options.range;
var Q;
this.start=kendo.date.firstDayOfMonth(new Date(S.start.setMonth(0)));
this.end=kendo.date.firstDayOfMonth(new Date(S.end.setMonth(12)));
if(R&&R.start){this.start=kendo.date.firstDayOfMonth(R.start);
}if(R&&R.end){Q=kendo.date.firstDayOfMonth(R.end);
this.end=kendo.date.getDate(new Date(Q.setMonth(Q.getMonth()+1)));
}},_createSlots:function(){var R=[];
var Q=this._months(this.start,this.end);
b(Q).each(function(S,T){T.span=1;
});
R.push(this._years(this.start,this.end));
R.push(Q);
return R;
},_layout:function(){var R=[];
var Q=this.options;
R.push(this._slotHeaders(this._slots[0],kendo.template(Q.yearHeaderTemplate)));
R.push(this._slotHeaders(this._slots[1],kendo.template(Q.monthHeaderTemplate)));
return R;
}});
var K={wrapper:"k-timeline k-grid k-widget",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",gridContentWrap:"k-grid-content",tasksWrapper:"k-gantt-tables",dependenciesWrapper:"k-gantt-dependencies",task:"k-task",line:"k-line",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskDragHandle:"k-task-draghandle",taskComplete:"k-task-complete",taskDelete:"k-task-delete",taskWrapActive:"k-task-wrap-active",taskWrap:"k-task-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",hovered:"k-state-hover",selected:"k-state-selected",origin:"k-origin"};
var k=kendo.ui.GanttTimeline=O.extend({init:function(Q,R){O.fn.init.call(this,Q,R);
if(!this.options.views||!this.options.views.length){this.options.views=["day","week","month"];
}o=kendo.support.isRtl(Q);
this._wrapper();
this._domTrees();
this._views();
this._selectable();
this._draggable();
this._resizable();
this._percentResizeDraggable();
this._createDependencyDraggable();
this._attachEvents();
this._tooltip();
},options:{name:"GanttTimeline",messages:{views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"}},snap:true,selectable:true,editable:true},destroy:function(){O.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
if(this._currentTimeUpdateTimer){clearInterval(this._currentTimeUpdateTimer);
}this._unbindView(this._selectedView);
if(this._moveDraggable){this._moveDraggable.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}if(this._percentDraggable){this._percentDraggable.destroy();
}if(this._dependencyDraggable){this._dependencyDraggable.destroy();
}if(this.touch){this.touch.destroy();
}this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
this.wrapper.off(y);
kendo.destroy(this.wrapper);
},_wrapper:function(){var S=k.styles;
var T=this;
var R=this.options;
var Q=function(){var X=typeof R.rowHeight===H?R.rowHeight:R.rowHeight+"px";
var Y=b(kendo.format(G,X));
var V;
var U;
var W=T.wrapper.find(i+S.tasksWrapper);
W.append(Y);
V=z(Y.find("tr"));
U=Y.find("td").height();
Y.remove();
return{row:V,cell:U};
};
this.wrapper=this.element.addClass(S.wrapper).append("<div class='"+S.gridHeader+"'><div class='"+S.gridHeaderWrap+"'></div></div>").append("<div class='"+S.gridContentWrap+"'><div class='"+S.tasksWrapper+"'></div><div class='"+S.dependenciesWrapper+"'></div></div>");
if(R.rowHeight){this._calculatedSize=Q();
}},_domTrees:function(){var Q=k.styles;
var R=kendo.dom.Tree;
var S=this.wrapper;
this._headerTree=new R(S.find(i+Q.gridHeaderWrap)[0]);
this._taskTree=new R(S.find(i+Q.tasksWrapper)[0]);
this._dependencyTree=new R(S.find(i+Q.dependenciesWrapper)[0]);
},_views:function(){var X=this.options.views;
var W;
var S;
var U;
var Q;
var V;
this.views={};
for(var R=0,T=X.length;
R<T;
R++){W=X[R];
S=n(W);
if(S&&W.selectable===false){continue;
}U=S?typeof W.type!=="string"?W.title:W.type:W;
Q=h[U];
if(Q){if(S){W.type=Q.type;
}Q.title=this.options.messages.views[U];
}W=j({title:U},Q,S?W:{});
if(U){this.views[U]=W;
if(!V||W.selected){V=U;
}}}if(V){this._selectedViewName=V;
}},view:function(Q){if(Q){this._selectView(Q);
this.trigger("navigate",{view:Q,action:"changeView"});
}return this._selectedView;
},_selectView:function(Q){if(Q&&this.views[Q]){if(this._selectedView){this._unbindView(this._selectedView);
}this._selectedView=this._initializeView(Q);
this._selectedViewName=Q;
}},_viewByIndex:function(Q){var R;
var S=this.views;
for(R in S){if(!Q){return R;
}Q--;
}},_initializeView:function(Q){var U=this.views[Q];
if(U){var T=U.type;
if(typeof T==="string"){T=kendo.getter(U.type)(window);
}if(T){var S={};
j(S,this.options.range,U.range);
var R=U.date||this.options.date;
U=new T(this.wrapper,L(j(true,{headerTree:this._headerTree,taskTree:this._taskTree,dependencyTree:this._dependencyTree,calculatedSize:this._calculatedSize},U,this.options,{date:R,range:S})));
}else{throw new Error("There is no such view");
}}return U;
},_unbindView:function(Q){if(Q){Q.destroy();
}},_range:function(U){var T={field:"start",dir:"asc"};
var R={field:"end",dir:"desc"};
if(!U||!U.length){return{start:new Date(),end:new Date()};
}var S=new D(U).sort(T).toArray()[0].start||new Date();
var Q=new D(U).sort(R).toArray()[0].end||new Date();
return{start:new Date(S),end:new Date(Q)};
},_render:function(S){var T=this.view();
var R=this._range(S);
var Q=T.options.date;
this._tasks=S;
T.range(R);
T.renderLayout();
T.render(S);
if(Q){T._scrollToDate(Q);
}},_renderDependencies:function(Q){this.view()._renderDependencies(Q);
},_taskByUid:function(U){var T=this._tasks;
var R=T.length;
var S;
for(var Q=0;
Q<R;
Q++){S=T[Q];
if(S.uid===U){return S;
}}},_draggable:function(){var Y=this;
var T;
var X;
var R;
var V;
var U=this.options.snap;
var W=k.styles;
var S=this.options.editable;
var Q=function(){Y.view()._removeDragHint();
if(T){T.css("opacity",1);
}T=null;
X=null;
Y.dragInProgress=false;
};
if(!S||S.move===false||S.update===false){return;
}this._moveDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:i+W.task,holdToDrag:kendo.support.mobileOS,ignore:i+W.taskResizeHandle});
this._moveDraggable.bind("dragstart",function(Z){var aa=Y.view();
T=Z.currentTarget.parent();
X=Y._taskByUid(Z.currentTarget.attr("data-uid"));
if(Y.trigger("moveStart",{task:X})){Z.preventDefault();
return;
}R=X.start;
V=aa._timeByPosition(Z.x.location,U)-R;
aa._createDragHint(T);
T.css("opacity",0.5);
clearTimeout(Y._tooltipTimeout);
Y.dragInProgress=true;
}).bind("drag",kendo.throttle(function(aa){if(!Y.dragInProgress){return;
}var ac=Y.view();
var Z=new Date(ac._timeByPosition(aa.x.location,U)-V);
var ab=Z;
if(!Y.trigger("move",{task:X,start:Z})){R=Z;
if(o){ab=new Date(R.getTime()+X.duration());
}ac._updateDragHint(ab);
}},15)).bind("dragend",function(){Y.trigger("moveEnd",{task:X,start:R});
Q();
}).bind("dragcancel",function(){Q();
}).userEvents.bind("select",function(){c();
});
},_resizable:function(){var Z=this;
var U;
var Y;
var S;
var R;
var V;
var W=this.options.snap;
var X=k.styles;
var T=this.options.editable;
var Q=function(){Z.view()._removeResizeHint();
U=null;
Y=null;
Z.dragInProgress=false;
};
if(!T||T.resize===false||T.update===false){return;
}this._resizeDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:i+X.taskResizeHandle,holdToDrag:false});
this._resizeDraggable.bind("dragstart",function(aa){V=aa.currentTarget.hasClass(X.taskResizeHandleWest);
if(o){V=!V;
}U=aa.currentTarget.closest(i+X.task);
Y=Z._taskByUid(U.attr("data-uid"));
if(Z.trigger("resizeStart",{task:Y})){aa.preventDefault();
return;
}S=Y.start;
R=Y.end;
Z.view()._createResizeHint(Y);
clearTimeout(Z._tooltipTimeout);
Z.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ab){if(!Z.dragInProgress){return;
}var ac=Z.view();
var aa=ac._timeByPosition(ab.x.location,W,!V);
if(V){if(aa<R){S=aa;
}else{S=R;
}}else{if(aa>S){R=aa;
}else{R=S;
}}if(!Z.trigger("resize",{task:Y,start:S,end:R})){ac._updateResizeHint(S,R,V);
}},15)).bind("dragend",function(){Z.trigger("resizeEnd",{task:Y,resizeStart:V,start:S,end:R});
Q();
}).bind("dragcancel",function(){Q();
}).userEvents.bind("select",function(){c();
});
},_percentResizeDraggable:function(){var aa=this;
var X;
var Y;
var Z;
var ab;
var V;
var U;
var R;
var ad;
var ac;
var W=k.styles;
var S;
var T=this.options.editable;
var Q=function(){aa.view()._removePercentCompleteTooltip();
Y=null;
X=null;
aa.dragInProgress=false;
};
var ae=function(af){Y.find(i+W.taskComplete).width(af).end().siblings(i+W.taskDragHandle).css(o?"right":"left",af);
};
if(!T||T.dragPercentComplete===false||T.update===false){return;
}this._percentDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:i+W.taskDragHandle,holdToDrag:false});
this._percentDraggable.bind("dragstart",function(af){if(aa.trigger("percentResizeStart")){af.preventDefault();
return;
}Y=af.currentTarget.siblings(i+W.task);
X=aa._taskByUid(Y.attr("data-uid"));
R=X.percentComplete;
Z=Y.offset();
ab=this.element.offset();
V=Y.find(i+W.taskComplete).width();
U=A(Y);
clearTimeout(aa._tooltipTimeout);
aa.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ag){if(!aa.dragInProgress){return;
}S=o?-ag.x.initialDelta:ag.x.initialDelta;
var af=Math.max(0,Math.min(U,V+S));
R=Math.round(af/U*100);
ae(af);
ad=Z.top-ab.top;
ac=Z.left+af-ab.left;
if(o){ac+=U-2*af;
}aa.view()._updatePercentCompleteTooltip(ad,ac,R);
},15)).bind("dragend",function(){aa.trigger("percentResizeEnd",{task:X,percentComplete:R/100});
Q();
}).bind("dragcancel",function(){ae(V);
Q();
}).userEvents.bind("select",function(){c();
});
},_createDependencyDraggable:function(){var Y=this;
var U;
var S=b();
var T=b();
var V;
var W;
var aa=d.msie&&d.version<9;
var X=k.styles;
var R=this.options.editable;
var Q=function(){U.css("display","").removeClass(X.hovered);
U.parent().removeClass(X.origin);
U=null;
Z(false);
T=b();
S=b();
Y.view()._removeDependencyDragHint();
Y.dragInProgress=false;
};
var Z=function(ab){if(!T.hasClass(X.origin)){T.find(i+X.taskDot).css("display",ab?"block":"");
S.toggleClass(X.hovered,ab);
}};
if(!R||R.dependencyCreate===false){return;
}if(aa&&document.namespaces){document.namespaces.add("kvml","urn:schemas-microsoft-com:vml","#default#VML");
}this._dependencyDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:i+X.taskDot,holdToDrag:false});
this._dependencyDraggable.bind("dragstart",function(ab){if(Y.trigger("dependencyDragStart")){ab.preventDefault();
return;
}U=ab.currentTarget.css("display","block").addClass(X.hovered);
U.parent().addClass(X.origin);
var ac=U.offset();
var ad=Y.wrapper.find(i+X.tasksWrapper).offset();
V=Math.round(ac.left-ad.left+z(U)/2);
W=Math.round(ac.top-ad.top+A(U)/2);
clearTimeout(Y._tooltipTimeout);
Y.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ad){if(!Y.dragInProgress){return;
}Y.view()._removeDependencyDragHint();
var af=b(kendo.elementUnderCursor(ad));
var ae=Y.wrapper.find(i+X.tasksWrapper).offset();
var ab=ad.x.location-ae.left;
var ac=ad.y.location-ae.top;
Y.view()._updateDependencyDragHint({x:V,y:W},{x:ab,y:ac},aa);
Z(false);
S=af.hasClass(X.taskDot)?af:b();
T=af.closest(i+X.taskWrap);
Z(true);
},15)).bind("dragend",function(){if(S.length){var ab=U.hasClass(X.taskDotStart);
var ae=S.hasClass(X.taskDotStart);
var af=ab?ae?3:2:ae?1:0;
var ac=Y._taskByUid(U.siblings(i+X.task).attr("data-uid"));
var ad=Y._taskByUid(S.siblings(i+X.task).attr("data-uid"));
if(ac!==ad){Y.trigger("dependencyDragEnd",{type:af,predecessor:ac,successor:ad});
}}Q();
}).bind("dragcancel",function(){Q();
}).userEvents.bind("select",function(){c();
});
},_selectable:function(){var R=this;
var Q=k.styles;
if(this.options.selectable){this.wrapper.on(e+y,i+Q.task,function(S){S.stopPropagation();
if(!S.ctrlKey){R.trigger("select",{uid:b(this).attr("data-uid")});
}else{R.trigger("clear");
}}).on(e+y,i+Q.taskWrap,function(S){S.stopPropagation();
b(this).css("z-index","0");
var T=b(document.elementFromPoint(S.clientX,S.clientY));
if(T.hasClass(Q.line)){T.click();
}b(this).css("z-index","");
}).on(e+y,i+Q.tasksWrapper,function(){if(R.selectDependency().length>0){R.clearSelection();
}else{R.trigger("clear");
}}).on(e+y,i+Q.line,function(S){S.stopPropagation();
R.selectDependency(this);
});
}},select:function(S){var Q=this.wrapper.find(S);
var R=k.styles;
if(Q.length){this.clearSelection();
Q.addClass(R.selected);
if(kendo.support.mobileOS){Q.parent().addClass(R.taskWrapActive);
}return;
}return this.wrapper.find(i+R.task+i+R.selected);
},selectDependency:function(T){var Q=this.wrapper.find(T);
var S;
var R=k.styles;
if(Q.length){this.clearSelection();
this.trigger("clear");
S=b(Q).attr("data-uid");
this.wrapper.find(i+R.line+"[data-uid='"+S+"']").addClass(R.selected);
return;
}return this.wrapper.find(i+R.line+i+R.selected);
},clearSelection:function(){var Q=k.styles;
this.wrapper.find(i+Q.selected).removeClass(Q.selected);
if(kendo.support.mobileOS){this.wrapper.find(i+Q.taskWrapActive).removeClass(Q.taskWrapActive);
}},_attachEvents:function(){var S=this;
var R=k.styles;
var Q=this.options.editable;
if(Q){this._tabindex();
this.wrapper.on(e+y,i+R.taskDelete,function(T){S.trigger("removeTask",{uid:b(this).closest(i+R.task).attr("data-uid")});
T.stopPropagation();
T.preventDefault();
}).on(s+y,function(T){var V;
var U=S.options.editable;
if(T.keyCode===t.DELETE&&U&&U.dependencyDestroy!==false){V=S.selectDependency();
if(V.length){S.trigger("removeDependency",{uid:V.attr("data-uid")});
S.clearSelection();
}}});
if(!kendo.support.mobileOS){this.wrapper.on(g+y,i+R.task,function(T){if(S.options.editable.update!==false){S.trigger("editTask",{uid:b(this).attr("data-uid")});
T.stopPropagation();
T.preventDefault();
}});
}else{this.touch=this.wrapper.kendoTouch({filter:i+R.task,doubletap:function(T){if(S.options.editable.update!==false){S.trigger("editTask",{uid:b(T.touch.currentTarget).attr("data-uid")});
}}}).data("kendoTouch");
}}},_tooltip:function(){var T=this;
var U=this.options.tooltip;
var S=k.styles;
var Q;
var R=function(V){Q=V.clientX;
};
if(U&&U.visible===false){return;
}if(!kendo.support.mobileOS){this.wrapper.on(v+y,i+S.task,function(){var V=this;
var W=T._taskByUid(b(this).attr("data-uid"));
if(T.dragInProgress){return;
}T._tooltipTimeout=setTimeout(function(){T.view()._createTaskTooltip(W,V,Q);
},800);
b(this).on(x,R);
}).on(w+y,i+S.task,function(){clearTimeout(T._tooltipTimeout);
T.view()._removeTaskTooltip();
b(this).off(x,R);
});
}else{this.wrapper.on(e+y,i+S.taskDelete,function(V){V.stopPropagation();
T.view()._removeTaskTooltip();
}).on(w+y,i+S.task,function(V){var W=b(V.relatedTarget).parents(i+S.taskWrap,i+S.task);
if(W.length===0){T.view()._removeTaskTooltip();
}});
if(this.touch){this.touch.bind("tap",function(W){var X=W.touch.target;
var Y=T._taskByUid(b(X).attr("data-uid"));
var V=W.touch.x.client;
if(T.view()._taskTooltip){T.view()._removeTaskTooltip();
}T.view()._createTaskTooltip(Y,X,V);
}).bind("doubletap",function(){T.view()._removeTaskTooltip();
});
}}}});
j(true,k,{styles:K});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
